Repository open-mpi/ompi, pull requests merged in 2018-04, with the labels that each got.

#4997 io/ompio: don't reset amode if MODE_SEQUENTIAL is set
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: Target: v2.x, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#4984 ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
Labels: Target: master

#4998 dist: Don't build case-conflicting html man pages
  contrib/dist/make-html-man-pages.pl
Labels: Target: v3.0.x

#4999 dist: Don't build case-conflicting html man pages
  contrib/dist/make-html-man-pages.pl
Labels: Target: v3.1.x

#4947 v3.1.x: ompi/opal: add support for HDR link speeds
  opal/mca/common/verbs/common_verbs_port.c
Labels: Target: v3.1.x

#4934 hwloc: bring back the configure error when external hwloc is >= 2.0
  opal/mca/hwloc/external/configure.m4
Labels: Target: v3.1.x, enhancement

#4982 ompi/oshmem: fix bug in shmem_finalize.
  oshmem/runtime/oshmem_shmem_finalize.c
  oshmem/shmem/c/shmem_finalize.c
Labels: Target: master

#4996 ompi/oshmem: fix cswap bug in mca/atomic/mxm.
  oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
Labels: Target: master

#5002 fcoll/dynamic_gen2: fix coverty warnings
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
Labels: Target: master

#5010 Move past the '.' when getting jobstepid
  opal/mca/pmix/s1/pmix_s1.c
  opal/mca/pmix/s2/pmix_s2.c
Labels: Target: master, Target: v2.0.x, Target: v2.x, Target: v3.0.x, Target: v3.1.x, bug

#4992 pmix: add "pmix*_library_version" info MCA var
  opal/mca/pmix/ext1x/pmix1x_component.c
  opal/mca/pmix/ext2x/ext2x_component.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
Labels: Target: master, enhancement

#5016 mpi/fortran: fix parsing arrays of Fortran strings
  ompi/mpi/fortran/base/fortran_base_strings.h
  ompi/mpi/fortran/base/strings.c
  ompi/mpi/fortran/mpif-h/comm_spawn_f.c
  ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
Labels: bug

#5021 MPI_Comm_spawn_multiple.3in: update Fortran string array notes
  ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Labels: documentation

#5001 configury: use javac vs javah whenever possible.
  config/opal_setup_java.m4
  ompi/mpi/java/java/Makefile.am
Labels: NEWS, Target: master, enhancement

#5033 NEWS: Add v3.0.1 bullets from v3.0.x branch
  NEWS
Labels: documentation

#5037 v3.1.x: Move past the '.' when getting jobstepid
  opal/mca/pmix/s1/pmix_s1.c
  opal/mca/pmix/s2/pmix_s2.c
Labels: bug

#5036 v3.0.x: Move past the '.' when getting jobstepid
  opal/mca/pmix/s1/pmix_s1.c
  opal/mca/pmix/s2/pmix_s2.c
Labels: bug

#5025 v3.0.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes
  ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Labels: Target: v3.0.x, documentation

#5026 v3.1.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes
  ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Labels: Target: v3.1.x, documentation

#5023 io/ompio: don't reset amode if MODE_SEQUENTIAL is set
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: Target: v3.1.x, bug

#5022 io/ompio: don't reset amode if MODE_SEQUENTIAL is set
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: Target: v3.0.x, bug

#5018 v3.0.x: mpi/fortran: fix parsing arrays of Fortran strings
  ompi/mpi/fortran/base/fortran_base_strings.h
  ompi/mpi/fortran/base/strings.c
  ompi/mpi/fortran/mpif-h/comm_spawn_f.c
  ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
Labels: Target: v3.0.x, bug

#5017 v3.1.x: mpi/fortran: fix parsing arrays of Fortran strings
  ompi/mpi/fortran/base/fortran_base_strings.h
  ompi/mpi/fortran/base/strings.c
  ompi/mpi/fortran/mpif-h/comm_spawn_f.c
  ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
Labels: Target: v3.1.x, bug

#5005 ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
Labels: Target: v3.1.x, bug

#5006 ompi/oshmem: fix bug in shmem_alltoall in mca/scoll/basic.
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
Labels: Target: v3.0.x, bug

#5007 Misc. trivial typos
  README
  README.JAVA.txt
  VERSION
  autogen.pl
  config/ompi_configure_options.m4
  config/ompi_cxx_have_exceptions.m4
  config/ompi_fortran_check_f08_assumed_rank.m4
  config/ompi_fortran_check_ignore_tkr.m4
  config/opal_check_cray_pmi.m4
  config/opal_check_openfabrics.m4
  config/opal_check_os_flavors.m4
  config/opal_check_package.m4
  config/opal_check_pthread_pids.m4
  config/opal_config_asm.m4
  config/opal_configure_options.m4
  config/opal_functions.m4
  config/opal_mca.m4
  config/opal_setup_wrappers.m4
  config/oshmem_configure_options.m4
  config/pkg.m4
  test/carto/carto-file
  test/carto/carto_test.c
  test/class/opal_pointer_array.c
  test/datatype/checksum.c
  test/datatype/ddt_lib.c
  test/datatype/opal_datatype_test.c
  test/datatype/opal_ddt_lib.c
  test/event/event-test.c
  test/event/signal-test.c
  test/event/time-test.c
  test/monitoring/monitoring_test.c
  test/monitoring/test_overhead.sh
  test/mpi/environment/run_tests
  test/mpi/run_tests
Labels: Target: master

#5041 mpool/memkind: be careful with the memkind API
  opal/mca/mpool/memkind/configure.m4
Labels: NEWS, RM approved

#5044 orterun.1in: fix typo
  orte/tools/orterun/orterun.1in
Labels: Target: v2.x, Target: v3.0.x, Target: v3.1.x, documentation

#5011 ompi/oshmem: fix bug in shmem_finalize.
  oshmem/runtime/oshmem_shmem_finalize.c
  oshmem/shmem/c/shmem_finalize.c
Labels: bug

#5014 ompi/oshmem: fix cswap bug in mca/atomic/mxm.
  oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
Labels: bug

#5029 configury: use javac vs javah whenever possible
  config/opal_setup_java.m4
  ompi/mpi/java/java/Makefile.am
Labels: Target: v3.0.x, enhancement

#4398 v3.0: configury: revamp ucx detection
  config/ompi_check_ucx.m4
Labels: Target: v3.0.x, bug

#5040 v3.1: mpool/memkind: be careful with the memkind API
  opal/mca/mpool/memkind/configure.m4
Labels: NEWS

#5045 v3.0.x: orterun.1in: fix typo
  orte/tools/orterun/orterun.1in
Labels: documentation

#5012 ompi/oshmem: fix bug in shmem_finalize.
  oshmem/runtime/oshmem_shmem_finalize.c
  oshmem/shmem/c/shmem_finalize.c
Labels: Target: v3.0.x, bug

#5013 ompi/oshmem: fix cswap bug in mca/atomic/mxm.
  oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
Labels: Target: v3.0.x, bug

#5049 pmix/base: set PMIx to follow OPAL's mca_component_show_load_errors
  opal/mca/pmix/base/pmix_base_select.c
Labels: Target: master, enhancement

#5035 v2.x: jobstepid parsing fix
  opal/mca/pmix/s1/pmix_s1.c
  opal/mca/pmix/s2/pmix_s2.c
Labels: NEWS, RM approved, Target: v2.x, bug

#5055 plm/base: fix typo in variable name
  orte/mca/plm/base/plm_base_frame.c
Labels: Target: master, blocker, bug

#5060 configure: Fix typo in `configure --help`
  config/opal_setup_wrappers.m4
Labels: Target: master, minor

#5054 master: mtl-portals4: don't call progress() in finalize() if Portals4 was not initialized
  ompi/mca/mtl/portals4/mtl_portals4.c
Labels: Target: master, bug

#5053 master: btl-portals4: don't free module resources when proc count goes to zero
  opal/mca/btl/portals4/btl_portals4.c
Labels: Target: master, bug

#5056 plm/base: fix typo in variable name
  orte/mca/plm/base/plm_base_frame.c
Labels: Target: v3.1.x, blocker, bug, critical

#5061 v3.1.x: configure: Fix typo in `configure --help`
  config/opal_setup_wrappers.m4
Labels: Target: v3.1.x, minor

#5024 v2.1.x: MPI_Comm_spawn_multiple.3in: update Fortran string array notes
  ompi/mpi/man/man3/MPI_Comm_spawn_multiple.3in
Labels: RM approved, Target: v2.x, documentation

#5019 v2.1.x: mpi/fortran: fix parsing arrays of Fortran strings
  ompi/mpi/fortran/base/fortran_base_strings.h
  ompi/mpi/fortran/base/strings.c
  ompi/mpi/fortran/mpif-h/comm_spawn_f.c
  ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
Labels: RM approved, Target: v2.x, bug

#5063 dist: Update NEWS with updates since rc3
  NEWS
Labels: Target: v3.1.x

#5068 io/romio314: fix minmax datatypes
  ompi/mca/io/romio314/romio/adio/common/ad_set_view.c
  ompi/mca/io/romio314/romio/adio/common/flatten.c
  ompi/mca/io/romio314/romio/adio/include/adioi.h
Labels: Target: master, Target: v3.0.x, Target: v3.1.x, bug, minor

#5062 v3.0.x: btl-portals4: don't free module resources when proc count goes to zero
  opal/mca/btl/portals4/btl_portals4.c
Labels: RM approved, Target: v3.0.x, bug

#5080 odls/base: fix support for PMIx < v2.1
  orte/mca/odls/base/odls_base_default_fns.c
Labels: Target: master, bug

#5038 fcoll/dynamic_gen2: Reduce number of realloc calls
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
Labels: Target: master, enhancement

#5030 v2.x: configury: use javac vs javah whenever possible
  config/opal_setup_java.m4
  ompi/mpi/java/java/Makefile.am
Labels: NEWS, RM approved, Target: v2.x, enhancement

#5104 fortran/tkr: Fix Makefile.am warnings
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Labels: bug

#5093 Topic/io configury
  config/ompi_check_lustre.m4
  config/ompi_check_pvfs2.m4
  ompi/mca/fs/lustre/configure.m4
  ompi/mca/fs/pvfs2/configure.m4
  ompi/mca/fs/ufs/configure.m4
Labels: Target: master, Target: v4.0.x

#5103 Fix external PMIx v1.2.5 support
  opal/mca/pmix/ext1x/pmix1x.h
  opal/mca/pmix/ext1x/pmix1x_client.c
  opal/mca/pmix/ext1x/pmix1x_component.c
Labels: Target: master, bug, critical

#4862 configury: fix PMI detection
  config/opal_check_pmi.m4
Labels: NEWS, RM approved, Target: v2.x, bug

#5102 fortran: build MPI_Sizeof() interface in use-mpi-tkr bindings
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Labels: NEWS, RM approved, Target: v2.x, bug, critical

#5107 pmix/ext1x: fix index handling when populating an info array
  opal/mca/pmix/ext1x/pmix1x_client.c
Labels: Target: master, bug

#5101 fortran: build MPI_Sizeof() interface in use-mpi-tkr bindings
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Labels: NEWS, Target: v3.0.x, bug, critical

#5081 Fix support for external PMIx v2.0 with legacy PMIx_Get()
  opal/mca/pmix/ext1x/pmix1x.c
  opal/mca/pmix/ext1x/pmix1x_client.c
  opal/mca/pmix/pmix.h
  opal/mca/pmix/pmix2x/pmix2x.c
  opal/mca/pmix/pmix2x/pmix2x.h
  opal/mca/pmix/pmix2x/pmix2x_client.c
  opal/mca/pmix/pmix2x/pmix2x_component.c
  orte/mca/grpcomm/direct/grpcomm_direct.c
  orte/mca/odls/base/odls_base_default_fns.c
  orte/mca/plm/base/plm_base_launch_support.c
  orte/mca/state/dvm/state_dvm.c
  orte/orted/orted_main.c
Labels: Target: v3.1.x, bug

#5100 fortran: build MPI_Sizeof() interface in use-mpi-tkr bindings
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Labels: NEWS, Target: v3.1.x, bug, critical

#5109 fortran/tkr: Fix Makefile.am warnings
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
Labels: NEWS, RM approved, Target: v2.x, bug

#5106 Fix external PMIx v1.2.5 support
  opal/mca/pmix/ext1x/pmix1x.h
  opal/mca/pmix/ext1x/pmix1x_client.c
  opal/mca/pmix/ext1x/pmix1x_component.c
Labels: Target: v3.1.x, blocker, bug

#5112 dist: Set version to 3.1.0rc6
  VERSION
Labels: Target: v3.1.x, blocker

#5015 config/opal_setup_java.m4: Improve JDK Tool Path Resolution on OS X/macOS
  config/opal_setup_java.m4
Labels: Target: master, java bindings

#5003 ompi/oshmem: fix shmem_free to perform no-op on null ptr
  oshmem/shmem/c/shmem_free.c
Labels: Target: master, bug, minor
