Repository open-mpi/ompi, pull requests merged in 2018-07, with the labels that each got.

#5345 PML/UCX: suppressed compilation warning
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: master, enhancement

#5355 MCA/ATOMICS/UCX: workaround for abstraction violation
  oshmem/mca/atomic/ucx/Makefile.am
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: Target: master, enhancement

#5309 Try to debug the MTT failures
  opal/mca/pmix/pmix2x/pmix2x.c
  opal/mca/pmix/pmix2x/pmix2x.h
Labels: Target: v3.1.x, bug

#5331 v3.1.x: btl/tcp: use a hash map for kernel IP interface indexes
  opal/mca/btl/tcp/btl_tcp_proc.c
Labels: NEWS, Target: v3.1.x, bug, code cleanup

#5330 v3.0.x: btl/tcp: use a hash map for kernel IP interface indexes
  opal/mca/btl/tcp/btl_tcp_proc.c
Labels: NEWS, Target: v3.0.x, bug, code cleanup

#5364 btl/ugni: update BTL_VERBOSE argument list
  opal/mca/btl/ugni/btl_ugni_component.c
  opal/mca/btl/ugni/btl_ugni_device.h
Labels: Target: master, bug

#5368 btl/vader: add support for atomics and emulated rdma
  opal/mca/btl/btl.h
  opal/mca/btl/vader/Makefile.am
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_atomic.c
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_frag.h
  opal/mca/btl/vader/btl_vader_get.c
  opal/mca/btl/vader/btl_vader_put.c
  opal/mca/btl/vader/btl_vader_sc_emu.c
Labels: Target: master, Target: v4.0.x

#5369 btl/ugni: fix race condition in completing frags
  opal/mca/btl/ugni/btl_ugni_frag.h
Labels: Target: master, bug

#5366 MCA/COMMON/UCX: minor unification of del_proces calls
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: master, enhancement

#5339 SHMEM/ATOMIC: refactoring of module API
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/atomic/atomic.h
  oshmem/mca/atomic/base/atomic_base_select.c
  oshmem/mca/atomic/basic/Makefile.am
  oshmem/mca/atomic/basic/atomic_basic.h
  oshmem/mca/atomic/basic/atomic_basic_cswap.c
  oshmem/mca/atomic/basic/atomic_basic_fadd.c
  oshmem/mca/atomic/basic/atomic_basic_module.c
  oshmem/mca/atomic/mxm/atomic_mxm.h
  oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
  oshmem/mca/atomic/mxm/atomic_mxm_fadd.c
  oshmem/mca/atomic/mxm/atomic_mxm_module.c
  oshmem/mca/atomic/ucx/Makefile.am
  oshmem/mca/atomic/ucx/atomic_ucx.h
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/op/op.c
  oshmem/op/op.h
  oshmem/shmem/c/shmem_add.c
  oshmem/shmem/c/shmem_cswap.c
  oshmem/shmem/c/shmem_fadd.c
  oshmem/shmem/c/shmem_fetch.c
  oshmem/shmem/c/shmem_finc.c
  oshmem/shmem/c/shmem_inc.c
  oshmem/shmem/c/shmem_lock.c
  oshmem/shmem/c/shmem_set.c
  oshmem/shmem/c/shmem_swap.c
  oshmem/shmem/fortran/bindings.h
  oshmem/shmem/fortran/shmem_int4_add_f.c
  oshmem/shmem/fortran/shmem_int4_cswap_f.c
  oshmem/shmem/fortran/shmem_int4_fadd_f.c
  oshmem/shmem/fortran/shmem_int4_fetch_f.c
  oshmem/shmem/fortran/shmem_int4_finc_f.c
  oshmem/shmem/fortran/shmem_int4_inc_f.c
  oshmem/shmem/fortran/shmem_int4_set_f.c
  oshmem/shmem/fortran/shmem_int4_swap_f.c
  oshmem/shmem/fortran/shmem_int8_add_f.c
  oshmem/shmem/fortran/shmem_int8_cswap_f.c
  oshmem/shmem/fortran/shmem_int8_fadd_f.c
  oshmem/shmem/fortran/shmem_int8_fetch_f.c
  oshmem/shmem/fortran/shmem_int8_finc_f.c
  oshmem/shmem/fortran/shmem_int8_inc_f.c
  oshmem/shmem/fortran/shmem_int8_set_f.c
  oshmem/shmem/fortran/shmem_int8_swap_f.c
  oshmem/shmem/fortran/shmem_real4_fetch_f.c
  oshmem/shmem/fortran/shmem_real4_set_f.c
  oshmem/shmem/fortran/shmem_real4_swap_f.c
  oshmem/shmem/fortran/shmem_real8_fetch_f.c
  oshmem/shmem/fortran/shmem_real8_set_f.c
  oshmem/shmem/fortran/shmem_real8_swap_f.c
  oshmem/shmem/fortran/shmem_swap_f.c
Labels: Target: master, code cleanup, enhancement

#5378 MCA/COMMON/UCX: unified logging across all UCX modules
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: master, code cleanup

#5389 hwloc/external: Suppress missing-include-dirs warning
  opal/mca/hwloc/external/configure.m4
Labels: Target: master, code cleanup

#5390 coll/libnbc: fix integer overflow
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: Target: master, bug

#5373 btl/ugni: fix race condition in completing frags
  opal/mca/btl/ugni/btl_ugni_frag.h
Labels: Target: v3.0.x, bug

#5372 btl/ugni: fix race condition in completing frags
  opal/mca/btl/ugni/btl_ugni_frag.h
Labels: RM approved, Target: v3.1.x, bug

#5300 oob/ud: remove as it has bitrotted
  orte/mca/oob/ud/Makefile.am
  orte/mca/oob/ud/configure.m4
  orte/mca/oob/ud/help-oob-ud.txt
  orte/mca/oob/ud/oob_ud.c
  orte/mca/oob/ud/oob_ud.h
  orte/mca/oob/ud/oob_ud_component.c
  orte/mca/oob/ud/oob_ud_component.h
  orte/mca/oob/ud/oob_ud_event.c
  orte/mca/oob/ud/oob_ud_peer.c
  orte/mca/oob/ud/oob_ud_peer.h
  orte/mca/oob/ud/oob_ud_ping.c
  orte/mca/oob/ud/oob_ud_ping.h
  orte/mca/oob/ud/oob_ud_qp.c
  orte/mca/oob/ud/oob_ud_qp.h
  orte/mca/oob/ud/oob_ud_recv.c
  orte/mca/oob/ud/oob_ud_req.c
  orte/mca/oob/ud/oob_ud_req.h
  orte/mca/oob/ud/oob_ud_send.c
  orte/mca/oob/ud/oob_ud_send.h
  orte/mca/oob/ud/owner.txt
Labels: Target: master, code cleanup

#5403 Fix output of XPMEM detection in configure summary
  config/opal_check_xpmem.m4
Labels: Target: master, bug

#5374 opal/fifo: fix 128-bit atomic fifo on Power9
  opal/class/opal_fifo.h
  opal/class/opal_lifo.h
Labels: Target: master, bug

#5407 osc/rdma: fix bug introduced in b90c838
  ompi/mca/osc/rdma/osc_rdma_request.c
Labels: Target: master, blocker, bug, critical

#5401 MCA/ATOMICS/UCX: workaround for abstraction violation - v3.0
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
  oshmem/mca/spml/ucx/Makefile.am
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: RM approved, Target: v3.0.x, bug

#5412 osc/sm: avoid filename collision when multiple windows share same CID
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: master, bug

#5410 v3.0: osc/rdma: fix bug introduced in b90c838
  ompi/mca/osc/rdma/osc_rdma_request.c
Labels: RM approved, Target: v3.0.x, blocker, bug, critical

#5409 v2.1: osc/rdma: fix bug introduced in b90c838
  ompi/mca/osc/rdma/osc_rdma_request.c
Labels: RM approved, Target: v2.x, blocker, bug, critical

#5415 pml/ob1: Fix data corruption of MPI_BSEND
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
Labels: bug

#5416 coll/libnbc: Suppress compiler warnings
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
  ompi/mca/coll/libnbc/nbc_ialltoallw.c
Labels: Target: master, code cleanup

#4765 OMPI/OSC/UCX: move memory hooks init in osc to win creation.
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: master, enhancement

#5079 status_set_cancelled: fix F08 binding
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.F90
  ompi/mpi/fortran/use-mpi-f08/mod/pmpi-f08-interfaces.F90
  ompi/mpi/fortran/use-mpi-f08/profile/pstatus_set_cancelled_f08.F90
  ompi/mpi/fortran/use-mpi-f08/status_set_cancelled_f08.F90
Labels: Target: master, bug

#5419 v3.0.x: opal/fifo: fix 128-bit atomic fifo on Power9
  opal/class/opal_fifo.h
  opal/class/opal_lifo.h
Labels: Target: v3.0.x, bug

#5418 v3.1: opal/fifo: fix 128-bit atomic fifo on Power9
  opal/class/opal_fifo.h
  opal/class/opal_lifo.h
Labels: Target: v3.1.x, bug

#5411 v3.1: osc/rdma: fix bug introduced in b90c838
  ompi/mca/osc/rdma/osc_rdma_request.c
Labels: RM approved, Target: v3.1.x, blocker, bug, critical

#5386 v3.1.x: Update to PMIx v2.1.2
  ompi/errhandler/errcode-internal.h
  ompi/runtime/ompi_mpi_init.c
  opal/mca/btl/usnic/btl_usnic_hwloc.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/pmix/pmix2x/pmix/LICENSE
  opal/mca/pmix/pmix2x/pmix/NEWS
  opal/mca/pmix/pmix2x/pmix/README
  opal/mca/pmix/pmix2x/pmix/VERSION
  opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
  opal/mca/pmix/pmix2x/pmix/test/simple/Makefile.am
  opal/mca/pmix/pmix2x/pmix/test/simple/quietclient.c
  opal/mca/pmix/pmix2x/pmix/test/simple/simptest.h
  opal/mca/pmix/pmix2x/pmix/test/simple/stability.c
  opal/mca/pmix/pmix2x/pmix2x_server_north.c
  orte/mca/iof/base/iof_base_frame.c
  orte/mca/odls/base/odls_base_default_fns.c
  orte/orted/pmix/pmix_server_gen.c
  orte/util/proc_info.c
Labels: RM approved, Target: v3.1.x, bug

#5381 MCA/MTL/MXM: fixed symbol duplicates
  ompi/mca/mtl/mxm/mtl_mxm_types.h
Labels: Target: v3.1.x

#5380 MCA/ATOMICS/UCX: workaround for abstraction violation - v3.1
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
  oshmem/mca/spml/ucx/Makefile.am
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: RM approved, Target: v3.1.x, bug

#5425 ATOMIC/MXM: fixed abstraction violation
  oshmem/mca/atomic/mxm/Makefile.am
  oshmem/mca/atomic/mxm/atomic_mxm.h
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
Labels: Target: master

#5323 coll/base: add MPI_Bcast based on a binomial tree scatter followed by a ring allgather
  ompi/mca/coll/base/coll_base_bcast.c
  ompi/mca/coll/base/coll_base_functions.h
  ompi/mca/coll/tuned/coll_tuned_bcast_decision.c
Labels: Target: master

#5423 ATOMICS: renamed atomic calls to unsigned datatypes
  oshmem/include/pshmem.h
  oshmem/include/pshmemx.h
  oshmem/include/shmem.h.in
  oshmem/include/shmemx.h
  oshmem/mca/atomic/atomic.h
  oshmem/shmem/c/profile/defines.h
  oshmem/shmem/c/shmem_and.c
  oshmem/shmem/c/shmem_fand.c
  oshmem/shmem/c/shmem_for.c
  oshmem/shmem/c/shmem_fxor.c
  oshmem/shmem/c/shmem_or.c
  oshmem/shmem/c/shmem_xor.c
Labels: Target: master

#5417 v2.x: MCA/ATOMICS/UCX: workaround for abstraction violation - v2.x
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_fadd.c
  oshmem/mca/spml/ucx/Makefile.am
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: RM approved, Target: v2.x

#5424 ATOMIC/MXM: fixed abstraction violation - v3.1
  oshmem/mca/atomic/mxm/Makefile.am
  oshmem/mca/atomic/mxm/atomic_mxm.h
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
Labels: Target: v3.1.x

#5435 mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)
  ompi/mpi/fortran/mpif-h/iscatter_f.c
  ompi/mpi/fortran/mpif-h/iscatterv_f.c
Labels: Target: master, bug

#5440 ATOMIC: fixed build issues (incorrect function proto)
  oshmem/include/pshmem.h
  oshmem/include/shmem.h.in
Labels: Target: master, bug

#5353 io/romio321: make grequest extensions internal
  ompi/include/mpi.h.in
  ompi/mca/io/romio321/configure.m4
  ompi/mca/io/romio321/romio/configure.ac
  ompi/mca/io/romio321/romio/include/ompi_grequestx.h
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/grequestx_class_allocate.c
  ompi/mpi/c/grequestx_class_create.c
  ompi/mpi/c/grequestx_start.c
  ompi/mpi/c/profile/Makefile.am
  ompi/request/grequest.h
  ompi/request/grequestx.c
  ompi/request/grequestx.h
Labels: Target: master, bug, enhancement

#5397 MTL OFI: Redesign sync send with reduced tag bits and quick ack
  ompi/mca/mtl/ofi/README
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: master, enhancement

#5441 MCA/COMMON/UCX: shift opal memhooks into common UCX
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
  opal/mca/common/ucx/Makefile.am
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: code cleanup

#5448 btl/ofi: Added FI_CONTEXT as requirement.
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: master, bug

#5414 btl/openib: only look for iwarp/roce by default
  opal/mca/btl/openib/btl_openib.h
  opal/mca/btl/openib/btl_openib_component.c
  opal/mca/btl/openib/btl_openib_mca.c
  opal/mca/btl/openib/help-mpi-btl-openib.txt
Labels: NEWS

#5444 io/ompio: Call component-specific file_delete function instead of POSIX unlink
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/fs/base/fs_base_file_delete.c
  ompi/mca/fs/lustre/fs_lustre.c
  ompi/mca/fs/pvfs2/fs_pvfs2.c
Labels: Target: master

#5402 MCA/COMMON/UCX: del_procs calls are unified to common module
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: master, code cleanup

#5452 OSC/UCX: fixed hang on OSC init
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: master, bug

#5456 Default to internal PMIx if newer than external
  config/opal_check_pmi.m4
  opal/mca/pmix/ext1x/configure.m4
Labels: Target: v4.0.x, Target: v5.0.x, bug

#5455 OSC/UCX: fixed hang on OSC UCX init - v4.0
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: bug

#5461 PML/UCX: fixed ucp request free on persistent request completion
  ompi/mca/pml/ucx/pml_ucx_request.c
Labels: Target: master, bug

#5446 MTL OFI: MTL_OFI_RETRY_UNTIL_DONE support for Resource overflow
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: master, bug

#5458 Default to internal PMIx if newer than external
  config/opal_check_pmi.m4
  opal/mca/pmix/ext1x/configure.m4
  orte/orted/pmix/pmix_server_gen.c
Labels: RM approved, Target: v4.0.x, bug

#5395 Change defaults to prefer external libevent/hwloc
  opal/mca/event/configure.m4
  opal/mca/event/external/configure.m4
  opal/mca/hwloc/external/configure.m4
  opal/mca/hwloc/hwloc201/configure.m4
Labels: Target: master, Target: v4.0.x, enhancement, help wanted

#5462 PML/UCX: fixed ucp request free on persistent request completion - v4.0
  ompi/mca/pml/ucx/pml_ucx_request.c
Labels: RM approved, Target: v4.0.x, bug

#5434 v3.0.x: osc/sm: avoid filename collision when multiple windows share same CID
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: v3.0.x, bug

#5428 v3.0.x: Allow support for PMIx versions > 2
  config/opal_check_pmi.m4
  opal/mca/pmix/pmix2x/pmix/NEWS
  opal/mca/pmix/pmix2x/pmix/VERSION
  opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix2x/pmix/include/pmix_version.h.in
  opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c
  opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v3.0.x, bug

#5463 PML/UCX: fixed ucp request free on persistent request completion - v3.1
  ompi/mca/pml/ucx/pml_ucx_request.c
Labels: Target: v3.1.x, bug

#5433 v3.1.x: osc/sm: avoid filename collision when multiple windows share same CID
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: v3.1.x, bug

#5429 v3.1.x: Support PMIx versions > 2
  config/opal_check_pmi.m4
  opal/mca/pmix/pmix2x/pmix/NEWS
  opal/mca/pmix/pmix2x/pmix/VERSION
  opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix2x/pmix/include/pmix_version.h.in
  opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_notification.c
  opal/mca/pmix/pmix2x/pmix/src/event/pmix_event_registration.c
  opal/mca/pmix/pmix2x/pmix2x.c
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v3.1.x, bug

#5468 MTL OFI: Add support for mem_tag_format
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: master, enhancement

#5464 VERSION: move master to 4.1
  VERSION
Labels: Target: master

#5475 MCA/ATOMIC: atomic_init renamed to atomic_startup - v4.0
  oshmem/mca/atomic/atomic.h
  oshmem/mca/atomic/base/atomic_base_available.c
  oshmem/mca/atomic/basic/atomic_basic.h
  oshmem/mca/atomic/basic/atomic_basic_component.c
  oshmem/mca/atomic/basic/atomic_basic_module.c
  oshmem/mca/atomic/mxm/atomic_mxm.h
  oshmem/mca/atomic/mxm/atomic_mxm_component.c
  oshmem/mca/atomic/mxm/atomic_mxm_module.c
  oshmem/mca/atomic/ucx/atomic_ucx.h
  oshmem/mca/atomic/ucx/atomic_ucx_component.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
Labels: RM approved, Target: v4.0.x

#5483 Fix the map-by modifier parsing
  .gitignore
  opal/mca/pmix/ext2x/ext2x_component.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
  orte/mca/rmaps/base/rmaps_base_frame.c
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: Target: master, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#5474 coll/base/allgather: fix MPI_IN_PLACE processing
  ompi/mca/coll/base/coll_base_allgather.c
Labels: RM approved, Target: v4.0.x

#5480 PML/SPML/UCX: init global objects using C99 style
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: enhancement

#5496 opal/atomic.h: prevent preprocessor macro redefinition
  opal/include/opal/sys/sync_builtin/atomic.h
Labels: RM approved, code cleanup

#5476 MTL OFI: Fix Deadlock in fi_cancel given completion during cancel
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug

#5467 MTL OFI: MTL_OFI_RETRY_UNTIL_DONE support for Resource overflow
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: RM approved, Target: v4.0.x, bug

#5477 MTL OFI: send/isend split into blocking/non-blocking paths
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: master, performance
