Repository open-mpi/ompi, pull requests merged in 2018-08, with the labels that each got.

#5506 v2.x: errhandler_predefined: remove erroneous assert()
  ompi/errhandler/errhandler_predefined.c
Labels: Target: v2.x, bug, critical

#5495 PML/SPML/UCX: init global objects using C99 style - v4.0
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: RM approved, Target: v4.0.x, enhancement

#5439 v3.0.x: mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)
  ompi/mpi/fortran/mpif-h/iscatter_f.c
  ompi/mpi/fortran/mpif-h/iscatterv_f.c
Labels: RM approved, Target: v3.0.x, bug, fortran bindings

#5422 v3.0.x update vader to favor /dev/shm for backing files
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
Labels: NEWS, RM approved, Target: v3.0.x, bug

#5509 v2.1.4 updates: VERSION, NEWS, AUTHORS
  .mailmap
  AUTHORS
  NEWS
  README
  VERSION
Labels: blocker, documentation

#5398 coll/libnbc: fix integer overflow
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: NEWS, Target: v3.0.x, bug

#5399 coll/libnbc: fix integer overflow
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: Target: v3.1.x, bug

#5438 v3.1.x: mpi/fortran: Fix IN_PLACE detection of ISCATTER(V)
  ompi/mpi/fortran/mpif-h/iscatter_f.c
  ompi/mpi/fortran/mpif-h/iscatterv_f.c
Labels: Target: v3.1.x, bug, fortran bindings

#5437 v3.0.x: pml/ob1: Fix data corruption of MPI_BSEND
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
Labels: RM approved, Target: v3.0.x, bug

#5499 MTL OFI: Fix Deadlock in fi_cancel given completion during cancel
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v4.0.x, bug

#5436 v3.1.x: pml/ob1: Fix data corruption of MPI_BSEND
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
Labels: RM approved, Target: v3.1.x, bug

#5521 v3.0.x: coll-portals4: retry PtlMEUnlink() if PTL_IN_USE
  ompi/mca/coll/portals4/coll_portals4_allreduce.c
  ompi/mca/coll/portals4/coll_portals4_barrier.c
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/coll/portals4/coll_portals4_gather.c
  ompi/mca/coll/portals4/coll_portals4_reduce.c
  ompi/mca/coll/portals4/coll_portals4_scatter.c
Labels: Target: v3.0.x, bug

#5522 v3.1.x: coll-portals4: retry PtlMEUnlink() if PTL_IN_USE
  ompi/mca/coll/portals4/coll_portals4_allreduce.c
  ompi/mca/coll/portals4/coll_portals4_barrier.c
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/coll/portals4/coll_portals4_gather.c
  ompi/mca/coll/portals4/coll_portals4_reduce.c
  ompi/mca/coll/portals4/coll_portals4_scatter.c
Labels: Target: v3.1.x, bug

#5526 Fix script abstraction break: mv make_manpage.pl to config
  Makefile.ompi-rules
  config/Makefile.am
  config/make_manpage.pl
  ompi/mpi/Makefile.am
Labels: Target: master, bug

#5527 External internal hwloc libevent fixes
  opal/mca/event/libevent2022/configure.m4
  opal/mca/hwloc/hwloc201/configure.m4
Labels: Target: master, bug

#5531 VERSION: Update to v2.1.5a1
  VERSION
Labels: RM approved, documentation

#5533 Fix internal/external hwloc and libevent
  opal/mca/event/libevent2022/configure.m4
  opal/mca/hwloc/hwloc201/configure.m4
Labels: Target: master, Target: v4.0.x, bug

#5504 MTL OFI: send/isend split into blocking/non-blocking paths
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: RM approved, Target: v4.0.x, bug

#5536 btl/vader: move memory barrier to where it belongs
  opal/mca/btl/vader/btl_vader_fbox.h
Labels: Target: master, bug

#5537 v3.1.x: Backport threadshift for show_help messages
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v3.1.x, bug

#5538 v3.0.x: Backport threadshift for show_help messages
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v3.0.x, bug

#5534 BUILD: fixed PML UCX build for v2.x branch
  ompi/mca/pml/ucx/Makefile.am
Labels: RM approved, Target: v2.x

#5542 v2.x: btl/vader: move memory barrier to where it belongs
  opal/mca/btl/vader/btl_vader_fbox.h
Labels: RM approved, bug

#5541 v3.1.x: btl/vader: move memory barrier to where it belongs
  opal/mca/btl/vader/btl_vader_fbox.h
Labels: bug

#5549 v2.1.5: looks like this will be needed after all
  NEWS
  VERSION
Labels: Target: v2.x, blocker, bug

#5472 v4.0.x: Prefer external hwloc and libevent
  opal/mca/event/configure.m4
  opal/mca/event/external/configure.m4
  opal/mca/event/libevent2022/configure.m4
  opal/mca/hwloc/external/configure.m4
  opal/mca/hwloc/hwloc201/configure.m4
Labels: NEWS, Target: v4.0.x, enhancement

#5471 btl/uct: fix compile warnings/errors
  opal/mca/btl/uct/btl_uct.h
  opal/mca/btl/uct/btl_uct_am.h
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/btl/uct/btl_uct_endpoint.c
  opal/mca/btl/uct/btl_uct_endpoint.h
  opal/mca/btl/uct/btl_uct_module.c
  opal/mca/btl/uct/btl_uct_tl.c
  opal/mca/btl/uct/configure.m4
Labels: Target: v4.0.x, bug

#5552 fortran/use TKR: remove excess declaration for PMPI_Type_extent
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
Labels: Target: master, Target: v4.0.x, bug

#5539 ompio: support for DDN's Infinite Memory Engine
  LICENSE
  config/ompi_check_ime.m4
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/fbtl/ime/Makefile.am
  ompi/mca/fbtl/ime/configure.m4
  ompi/mca/fbtl/ime/fbtl_ime.c
  ompi/mca/fbtl/ime/fbtl_ime.h
  ompi/mca/fbtl/ime/fbtl_ime_blocking_op.c
  ompi/mca/fbtl/ime/fbtl_ime_component.c
  ompi/mca/fbtl/ime/fbtl_ime_nonblocking_op.c
  ompi/mca/fbtl/ime/owner.txt
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/ime/Makefile.am
  ompi/mca/fs/ime/configure.m4
  ompi/mca/fs/ime/fs_ime.c
  ompi/mca/fs/ime/fs_ime.h
  ompi/mca/fs/ime/fs_ime_component.c
  ompi/mca/fs/ime/fs_ime_file_close.c
  ompi/mca/fs/ime/fs_ime_file_delete.c
  ompi/mca/fs/ime/fs_ime_file_get_size.c
  ompi/mca/fs/ime/fs_ime_file_open.c
  ompi/mca/fs/ime/fs_ime_file_set_size.c
  ompi/mca/fs/ime/fs_ime_file_sync.c
  ompi/mca/fs/ime/owner.txt
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: master

#5561 common/ompio: fix an ordering problem during file_open
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: Target: master, bug

#5550 Update NEWS for 3.1.2rc2
  NEWS
Labels: Target: v3.1.x

#5555 v4.0.x/pmix: added check for pmix fence status
  ompi/dpm/dpm.c
  ompi/mca/bml/r2/bml_r2_ft.c
  ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c
  ompi/mca/pml/bfo/pml_bfo.c
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/yalla/pml_yalla.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  orte/mca/ess/pmi/ess_pmi_module.c
  orte/mca/snapc/full/snapc_full_app.c
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: RM approved, Target: v4.0.x, bug

#5571 dist: Update NEWS with 2.1.5 updates
  NEWS
Labels: Target: master

#5572 osc/pt2pt: use c99 for module initialization
  ompi/mca/osc/pt2pt/osc_pt2pt_component.c
Labels: Target: master

#5574 dist: Update NEWS with 2.1.5 updates
  NEWS
Labels: Target: v3.1.x

#5573 dist: bump version to 3.1.2rc2
  VERSION
Labels: Target: v3.1.x

#5486 Cleanup pmix selection and map-by modifiers
  opal/mca/pmix/ext2x/ext2x_component.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
  orte/mca/rmaps/base/rmaps_base_frame.c
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: NEWS, RM approved, Target: v4.0.x, bug

#5553 snprintf() length fix for info
  opal/util/info.c
Labels: Target: master

#5503 MTL OFI: Fix race condition due to global progress entries array
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: master

#5579 dist: Update VERSION to 3.1.3a1
  VERSION
Labels: Target: v3.1.x

#5576 OSHMEM/API/C11: fixed API macro
  oshmem/include/pshmem.h
  oshmem/include/shmem.h.in
  oshmem/runtime/runtime.h
Labels: Target: master

#5580 OSHMEM/API/C11: fixed API macro - v4.0
  oshmem/include/pshmem.h
  oshmem/include/shmem.h.in
  oshmem/runtime/runtime.h
Labels: RM approved, Target: v4.0.x, bug, critical

#5577 btl/vader: clean up debuging and squash warning
  opal/mca/btl/vader/btl_vader_sc_emu.c
Labels: Target: master, bug

#5589 config: remove OPAL_ENABLE_MULTI_THREADS config macro
  config/opal_config_threads.m4
  ompi/mca/pml/ob1/pml_ob1_comm.h
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
  ompi/mca/pml/ob1/pml_ob1_start.c
  orte/tools/orte-info/param.c
  test/threads/opal_thread.c
Labels: Target: master, code cleanup

#5592 btl/vader: clean up debuging and squash warning
  opal/mca/btl/vader/btl_vader_sc_emu.c
Labels: bug

#5485 Fix the multiple pe/proc option
  orte/mca/rmaps/base/rmaps_base_frame.c
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: Target: v3.1.x, bug

#5556 v3.1.x/pmix: added check for pmix fence status
  ompi/dpm/dpm.c
  ompi/mca/bml/r2/bml_r2_ft.c
  ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c
  ompi/mca/pml/bfo/pml_bfo.c
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/yalla/pml_yalla.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  orte/mca/ess/pmi/ess_pmi_module.c
  orte/mca/snapc/full/snapc_full_app.c
Labels: Target: v3.1.x, bug

#5557 v3.0.x/pmix: added check for pmix fence status
  ompi/dpm/dpm.c
  ompi/mca/bml/r2/bml_r2_ft.c
  ompi/mca/crcp/bkmrk/crcp_bkmrk_pml.c
  ompi/mca/pml/bfo/pml_bfo.c
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/yalla/pml_yalla.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  orte/mca/ess/pmi/ess_pmi_module.c
  orte/mca/snapc/full/snapc_full_app.c
Labels: Target: v3.0.x, bug

#5484 Fix the multiple pe/proc option
  orte/mca/rmaps/base/rmaps_base_frame.c
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: NEWS, Target: v3.0.x, bug

#5586 OSHMEM: removed incorrect pshmem_wait_until macro redefinition
  oshmem/shmem/c/profile/defines.h
Labels: Target: master

#5497 v4.0.x: apply romio314 patch to romio321
  ompi/mca/io/romio321/romio/mpi-io/mpioimpl.h
Labels: RM approved, Target: v4.0.x, bug

#5519 fcntl include bugfix
  opal/util/stacktrace.c
Labels: Target: master, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x

#5590 MTL OFI: Ask for FI_THREAD_DOMAIN support as needed
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: master

#5591 osc/rdma: clean out stale aggregation code
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_comm.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_peer.h
  ompi/mca/osc/rdma/osc_rdma_sync.c
  ompi/mca/osc/rdma/osc_rdma_sync.h
  ompi/mca/osc/rdma/osc_rdma_types.h
Labels: Target: master, code cleanup

#5587 PML/UCX/BUILD: fix for build on non-default UCX location
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/Makefile.am
Labels: RM approved, Target: v2.0.x

#5603 v3.0.x: add missing #ifdef protection around header files
  opal/util/stacktrace.c
  test/util/opal_path_nfs.c
Labels: RM approved, Target: v3.0.x, bug, code cleanup

#5598 v4.0.x: Allow run-as-root if 2 envars are set
  orte/orted/orted_submit.c
  orte/tools/orterun/orterun.1in
Labels: NEWS, RM approved, Target: v4.0.x, enhancement

#5602 v3.1.x: add missing #ifdef protection around header files
  opal/util/stacktrace.c
  test/util/opal_path_nfs.c
Labels: RM approved, Target: v3.1.x, bug, code cleanup

#5582 v2.0.x: osc/rdma: fix a segfault in MPI_Win_unlock due to an access to a NULL…
  ompi/mca/osc/rdma/osc_rdma_lock.h
Labels: RM approved, Target: v2.0.x

#5596 Fixed the NUMA obj detection for hwloc ver >= 2.0.0
  opal/mca/hwloc/base/hwloc_base_util.c
  orte/mca/rmaps/mindist/rmaps_mindist_module.c
Labels: Target: master, bug

#5612 io/base: fixes to file_delete selection logic
  ompi/mca/io/base/io_base_delete.c
Labels: Target: master, Target: v4.0.x, bug

#5601 v4.0.x: add missing #ifdef protection around header files
  opal/util/stacktrace.c
  test/util/opal_path_nfs.c
Labels: RM approved, Target: v4.0.x, bug, code cleanup

#5546 Fix the detection of 128 bits atomics.
  config/opal_config_asm.m4
  config/opal_functions.m4
Labels: Target: master, blocker, bug

#5623 odls/alps: resolve hang when launching with mpirun on Crays
  orte/mca/odls/alps/odls_alps_module.c
Labels: Target: master, bug

#5570 MCA/COMMON/UCX: added synonym to opal_mem_hook variable
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/atomic/ucx/atomic_ucx_component.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: master

#5624 Plug misc finalize leaks on finalize
  ompi/info/info.c
  ompi/mca/hook/base/hook_base.c
  ompi/mca/mtl/psm2/mtl_psm2_component.c
  ompi/mca/pml/ob1/pml_ob1_component.c
  opal/mca/mpool/memkind/mpool_memkind_component.c
  opal/mca/pmix/base/pmix_base_select.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
  opal/util/info_subscriber.c
  orte/mca/ess/hnp/ess_hnp_module.c
Labels: Target: master

#5632 common/verbs-usnic: check that it will actually compile
  opal/mca/common/verbs_usnic/configure.m4
Labels: Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#5627 odls/alps: resolve hang when launching with mpirun on Crays
  orte/mca/odls/alps/odls_alps_module.c
Labels: RM approved, Target: v4.0.x, bug

#5633 README: Add note about --with-verbs-usnic
  README
Labels: Target: master, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, documentation

#5565 Update to PMIx 3.0.1
  .gitignore
  opal/include/opal/constants.h
  opal/mca/pmix/ext1x/pmix1x.c
  opal/mca/pmix/ext2x/ext2x.c
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/include/pmix_common.h.in
  opal/mca/pmix/pmix3x/pmix/include/pmix_version.h.in
  opal/mca/pmix/pmix3x/pmix/src/common/pmix_control.c
  opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_dstore.c
  opal/mca/pmix/pmix3x/pmix/src/mca/psensor/base/psensor_base_stubs.c
  opal/mca/pmix/pmix3x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.c
  opal/mca/pmix/pmix3x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat.h
  opal/mca/pmix/pmix3x/pmix/src/mca/psensor/heartbeat/psensor_heartbeat_component.c
  opal/mca/pmix/pmix3x/pmix/src/server/pmix_server.c
  opal/mca/pmix/pmix3x/pmix/src/server/pmix_server_ops.c
  opal/mca/pmix/pmix3x/pmix/test/simple/Makefile.am
  opal/mca/pmix/pmix3x/pmix/test/simple/simpjctrl.c
  opal/mca/pmix/pmix3x/pmix/test/simple/simptest.c
  opal/mca/pmix/pmix3x/pmix3x.c
  opal/mca/pmix/pmix3x/pmix3x_client.c
  orte/include/orte/constants.h
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v4.0.x, bug

#5616 io/base: fixes to file_delete selection logic
  ompi/mca/io/base/io_base_delete.c
Labels: Target: v4.0.x, bug

#5622 MTL OFI: Fix race condition due to global progress entries array
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: bug

#5626 MCA/COMMON/UCX: added synonim to opal_mem_hook variable - v4.0
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/atomic/ucx/atomic_ucx_component.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v4.0.x

#5625 PML/UCX: blocked calls optimizations - v4.0
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: Target: v4.0.x
