Repository open-mpi/ompi, pull requests merged in 2018-02, with the labels that each got.

#4527 Remove inter-dependencies between OSC modules.
  ompi/mca/coll/monitoring/coll_monitoring_allgather.c
  ompi/mca/coll/monitoring/coll_monitoring_allgatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_allreduce.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoall.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoallv.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoallw.c
  ompi/mca/coll/monitoring/coll_monitoring_barrier.c
  ompi/mca/coll/monitoring/coll_monitoring_bcast.c
  ompi/mca/coll/monitoring/coll_monitoring_exscan.c
  ompi/mca/coll/monitoring/coll_monitoring_gather.c
  ompi/mca/coll/monitoring/coll_monitoring_gatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_allgather.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_allgatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoall.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoallv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoallw.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce_scatter.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce_scatter_block.c
  ompi/mca/coll/monitoring/coll_monitoring_scan.c
  ompi/mca/coll/monitoring/coll_monitoring_scatter.c
  ompi/mca/coll/monitoring/coll_monitoring_scatterv.c
  ompi/mca/common/monitoring/common_monitoring.h
  ompi/mca/common/monitoring/common_monitoring_coll.c
  ompi/mca/osc/monitoring/Makefile.am
  ompi/mca/osc/monitoring/configure.m4
  ompi/mca/osc/monitoring/osc_monitoring_accumulate.h
  ompi/mca/osc/monitoring/osc_monitoring_comm.h
  ompi/mca/osc/monitoring/osc_monitoring_component.c
  ompi/mca/osc/monitoring/osc_monitoring_module.h
  ompi/mca/osc/monitoring/osc_monitoring_template.h
  ompi/mca/pml/monitoring/pml_monitoring_isend.c
  ompi/mca/pml/monitoring/pml_monitoring_start.c
Labels: Target: master

#4791 mca/registry: fix problem group_component_register
  opal/mca/base/mca_base_var_group.c
Labels: NEWS, RM approved, Target: v3.0.x

#4787 v3.1: rmaps: fixed the ordering of `mpirun` target nodes
  orte/mca/rmaps/base/rmaps_base_support_fns.c
Labels: Target: v3.1.x, bug

#4783 MTL PSM2: Remove shadow variables from v3.1.x
  ompi/mca/mtl/psm2/mtl_psm2_component.c
  ompi/mca/mtl/psm2/mtl_psm2_types.h
Labels: RM approved, Target: v3.1.x, bug, performance

#4782 pmix/ext2x: generate component source when only static libraries are …
  opal/mca/pmix/ext2x/Makefile.am
Labels: RM approved, Target: v3.1.x, bug

#4731 OMPI/OSC/UCX: adding atomic lock for fetch_and_op and compare_and_swap
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: v3.1.x, bug

#4747 Cherry-pick regx framework
  orte/mca/dfs/orted/dfs_orted.c
  orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
  orte/mca/errmgr/default_orted/errmgr_default_orted.c
  orte/mca/errmgr/dvm/errmgr_dvm.c
  orte/mca/ess/alps/ess_alps_module.c
  orte/mca/ess/alps/ess_alps_utils.c
  orte/mca/ess/base/ess_base_fns.c
  orte/mca/ess/base/ess_base_std_orted.c
  orte/mca/ess/env/ess_env_module.c
  orte/mca/ess/hnp/ess_hnp_module.c
  orte/mca/ess/lsf/ess_lsf_module.c
  orte/mca/ess/pmi/ess_pmi_module.c
  orte/mca/ess/slurm/ess_slurm_module.c
  orte/mca/ess/tm/ess_tm_module.c
  orte/mca/grpcomm/base/grpcomm_base_stubs.c
  orte/mca/grpcomm/direct/grpcomm_direct.c
  orte/mca/odls/base/odls_base_default_fns.c
  orte/mca/plm/base/plm_base_frame.c
  orte/mca/plm/base/plm_base_launch_support.c
  orte/mca/plm/base/plm_private.h
  orte/mca/plm/rsh/plm_rsh_module.c
  orte/mca/regx/Makefile.am
  orte/mca/regx/base/Makefile.am
  orte/mca/regx/base/base.h
  orte/mca/regx/base/owner.txt
  orte/mca/regx/base/regx_base_default_fns.c
  orte/mca/regx/base/regx_base_frame.c
  orte/mca/regx/base/regx_base_select.c
  orte/mca/regx/fwd/Makefile.am
  orte/mca/regx/fwd/owner.txt
  orte/mca/regx/fwd/regx_fwd.c
  orte/mca/regx/fwd/regx_fwd.h
  orte/mca/regx/fwd/regx_fwd_component.c
  orte/mca/regx/regx.h
  orte/mca/regx/reverse/Makefile.am
  orte/mca/regx/reverse/owner.txt
  orte/mca/regx/reverse/regx_reverse.c
  orte/mca/regx/reverse/regx_reverse.h
  orte/mca/regx/reverse/regx_reverse_component.c
  orte/mca/routed/binomial/routed_binomial.c
  orte/mca/state/dvm/state_dvm.c
  orte/orted/orted_comm.c
  orte/orted/orted_main.c
  orte/runtime/orte_init.c
  orte/util/Makefile.am
  orte/util/help-regex.txt
  orte/util/nidmap.c
  orte/util/nidmap.h
  orte/util/regex.c
  orte/util/regex.h
Labels: RM approved, Target: v3.1.x, bug

#4746 Sync to PMIx v2.1.0
  opal/mca/pmix/pmix2x/pmix/NEWS
  opal/mca/pmix/pmix2x/pmix/VERSION
  opal/mca/pmix/pmix2x/pmix/etc/pmix-mca-params.conf
  opal/mca/pmix/pmix2x/pmix/examples/client.c
  opal/mca/pmix/pmix2x/pmix/include/pmi.h
  opal/mca/pmix/pmix2x/pmix/include/pmi2.h
  opal/mca/pmix/pmix2x/pmix/include/pmix_common.h.in
  opal/mca/pmix/pmix2x/pmix/include/pmix_rename.h.in
  opal/mca/pmix/pmix2x/pmix/src/Makefile.am
  opal/mca/pmix/pmix2x/pmix/src/atomics/sys/powerpc/atomic.h
  opal/mca/pmix/pmix2x/pmix/src/client/Makefile.include
  opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c
  opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_ops.h
  opal/mca/pmix/pmix2x/pmix/src/common/pmix_data.c
  opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.c
  opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.h
  opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_open.c
  opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_var.h
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/hash/gds_hash.c
  opal/mca/pmix/pmix2x/pmix/src/mca/preg/native/preg_native.c
  opal/mca/pmix/pmix2x/pmix/src/mca/psec/base/psec_base_select.c
  opal/mca/pmix/pmix2x/pmix/src/mca/psec/munge/Makefile.am
  opal/mca/pmix/pmix2x/pmix/src/mca/psec/munge/psec_munge.c
  opal/mca/pmix/pmix2x/pmix/src/mca/psec/none/psec_none.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/base.h
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_frame.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/usock/ptl_usock_component.c
  opal/mca/pmix/pmix2x/pmix/src/runtime/Makefile.include
  opal/mca/pmix/pmix2x/pmix/src/runtime/help-pmix-runtime.txt
  opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c
  opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_ops.c
  opal/mca/pmix/pmix2x/pmix/src/threads/Makefile.include
  opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
  opal/mca/pmix/pmix2x/pmix/src/util/output.c
  opal/mca/pmix/pmix2x/pmix/test/Makefile.am
  opal/mca/pmix/pmix2x/pmix/test/pmi2_client.c
  opal/mca/pmix/pmix2x/pmix/test/pmi_client.c
  opal/mca/pmix/pmix2x/pmix2x.h
Labels: Target: v3.1.x, bug

#4804 VERSION, etc. for rolling 2.1.3rc1
  NEWS
  README
  VERSION
Labels: RM approved, Target: v2.x, documentation

#4808 io/ompio: correctly reset the request
  ompi/mca/io/ompio/io_ompio_request.c
Labels: bug

#4809 Ensure that output-filename is passed as an absolute path
  .gitignore
  orte/mca/schizo/ompi/schizo_ompi.c
  orte/orted/orted_submit.c
  orte/tools/orterun/orterun.1in
Labels: Target: v3.0.x, Target: v3.1.x, bug

#4816 output-filename: cleanup obsolete code.
  orte/mca/iof/base/iof_base_frame.c
  orte/mca/plm/base/plm_base_launch_support.c
  orte/orted/orted_submit.c
  orte/runtime/orte_globals.c
  orte/runtime/orte_globals.h
  orte/runtime/orte_mca_params.c
Labels: Target: master, bug, code cleanup

#4796 opal/btl: add support for flushing RDMA/atomic operations
  opal/mca/btl/base/btl_base_frame.c
  opal/mca/btl/base/btl_base_mca.c
  opal/mca/btl/btl.h
Labels: Target: master

#4815 plm/slurm:
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: enhancement

#4825 btl/usnic: update BTL_VERSION handling
  opal/mca/btl/usnic/btl_usnic_compat.h
Labels: bug

#4826 ompi: ompi_mpi_init(): do not export threading level to modex.
  ompi/runtime/ompi_mpi_init.c
Labels: Target: master, enhancement

#4802 oshmem: scoll: fixes strided alltoall
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
Labels: Target: master, bug

#4820 osc/rdma: remove erroneous check
  ompi/mca/osc/rdma/osc_rdma_active_target.c
Labels: RM approved, Target: v2.x, blocker, critical

#4835 oshmem: increase group cache size to 1000
  oshmem/proc/proc_group_cache.c
Labels: bug

#4831 v3.1.x: Sync to PMIx v2.1.1
  opal/mca/pmix/pmix2x/pmix/NEWS
  opal/mca/pmix/pmix2x/pmix/VERSION
  opal/mca/pmix/pmix2x/pmix/config/pmix_check_attributes.m4
  opal/mca/pmix/pmix2x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix2x/pmix/contrib/pmix_jenkins.sh
  opal/mca/pmix/pmix2x/pmix/include/pmix_common.h.in
  opal/mca/pmix/pmix2x/pmix/src/client/pmix_client_pub.c
  opal/mca/pmix/pmix2x/pmix/src/include/pmix_globals.h
  opal/mca/pmix/pmix2x/pmix/src/mca/base/pmix_mca_base_var_group.c
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_dstore.c
  opal/mca/pmix/pmix2x/pmix/src/mca/preg/native/preg_native.c
  opal/mca/pmix/pmix2x/pmix/src/mca/ptl/base/ptl_base_sendrecv.c
  opal/mca/pmix/pmix2x/pmix/src/server/pmix_server.c
  opal/mca/pmix/pmix2x/pmix/src/server/pmix_server_get.c
  opal/mca/pmix/pmix2x/pmix/src/tool/pmix_tool.c
  opal/mca/pmix/pmix2x/pmix/test/cli_stages.c
  opal/mca/pmix/pmix2x/pmix/test/cli_stages.h
  opal/mca/pmix/pmix2x/pmix/test/simple/test_pmix.c
Labels: RM approved, bug

#4817 Remove inter-dependencies between OSC modules.
  ompi/mca/coll/monitoring/coll_monitoring_allgather.c
  ompi/mca/coll/monitoring/coll_monitoring_allgatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_allreduce.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoall.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoallv.c
  ompi/mca/coll/monitoring/coll_monitoring_alltoallw.c
  ompi/mca/coll/monitoring/coll_monitoring_barrier.c
  ompi/mca/coll/monitoring/coll_monitoring_bcast.c
  ompi/mca/coll/monitoring/coll_monitoring_exscan.c
  ompi/mca/coll/monitoring/coll_monitoring_gather.c
  ompi/mca/coll/monitoring/coll_monitoring_gatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_allgather.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_allgatherv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoall.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoallv.c
  ompi/mca/coll/monitoring/coll_monitoring_neighbor_alltoallw.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce_scatter.c
  ompi/mca/coll/monitoring/coll_monitoring_reduce_scatter_block.c
  ompi/mca/coll/monitoring/coll_monitoring_scan.c
  ompi/mca/coll/monitoring/coll_monitoring_scatter.c
  ompi/mca/coll/monitoring/coll_monitoring_scatterv.c
  ompi/mca/common/monitoring/common_monitoring.h
  ompi/mca/common/monitoring/common_monitoring_coll.c
  ompi/mca/osc/monitoring/Makefile.am
  ompi/mca/osc/monitoring/configure.m4
  ompi/mca/osc/monitoring/osc_monitoring_accumulate.h
  ompi/mca/osc/monitoring/osc_monitoring_comm.h
  ompi/mca/osc/monitoring/osc_monitoring_component.c
  ompi/mca/osc/monitoring/osc_monitoring_module.h
  ompi/mca/osc/monitoring/osc_monitoring_template.h
  ompi/mca/pml/monitoring/pml_monitoring_isend.c
  ompi/mca/pml/monitoring/pml_monitoring_start.c
Labels: RM approved, Target: v3.1.x

#4813 Ensure output filename is passed as absolute path
  orte/mca/iof/base/iof_base_frame.c
  orte/mca/plm/base/plm_base_launch_support.c
  orte/mca/schizo/ompi/schizo_ompi.c
  orte/orted/orted_submit.c
  orte/runtime/orte_globals.c
  orte/runtime/orte_globals.h
  orte/runtime/orte_mca_params.c
  orte/tools/orterun/orterun.1in
Labels: RM approved, Target: v3.0.x, bug

#4814 Ensure output filename is passed as absolute path
  orte/mca/iof/base/iof_base_frame.c
  orte/mca/plm/base/plm_base_launch_support.c
  orte/mca/schizo/ompi/schizo_ompi.c
  orte/orted/orted_submit.c
  orte/runtime/orte_globals.c
  orte/runtime/orte_globals.h
  orte/runtime/orte_mca_params.c
  orte/tools/orterun/orterun.1in
Labels: RM approved, Target: v3.1.x, bug

#4811 io/ompio: correctly reset the request
  ompi/mca/io/ompio/io_ompio_request.c
Labels: RM approved, Target: v3.1.x, bug

#4810 io/ompio: correctly reset the request
  ompi/mca/io/ompio/io_ompio_request.c
Labels: RM approved, Target: v3.0.x, bug

#4819 osc/rdma: remove erroneous check
  ompi/mca/osc/rdma/osc_rdma_active_target.c
Labels: RM approved, Target: v3.0.x, bug, critical

#4840 orted_submit: fix the --oversubscribe option
  orte/orted/orted_submit.c
Labels: Target: master, bug

#4839 dist: Update NEWS for 3.1.0rc2
  NEWS
Labels: Target: v3.1.x, blocker

#4838 dist: Update .so version numbers for v3.1.0
  VERSION
Labels: RM approved, Target: v3.1.x, blocker

#4841 oshmem: scoll: fixes strided alltoall
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
Labels: Target: v3.1.x, bug

#4837 ompi: ompi_mpi_init(): do not export threading level to modex.
  ompi/runtime/ompi_mpi_init.c
Labels: Target: v3.1.x

#4821 MTL OFI: Added support for reading multiple CQ events in ofi progress
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: master, enhancement, performance

#4849 roll to v2.1.3rc2
  VERSION
Labels: RM approved, documentation

#4853 configury: fix PMI detection
  config/opal_check_pmi.m4
Labels: Target: master

#4864 configury: look for PMI header in DIR provided by --with-pmi=DIR
  config/opal_check_pmi.m4
Labels: Target: master, enhancement
