Repository open-mpi/ompi, pull requests merged in 2019-12, with the labels that each got.

#7172 Nidmap.c and onesided_aggregation.c Compiler Warnings fix
  ompi/mca/io/romio321/romio/adio/common/onesided_aggregation.c
  orte/util/nidmap.c
Labels: Target: master

#7222 mpool/base: fix basic mpool_base() function
  opal/mca/mpool/base/mpool_base_basic.c
Labels: bug

#7227 v4.0.x: fcoll/two_phase: Compiler warning for wrong variable type used
  ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
Labels: Target: v4.0.x, bug

#7066 portals4: fix flow control bugs
  ompi/mca/mtl/portals4/mtl_portals4.c
  opal/mca/btl/portals4/configure.m4
Labels: Target: master, bug

#7224 v4.0.x: mpool/base: fix basic mpool_base() function
  opal/mca/mpool/base/mpool_base_basic.c
Labels: NEWS, Severity: minor, Target: v4.0.x, bug

#7116 v4.0.x: fortran/use-mpi-f08: revamp mpi_f08 constants
  .gitignore
  config/ompi_setup_mpi_fortran.m4
  ompi/include/mpif-values.pl
  ompi/mpi/fortran/common_sym_whitelist.txt
  ompi/mpi/fortran/configure-fortran-output-bottom.h
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/use-mpi-f08/constants.c
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
Labels: Target: v4.0.x, enhancement, fortran bindings

#7236 v4.0.x/several fixes
  ompi/dpm/dpm.c
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/io/romio321/romio/adio/common/ad_read_coll.c
  opal/mca/memory/patcher/memory_patcher_component.c
  orte/mca/odls/default/odls_default_module.c
Labels: Target: v4.0.x, bug

#7237 v4.0.x/two fixes
  HACKING
  ompi/mca/io/romio321/romio/adio/common/onesided_aggregation.c
Labels: Target: v4.0.x, bug

#7241 v3.1.x: Fix mmap infinite recurse in memory patcher
  opal/mca/memory/patcher/configure.m4
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Target: v3.1.x, bug

#7242 v3.0.x: Fix mmap infinite recurse in memory patcher
  opal/mca/memory/patcher/configure.m4
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Target: v3.0.x, bug

#7229 v4.0.x: portals4: fix flow control bugs
  ompi/mca/mtl/portals4/mtl_portals4.c
  opal/mca/btl/portals4/configure.m4
Labels: Target: v4.0.x, bug

#7252 hwloc: clarify --with-hwloc behavior
  README
  opal/mca/hwloc/configure.m4
Labels: bug, documentation

#7254 v4.0.x: hwloc: clarify --with-hwloc behavior
  README
  opal/mca/hwloc/configure.m4
Labels: NEWS, Target: v4.0.x

#7250 V4.0.x oshmem atomic set fix
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/shmem/c/shmem_set.c
Labels: NEWS

#7243 v4.0.x: neighbor alltoall fix
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/basic/coll_basic_neighbor_allgather.c
  ompi/mca/coll/basic/coll_basic_neighbor_allgatherv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoall.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c
Labels: NEWS, Target: v4.0.x, bug
