Repository open-mpi/ompi, pull requests merged in 2019-04, with the labels that each got.

#6519 v4.0.x: shmem/fortran: Fix invalid datatype size in call to atomic cswap
  oshmem/shmem/fortran/shmem_int4_cswap_f.c
Labels: Target: v4.0.x, bug

#6554 Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v4.0.x cherry pick)
  config/orte_setup_debugger_flags.m4
  ompi/runtime/Makefile.am
  orte/mca/ess/Makefile.am
  orte/mca/ess/pmi/Makefile.am
  orte/runtime/Makefile.am
Labels: NEWS, Target: v4.0.x

#6448 in-place conversion macro writes into INPUT argument
  ompi/mpi/fortran/base/fint_2_int.h
  ompi/mpi/fortran/mpif-h/cart_create_f.c
  ompi/mpi/fortran/mpif-h/cart_map_f.c
  ompi/mpi/fortran/mpif-h/cart_sub_f.c
Labels: Target: master

#6545 Fix use of bitwise operation in CPP condition (v4.0.x)
  ompi/mpi/cxx/mpicxx.h
Labels: Target: v4.0.x

#6567 opal/sys: Native timer cleanup
  opal/include/opal/sys/arm64/timer.h
  opal/include/opal/sys/ia32/timer.h
  opal/include/opal/sys/powerpc/timer.h
  opal/include/opal/sys/timer.h
  opal/include/opal/sys/x86_64/timer.h
  opal/mca/timer/linux/timer_linux_component.c
Labels: Target: master, code cleanup

#6577 v3.1.4 release prep
  NEWS
  README
  VERSION
Labels: Target: v3.1.x

#6576 v3.0.4 release prep
  NEWS
  README
  VERSION
Labels: Target: v3.0.x

#6582 v4.0.x: pml/ob1: fix deadlock with communicator flag ALLOW_OVERTAKE.
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
Labels: NEWS, Severity: critical, Target: v4.0.x, bug

#6574 Fixes the O(N^2) loop in the mca_scoll_mpi_comm_query
  oshmem/mca/scoll/mpi/scoll_mpi_module.c
Labels: performance

#6588 dist: Rotate branch to 3.1.5
  NEWS
  VERSION
Labels: Target: v3.1.x

#6587 dist: Rotate branch to 3.0.5
  NEWS
  VERSION
Labels: Target: v3.0.x

#6596 opal_summary.m4: make message consistent with others
  config/opal_summary.m4
Labels: code cleanup

#6603 fortran/use-mpi-f08: fix intent of the internal ompi_*_f bindings
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
Labels: Target: master, bug

#6600 OSC/UCX: correctly handle NULL origin addr and MPI_NO_OP
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: v4.0.x

#6431 mpiext/shortfloat: do not create empty libraries
  config/ompi_ext.m4
  ompi/mpiext/example/configure.m4
  ompi/mpiext/shortfloat/c/Makefile.am
  ompi/mpiext/shortfloat/configure.m4
  ompi/mpiext/shortfloat/mpif-h/Makefile.am
  ompi/mpiext/shortfloat/use-mpi-f08/Makefile.am
Labels: Target: master, bug

#6555 pml/ob1: fixed exit from get_frag_fail when falling back on btl_put
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
Labels: Target: master

#6532 configury: add option to disable enable-new-dtags
  README
  config/opal_setup_wrappers.m4
Labels: RM approved, Target: v3.0.x

#6543 v3.0.x: Fix use of bitwise operation in CPP condition
  ompi/mpi/cxx/mpicxx.h
Labels: Severity: minor, Target: v3.0.x, bug

#6512 v3.1.x: add gen p5 chip pci id to ini file
  opal/mca/btl/openib/mca-btl-openib-device-params.ini
Labels: RM approved, Severity: minor, Target: v3.1.x

#6544 v3.1.x: Fix use of bitwise operation in CPP condition
  ompi/mpi/cxx/mpicxx.h
Labels: RM approved, Severity: minor, Target: v3.1.x, bug

#6551 Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v3.1.x cherry pick)
  config/orte_setup_debugger_flags.m4
  ompi/runtime/Makefile.am
  orte/mca/ess/Makefile.am
  orte/mca/ess/pmi/Makefile.am
  orte/runtime/Makefile.am
Labels: RM approved, Target: v3.1.x

#6553 Add a compilation flag that adds unwind info to all files that are present in the stack starting from MPI_Init (v3.0.x cherry pick)
  config/orte_setup_debugger_flags.m4
  ompi/runtime/Makefile.am
  orte/mca/ess/Makefile.am
  orte/mca/ess/pmi/Makefile.am
  orte/runtime/Makefile.am
Labels: RM approved, Target: v3.0.x

#6610 v4.0.x: ob1 get_frag fail fix
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
Labels: Severity: minor, Target: v4.0.x, bug

#6556 pml/ob1: fixed local handle sent during PUT control message
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
Labels: Target: master

#6624 v4.0.x: make-authors.pl script not compatible with being a submodule.
  contrib/dist/make-authors.pl
Labels: NEWS, Target: v4.0.x

#6623 v3.1: make-authors.pl script not compatible with being a submodule.
  contrib/dist/make-authors.pl
Labels: RM approved, Target: v3.1.x

#6622 v3.0.x: make-authors.pl script not compatible with being a submodule.
  contrib/dist/make-authors.pl
Labels: RM approved, Target: v3.0.x
