Repository open-mpi/ompi, pull requests merged in 2019-02, with the labels that each got.

#6348 opal/datatype: reset ptypes in opal_datatype_clone()
  opal/datatype/opal_datatype_clone.c
Labels: Target: master, bug

#6325 mtl/ofi: Fix reference to help text object
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug

#6351 btl/ofi: Fix valgrind complaints on uninitialized pointer use
  opal/mca/btl/ofi/btl_ofi_module.c
Labels: bug

#6363 Consolidated: fix OFI configury / linking issues
  VERSION
  config/opal_check_ofi.m4
  configure.ac
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/configure.m4
  opal/mca/btl/ofi/Makefile.am
  opal/mca/btl/ofi/configure.m4
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/configure.m4
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/configure.m4
  opal/mca/common/ofi/owner.txt
Labels: NEWS, Target: master, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#6335 Pr/v4.0.x floating point division problem
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
Labels: RM approved, Target: v4.0.x, bug

#6205 Add FP16 datatypes
  .gitignore
  README
  config/ompi_fortran_check.m4
  config/ompi_setup_mpi_fortran.m4
  config/opal_check_alt_short_float.m4
  configure.ac
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_internal.h
  ompi/datatype/ompi_datatype_module.c
  ompi/include/Makefile.am
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
  ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/op.h
  ompi/mpi/c/type_create_f90_complex.c
  ompi/mpi/c/type_create_f90_real.c
  ompi/mpi/fortran/base/gen-mpi-sizeof.pl
  ompi/mpi/fortran/common_sym_whitelist.txt
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/constants.c
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/fortran_sizes.h.in
  ompi/mpiext/shortfloat/Makefile.am
  ompi/mpiext/shortfloat/README.txt
  ompi/mpiext/shortfloat/c/Makefile.am
  ompi/mpiext/shortfloat/c/mpiext_shortfloat_c.h.in
  ompi/mpiext/shortfloat/configure.m4
  ompi/mpiext/shortfloat/mpif-h/Makefile.am
  ompi/mpiext/shortfloat/mpif-h/mpiext_shortfloat_mpifh.h.in
  ompi/mpiext/shortfloat/use-mpi-f08/Makefile.am
  ompi/mpiext/shortfloat/use-mpi-f08/mpiext_shortfloat_usempif08.h.in
  ompi/mpiext/shortfloat/use-mpi/Makefile.am
  ompi/mpiext/shortfloat/use-mpi/mpiext_shortfloat_usempi.h
  ompi/op/op.c
  ompi/runtime/mpiruntime.h
  ompi/runtime/ompi_mpi_init.c
  ompi/tools/ompi_info/param.c
  opal/datatype/opal_copy_functions.c
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_module.c
Labels: Target: master, enhancement

#6306 regex: fixed host ordering for different prefixes
  orte/mca/regx/fwd/regx_fwd.c
  orte/mca/regx/reverse/regx_reverse.c
  orte/test/system/regex.c
Labels: Target: master, bug

#6370 v3.0.x: Fix ofi configury
  VERSION
  config/opal_check_libfabric.m4
  configure.ac
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/configure.m4
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/configure.m4
  opal/mca/common/libfabric/Makefile.am
  opal/mca/common/libfabric/common_libfabric.c
  opal/mca/common/libfabric/common_libfabric.h
  opal/mca/common/libfabric/configure.m4
  opal/mca/common/libfabric/owner.txt
Labels: RM approved, Severity: critical, Target: v3.0.x, bug

#6347 opal/datatype: fix opal_convertor_raw()
  opal/datatype/opal_convertor_raw.c
  test/datatype/Makefile.am
  test/datatype/ddt_raw2.c
Labels: RM approved, Severity: critical, Target: v4.0.x, bug

#6307 Adding changes for issue #6303 for branch v4.0.x.
  orte/mca/odls/alps/odls_alps_module.c
  orte/mca/odls/default/odls_default_module.c
  orte/mca/odls/pspawn/odls_pspawn.c
Labels: RM approved, Severity: minor, Target: v4.0.x, bug

#6330 ompi/datatype: fix how we compute the space needed for the args
  ompi/datatype/ompi_datatype_args.c
  test/datatype/ddt_pack.c
Labels: NEWS, RM approved, Severity: blocker, Target: v4.0.x, bug

#6336 v4.0.x: opal/datatype: plug a memory leak in opal_datatype_t destructor
  opal/datatype/opal_datatype_clone.c
  opal/datatype/opal_datatype_create.c
Labels: NEWS, RM approved, Target: v4.0.x, bug

#6368 v4.0.x: fix OFI configury
  VERSION
  config/opal_check_ofi.m4
  configure.ac
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/configure.m4
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/configure.m4
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/configure.m4
  opal/mca/common/ofi/owner.txt
Labels: RM approved, Severity: critical, Target: v4.0.x, bug

#6249 v4.0.x: btl/vader: don't try to set reachabilty in add_procs if not requested
  opal/mca/btl/vader/btl_vader_module.c
Labels: RM approved, Target: v4.0.x, bug

#6375 v4.0.x/regex: fixed host ordering for different prefixes
  orte/mca/regx/fwd/regx_fwd.c
  orte/mca/regx/reverse/regx_reverse.c
  orte/test/system/regex.c
Labels: RM approved, Target: v4.0.x, bug

#6333 v4.0.x: Various minor hwloc cleanups
  ompi/mca/topo/treematch/Makefile.am
  ompi/mca/topo/treematch/configure.m4
  opal/include/opal_config_bottom.h
  opal/mca/hwloc/base/hwloc_base_dt.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/hwloc/external/external.h
Labels: RM approved, Target: v4.0.x, bug

#6308 Adding changes for issue #6303 for branch v3.1.x.
  orte/mca/odls/alps/odls_alps_module.c
  orte/mca/odls/default/odls_default_module.c
Labels: Severity: minor, Target: v3.1.x, bug

#6310 Adding changes for issue #6303 for branch v3.0.x.
  orte/mca/odls/alps/odls_alps_module.c
  orte/mca/odls/default/odls_default_module.c
Labels: Severity: minor, Target: v3.0.x, bug

#6329 ompi/op: fix support of non predefined datatypes with predefined oper…
  ompi/op/op.h
Labels: Target: v3.0.x, bug

#6328 ompi/op: fix support of non predefined datatypes with predefined oper…
  ompi/op/op.h
Labels: Target: v3.1.x, bug

#6331 ompi/datatype: fix how we compute the space needed for the args
  ompi/datatype/ompi_datatype_args.c
  test/datatype/ddt_pack.c
Labels: Severity: critical, Target: v3.1.x, bug

#6332 ompi/datatype: fix how we compute the space needed for the args
  ompi/datatype/ompi_datatype_args.c
  test/datatype/ddt_pack.c
Labels: Severity: critical, Target: v3.0.x, bug

#6342 v3.0.x: mpi.h.in: use C++ static_cast<> where appropriate
  ompi/include/mpi.h.in
Labels: NEWS, Severity: minor, Target: v3.0.x, bug

#6341 v3.1.x: mpi.h.in: use C++ static_cast<> where appropriate
  ompi/include/mpi.h.in
Labels: NEWS, Severity: minor, Target: v3.1.x, bug

#6369 v3.1.x: fix OFI configury
  VERSION
  config/opal_check_ofi.m4
  configure.ac
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/configure.m4
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/configure.m4
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/configure.m4
  opal/mca/common/ofi/owner.txt
Labels: Severity: critical, Target: v3.1.x, bug

#6344 Pr/v3.1.x floating point division problem
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/io/ompio/io_ompio_aggregators.c
Labels: Target: v3.1.x, bug

#6283 Update mpool_hugepage_component.c
  opal/mca/mpool/hugepage/mpool_hugepage_component.c
Labels: Target: v3.1.x

#6361 mtl/ofi: Fix segfault when not using Thread-Grouping feature
  ompi/mca/mtl/ofi/README
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: master

#6381 opal/util: remove opal_strncpy()
  opal/util/Makefile.am
  opal/util/strncpy.c
  opal/util/strncpy.h
Labels: Target: master, Target: v5.0.x, code cleanup

#6273 v4.0.x: configury: enhance C11 detection
  config/opal_setup_cc.m4
Labels: RM approved, Target: v4.0.x, enhancement

#6327 ompi/op: fix support of non predefined datatypes with predefined oper…
  ompi/op/op.h
Labels: NEWS, RM approved, Severity: blocker, Target: v4.0.x, bug

#6340 v4.0.x: mpi.h.in: use C++ static_cast<> where appropriate
  ompi/include/mpi.h.in
Labels: NEWS, RM approved, Severity: minor, Target: v4.0.x, bug

#6385 MTL_OFI: Changed Recv cancel to be non-blocking
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug

#6380 v4.0.x: oob/tcp: add cross version compatibility support
  orte/mca/oob/tcp/oob_tcp_connection.c
Labels: Target: v4.0.x

#6384 PML/UCX: Use net worker address for remote peers
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: master, performance

#6392 config: Remove remaining HAVE_LONG_LONG
  config/ompi_fortran_get_value_true.m4
Labels: Target: master, code cleanup

#6387 v3.0.x: java: Fix Java devel header build error
  ompi/mpi/java/java/Makefile.am
Labels: RM approved, Target: v3.0.x, bug, java bindings

#6386 v3.1.x: java: Fix Java devel header build error
  ompi/mpi/java/java/Makefile.am
Labels: RM approved, Target: v3.1.x, bug, java bindings

#6388 v2.1.x: java: Fix Java devel header build error
  ompi/mpi/java/java/Makefile.am
Labels: RM approved, Target: v2.x, bug, java bindings

#6311 Adding changes for issue #6303 for branch v2.x.
  orte/mca/odls/alps/odls_alps_module.c
  orte/mca/odls/default/odls_default_module.c
Labels: Severity: minor, Target: v2.x, bug

#6402 man: fix typos in MPI_Win_{attach,detach} man pages
  ompi/mpi/man/man3/MPI_Win_attach.3in
  ompi/mpi/man/man3/MPI_Win_detach.3in
Labels: Target: master, documentation

#6403 man: fix more typos in MPI_Win_attach man page
  ompi/mpi/man/man3/MPI_Win_attach.3in
Labels: Target: master, documentation

#6401 osc/rdma: correctly handle communications to self
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master, bug

#6408 Misc ORTE related cleanups
  autogen.pl
  ompi/mca/rte/orte/Makefile.am
  ompi/mca/rte/orte/configure.m4
  ompi/mca/rte/pmix/configure.m4
  ompi/mca/rte/pmix/rte_pmix_module.c
  oshmem/include/oshmem/constants.h
  oshmem/info/info.c
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/base/memheap_base_select.c
  oshmem/mca/memheap/buddy/memheap_buddy.c
  oshmem/mca/memheap/ptmalloc/memheap_ptmalloc.c
  oshmem/mca/scoll/basic/scoll_basic_barrier.c
  oshmem/mca/scoll/basic/scoll_basic_broadcast.c
  oshmem/mca/scoll/basic/scoll_basic_collect.c
  oshmem/mca/scoll/mpi/scoll_mpi.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/mca/spml/base/spml_base_select.c
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
  oshmem/mca/spml/ikrit/spml_ikrit_component.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/base/base.h
  oshmem/mca/sshmem/base/sshmem_base_wrappers.c
  oshmem/mca/sshmem/mmap/sshmem_mmap_module.c
  oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/op/op.c
  oshmem/op/op.h
  oshmem/proc/proc.c
  oshmem/proc/proc.h
  oshmem/runtime/oshmem_shmem_abort.c
  oshmem/runtime/oshmem_shmem_finalize.c
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/shmem_alltoall.c
  oshmem/shmem/c/shmem_broadcast.c
  oshmem/shmem/c/shmem_clear_lock.c
  oshmem/shmem/c/shmem_collect.c
  oshmem/shmem/c/shmem_context.c
  oshmem/shmem/c/shmem_global_exit.c
  oshmem/shmem/c/shmem_init.c
  oshmem/shmem/c/shmem_pe_accessible.c
  oshmem/shmem/c/shmem_ptr.c
  oshmem/shmem/c/shmem_set_lock.c
  oshmem/shmem/c/shmem_test_lock.c
  oshmem/tools/wrappers/Makefile.am
Labels: Target: master, bug, code cleanup, enhancement

#6405 man: fix typos in MPI_Win_{attach,detach}
  ompi/mpi/man/man3/MPI_Win_attach.3in
  ompi/mpi/man/man3/MPI_Win_detach.3in
Labels: RM approved, Target: v4.0.x, documentation

#6404 osc/rdma: correctly handle communications to self
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: NEWS, Target: v4.0.x, bug

#6163 Refactoring of osc/ucx component for MT
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  ompi/mca/osc/ucx/osc_ucx_request.c
  ompi/mca/osc/ucx/osc_ucx_request.h
  opal/mca/common/ucx/Makefile.am
  opal/mca/common/ucx/common_ucx.h
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
  opal/mca/common/ucx/common_ucx_wpool_int.h
Labels: Target: master, enhancement, ⚠️ WIP-DNM!

#6406 man: fix typos in MPI_Win_{attach,detach}
  ompi/mpi/man/man3/MPI_Win_attach.3in
  ompi/mpi/man/man3/MPI_Win_detach.3in
Labels: RM approved, Target: v3.0.x, documentation

#6395 PML/UCX: Use net worker address for remote peers - v4.0.x
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v4.0.x

#6417 Cart/Graph create would not run the next_cid algorithm
  ompi/communicator/comm.c
Labels: RM approved, Severity: critical, State: PR posted, Target: master, Target: v3.1.x, Target: v4.0.x, bug

#6423 v4.x: Cart/Graph create would not run the next_cid algorithm
  ompi/communicator/comm.c
Labels: Target: v4.0.x

#6290 OMPI/OSHMEM: bug-fix: store mkeys for each oshmem ctx.
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/memheap/base/base.h
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/spml/base/base.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/shmem/c/shmem_addr_accessible.c
  oshmem/shmem/c/shmem_ptr.c
Labels: Target: master

#6407 man: fix typos in MPI_Win_{attach,detach}
  ompi/mpi/man/man3/MPI_Win_attach.3in
  ompi/mpi/man/man3/MPI_Win_detach.3in
Labels: RM approved, Target: v3.1.x, documentation

#6353 Fix the PVAR allocation usage.
  ompi/mca/common/monitoring/HowTo_pml_monitoring.tex
  test/monitoring/check_monitoring.c
  test/monitoring/example_reduce_count.c
  test/monitoring/monitoring_test.c
  test/monitoring/test_pvar_access.c
Labels: Severity: minor, Target: master

#6434 README: updates for v4.0.1 release
  README
Labels: Target: v4.0.x

#6419 fortran:use mpif08 fix for PGI linking
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
Labels: Target: v4.0.x

#6432 hwloc/external: configure: delay feature tests until after version tests
  opal/mca/hwloc/external/configure.m4
Labels: Target: master

#6435 Hold off running hwloc:external feature tests until after we decide i…
  opal/mca/hwloc/external/configure.m4
Labels: NEWS, Severity: critical, Target: v4.0.x, bug

#6428 Pr/v3.0.x OMPIO Crash on Large Data
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/io/ompio/io_ompio_aggregators.c
Labels: Severity: critical, Target: v3.0.x, bug

#6358 Fix MPI1 function removal [master] Issue 6114 [API Change]
  config/ompi_config_files.m4
  ompi/datatype/ompi_datatype_args.c
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/address.c
  ompi/mpi/c/errhandler_create.c
  ompi/mpi/c/errhandler_get.c
  ompi/mpi/c/errhandler_set.c
  ompi/mpi/c/profile/Makefile.am
  ompi/mpi/c/type_extent.c
  ompi/mpi/c/type_hindexed.c
  ompi/mpi/c/type_hvector.c
  ompi/mpi/c/type_lb.c
  ompi/mpi/c/type_struct.c
  ompi/mpi/c/type_ub.c
  ompi/mpi/cxx/mpicxx.cc
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr.F90
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/mpi.F90
Labels: Target: master

#6359 Fix MPI1 function removal [v4.0.x] Issue 6114
  ompi/include/mpi.h.in
  ompi/mpi/c/address.c
  ompi/mpi/c/errhandler_create.c
  ompi/mpi/c/errhandler_get.c
  ompi/mpi/c/errhandler_set.c
  ompi/mpi/c/type_extent.c
  ompi/mpi/c/type_hindexed.c
  ompi/mpi/c/type_hvector.c
  ompi/mpi/c/type_lb.c
  ompi/mpi/c/type_struct.c
  ompi/mpi/c/type_ub.c
Labels: Target: v4.0.x

#6418 Update slurm pmi configury to account for pmix
  config/opal_check_pmi.m4
  configure.ac
  opal/mca/pmix/s1/configure.m4
  opal/mca/pmix/s2/configure.m4
Labels: Target: master

#6413 osc/rdma: fix when determining the node with the rank_array info for a peer
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_peer.c
Labels: Severity: critical, State: PR posted, Target: master, bug
