Repository open-mpi/ompi, pull requests merged in 2019-06, with the labels that each got.

#6696 btl/uct: check for support before disabling UCX memory hooks
  opal/mca/btl/uct/btl_uct_component.c
Labels: Target: v4.0.x

#6692 V4.0.x Coll/hcoll: don't init opal memhooks unless explicitely requested
  ompi/mca/coll/hcoll/coll_hcoll_component.c
  ompi/mca/coll/hcoll/coll_hcoll_module.c
Labels: Target: v4.0.x, bug

#6152 btl/openib: delay UCX warning to add_procs()
  opal/mca/btl/openib/btl_openib.c
  opal/mca/btl/openib/btl_openib.h
  opal/mca/btl/openib/btl_openib_component.c
  opal/mca/btl/openib/btl_openib_proc.c
Labels: Target: v4.0.x, enhancement

#6699 java: Fix compilation error in allToAllw using Java arrays
  ompi/mpi/java/c/mpiJava.h
  ompi/mpi/java/c/mpi_Comm.c
  ompi/mpi/java/c/mpi_MPI.c
  ompi/mpi/java/java/Comm.java
Labels: Target: master, java bindings, ⚠️ WIP-DNM!, 😳 Backward compat break

#6722 shmat/shmdt additions for patcher
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: RM approved, Target: v3.0.x

#6721 shmat/shmdt additions for patcher
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: RM approved, Target: v3.1.x

#6706 common/ompio: fix division by zero problem with empty fview
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: RM approved, Target: v3.0.x, bug

#6705 common/ompio: fix division by zero problem with empty fview
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: RM approved, Target: v3.1.x, bug

#6674 v3.0.x: plm_slurm_module: adjust for new SLURM CLI options
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: NEWS, RM approved, Target: v3.0.x, bug

#6665 v3.0.x: openmpi.spec: make sure grep failure doesn't abort
  contrib/dist/linux/openmpi.spec
Labels: RM approved, Target: v3.0.x, bug

#6673 v3.1.x: plm_slurm_module: adjust for new SLURM CLI options
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: NEWS, RM approved, Target: v3.1.x, bug

#6664 v3.1.x: openmpi.spec: make sure grep failure doesn't abort
  contrib/dist/linux/openmpi.spec
Labels: RM approved, Target: v3.1.x, bug

#6716 Fix tree spawn at scale
  orte/mca/routed/debruijn/Makefile.am
  orte/mca/routed/debruijn/owner.txt
  orte/mca/routed/debruijn/routed_debruijn.c
  orte/mca/routed/debruijn/routed_debruijn.h
  orte/mca/routed/debruijn/routed_debruijn_component.c
Labels: Target: v3.0.x, bug

#6715 Fix tree spawn at scale
  orte/mca/routed/debruijn/Makefile.am
  orte/mca/routed/debruijn/owner.txt
  orte/mca/routed/debruijn/routed_debruijn.c
  orte/mca/routed/debruijn/routed_debruijn.h
  orte/mca/routed/debruijn/routed_debruijn_component.c
Labels: Target: v3.1.x, bug

#6724 shmem/c: Fix shmem type for calls to shmem_test and shmem_wait_until …
  oshmem/shmem/c/shmem_wait.c
Labels: Target: master, bug

#6701 SSHMEM/COLL: added sshmem/mpi implementation for shmem_collect call - v4.0
  oshmem/mca/scoll/mpi/scoll_mpi_ops.c
Labels: Target: v4.0.x

#6732 PML/UCX: Don't destroy UCP worker if it wasn't created
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: master

#6707 ALLOC_WITH_HINT: added inplace realloc - v4.0
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/sshmem/ucx/sshmem_ucx.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
Labels: Target: v4.0.x

#6726 mpiext/pcollreq: Add `_f08` to procedure names
  ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_usempif08.h
Labels: Target: master, bug, fortran bindings

#6745 v4.0.x: mpiext/pcollreq: Add `_f08` to procedure names
  ompi/mpiext/pcollreq/use-mpi-f08/mpiext_pcollreq_usempif08.h
Labels: Target: v4.0.x, bug, fortran bindings

#6741 v4.0.x: shmem/c: Fix shmem type for calls to shmem_test and shmem_wait_until …
  oshmem/shmem/c/shmem_wait.c
Labels: Target: v4.0.x, bug

#6739 v4.0.x: regx/base: fix an integer overflow
  orte/mca/regx/base/regx_base_default_fns.c
Labels: NEWS, Target: v4.0.x, bug

#6714 Fix tree spawn at scale
  .gitignore
  orte/mca/routed/debruijn/Makefile.am
  orte/mca/routed/debruijn/owner.txt
  orte/mca/routed/debruijn/routed_debruijn.c
  orte/mca/routed/debruijn/routed_debruijn.h
  orte/mca/routed/debruijn/routed_debruijn_component.c
Labels: Target: v4.0.x, bug

#6686 coll/libnbc: add recursive doubling algorithm for MPI_Iallreduce
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/coll/libnbc/nbc_iallreduce.c
Labels: Target: master

#6747 OSC rdma: make sure accumulating in shared memory is safe
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: NEWS

#6748 btl/uct: add support for UCX 1.6.x
  opal/mca/btl/uct/btl_uct_endpoint.c
  opal/mca/btl/uct/btl_uct_tl.c
Labels: fix for v4.0.2

#6746 OSC rdma win allocate: propagate errors to avoid deadlocks
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: NEWS

#6764 Fix finalize of flux component
  opal/mca/pmix/flux/pmix_flux.c
Labels: Target: v3.1.x, Target: v4.0.x

#6767 Fix finalize of flux component
  opal/mca/pmix/flux/pmix_flux.c
Labels: RM approved, bug

#6766 Fix finalize of flux component
  opal/mca/pmix/flux/pmix_flux.c
Labels: RM approved, bug

#6754 OSC/UCX: Fix early cleanup + race conditions
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v5.0.x, bug

#6771 pmix/pmix4x: refresh to the latest PMIx master
  opal/mca/pmix/pmix4x/pmix/VERSION
  opal/mca/pmix/pmix4x/pmix/bindings/python/sched.py.in
  opal/mca/pmix/pmix4x/pmix/config/pmix.m4
  opal/mca/pmix/pmix4x/pmix/include/pmix_common.h.in
  opal/mca/pmix/pmix4x/pmix/src/include/types.h
  opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_pack.c
  opal/mca/pmix/pmix4x/pmix/src/mca/bfrops/base/bfrop_base_unpack.c
  opal/mca/pmix/pmix4x/pmix/src/mca/pnet/tcp/pnet_tcp.c
  opal/mca/pmix/pmix4x/pmix/src/mca/pnet/test/pnet_test.c
  opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_progress_threads.c
Labels: Target: master, bug

#6725 Cherrypick/6683
  ompi/mpi/man/man3/MPI_T_cvar_handle_alloc.3in
  ompi/mpi/man/man3/MPI_T_finalize.3in
  ompi/mpi/man/man3/MPI_T_pvar_handle_alloc.3in
  ompi/mpi/man/man3/MPI_T_pvar_session_create.3in
  ompi/mpi/man/man3/MPI_T_pvar_start.3in
  ompi/mpi/man/man3/MPI_T_pvar_write.3in
  ompi/runtime/ompi_spc.c
  test/spc/spc_test.c
Labels: Severity: minor, Target: v4.0.x

#6765 v4.0.x: Fix finalize of flux component
  opal/mca/pmix/flux/pmix_flux.c
Labels: bug

#6634 v4.0.x: Cherry pick ob1 fixes from master
  ompi/mca/pml/ob1/pml_ob1_rdmafrag.h
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
  opal/threads/thread_usage.h
Labels: NEWS, Severity: blocker, Target: v4.0.x, bug

#6780 pmix/pmix4x: refresh to the latest PMIx master
  opal/mca/pmix/pmix4x/pmix/VERSION
  opal/mca/pmix/pmix4x/pmix/configure.ac
Labels: Target: master, bug

#6782 mpi/c: fix param checks in [I]Neighbor_alltoall{v,w}
  ompi/mpi/c/ineighbor_alltoallv.c
  ompi/mpi/c/ineighbor_alltoallw.c
  ompi/mpi/c/neighbor_alltoallv.c
  ompi/mpi/c/neighbor_alltoallw.c
Labels: Target: master, bug

#6649 OSC rdma: make sure accumulating in shared memory is safe
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master
