Repository open-mpi/ompi, pull requests merged in 2019-03, with the labels that each got.

#6438 Issues/6436/v3.0
  opal/datatype/opal_convertor_raw.c
  test/datatype/Makefile.am
  test/datatype/ddt_raw2.c
Labels: RM approved, Severity: blocker, Target: v3.0.x

#6437 Issues/6436/v3.1
  opal/datatype/opal_convertor_raw.c
  test/datatype/Makefile.am
  test/datatype/ddt_raw2.c
Labels: RM approved, Severity: blocker, Target: v3.1.x

#6424 v3.1.x: Cart/Graph create would not run the next_cid algorithm
  ompi/communicator/comm.c
Labels: Target: v3.1.x

#6400 Prepare for v3.0.4 release
  NEWS
  README
  VERSION
Labels: Target: v3.0.x

#6445 v4.0.x: Update Slurm PMI configury to account for PMIx
  config/opal_check_pmi.m4
  configure.ac
  opal/mca/pmix/s1/configure.m4
  opal/mca/pmix/s2/configure.m4
Labels: Target: v4.0.x, enhancement, feature request

#6449 btl/usnic: fix usnic_btl_run_tests CPPFLAGS
  opal/mca/btl/usnic/Makefile.am
Labels: Target: master, bug

#6459 btl/usnic: amend Makefile.am fix from b4097626ab
  opal/mca/btl/usnic/Makefile.am
Labels: code cleanup

#6466 Backport/4.x/6029
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_copy_functions.c
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_copy.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_fake_stack.c
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_position.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  test/datatype/Makefile.am
  test/datatype/large_data.c
Labels: Target: v4.0.x, bug

#6446 v4.0.x: Fix cross-mpirun connect/accept operations
  orte/mca/state/base/state_base_fns.c
  orte/orted/pmix/pmix_server_dyn.c
  orte/orted/pmix/pmix_server_fence.c
  orte/orted/pmix/pmix_server_register_fns.c
Labels: NEWS, Target: v4.0.x, bug

#6450 v4.0.x: btl/usnic: fix usnic_btl_run_tests CPPFLAGS
  opal/mca/btl/usnic/Makefile.am
Labels: NEWS, Target: v4.0.x, bug

#6414 Prepare for v3.1.4 release
  NEWS
  README
  VERSION
Labels: Target: v3.1.x

#6465 V4.0.x self contained pshmem
  oshmem/include/pshmem.h
Labels: Target: v4.0.x

#6451 man: remove man pages of removed MPI1 subroutines
  ompi/mpi/man/man3/MPI_Address.3in
  ompi/mpi/man/man3/MPI_Errhandler_create.3in
  ompi/mpi/man/man3/MPI_Errhandler_get.3in
  ompi/mpi/man/man3/MPI_Errhandler_set.3in
  ompi/mpi/man/man3/MPI_Type_extent.3in
  ompi/mpi/man/man3/MPI_Type_hindexed.3in
  ompi/mpi/man/man3/MPI_Type_hvector.3in
  ompi/mpi/man/man3/MPI_Type_lb.3in
  ompi/mpi/man/man3/MPI_Type_struct.3in
  ompi/mpi/man/man3/MPI_Type_ub.3in
  ompi/mpi/man/man3/Makefile.extra
Labels: Target: master, documentation

#6463 v3.1.x: Fix typo in PMIx atomics
  opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
Labels: Target: v3.1.x, bug

#6462 v3.0.x: Fix typo in PMIx atomics
  opal/mca/pmix/pmix2x/pmix/src/atomics/sys/gcc_builtin/atomic.h
Labels: Target: v3.0.x, bug

#6476 configury: Remove --enable-mpi1-compatibility
  README
  config/ompi_configure_options.m4
Labels: Target: v5.0.x, code cleanup

#6461 v3.1.x: usnic makefile fix
  opal/mca/btl/usnic/Makefile.am
Labels: Target: v3.1.x, bug

#6474 v3.1.x: Avoid a double lock interlock when calling pmix_finalize
  opal/mca/pmix/pmix2x/pmix2x_client.c
  opal/mca/pmix/pmix2x/pmix2x_server_south.c
Labels: RTE, Severity: minor, Target: v3.1.x, bug

#6460 v3.0.x: usnic makefile fix
  opal/mca/btl/usnic/Makefile.am
Labels: Target: v3.0.x, bug

#6457 v3.1.x: remove stale rml ofi component
  orte/mca/rml/ofi/Makefile.am
  orte/mca/rml/ofi/configure.m4
  orte/mca/rml/ofi/rml_ofi.h
  orte/mca/rml/ofi/rml_ofi_component.c
  orte/mca/rml/ofi/rml_ofi_request.h
  orte/mca/rml/ofi/rml_ofi_send.c
Labels: Target: v3.1.x, code cleanup

#6455 Fix 6238 for v3.1.x
  orte/mca/rmaps/base/base.h
  orte/mca/rmaps/base/rmaps_base_frame.c
  orte/orted/orted_submit.c
  orte/orted/pmix/pmix_server_dyn.c
  orte/orted/pmix/pmix_server_gen.c
Labels: Target: v3.1.x

#6473 v4.0.x: Avoid a double lock interlock when calling pmix_finalize
  opal/mca/pmix/ext2x/ext2x_client.c
  opal/mca/pmix/ext2x/ext2x_server_south.c
  opal/mca/pmix/pmix3x/pmix3x_client.c
  opal/mca/pmix/pmix3x/pmix3x_server_south.c
Labels: RTE, Severity: minor, State: PR posted, Target: v4.0.x, bug

#6479 v3.0.x: Avoid a double lock interlock when calling pmix_finalize
  opal/mca/pmix/pmix2x/pmix2x_client.c
  opal/mca/pmix/pmix2x/pmix2x_server_south.c
Labels: RTE, Severity: minor, Target: v3.0.x, bug

#6482 Fix integer overflows with indexed datatype creation.
  ompi/datatype/ompi_datatype_create_indexed.c
Labels: Target: master, bug, code cleanup

#6485 v4.0.x: Fix integer overflows with indexed datatype creation.
  ompi/datatype/ompi_datatype_create_indexed.c
Labels: Target: v4.0.x, bug

#6477 opal_hwloc_base_cset2str() off-by-1 in its strncat()
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: Target: v4.0.x, bug

#6489 v4.0.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: Severity: minor, Target: v4.0.x, bug

#6486 PML/SPML/UCX: added evaluation of mmap events - v4.0
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: v4.0.x

#6491 v4.0.x: Cherry-pick fixes for issue #6258 from master (vader fixes)
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_endpoint.h
  opal/mca/btl/vader/btl_vader_fbox.h
  opal/mca/btl/vader/btl_vader_frag.c
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/mpool/base/Makefile.am
  opal/mca/mpool/base/base.h
  opal/mca/mpool/base/mpool_base_basic.c
Labels: Severity: blocker, Target: v4.0.x, bug

#6484 v3.0.x: Fix integer overflows with indexed datatype creation.
  ompi/datatype/ompi_datatype_create_indexed.c
Labels: Severity: minor, Target: v3.0.x, bug

#6487 v3.0.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: Severity: minor, Target: v3.0.x, bug

#6483 v3.1.x: Fix integer overflows with indexed datatype creation.
  ompi/datatype/ompi_datatype_create_indexed.c
Labels: Target: v3.1.x, bug

#6488 v3.1.x: opal_hwloc_base_cset2str() off-by-1 in its strncat()
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: Severity: minor, Target: v3.1.x, bug

#6499 NEWS: add a few news items for 4.0.1rc2
  NEWS
Labels: Target: v4.0.x

#6500 opal/atomics: Add acquire semantics back for spinlocks
  opal/include/opal/sys/atomic_impl.h
Labels: bug

#6498 Do not force 'hash' gds on direct modex
  opal/mca/pmix/ext3x/ext3x_client.c
  opal/mca/pmix/ext3x/ext3x_server_south.c
Labels: bug

#6502 opal/atomics: Add acquire semantics back for spinlocks
  opal/include/opal/sys/atomic_impl.h
Labels: Target: v4.0.x, bug

#6503 Do not force 'hash' gds on direct modex
  opal/mca/pmix/pmix3x/pmix3x_client.c
  opal/mca/pmix/pmix3x/pmix3x_server_south.c
Labels: Target: v4.0.x, bug

#6371 osc/base: Add debug output stating a selected component
  ompi/mca/osc/base/osc_base_init.c
Labels: Target: master

#6510 shmem/fortran: Fix invalid datatype size in call to atomic cswap
  oshmem/shmem/fortran/shmem_int4_cswap_f.c
Labels: Target: master, bug

#6440 schizo/ompi: correctly handle the yield_when_idle option
  ompi/runtime/ompi_mpi_params.c
  orte/mca/schizo/ompi/schizo_ompi.c
Labels: Target: master, bug

#6526 btl/vader: fix finalize sequence
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
Labels: Target: master, bug

#6140 Fix use of bitwise operation in CPP condition
  ompi/mpi/cxx/mpicxx.h
Labels: Target: master

#6527 Add compilation flag to allow unwinding through files that are present in the stack when attaching with MPIR
  config/orte_setup_debugger_flags.m4
  ompi/runtime/Makefile.am
  orte/mca/ess/Makefile.am
  orte/mca/ess/pmi/Makefile.am
  orte/runtime/Makefile.am
Labels: Severity: minor, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, enhancement

#6541 btl/tcp: Skip printing error message in racy cleanup path
  opal/mca/btl/tcp/btl_tcp_component.c
Labels: Target: master, bug

#6542 man: Fix typo of MPI_TYPE_GET_NAME
  ompi/mpi/man/man3/MPI_Type_get_name.3in
Labels: Severity: minor, Target: master, documentation
