Repository open-mpi/ompi, pull requests merged in 2019-07, with the labels that each got.

#6791 pml/ucx: Fix the max tag and context id values
  ompi/mca/pml/ucx/pml_ucx.c
Labels: bug

#6790 fortran/mpif-h: correctly handle array_of_errcodes in ompi_comm_spawn…
  ompi/mpi/fortran/mpif-h/comm_spawn_f.c
  ompi/mpi/fortran/mpif-h/comm_spawn_multiple_f.c
Labels: Target: master, bug

#6798 man: fix MPI_Allgather[v] man pages
  ompi/mpi/man/man3/MPI_Allgather.3in
  ompi/mpi/man/man3/MPI_Allgatherv.3in
Labels: Target: master, documentation

#6787 v4.0.x: Update PMIx to official v3.1.3 release
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/config/pmix.m4
  opal/mca/pmix/pmix3x/pmix/configure.ac
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/contrib/whitespace-purge.sh
  opal/mca/pmix/pmix3x/pmix/src/mca/pnet/opa/configure.m4
Labels: bug, code cleanup

#6781 Fix ORTE_FORCED_TERMINATE message
  orte/mca/state/state.h
Labels: NEWS, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#6796 Fix oob_tcp tcp_component_close segfault with active listeners
  orte/mca/oob/tcp/oob_tcp_component.c
Labels: Target: v4.0.x

#6793 Add missing argument name.
  ompi/include/mpi.h.in
Labels: NEWS

#6800 v4.0.x: Fix oob_tcp tcp_component_close segfault with active listeners
  orte/mca/oob/tcp/oob_tcp_component.c
Labels: NEWS, Target: v4.0.x, bug

#6797 Fix if_linux_ipv6 verbose output of interface addresses
  opal/mca/if/linux_ipv6/Makefile.am
  opal/mca/if/linux_ipv6/help-opal-if-linux-ipv6.txt
  opal/mca/if/linux_ipv6/if_linux_ipv6.c
Labels: Target: v4.0.x

#6802 opal/if/linux_ipv6: unify gethostname() call behavior
  opal/mca/if/linux_ipv6/if_linux_ipv6.c
Labels: Target: master, bug

#6709 opal/util: revamp opal_output_verbose()
  opal/util/output.c
  opal/util/output.h
Labels: Target: master, enhancement

#6807 ess/base: fix a misc memory leak in orte_ess_base_proc_binding()
  orte/mca/ess/base/ess_base_fns.c
Labels: Target: master, memory leak

#6805 Reachable
  opal/mca/reachable/netlink/reachable_netlink_module.c
  opal/mca/reachable/reachable.h
  opal/mca/reachable/weighted/reachable_weighted.c
Labels: Target: master, code cleanup, documentation

#6809 man page of MPI_Type_vector
  ompi/mpi/man/man3/MPI_Type_vector.3in
Labels: Severity: minor, Target: master, bug, documentation

#2154 non-blocking collectives: retain MPI_op and MPI_Datatype(s)
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/coll_libnbc.h
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/coll/libnbc/nbc.c
  ompi/mpi/c/iallgather.c
  ompi/mpi/c/iallgatherv.c
  ompi/mpi/c/iallreduce.c
  ompi/mpi/c/ialltoall.c
  ompi/mpi/c/ialltoallv.c
  ompi/mpi/c/ialltoallw.c
  ompi/mpi/c/ibcast.c
  ompi/mpi/c/iexscan.c
  ompi/mpi/c/igather.c
  ompi/mpi/c/igatherv.c
  ompi/mpi/c/ineighbor_allgather.c
  ompi/mpi/c/ineighbor_allgatherv.c
  ompi/mpi/c/ineighbor_alltoall.c
  ompi/mpi/c/ineighbor_alltoallv.c
  ompi/mpi/c/ineighbor_alltoallw.c
  ompi/mpi/c/ireduce.c
  ompi/mpi/c/ireduce_scatter.c
  ompi/mpi/c/ireduce_scatter_block.c
  ompi/mpi/c/iscan.c
  ompi/mpi/c/iscatter.c
  ompi/mpi/c/iscatterv.c
  ompi/mpiext/pcollreq/c/allgather_init.c
  ompi/mpiext/pcollreq/c/allgatherv_init.c
  ompi/mpiext/pcollreq/c/allreduce_init.c
  ompi/mpiext/pcollreq/c/alltoall_init.c
  ompi/mpiext/pcollreq/c/alltoallv_init.c
  ompi/mpiext/pcollreq/c/alltoallw_init.c
  ompi/mpiext/pcollreq/c/bcast_init.c
  ompi/mpiext/pcollreq/c/exscan_init.c
  ompi/mpiext/pcollreq/c/gather_init.c
  ompi/mpiext/pcollreq/c/gatherv_init.c
  ompi/mpiext/pcollreq/c/neighbor_allgather_init.c
  ompi/mpiext/pcollreq/c/neighbor_allgatherv_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoall_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoallv_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoallw_init.c
  ompi/mpiext/pcollreq/c/reduce_init.c
  ompi/mpiext/pcollreq/c/reduce_scatter_block_init.c
  ompi/mpiext/pcollreq/c/reduce_scatter_init.c
  ompi/mpiext/pcollreq/c/scan_init.c
  ompi/mpiext/pcollreq/c/scatter_init.c
  ompi/mpiext/pcollreq/c/scatterv_init.c
Labels: Target: master, bug

#6813 fortran/mpif-h: fix MPI_Alltoallw() binding
  ompi/mpi/fortran/mpif-h/alltoallw_f.c
  ompi/mpi/fortran/mpif-h/ialltoallw_f.c
Labels: NEWS, Target: master, bug, fortran bindings

#6806 v4.0.x: retain operation and datatype(s) in non blocking collectives
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/coll_libnbc.h
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/coll/libnbc/nbc.c
  ompi/mpi/c/iallgather.c
  ompi/mpi/c/iallgatherv.c
  ompi/mpi/c/iallreduce.c
  ompi/mpi/c/ialltoall.c
  ompi/mpi/c/ialltoallv.c
  ompi/mpi/c/ialltoallw.c
  ompi/mpi/c/ibcast.c
  ompi/mpi/c/iexscan.c
  ompi/mpi/c/igather.c
  ompi/mpi/c/igatherv.c
  ompi/mpi/c/ineighbor_allgather.c
  ompi/mpi/c/ineighbor_allgatherv.c
  ompi/mpi/c/ineighbor_alltoall.c
  ompi/mpi/c/ineighbor_alltoallv.c
  ompi/mpi/c/ineighbor_alltoallw.c
  ompi/mpi/c/ireduce.c
  ompi/mpi/c/ireduce_scatter.c
  ompi/mpi/c/ireduce_scatter_block.c
  ompi/mpi/c/iscan.c
  ompi/mpi/c/iscatter.c
  ompi/mpi/c/iscatterv.c
  ompi/mpiext/pcollreq/c/allgather_init.c
  ompi/mpiext/pcollreq/c/allgatherv_init.c
  ompi/mpiext/pcollreq/c/allreduce_init.c
  ompi/mpiext/pcollreq/c/alltoall_init.c
  ompi/mpiext/pcollreq/c/alltoallv_init.c
  ompi/mpiext/pcollreq/c/alltoallw_init.c
  ompi/mpiext/pcollreq/c/bcast_init.c
  ompi/mpiext/pcollreq/c/exscan_init.c
  ompi/mpiext/pcollreq/c/gather_init.c
  ompi/mpiext/pcollreq/c/gatherv_init.c
  ompi/mpiext/pcollreq/c/neighbor_allgather_init.c
  ompi/mpiext/pcollreq/c/neighbor_allgatherv_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoall_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoallv_init.c
  ompi/mpiext/pcollreq/c/neighbor_alltoallw_init.c
  ompi/mpiext/pcollreq/c/reduce_init.c
  ompi/mpiext/pcollreq/c/reduce_scatter_block_init.c
  ompi/mpiext/pcollreq/c/reduce_scatter_init.c
  ompi/mpiext/pcollreq/c/scan_init.c
  ompi/mpiext/pcollreq/c/scatter_init.c
  ompi/mpiext/pcollreq/c/scatterv_init.c
Labels: NEWS, Target: v4.0.x, bug

#6824 fortran/mpif-h: fix MPI_Alltoallw and friends bindings
  ompi/mpi/fortran/mpif-h/alltoallw_f.c
  ompi/mpi/fortran/mpif-h/ialltoallw_f.c
  ompi/mpiext/pcollreq/mpif-h/alltoallw_init_f.c
Labels: Target: master, bug

#6812 fortran/mpif-h: fix C to Fortran error code conversion
  ompi/mpi/fortran/mpif-h/comm_split_type_f.c
  ompi/mpi/fortran/mpif-h/dist_graph_create_adjacent_f.c
  ompi/mpi/fortran/mpif-h/dist_graph_create_f.c
  ompi/mpi/fortran/mpif-h/dist_graph_neighbors_count_f.c
  ompi/mpi/fortran/mpif-h/dist_graph_neighbors_f.c
  ompi/mpi/fortran/mpif-h/improbe_f.c
  ompi/mpi/fortran/mpif-h/imrecv_f.c
  ompi/mpi/fortran/mpif-h/mprobe_f.c
  ompi/mpi/fortran/mpif-h/mrecv_f.c
Labels: Target: master, bug, fortran bindings

#6830 Provide locality for all procs on node
  ompi/dpm/dpm.c
  opal/mca/pmix/pmix4x/pmix/VERSION
  opal/mca/pmix/pmix4x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix4x/pmix/src/client/pmi1.c
  opal/mca/pmix/pmix4x/pmix/src/client/pmix_client_fence.c
  opal/mca/pmix/pmix4x/pmix/src/client/pmix_client_get.c
  opal/mca/pmix/pmix4x/pmix/src/event/pmix_event_notification.c
  opal/mca/pmix/pmix4x/pmix/src/include/pmix_globals.h
  opal/mca/pmix/pmix4x/pmix/src/mca/gds/hash/gds_hash.c
  opal/mca/pmix/pmix4x/pmix/src/mca/pfexec/base/pfexec_base_default_fns.c
  opal/mca/pmix/pmix4x/pmix/src/mca/pnet/base/pnet_base_fns.c
  opal/mca/pmix/pmix4x/pmix/src/mca/pnet/test/pnet_test.c
  opal/mca/pmix/pmix4x/pmix/src/mca/ptl/tcp/ptl_tcp_component.c
  opal/mca/pmix/pmix4x/pmix/src/mca/ptl/usock/ptl_usock_component.c
  opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_finalize.c
  opal/mca/pmix/pmix4x/pmix/src/runtime/pmix_init.c
  opal/mca/pmix/pmix4x/pmix/src/server/pmix_server.c
  opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_get.c
  opal/mca/pmix/pmix4x/pmix/src/server/pmix_server_ops.c
  opal/mca/pmix/pmix4x/pmix/src/tool/pmix_tool.c
  opal/mca/pmix/pmix4x/pmix/src/util/name_fns.c
  opal/mca/pmix/pmix4x/pmix/test/pmi_client.c
  opal/mca/pmix/pmix4x/pmix/test/simple/Makefile.am
  opal/mca/pmix/pmix4x/pmix/test/simple/simpcoord.c
  opal/mca/pmix/pmix4x/pmix/test/simple/simplegacy.c
Labels: Target: master

#6695 A big refresh of the datatype engine
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_create_indexed.c
  ompi/datatype/ompi_datatype_external.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_add.c
  opal/datatype/opal_datatype_copy.h
  opal/datatype/opal_datatype_get_count.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_module.c
  opal/datatype/opal_datatype_monotonic.c
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_position.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  test/datatype/ddt_raw2.c
  test/datatype/opal_datatype_test.c
  test/datatype/opal_ddt_lib.c
  test/datatype/to_self.c
  test/datatype/unpack_ooo.c
Labels: Target: master

#6828 Try to prevent the compiler from optimizing out MPIR_Breakpoint().
  orte/orted/orted_submit.c
Labels: Target: master

#6841 v3.0.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().
  orte/orted/orted_submit.c
Labels: RM approved, Target: v3.0.x, bug

#6814 COLL/TUNED: Update alltoall selection rule for mellanox platform
  contrib/platform/mellanox/optimized.conf
  ompi/mca/coll/tuned/coll_tuned.h
  ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
  ompi/mca/coll/tuned/coll_tuned_component.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: Target: master

#6840 osc/ucx: Fix data corruption with non-contiguous accumulates
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: master, bug

#6843 v4.0.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().
  orte/orted/orted_submit.c
Labels: NEWS, Target: v4.0.x, bug

#6842 v3.1.x: Try to prevent the compiler from optimizing out MPIR_Breakpoint().
  orte/orted/orted_submit.c
Labels: RM approved, Target: v3.1.x, bug

#6848 v3.1.x: osc/ucx: Fix data corruption with non-contiguous accumulates
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: RM approved, Target: v3.1.x, bug

#6845 COLL/TUNED: Update alltoall selection rule for mellanox platform - v4.0.x
  contrib/platform/mellanox/optimized.conf
  ompi/mca/coll/tuned/coll_tuned.h
  ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
  ompi/mca/coll/tuned/coll_tuned_component.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: Target: v4.0.x
