Repository open-mpi/ompi, pull requests merged in 2019-10, with the labels that each got.

#7023 v3.1.x: datatype_optimize: keep 0-extent instances
  opal/datatype/opal_datatype_optimize.c
Labels: NEWS, RM approved, Severity: critical, Target: v3.1.x, bug

#7024 v3.0.x: datatype_optimize: keep 0-extent instances
  opal/datatype/opal_datatype_optimize.c
Labels: NEWS, RM approved, Severity: critical, Target: v3.1.x, bug

#7028 mtl/ofi: replace OMPI_UNLIKELY with OPAL version
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: master, bug

#7003 v3.1.x: REF6976 Silent failure of OMPI over OFI with large messages sizes
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v3.1.x, bug

#7006 v3.0.x: REF6976 Silent failure of OMPI over OFI with large messages sizes
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v3.0.x, bug

#7038 btl/usnic fixes and optimizations
  opal/mca/btl/usnic/btl_usnic.h
  opal/mca/btl/usnic/btl_usnic_component.c
  opal/mca/btl/usnic/btl_usnic_frag.h
  opal/mca/btl/usnic/btl_usnic_mca.c
  opal/mca/btl/usnic/btl_usnic_module.c
  opal/mca/btl/usnic/btl_usnic_recv.h
Labels: Target: master, bug

#7046 comomn_ompio_file_read/write: fix 2GB limiting issue
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
Labels: bug

#7054 v3.1.x: common_ompio_file_read/write: fix 2GB limiting issue
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
Labels: RM approved, Target: v3.1.x, bug

#7055 v3.0.x: common_ompio_file_read/write: fix 2GB limiting issue
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
Labels: RM approved, Target: v3.0.x, bug

#7053 v3.1: pml_ucx: add ompi datatype attribute to release ucp_datatype - v3.1
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_datatype.c
  ompi/mca/pml/ucx/pml_ucx_datatype.h
Labels: RM approved, Target: v3.1.x, bug

#7052 v3.0.x: pml_ucx: add ompi datatype attribute to release ucp_datatype - v3.0
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_datatype.c
  ompi/mca/pml/ucx/pml_ucx_datatype.h
Labels: RM approved, Target: v3.0.x, bug

#7062 travis: fix make distcheck
  .travis.yml
Labels: Target: master

#7061 pml/ucx: correctly handle zero size datatypes
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: Target: master, bug

#7059 v3.0.x: pml/cm: check for request comp. before completing bsend.
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: RM approved, Target: v3.0.x, bug

#7078 fix address
  README
Labels: documentation

#7070 updated readme to remove double space on line 297
  README
Labels: documentation

#7072 README-fixed-bfitzgit23
  README
Labels: documentation

#7074 Deleted paragraph
  README
Labels: documentation

#7073 README: edit "dist_graph topologies" to "communicator topologies"
  README
Labels: documentation

#7082 Fix ipv6 improper address copy bug
  opal/mca/btl/tcp/btl_tcp_proc.c
Labels: bug

#7079 Edit README
  README
Labels: documentation

#7081 Removed text block from line 883 of README.
  README
  ompi/mpiext/cr/Makefile.am
  ompi/mpiext/cr/c/Makefile.am
  ompi/mpiext/cr/c/checkpoint.c
  ompi/mpiext/cr/c/inc_register_callback.c
  ompi/mpiext/cr/c/migrate.c
  ompi/mpiext/cr/c/mpiext_cr_c.h
  ompi/mpiext/cr/c/quiesce_checkpoint.c
  ompi/mpiext/cr/c/quiesce_end.c
  ompi/mpiext/cr/c/quiesce_start.c
  ompi/mpiext/cr/c/restart.c
  ompi/mpiext/cr/c/self_register_checkpoint.c
  ompi/mpiext/cr/c/self_register_continue.c
  ompi/mpiext/cr/c/self_register_restart.c
  ompi/mpiext/cr/configure.m4
Labels: code cleanup, documentation

#7076 README: Remove info for plugins that aren't used anymore
  README
Labels: documentation

#7060 BTL usnic MCA updates
  opal/mca/btl/usnic/btl_usnic_mca.c
Labels: bug

#6998 v3.0.x: Do not use CMA in user namespaces
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/btl/vader/help-btl-vader.txt
Labels: NEWS, RM approved, Severity: critical, Target: v3.0.x, enhancement

#7040 Updates for v3.0.5rc1
  NEWS
  README
  VERSION
Labels: RM approved, Target: v3.0.x, documentation

#6999 v3.1.x: Do not use CMA in user namespaces
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/btl/vader/help-btl-vader.txt
Labels: NEWS, RM approved, Severity: critical, Target: v3.1.x, enhancement

#7037 Updates for v3.1.5rc1
  NEWS
  README
  VERSION
Labels: RM approved, Target: v3.1.x, documentation

#7041 v3.0.x: usnic fixes and optimizations
  opal/mca/btl/usnic/btl_usnic.h
  opal/mca/btl/usnic/btl_usnic_component.c
  opal/mca/btl/usnic/btl_usnic_mca.c
  opal/mca/btl/usnic/btl_usnic_module.c
  opal/mca/btl/usnic/btl_usnic_recv.h
Labels: RM approved, Target: v3.0.x, bug

#7039 v3.1.x: usnic fixes and optimizations
  opal/mca/btl/usnic/btl_usnic.h
  opal/mca/btl/usnic/btl_usnic_component.c
  opal/mca/btl/usnic/btl_usnic_mca.c
  opal/mca/btl/usnic/btl_usnic_module.c
  opal/mca/btl/usnic/btl_usnic_recv.h
Labels: RM approved, Target: v3.1.x, bug

#7016 btl/uct: add support for OpenUCX v1.8 API changes
  opal/mca/btl/uct/btl_uct.h
  opal/mca/btl/uct/btl_uct_am.c
  opal/mca/btl/uct/btl_uct_amo.c
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/btl/uct/btl_uct_rdma.c
  opal/mca/btl/uct/btl_uct_rdma.h
  opal/mca/btl/uct/btl_uct_tl.c
Labels: Target: master

#7057 MPIR_Status_set_bytes: fix for large counts
  ompi/mca/io/romio321/src/io_romio321_module.c
Labels: Target: master, enhancement

#7043 v4.0.x: usnic fixes and optimizations
  opal/mca/btl/usnic/btl_usnic.h
  opal/mca/btl/usnic/btl_usnic_component.c
  opal/mca/btl/usnic/btl_usnic_mca.c
  opal/mca/btl/usnic/btl_usnic_module.c
  opal/mca/btl/usnic/btl_usnic_recv.h
Labels: Target: v4.0.x, bug

#7033 v4.0.x:Fix the sigkill timeout sleep to prevent SIGCHLD from preventing completion
  orte/mca/odls/base/odls_base_default_fns.c
Labels: Target: v4.0.x, bug

#7096 opal_check_alps: fix configure output
  config/opal_check_alps.m4
Labels: Severity: minor, Target: master

#6933 UCX osc: properly release exclusive lock to avoid lockup
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
Labels: Target: master, bug

#6284 Ensure proper alignment of memory provided by MPI
  ompi/mca/osc/rdma/osc_rdma_component.c
  opal/include/opal/align.h
  opal/mca/mpool/base/mpool_base_alloc.c
  opal/mca/shmem/shmem_types.h
  test/mpool/mpool_memkind.c
Labels: Target: master, Target: v5.0.x, enhancement

#7105 fortran/use-mpi-f08: revamp mpi_f08 constants
  .gitignore
  config/ompi_fortran_check_protected.m4
  config/ompi_setup_mpi_fortran.m4
  ompi/include/mpif-values.pl
  ompi/mpi/fortran/common_sym_whitelist.txt
  ompi/mpi/fortran/configure-fortran-output-bottom.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/constants.c
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
  ompi/mpiext/shortfloat/use-mpi-f08/mpiext_shortfloat_usempif08.h.in
  ompi/tools/ompi_info/param.c
Labels: Target: master, fortran bindings

#7092 plm/rsh: Add chdir option to change directory before orted exec
  orte/mca/plm/rsh/plm_rsh.h
  orte/mca/plm/rsh/plm_rsh_component.c
  orte/mca/plm/rsh/plm_rsh_module.c
Labels: Target: master, enhancement

#7122 common/ompio: fix calculation in simple-grouping option
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: bug

#7125 plm/rsh: Add chdir option to change directory before orted exec
  orte/mca/plm/rsh/plm_rsh.h
  orte/mca/plm/rsh/plm_rsh_component.c
  orte/mca/plm/rsh/plm_rsh_module.c
Labels: Target: v4.0.x, enhancement

#7117 fortran/use-mpi-f08: misc fixes
  ompi/mpi/fortran/configure-fortran-output.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
Labels: Target: master, bug, code cleanup, fortran bindings
