Repository open-mpi/ompi, pull requests merged in 2019-11, with the labels that each got.

#7047 comomn_ompio_file_read/write: fix 2GB limiting issue
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
Labels: NEWS, Target: v4.0.x, bug

#7102 MPIR_Status_set_bytes: fix for large count sizes
  ompi/mca/io/romio321/src/io_romio321_module.c
Labels: NEWS, Target: v4.0.x, bug

#7119 Ensure that grequestx continuously make progress (v4.0.x)
  ompi/request/grequestx.c
Labels: Target: v4.0.x, bug

#7144 btl/uct: fix compilation for UCX 1.7.0
  opal/mca/btl/uct/btl_uct.h
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/btl/uct/btl_uct_rdma.h
  opal/mca/btl/uct/btl_uct_tl.c
Labels: Target: master, bug

#7145 Shmem: use bitwise and instead of logical and to check for allocator capabilities (v4.0.x)
  oshmem/mca/memheap/base/memheap_base_alloc.c
Labels: Target: v4.0.x

#5507 Adding -mca comm_method to print table of communication methods
  ompi/mca/hook/comm_method/Makefile.am
  ompi/mca/hook/comm_method/configure.m4
  ompi/mca/hook/comm_method/hook_comm_method.h
  ompi/mca/hook/comm_method/hook_comm_method_component.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/hook/comm_method/owner.txt
  ompi/mca/pml/base/pml_base_frame.c
  ompi/mca/pml/cm/pml_cm.c
  ompi/mca/pml/crcpw/pml_crcpw_module.c
  ompi/mca/pml/example/pml_example.c
  ompi/mca/pml/monitoring/pml_monitoring_component.c
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/yalla/pml_yalla.c
Labels: State: Awaiting user information, Target: master

#7170 Add detection for JSM direct launch
  orte/mca/schizo/jsm/Makefile.am
  orte/mca/schizo/jsm/configure.m4
  orte/mca/schizo/jsm/owner.txt
  orte/mca/schizo/jsm/schizo_jsm.c
  orte/mca/schizo/jsm/schizo_jsm.h
  orte/mca/schizo/jsm/schizo_jsm_component.c
Labels: enhancement

#7175 OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs
  opal/mca/btl/openib/mca-btl-openib-device-params.ini
  opal/mca/common/verbs/common_verbs_port.c
Labels: NEWS

#7126 fcoll/two_phase: fix error in calculating aggregators in 32bit mode
  ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
Labels: bug

#7075 Remove mxm
  README
  config/ompi_check_mxm.m4
  ompi/mca/pml/yalla/Makefile.am
  ompi/mca/pml/yalla/configure.m4
  ompi/mca/pml/yalla/owner.txt
  ompi/mca/pml/yalla/pml_yalla.c
  ompi/mca/pml/yalla/pml_yalla.h
  ompi/mca/pml/yalla/pml_yalla_component.c
  ompi/mca/pml/yalla/pml_yalla_datatype.c
  ompi/mca/pml/yalla/pml_yalla_datatype.h
  ompi/mca/pml/yalla/pml_yalla_freelist.h
  ompi/mca/pml/yalla/pml_yalla_request.c
  ompi/mca/pml/yalla/pml_yalla_request.h
  oshmem/mca/atomic/mxm/Makefile.am
  oshmem/mca/atomic/mxm/atomic_mxm.h
  oshmem/mca/atomic/mxm/atomic_mxm_component.c
  oshmem/mca/atomic/mxm/atomic_mxm_cswap.c
  oshmem/mca/atomic/mxm/atomic_mxm_fadd.c
  oshmem/mca/atomic/mxm/atomic_mxm_module.c
  oshmem/mca/atomic/mxm/configure.m4
  oshmem/mca/spml/ikrit/Makefile.am
  oshmem/mca/spml/ikrit/configure.m4
  oshmem/mca/spml/ikrit/help-oshmem-spml-ikrit.txt
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
  oshmem/mca/spml/ikrit/spml_ikrit_component.c
  oshmem/mca/spml/ikrit/spml_ikrit_component.h
Labels: code cleanup, documentation, ⚠️ WIP-DNM!

#7138 3.0.x Oct->Nov slip release fixes
  NEWS
  README
  VERSION
Labels: Target: v3.0.x

#7139 3.1.x Oct->Nov slip release fixes
  NEWS
  README
  VERSION
Labels: Target: v3.1.x

#7196 dist: Prep for 3.0.6
  NEWS
  VERSION
Labels: Target: v3.0.x

#7193 common/ompio: fix calculation in simple-grouping option
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: NEWS, Target: v4.0.x, bug

#7197 dist: Prep for 3.1.6
  NEWS
  VERSION
Labels: Target: v3.1.x

#7194 fcoll/two_phase: fix error in calculating aggregators in 32bit mode
  ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
Labels: NEWS, Target: v4.0.x, bug

#7184 cray ftn: modify fortran module loc checker
  config/ompi_fortran_find_module_include_flag.m4
Labels: Target: master

#7205 configury: fix a typo in mpiext/shortfloat
  ompi/mpiext/shortfloat/configure.m4
Labels: Target: master, bug

#7065 oshmem: fix race condition on new contexts
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: v4.0.x, bug
