Repository open-mpi/ompi, pull requests merged in 2019-09, with the labels that each got.

#6942 v4.0.x: Fix osc sm posts when only 32 bit atomics support v4.0.x
  ompi/mca/osc/sm/osc_sm_active_target.c
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: v4.0.x, bug

#6945 Small optimization on the datatype commit.
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  test/datatype/to_self.c
Labels: Target: v4.0.x

#6947 v3.1.x: regx/naive: add regx/naive component
  orte/mca/regx/fwd/regx_fwd.c
  orte/mca/regx/naive/Makefile.am
  orte/mca/regx/naive/owner.txt
  orte/mca/regx/naive/regx_naive.c
  orte/mca/regx/naive/regx_naive.h
  orte/mca/regx/naive/regx_naive_component.c
  orte/mca/regx/reverse/regx_reverse.c
Labels: RM approved, Target: v3.1.x, bug

#6857 Pr/ompio_fcoll_write_clean
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
Labels: code cleanup, enhancement

#6956 v3.0.x: io_ompio_file_open: fix offset calculation with SEEK_END
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: RM approved, Target: v3.0.x, bug

#6955 v3.1.x: io_ompio_file_open: fix offset calculation with SEEK_END
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: RM approved, Target: v3.1.x, bug

#6957 Ensure buffer_unload leaves the buffer in a clean state
  opal/dss/dss_load_unload.c
  orte/util/nidmap.c
  test/class/opal_tree.c
Labels: Target: master, bug

#6756 romio info: letting romio keep its internal setup
  ompi/mca/io/io.h
  ompi/mca/io/ompio/io_ompio_module.c
  ompi/mca/io/romio321/src/io_romio321.h
  ompi/mca/io/romio321/src/io_romio321_file_open.c
  ompi/mca/io/romio321/src/io_romio321_module.c
  ompi/mpi/c/file_get_info.c
  ompi/mpi/c/file_set_info.c
Labels: Target: master

#6961 btl/vader: when using single-copy emulation fragment large rdma
  opal/mca/btl/vader/btl_vader_atomic.c
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_frag.h
  opal/mca/btl/vader/btl_vader_get.c
  opal/mca/btl/vader/btl_vader_put.c
Labels: Target: master, bug

#6967 v4.0.x: Be a little less restrictive on interface requirements
  orte/mca/oob/tcp/help-oob-tcp.txt
  orte/mca/oob/tcp/oob_tcp_listener.c
Labels: bug

#6952 v4.0.x: Datatype optimization and fix
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  test/datatype/to_self.c
Labels: Target: v4.0.x, bug

#6944 Fix tree spawn routed component issue
  orte/mca/plm/rsh/plm_rsh_module.c
Labels: NEWS, Severity: critical, Target: v4.0.x

#6968 v3.1.x: Be a little less restrictive on interface requirements
  orte/mca/oob/tcp/help-oob-tcp.txt
  orte/mca/oob/tcp/oob_tcp_listener.c
Labels: NEWS, RM approved, bug

#6943 v3.1.x: Fix osc sm posts when only 32 bit atomics support v3.1
  ompi/mca/osc/sm/osc_sm_active_target.c
  ompi/mca/osc/sm/osc_sm_component.c
Labels: RM approved, Target: v3.1.x, bug

#6904 Conform MPIR_Breakpoint to MPIR standard.
  orte/orted/orted_submit.c
Labels: Target: master

#6991 Ensure that grequestx continuously make progress
  ompi/request/grequestx.c
Labels: NEWS, bug

#6989 v3.1.x: Conform MPIR_Breakpoint to MPIR standard.
  orte/orted/orted_submit.c
Labels: RM approved, Target: v3.1.x, bug

#6988 v3.0.x: Conform MPIR_Breakpoint to MPIR standard.
  orte/orted/orted_submit.c
Labels: RM approved, Target: v3.0.x, bug

#6990 v4.0.x: Conform MPIR_Breakpoint to MPIR standard.
  orte/orted/orted_submit.c
Labels: Target: v4.0.x, bug

#6996 v4.0.x: ess/pmi: Fix `--enable-timing` compilation error
  orte/mca/ess/pmi/ess_pmi_module.c
  orte/mca/ess/singleton/ess_singleton_module.c
Labels: Target: v4.0.x, bug

#6844 Do not use CMA in user namespaces
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/btl/vader/help-btl-vader.txt
Labels: Target: master

#6997 v4.0.x: Do not use CMA in user namespaces
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/btl/vader/help-btl-vader.txt
Labels: NEWS, Severity: critical, Target: v4.0.x, enhancement

#7000 platform/mellanox: disable missing libcuda warning
  contrib/platform/mellanox/optimized.conf
Labels: Target: master, enhancement

#7004 REF6976 Silent failure of OMPI over OFI with large messages sizes
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: master, bug

#7001 platform/mellanox: disable missing libcuda warning — v4
  contrib/platform/mellanox/optimized.conf
Labels: Target: v4.0.x, enhancement

#7005 v4.0.x: REF6976 Silent failure of OMPI over OFI with large messages sizes
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v4.0.x, bug

#7002 IKRIT: restored compilation - v4.0
  oshmem/mca/memheap/base/base.h
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/ikrit/spml_ikrit.h
Labels: fix for v4.0.2

#7010 Cleanup stale code in ORTE/OOB
  orte/mca/oob/base/base.h
  orte/mca/oob/base/oob_base_frame.c
  orte/mca/oob/tcp/oob_tcp.c
  orte/mca/oob/tcp/oob_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_component.h
  orte/mca/oob/tcp/oob_tcp_connection.c
  orte/mca/oob/tcp/oob_tcp_connection.h
  orte/mca/oob/tcp/oob_tcp_peer.h
  orte/mca/oob/tcp/oob_tcp_sendrecv.h
Labels: Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug, code cleanup

#7013 v3.1.x: Cleanup stale code in ORTE/OOB
  opal/mca/pmix/pmix2x/pmix/src/mca/pnet/base/pnet_base_fns.c
  orte/mca/oob/base/base.h
  orte/mca/oob/base/oob_base_frame.c
  orte/mca/oob/tcp/oob_tcp.c
  orte/mca/oob/tcp/oob_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_component.h
  orte/mca/oob/tcp/oob_tcp_connection.c
  orte/mca/oob/tcp/oob_tcp_connection.h
  orte/mca/oob/tcp/oob_tcp_listener.c
  orte/mca/oob/tcp/oob_tcp_peer.h
  orte/mca/oob/tcp/oob_tcp_sendrecv.h
Labels: RM approved, Target: v3.1.x, bug, code cleanup

#7014 v3.0.x: Cleanup stale code in ORTE/OOB
  opal/mca/pmix/pmix2x/pmix/src/mca/pnet/base/pnet_base_fns.c
  orte/mca/oob/base/base.h
  orte/mca/oob/base/oob_base_frame.c
  orte/mca/oob/tcp/oob_tcp.c
  orte/mca/oob/tcp/oob_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_component.h
  orte/mca/oob/tcp/oob_tcp_connection.c
  orte/mca/oob/tcp/oob_tcp_connection.h
  orte/mca/oob/tcp/oob_tcp_listener.c
  orte/mca/oob/tcp/oob_tcp_peer.h
  orte/mca/oob/tcp/oob_tcp_sendrecv.h
Labels: RM approved, Target: v3.0.x, bug, code cleanup

#7012 v3.0.x: Fix oob_tcp tcp_component_close segfault with active listeners
  orte/mca/oob/tcp/oob_tcp_component.c
Labels: RM approved, Target: v3.0.x, bug

#7011 v3.1.x: Fix oob_tcp tcp_component_close segfault with active listeners
  orte/mca/oob/tcp/oob_tcp_component.c
Labels: RM approved, Target: v3.1.x, bug

#7018 v4.0.x: Cleanup stale code in ORTE/OOB
  orte/mca/oob/base/base.h
  orte/mca/oob/base/oob_base_frame.c
  orte/mca/oob/tcp/oob_tcp.c
  orte/mca/oob/tcp/oob_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_component.h
  orte/mca/oob/tcp/oob_tcp_connection.c
  orte/mca/oob/tcp/oob_tcp_connection.h
  orte/mca/oob/tcp/oob_tcp_listener.c
  orte/mca/oob/tcp/oob_tcp_peer.h
  orte/mca/oob/tcp/oob_tcp_sendrecv.h
Labels: bug, code cleanup
