Repository open-mpi/ompi, pull requests merged in 2019-05, with the labels that each got.

#6605 SPML/UCX: Add shmemx_alltoall_global_nb routine to shmemx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/include/shmemx.h
  oshmem/mca/spml/base/base.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/shmem/c/shmem_put_nb.c
Labels: Target: master

#6615 fixing an unsafe usage of integer disps[] (romio321 gpfs)
  ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_aggrs.c
Labels: NEWS, Target: v4.0.x

#6594 OSC/UCX: use correct rkey for atomic_fadd in rget/rput
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: v4.0.x

#6572 in-place conversion macro writes into INPUT argument
  ompi/mpi/fortran/base/fint_2_int.h
  ompi/mpi/fortran/mpif-h/cart_create_f.c
  ompi/mpi/fortran/mpif-h/cart_map_f.c
  ompi/mpi/fortran/mpif-h/cart_sub_f.c
Labels: Target: v4.0.x

#6629 buildrpm.sh no longer respects the value of rpmtopdir
  contrib/dist/linux/README
  contrib/dist/linux/buildrpm.sh
Labels: Target: master

#6621 Fix the leak of fragments for persistent sends (issue #6565)
  ompi/mca/pml/ob1/pml_ob1_rdmafrag.h
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
Labels: Target: master, Target: v3.0.x, Target: v3.1.x, Target: v4.0.x, bug

#6637 v3.0.x buildrpm.sh no longer respects the value of rpmtopdir
  contrib/dist/linux/README
  contrib/dist/linux/buildrpm.sh
Labels: RM approved, Target: v3.0.x

#6638 v3.1.x buildrpm.sh no longer respects the value of rpmtopdir
  contrib/dist/linux/README
  contrib/dist/linux/buildrpm.sh
Labels: RM approved, Target: v3.1.x

#6626 v4.0.x: mpi: mark MPI_COMBINER_{HVECTOR,HINDEXED,STRUCT}_INTEGER removed
  ompi/include/mpi.h.in
  ompi/mpi/cxx/constants.h
Labels: NEWS, Target: v4.0.x, code cleanup

#6632 SPML/UCX: Add shmemx_alltoall_global_nb routine to shmemx.h 4.0.x
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/include/shmemx.h
  oshmem/mca/spml/base/base.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/mca/spml/ikrit/spml_ikrit.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/shmem/c/shmem_put_nb.c
Labels: Target: v4.0.x

#6636 v4.0.x buildrpm.sh no longer respects the value of rpmtopdir
  contrib/dist/linux/README
  contrib/dist/linux/buildrpm.sh
Labels: Target: v4.0.x

#6646 osc/rdma: fix CAS 32-bit network atomic compatibility check
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: master, bug

#6645 btl/ugni: fix 32-bit compare-and-swap atomics
  opal/mca/btl/ugni/btl_ugni_atomic.c
Labels: Target: master, bug

#5215 usNIC updates
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/README.txt
  opal/mca/btl/usnic/btl_usnic.h
  opal/mca/btl/usnic/btl_usnic_compat.c
  opal/mca/btl/usnic/btl_usnic_compat.h
  opal/mca/btl/usnic/btl_usnic_component.c
  opal/mca/btl/usnic/btl_usnic_connectivity.h
  opal/mca/btl/usnic/btl_usnic_frag.h
  opal/mca/btl/usnic/btl_usnic_hwloc.c
  opal/mca/btl/usnic/btl_usnic_hwloc.h
  opal/mca/btl/usnic/btl_usnic_mca.c
  opal/mca/btl/usnic/btl_usnic_module.c
  opal/mca/btl/usnic/btl_usnic_recv.c
  opal/mca/btl/usnic/btl_usnic_send.c
  opal/mca/btl/usnic/btl_usnic_util.h
Labels: Target: master, code cleanup

#6382 mtl/ofi: add a .gitignore
  ompi/mca/mtl/ofi/.gitignore
Labels: Target: master, code cleanup

#6651 btl/vader: fix finalize sequence
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
  ompi/mca/topo/treematch/treematch/tm_topology.c
  ompi/mca/topo/treematch/treematch/tm_tree.c
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_module.c
Labels: NEWS, Target: v4.0.x, bug

#6647 Fix/length 0
  ompi/datatype/ompi_datatype_create_contiguous.c
  ompi/datatype/ompi_datatype_create_darray.c
  ompi/datatype/ompi_datatype_create_indexed.c
  ompi/datatype/ompi_datatype_create_struct.c
  ompi/datatype/ompi_datatype_create_vector.c
  ompi/datatype/ompi_datatype_module.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype_dump.c
  test/datatype/ddt_raw.c
Labels: Target: master, bug

#6668 btl/uct: check for support before disabling UCX memory hooks
  opal/mca/btl/uct/btl_uct_component.c
Labels: Target: master, bug

#6675 COMMON/UCX: init memhooks infra on external hooks only
  opal/mca/common/ucx/common_ucx.c
Labels: Target: master

#6676 oshmem: remove useless reference to orte header
  oshmem/mca/memheap/base/memheap_base_select.c
Labels: code cleanup

#6679 COMMON/UCX: init memhooks infra on external hooks only - v4.0
  opal/mca/common/ucx/common_ucx.c
Labels: Target: v4.0.x

#6663 v4.0.x: openmpi.spec: make sure grep failure doesn't abort
  contrib/dist/linux/openmpi.spec
Labels: NEWS, Target: v4.0.x, bug

#6661 SPML/UCX: Fix coverity error - 4.0.x
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: v4.0.x

#6652 OSHMEM: Add support for shmemx_malloc_with_hint() - v4.0.x
  oshmem/include/pshmemx.h
  oshmem/include/shmemx.h
  oshmem/mca/memheap/base/base.h
  oshmem/mca/memheap/base/memheap_base_alloc.c
  oshmem/mca/memheap/base/memheap_base_frame.c
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/base/memheap_base_select.c
  oshmem/mca/memheap/base/memheap_base_static.c
  oshmem/mca/memheap/memheap.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/base/base.h
  oshmem/mca/sshmem/base/sshmem_base_wrappers.c
  oshmem/mca/sshmem/mmap/sshmem_mmap_module.c
  oshmem/mca/sshmem/sshmem.h
  oshmem/mca/sshmem/sshmem_types.h
  oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
  oshmem/mca/sshmem/ucx/Makefile.am
  oshmem/mca/sshmem/ucx/configure.m4
  oshmem/mca/sshmem/ucx/sshmem_ucx.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_shadow.c
  oshmem/shmem/c/profile/defines.h
  oshmem/shmem/c/shmem_alloc.c
  oshmem/shmem/c/shmem_free.c
  oshmem/shmem/c/shmem_realloc.c
Labels: Target: v4.0.x

#6680 PML/UCX: disable PML UCX if MT is requested but not supported
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
Labels: Target: master

#6687 OSC/UCX: Fix deadlock with atomic lock
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
Labels: Target: master, bug

#6693 SPML/UCX: fixed few compilation warnings
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/sshmem/ucx/configure.m4
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: Target: master

#6697 Topic/external32 v2
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_buffer.c
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_read_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/io/ompio/io_ompio_file_read.c
  ompi/mca/io/ompio/io_ompio_file_set_view.c
  ompi/mca/io/ompio/io_ompio_file_write.c
Labels: Target: master, Target: v5.0.x, enhancement

#6670 btl/uct: add support for UCX 1.6.x
  opal/mca/btl/uct/btl_uct_endpoint.c
  opal/mca/btl/uct/btl_uct_tl.c
Labels: Target: master, bug

#6698 SSHMEM/COLL: added sshmem/mpi implementation for shmem_collect call
  oshmem/mca/scoll/mpi/scoll_mpi_ops.c
Labels: Target: master

#6688 OSC/UCX: Fix deadlock with atomic lock - v4.0
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
Labels: NEWS, Target: v4.0.x, bug

#6689 PML/UCX: disable PML UCX if MT is requested but not supported - v4.0
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
Labels: Target: v4.0.x

#6704 common/ompio: fix division by zero problem with empty fview
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: NEWS, Target: v4.0.x, bug

#6694 SPML/UCX: added synchronized flush on quiet
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: master

#6672 v4.0.x: plm_slurm_module: adjust for new SLURM CLI options
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: NEWS, Target: v4.0.x, bug

#6711 opal/atomic: work around memory barrier bug in older gcc
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: master, bug

#6531 shmat/shmdt additions for patcher
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Target: master

#6683 Fixed SPC/MPI_T initialization error.
  ompi/mpi/man/man3/MPI_T_cvar_handle_alloc.3in
  ompi/mpi/man/man3/MPI_T_finalize.3in
  ompi/mpi/man/man3/MPI_T_pvar_handle_alloc.3in
  ompi/mpi/man/man3/MPI_T_pvar_session_create.3in
  ompi/mpi/man/man3/MPI_T_pvar_start.3in
  ompi/mpi/man/man3/MPI_T_pvar_write.3in
  ompi/runtime/ompi_spc.c
  test/spc/spc_test.c
Labels: bug

#6718 SPML/UCX: added synchronized flush on quiet - v4.0
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v4.0.x
