Repository open-mpi/ompi, pull requests merged in 2020-10, with the labels that each got.

#8073 Prep for 4.1.0rc2 release
  NEWS
  VERSION
Labels: Target: v4.1.x

#8071 oob/tcp: fix a race condition on stop_thread pipe
  orte/mca/oob/tcp/oob_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_listener.c
Labels: Target: v4.0.x, Target: v4.1.x, bug

#7839 noinline to avoid compiler reading TOC before PATCHER_BEGIN
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Target: v3.1.x, enhancement

#8076 build: Ignore use-mpi's types file
  .gitignore
Labels: Target: master

#8077 Fix 3rd-party package CPPFLAGS (and others) handlinge
  config/aclocal_subcfg.m4
  config/ompi_setup_prrte.m4
  config/opal_config_hwloc.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
  config/opal_subdir_env.m4
Labels: Target: master, bug

#8067 PML OB1: Fix potential overcounting of SPC sent/received message sizes and account for fin messages
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
Labels: Target: master

#8066 PML UCX: add SPC instrumentation for sent/received message sizes
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
Labels: Target: master

#8088 v4.1.x: opal/util: Fix typo
  opal/util/stacktrace.c
Labels: RM approved, Severity: minor, Target: v4.1.x

#8079 symbol pollution
  ompi/mca/hook/comm_method/hook_comm_method.h
  ompi/mca/hook/comm_method/hook_comm_method_component.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/runtime/ompi_spc.c
Labels: Target: master

#8083 symbol pollution
  ompi/runtime/ompi_spc.c
Labels: Target: v4.0.x

#8087 v4.0.x: opal/util: Fix typo
  opal/util/stacktrace.c
Labels: Severity: minor, Target: v4.0.x

#8101 fortran.m4: reword error message when sizeof(int) != sizeof(INTEGER)
  config/ompi_setup_mpi_fortran.m4
Labels: Target: v4.1.x, documentation, fortran bindings

#8096 v4.0.x: make Type_create_resized set FLAG_USER_UB
  opal/datatype/opal_datatype_resize.c
Labels: Target: v4.0.x

#8105 pml/ucx: fix zero sized datatype transfers
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: bug

#7926 oshmem/mca/sshmem: Fix build with `--enable-mem-debug`
  oshmem/mca/memheap/base/memheap_base_alloc.c
  oshmem/mca/sshmem/sshmem_types.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/shmem/c/shmem_free.c
  oshmem/shmem/c/shmem_realloc.c
Labels: Target: master

#8107 oshmem/mca/sshmem: Fix build with `--enable-mem-debug`
  oshmem/mca/memheap/base/memheap_base_alloc.c
  oshmem/mca/sshmem/sshmem_types.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/shmem/c/shmem_free.c
  oshmem/shmem/c/shmem_realloc.c
Labels: Target: master

#8108 dist: Update NEWS file from branches
  NEWS
Labels: Target: master

#8095 v4.1.x: make Type_create_resized set FLAG_USER_UB
  opal/datatype/opal_datatype_resize.c
Labels: Target: v4.1.x

#8094 v4.1.x: Adding ofi include to CPPFLAGS so that configure can check fabric.h
  config/opal_check_ofi.m4
Labels: RM approved, Target: v4.1.x, bug

#8082 v4.1.x: symbol pollution
  ompi/runtime/ompi_spc.c
Labels: RM approved, Target: v4.1.x

#8111 NEWS and VERSION updates for v4.1.x branch
  NEWS
  VERSION
Labels: Target: v4.1.x

#8115 add blurb about issue 7968 to the README
  README
Labels: RM approved, Target: v4.1.x, documentation

#8119 [v4.1.x] mtl/ofi: Do not fail if error CQ is empty
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v4.1.x, bug

#8125 [v4.0.x] mtl/ofi: Do not fail if error CQ is empty
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v4.0.x, bug

#8130 v4.1.x: Check for spaces in prefix, srcdir, and builddir
  config/opal_get_version.m4
  configure.ac
Labels: RM approved, Target: v4.1.x

#8134 Converted MPI_Barrier.3in to MPI_Barrier.md
  ompi/mpi/man/man3/MPI_Barrier.3in
  ompi/mpi/man/man3/MPI_Barrier.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#7735 A hierarchical, architecture-aware collective communication module
  ompi/communicator/comm.c
  ompi/communicator/communicator.h
  ompi/group/group.c
  ompi/group/group.h
  ompi/mca/coll/adapt/coll_adapt_ibcast.c
  ompi/mca/coll/base/coll_base_comm_select.c
  ompi/mca/coll/base/coll_base_comm_unselect.c
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/coll.h
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_allgather.c
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_bcast.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_dynamic_file.c
  ompi/mca/coll/han/coll_han_dynamic_file.h
  ompi/mca/coll/han/coll_han_gather.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_reduce.c
  ompi/mca/coll/han/coll_han_scatter.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mca/coll/han/coll_han_topo.c
  ompi/mca/coll/han/coll_han_trigger.c
  ompi/mca/coll/han/coll_han_trigger.h
  ompi/mca/coll/sm/coll_sm_module.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
  ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
  ompi/request/request.c
  opal/datatype/opal_datatype_unpack.c
Labels: Target: v5.0.x, performance

#8103 v4.0.x: fortran.m4: reword error message when sizeof(int) != sizeof(INTEGER)
  config/ompi_setup_mpi_fortran.m4
Labels: Target: v4.0.x, documentation, fortran bindings

#8129 v4.0.x: Check for spaces in prefix, srcdir, and builddir
  config/opal_get_version.m4
  configure.ac
Labels: Target: v4.0.x

#8124 mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug

#8138 [v4.1.x] mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: RM approved, Target: v4.1.x, bug

#8122 Fix cpu-list for non-uniform nodes
  orte/mca/plm/base/plm_base_launch_support.c
  orte/mca/rmaps/round_robin/rmaps_rr_assign.c
Labels: RM approved, Target: v4.1.x

#8133 Convert MPI_Bcast.3in to markdown
  ompi/mpi/man/man3/MPI_Bcast.3in
  ompi/mpi/man/man3/MPI_Bcast.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8146 Fix HAN issues reported by Coverity.
  ompi/mca/coll/base/coll_base_comm_select.c
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/han/coll_han_dynamic_file.c
Labels: Target: v5.0.x

#7945 Import the HAN collective into 4.1
  ompi/communicator/comm.c
  ompi/communicator/communicator.h
  ompi/group/group.c
  ompi/group/group.h
  ompi/mca/coll/adapt/coll_adapt_ibcast.c
  ompi/mca/coll/base/coll_base_comm_select.c
  ompi/mca/coll/base/coll_base_comm_unselect.c
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/coll.h
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_allgather.c
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_bcast.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_dynamic_file.c
  ompi/mca/coll/han/coll_han_dynamic_file.h
  ompi/mca/coll/han/coll_han_gather.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_reduce.c
  ompi/mca/coll/han/coll_han_scatter.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mca/coll/han/coll_han_topo.c
  ompi/mca/coll/han/coll_han_trigger.c
  ompi/mca/coll/han/coll_han_trigger.h
  ompi/mca/coll/sm/coll_sm_module.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
  ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
  ompi/request/request.c
  opal/datatype/opal_datatype_unpack.c
Labels: RM approved, Severity: blocker, Target: v4.1.x

#8142 [v4.1.x] pml/ucx: fix zero sized datatype transfers
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: RM approved, Target: v4.1.x, bug

#8135 Convert rest of the MPI_B* man pages to Markdown
  ompi/mpi/man/man3/MPI_Bsend.3in
  ompi/mpi/man/man3/MPI_Bsend.md
  ompi/mpi/man/man3/MPI_Bsend_init.3in
  ompi/mpi/man/man3/MPI_Bsend_init.md
  ompi/mpi/man/man3/MPI_Buffer_attach.3in
  ompi/mpi/man/man3/MPI_Buffer_attach.md
  ompi/mpi/man/man3/MPI_Buffer_detach.3in
  ompi/mpi/man/man3/MPI_Buffer_detach.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8154 Convert MPI_File_write_ordered.3in - MPI_Free_mem.3in to md
  ompi/mpi/man/man3/MPI_File_write_ordered.md
  ompi/mpi/man/man3/MPI_File_write_ordered_begin.3in
  ompi/mpi/man/man3/MPI_File_write_ordered_begin.md
  ompi/mpi/man/man3/MPI_File_write_ordered_end.3in
  ompi/mpi/man/man3/MPI_File_write_ordered_end.md
  ompi/mpi/man/man3/MPI_File_write_shared.3in
  ompi/mpi/man/man3/MPI_File_write_shared.md
  ompi/mpi/man/man3/MPI_Finalize.3in
  ompi/mpi/man/man3/MPI_Finalize.md
  ompi/mpi/man/man3/MPI_Finalized.3in
  ompi/mpi/man/man3/MPI_Finalized.md
  ompi/mpi/man/man3/MPI_Free_mem.3in
  ompi/mpi/man/man3/MPI_Free_mem.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8144 OPAL: fix string buffer allocation for large env variables
  opal/util/keyval_parse.c
Labels: Target: master

#8155 OPAL: fix string buffer allocation for large env variables [v4.1.x]
  opal/util/keyval_parse.c
Labels: RM approved, Target: v4.1.x

#8160 v4.1.x: coll/adapt and coll/han: fix trivial compiler warnings
  ompi/mca/coll/adapt/coll_adapt_ireduce.c
  ompi/mca/coll/adapt/coll_adapt_topocache.h
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_bcast.c
  ompi/mca/coll/han/coll_han_gather.c
Labels: Target: v4.1.x, bug

#8158 Converted first half of MPI_C* (from MPI_Cancel to MPI_Close_port)
  ompi/mpi/man/man3/MPI_Cancel.3in
  ompi/mpi/man/man3/MPI_Cancel.md
  ompi/mpi/man/man3/MPI_Cart_coords.3in
  ompi/mpi/man/man3/MPI_Cart_coords.md
  ompi/mpi/man/man3/MPI_Cart_create.3in
  ompi/mpi/man/man3/MPI_Cart_create.md
  ompi/mpi/man/man3/MPI_Cart_get.3in
  ompi/mpi/man/man3/MPI_Cart_get.md
  ompi/mpi/man/man3/MPI_Cart_map.3in
  ompi/mpi/man/man3/MPI_Cart_map.md
  ompi/mpi/man/man3/MPI_Cart_rank.3in
  ompi/mpi/man/man3/MPI_Cart_rank.md
  ompi/mpi/man/man3/MPI_Cart_shift.3in
  ompi/mpi/man/man3/MPI_Cart_shift.md
  ompi/mpi/man/man3/MPI_Cart_sub.md
  ompi/mpi/man/man3/MPI_Cartdim_get.3in
  ompi/mpi/man/man3/MPI_Cartdim_get.md
  ompi/mpi/man/man3/MPI_Close_port.3in
  ompi/mpi/man/man3/MPI_Close_port.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8161 Convert MPI_Gather.3in - MPI_Get_version.3in to md
  ompi/mpi/man/man3/MPI_Gather.3in
  ompi/mpi/man/man3/MPI_Gather.md
  ompi/mpi/man/man3/MPI_Gatherv.3in
  ompi/mpi/man/man3/MPI_Gatherv.md
  ompi/mpi/man/man3/MPI_Get.3in
  ompi/mpi/man/man3/MPI_Get.md
  ompi/mpi/man/man3/MPI_Get_accumulate.3in
  ompi/mpi/man/man3/MPI_Get_accumulate.md
  ompi/mpi/man/man3/MPI_Get_address.3in
  ompi/mpi/man/man3/MPI_Get_address.md
  ompi/mpi/man/man3/MPI_Get_count.3in
  ompi/mpi/man/man3/MPI_Get_count.md
  ompi/mpi/man/man3/MPI_Get_elements.3in
  ompi/mpi/man/man3/MPI_Get_elements.md
  ompi/mpi/man/man3/MPI_Get_library_version.3in
  ompi/mpi/man/man3/MPI_Get_library_version.md
  ompi/mpi/man/man3/MPI_Get_processor_name.3in
  ompi/mpi/man/man3/MPI_Get_processor_name.md
  ompi/mpi/man/man3/MPI_Get_version.3in
  ompi/mpi/man/man3/MPI_Get_version.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8164 v4.1.x: Keyval parse tweaks
  opal/util/keyval_parse.c
Labels: RM approved, Target: v4.1.x, bug

#8162 Converted batch 2 of MPI_C* (MPI_Comm_accept - MPI_Comm_dup_with_info)
  ompi/mpi/man/man3/MPI_Comm_accept.3in
  ompi/mpi/man/man3/MPI_Comm_accept.md
  ompi/mpi/man/man3/MPI_Comm_call_errhandler.3in
  ompi/mpi/man/man3/MPI_Comm_call_errhandler.md
  ompi/mpi/man/man3/MPI_Comm_compare.3in
  ompi/mpi/man/man3/MPI_Comm_compare.md
  ompi/mpi/man/man3/MPI_Comm_connect.3in
  ompi/mpi/man/man3/MPI_Comm_connect.md
  ompi/mpi/man/man3/MPI_Comm_create.3in
  ompi/mpi/man/man3/MPI_Comm_create.md
  ompi/mpi/man/man3/MPI_Comm_create_errhandler.3in
  ompi/mpi/man/man3/MPI_Comm_create_errhandler.md
  ompi/mpi/man/man3/MPI_Comm_create_group.3in
  ompi/mpi/man/man3/MPI_Comm_create_group.md
  ompi/mpi/man/man3/MPI_Comm_create_keyval.3in
  ompi/mpi/man/man3/MPI_Comm_create_keyval.md
  ompi/mpi/man/man3/MPI_Comm_delete_attr.3in
  ompi/mpi/man/man3/MPI_Comm_delete_attr.md
  ompi/mpi/man/man3/MPI_Comm_disconnect.3in
  ompi/mpi/man/man3/MPI_Comm_disconnect.md
  ompi/mpi/man/man3/MPI_Comm_dup.3in
  ompi/mpi/man/man3/MPI_Comm_dup.md
  ompi/mpi/man/man3/MPI_Comm_dup_with_info.3in
  ompi/mpi/man/man3/MPI_Comm_dup_with_info.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest
