Repository open-mpi/ompi, pull requests merged in 2020-06, with the labels that each got.

#7773 opal/util: fix opal_str_to_bool()
  opal/util/info.c
Labels: Target: master, bug

#7774 v4.0.x: opal/util: fix opal_str_to_bool()
  opal/util/info.c
Labels: NEWS, Target: v4.0.x, bug

#7786 dist: Update NEWS
  NEWS
Labels: Target: master, documentation

#7791 Update 4.0.x news file
  NEWS
Labels: Target: v4.0.x, documentation

#7777 adding op-codes for syscall ipc for shmat/shmdt
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Severity: critical, Target: master, bug

#7792 Update 3.1.x NEWS file
  NEWS
Labels: RM approved, Target: v3.1.x, documentation

#7775 v3.1: opal/util: fix opal_str_to_bool()
  opal/util/info.c
Labels: RM approved, Target: v3.1.x, bug

#7793 Update 3.0.x NEWS file
  NEWS
Labels: RM approved, Target: v3.0.x, documentation

#7778 v4.0.x: adding op-codes for syscall ipc for shmat/shmdt
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Severity: critical, Target: v4.0.x, bug

#7803 v3.1.x: adding op-codes for syscall ipc for shmat/shmdt
  NEWS
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: RM approved, Target: v3.1.x

#7817 mpi.h.in: protect checking __STDC_VERSION__
  ompi/include/mpi.h.in
Labels: Target: master, Target: v5.0.x, bug

#7822 v4.1.x: fixup mpih stdc version usage
  ompi/include/mpi.h.in
Labels: RM approved, Target: v4.1.x

#7789 COMMON/UCX: improved missing events test
  config/ompi_check_ucx.m4
  opal/mca/common/ucx/common_ucx.c
Labels: Target: master

#7819 common/ompio: use avg. file view size in the aggregator selection logic
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_file_view.c
Labels: Target: v4.0.x, Target: v4.1.x, bug

#7826 More carefully test "alternate" short float type in configure
  config/opal_check_alt_short_float.m4
  ompi/mpiext/shortfloat/README.txt
Labels: Target: master, bug

#7834 tests/asm/run_tests: fix basename usage
  test/asm/run_tests
Labels: Target: master, Target: v4.0.x, Target: v4.1.x, bug

#7799 noinline to avoid compiler reading TOC before PATCHER_BEGIN
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: Target: master

#7807 Backport OFI changes from master to v4.1.x
  .mailmap
  NEWS
  VERSION
  config/opal_check_ofi.m4
  configure.ac
  ompi/mca/mtl/ofi/.gitignore
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/README
  ompi/mca/mtl/ofi/configure.m4
  ompi/mca/mtl/ofi/generate-opt-funcs.pl
  ompi/mca/mtl/ofi/help-mtl-ofi.txt
  ompi/mca/mtl/ofi/mtl_ofi.c
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
  ompi/mca/mtl/ofi/mtl_ofi_improbe_opt.pm
  ompi/mca/mtl/ofi/mtl_ofi_iprobe_opt.pm
  ompi/mca/mtl/ofi/mtl_ofi_irecv_opt.pm
  ompi/mca/mtl/ofi/mtl_ofi_isend_opt.pm
  ompi/mca/mtl/ofi/mtl_ofi_opt.h
  ompi/mca/mtl/ofi/mtl_ofi_send_opt.pm
  ompi/mca/mtl/ofi/mtl_ofi_types.h
  ompi/mca/mtl/ofi/opt_common/mtl_ofi_opt.pm.template
  ompi/mca/mtl/ofi/opt_common/mtl_ofi_opt_common.pm
  opal/mca/btl/ofi/Makefile.am
  opal/mca/btl/ofi/README
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_atomics.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_context.c
  opal/mca/btl/ofi/btl_ofi_endpoint.c
  opal/mca/btl/ofi/btl_ofi_endpoint.h
  opal/mca/btl/ofi/btl_ofi_frag.c
  opal/mca/btl/ofi/btl_ofi_frag.h
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/btl/ofi/btl_ofi_rdma.c
  opal/mca/btl/ofi/btl_ofi_rdma.h
  opal/mca/btl/ofi/configure.m4
  opal/mca/btl/ofi/owner.txt
  opal/mca/btl/usnic/configure.m4
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/configure.m4
  opal/mca/common/ofi/owner.txt
Labels: Target: v4.1.x

#7776 Fix language in CUDA error
  opal/mca/common/cuda/help-mpi-common-cuda.txt
Labels: Target: master, documentation

#7838 noinline to avoid compiler reading TOC before PATCHER_BEGIN
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: enhancement

#7835 v4.0.x: tests/asm/run_tests: fix basename usage
  test/asm/run_tests
Labels: NEWS, Severity: minor, Target: v4.0.x, bug

#7846 VERSION: Bump to 5.0.0a1
  VERSION
Labels: Target: master, documentation

#7829 osc rdma: check for outstanding transfers before completing a request
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: Target: master, bug

#7849 ompi_info: trim some redundant output
  ompi/runtime/ompi_info_support.c
  ompi/tools/ompi_info/ompi_info.c
  ompi/tools/ompi_info/param.c
Labels: Target: master, enhancement

#7852 osc rdma: check for outstanding fragments before completing a request (v4.0.x)
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: NEWS, Target: v4.0.x

#7173 Add detection for JSM direct launch
  orte/mca/schizo/jsm/Makefile.am
  orte/mca/schizo/jsm/configure.m4
  orte/mca/schizo/jsm/owner.txt
  orte/mca/schizo/jsm/schizo_jsm.c
  orte/mca/schizo/jsm/schizo_jsm.h
  orte/mca/schizo/jsm/schizo_jsm_component.c
Labels: RM approved, Target: v4.1.x, enhancement

#7853 osc rdma: check for outstanding fragments before completing a request (v4.1.x)
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: RM approved, Target: v4.1.x

#7844 Some spawn info keys are standard mandated and cannot be deprecated
  ompi/dpm/dpm.c
Labels: MPI-3.1, Target: v5.0.x

#7856 osc/rdma: fix bug in attach for non-debug builds
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
Labels: RM approved, Target: v4.1.x, bug

#7848 Fix wrongly placed bounds check; mark failure as unlikely
  opal/runtime/opal_cr.c
Labels: Target: master

#7855 osc/rdma: fix bug in attach for non-debug builds
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
Labels: NEWS, Target: v4.0.x, bug

#7863 add a common ofi include/exclude list
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/ofi/mtl_ofi.c
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/Makefile.am
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: RM approved, Target: v4.1.x

#7837 noinline to avoid compiler reading TOC before PATCHER_BEGIN
  opal/mca/memory/patcher/memory_patcher_component.c
Labels: RM approved, Target: v4.1.x, enhancement

#7827 v4.0.x: common/ompio: use avg. file view size in the aggregator selection logic
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_file_view.c
Labels: NEWS, Target: v4.0.x, bug

#7854 Remove stale datatype functions from opal header
  opal/datatype/opal_datatype.h
Labels: Target: master

#7845 Fix unexpected optimizations detected by STACK
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/topo/treematch/treematch/tm_malloc.c
Labels: Target: master

#6980 UCX osc: add support for acc_single_intrinsic
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_request.h
  opal/mca/common/ucx/common_ucx.h
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x, enhancement

#7836 v4.1.x: tests/asm/run_tests: fix basename usage
  test/asm/run_tests
Labels: RM approved, Severity: minor, Target: v4.1.x, bug

#7831 Backports/v4.1.x psm2 updates
  README
  config/ompi_check_psm2.m4
  ompi/mca/mtl/psm2/mtl_psm2_component.c
Labels: Target: v4.1.x

#7812 RAS:ALPS add support for ANL Cobalt
  orte/mca/ras/alps/help-ras-alps.txt
  orte/mca/ras/alps/ras_alps_component.c
Labels: Target: v4.1.x

#7814 fs/gpfs: Bring over GPFS component from master to v4.1
  config/ompi_check_gpfs.m4
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/gpfs/Makefile.am
  ompi/mca/fs/gpfs/configure.m4
  ompi/mca/fs/gpfs/fs_gpfs.c
  ompi/mca/fs/gpfs/fs_gpfs.h
  ompi/mca/fs/gpfs/fs_gpfs_component.c
  ompi/mca/fs/gpfs/fs_gpfs_file_get_info.c
  ompi/mca/fs/gpfs/fs_gpfs_file_open.c
  ompi/mca/fs/gpfs/fs_gpfs_file_set_info.c
Labels: RM approved, Target: v4.1.x

#7824 COMMON/UCX: improved missing events test - v4.1
  config/ompi_check_ucx.m4
  opal/mca/common/ucx/common_ucx.c
Labels: RM approved, Target: v4.1.x

#7843 Some fixups for issues detected by clang-tidy
  ompi/attribute/attribute.c
  ompi/mca/coll/base/coll_base_allgather.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/osc/sm/osc_sm_component.c
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
  opal/mca/base/mca_base_alias.c
  opal/mca/btl/tcp/btl_tcp_component.c
  opal/mca/reachable/base/reachable_base_alloc.c
Labels: Target: master, enhancement

#7828 common/ompio: use avg. file view size in the aggregator selection logic
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_file_view.c
Labels: RM approved, Target: v4.1.x, bug

#7875 OSC UCX: Remove stale free from merge conflict
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: master

#7871 OSC UCX: make sure no-op fetch in rget/rput is properly aligned
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: master, bug

#7879 common_ofi: fix preprocessor macro typo
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v4.1.x

#7858 mtl-portals4: use the active PML to call add_procs()
  ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
Labels: Target: master, bug

#7808 Backport Collective changes from master to v4.1.x
  NEWS
  contrib/platform/mellanox/optimized.conf
  ompi/mca/coll/base/coll_base_allgatherv.c
  ompi/mca/coll/base/coll_base_allreduce.c
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/base/coll_base_barrier.c
  ompi/mca/coll/base/coll_base_bcast.c
  ompi/mca/coll/base/coll_base_functions.h
  ompi/mca/coll/base/coll_base_gather.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/coll/base/coll_base_reduce_scatter.c
  ompi/mca/coll/base/coll_base_scatter.c
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/cuda/coll_cuda_module.c
  ompi/mca/coll/hcoll/coll_hcoll.h
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
  ompi/mca/coll/libnbc/coll_libnbc.h
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/coll/libnbc/libdict/dict.h
  ompi/mca/coll/libnbc/libdict/dict_private.h
  ompi/mca/coll/libnbc/libdict/hb_tree.c
  ompi/mca/coll/libnbc/libdict/hb_tree.h
  ompi/mca/coll/libnbc/nbc_iallgather.c
  ompi/mca/coll/libnbc/nbc_iallreduce.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_iexscan.c
  ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/mca/coll/libnbc/nbc_iscan.c
  ompi/mca/coll/tuned/coll_tuned.h
  ompi/mca/coll/tuned/coll_tuned_component.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
  ompi/mca/coll/tuned/coll_tuned_dynamic_file.c
  ompi/mca/coll/tuned/coll_tuned_module.c
  ompi/mca/coll/tuned/coll_tuned_scatter_decision.c
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v4.1.x

#7815 Topic/ime: Bring over IME component from master to v4.1
  config/ompi_check_ime.m4
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/fbtl/ime/Makefile.am
  ompi/mca/fbtl/ime/configure.m4
  ompi/mca/fbtl/ime/fbtl_ime.c
  ompi/mca/fbtl/ime/fbtl_ime.h
  ompi/mca/fbtl/ime/fbtl_ime_blocking_op.c
  ompi/mca/fbtl/ime/fbtl_ime_component.c
  ompi/mca/fbtl/ime/fbtl_ime_nonblocking_op.c
  ompi/mca/fbtl/ime/owner.txt
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/ime/Makefile.am
  ompi/mca/fs/ime/configure.m4
  ompi/mca/fs/ime/fs_ime.c
  ompi/mca/fs/ime/fs_ime.h
  ompi/mca/fs/ime/fs_ime_component.c
  ompi/mca/fs/ime/fs_ime_file_close.c
  ompi/mca/fs/ime/fs_ime_file_delete.c
  ompi/mca/fs/ime/fs_ime_file_get_size.c
  ompi/mca/fs/ime/fs_ime_file_open.c
  ompi/mca/fs/ime/fs_ime_file_set_size.c
  ompi/mca/fs/ime/fs_ime_file_sync.c
  ompi/mca/fs/ime/owner.txt
Labels: RM approved, Target: v4.1.x

#7885 v4.1.x: pmix3x: Remove --enable-install-libpmix option
  opal/mca/pmix/pmix3x/configure.m4
Labels: RM approved, Target: v4.1.x

#7882 osc rdma: check for outstanding fragments before completing a request (II)
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: Target: master

#7888 osc rdma: check for outstanding fragments before completing a request (II) (v4.0.x)
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: NEWS, Target: v4.0.x

#7872 OSC UCX: make sure no-op fetch in rget/rput is properly aligned (v4.0.x)
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: NEWS, Target: v4.0.x

#7889 osc rdma: check for outstanding fragments before completing a request (II) (v4.1.x)
  ompi/mca/osc/rdma/osc_rdma_comm.c
Labels: RM approved, Target: v4.1.x

#7873 OSC UCX: make sure no-op fetch in rget/rput is properly aligned (v4.1.x)
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: RM approved, Target: v4.1.x

#7887 Fix rank-by computation
  orte/mca/rmaps/base/rmaps_base_ranking.c
Labels: Target: v4.0.x, bug

#7825 COMMON/UCX: improved missing events test - v4.0
  config/ompi_check_ucx.m4
  opal/mca/common/ucx/common_ucx.c
Labels: Target: v4.0.x

#7821 v4.0.x: fixup mpi.h stdc version usage
  ompi/include/mpi.h.in
Labels: Target: v4.0.x

#7800 MPI4: Add ERRORS_ABORT infrastructure
  contrib/check_unnecessary_headers.sh
  ompi/debuggers/MPI_Handles_interface.txt
  ompi/debuggers/ompi_mpihandles_dll.c
  ompi/errhandler/errcode.c
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
  ompi/errhandler/errhandler_predefined.c
  ompi/errhandler/errhandler_predefined.h
  ompi/errhandler/help-mpi-errors.txt
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
  ompi/mpi/java/c/mpi_Constant.c
  ompi/mpi/java/c/mpi_Errhandler.c
  ompi/mpi/java/java/Constant.java
  ompi/mpi/java/java/MPI.java
  ompi/mpi/man/man5/Open-MPI.5.md
  ompi/runtime/ompi_mpi_abort.c
  test/simple/Makefile
  test/simple/comm_abort.c
Labels: MPI-4.0, NEWS, Target: v5.0.x, enhancement, 😳 Backward compat break

#7883 UCX/WPOOL: fixed potential deadlock
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: master, bug

#7866 portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/mtl/portals4/mtl_portals4_component.c
Labels: Target: master, bug

#6784 Address a race condition in libevent select.
  opal/mca/event/libevent2022/libevent/select.c
Labels: Severity: minor, State: PR posted, Target: master, Target: v5.0.x, bug

#7823 Fix typos in OSC RDMA BTL allowlist
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master, bug

#7894 v4.0.x: portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/mtl/portals4/mtl_portals4_component.c
Labels: Target: v4.0.x, bug

#7884 v4.0.x: pmix3x: Remove --enable-install-libpmix option
  opal/mca/pmix/pmix3x/configure.m4
Labels: Target: v4.0.x

#7680 oshmem spml ucx: set default nonblocking put/get progress thresholds
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: NEWS, Target: master, Target: v5.0.x, enhancement
