Repository open-mpi/ompi, pull requests merged in 2020-09, with the labels that each got.

#7716 ADAPT: Event-driven collective implementation
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/mca/coll/adapt/Makefile.am
  ompi/mca/coll/adapt/coll_adapt.h
  ompi/mca/coll/adapt/coll_adapt_algorithms.h
  ompi/mca/coll/adapt/coll_adapt_bcast.c
  ompi/mca/coll/adapt/coll_adapt_component.c
  ompi/mca/coll/adapt/coll_adapt_context.c
  ompi/mca/coll/adapt/coll_adapt_context.h
  ompi/mca/coll/adapt/coll_adapt_ibcast.c
  ompi/mca/coll/adapt/coll_adapt_inbuf.c
  ompi/mca/coll/adapt/coll_adapt_inbuf.h
  ompi/mca/coll/adapt/coll_adapt_ireduce.c
  ompi/mca/coll/adapt/coll_adapt_item.c
  ompi/mca/coll/adapt/coll_adapt_item.h
  ompi/mca/coll/adapt/coll_adapt_module.c
  ompi/mca/coll/adapt/coll_adapt_reduce.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/coll_libnbc.h
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/tuned/coll_tuned_component.c
  ompi/mpi/c/ibcast.c
  ompi/mpi/c/ireduce_scatter_block.c
  ompi/mpi/c/reduce_scatter_block.c
  ompi/request/request.h
Labels: Target: v5.0.x, performance

#8035 UCX: do not dereference NULL pointer in wpmem_[free|flush]
  opal/mca/common/ucx/common_ucx_wpool.c
Labels: Target: master, Target: v5.0.x, bug

#8043 mpif-h: fix a typo in MPI_Status_f2f08()
  ompi/mpi/fortran/mpif-h/status_f2f08_f.c
Labels: bug, fortran bindings

#8025 suppress icc long double message
  config/opal_setup_cc.m4
  config/opal_setup_cxx.m4
Labels: RM approved

#8042 Fix a copy/paste in the RDMA emulation.
  opal/mca/btl/sm/btl_sm_sc_emu.c
Labels: bug

#8048 v4.1.x: coll/tuned: Fix dynamic message size for gather and scatter
  ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
Labels: RM approved, Target: v4.1.x, bug

#8039 Fix some corner cases with ADAPT
  ompi/mca/coll/adapt/Makefile.am
  ompi/mca/coll/adapt/coll_adapt.h
  ompi/mca/coll/adapt/coll_adapt_context.c
  ompi/mca/coll/adapt/coll_adapt_context.h
  ompi/mca/coll/adapt/coll_adapt_ibcast.c
  ompi/mca/coll/adapt/coll_adapt_ireduce.c
  ompi/mca/coll/adapt/coll_adapt_module.c
  ompi/mca/coll/adapt/coll_adapt_reduce.c
  ompi/mca/coll/adapt/coll_adapt_topocache.c
  ompi/mca/coll/adapt/coll_adapt_topocache.h
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: Target: v4.1.x, Target: v5.0.x, bug

#7944 Import the ADAPT collective into the 4.1
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/mca/coll/adapt/Makefile.am
  ompi/mca/coll/adapt/coll_adapt.h
  ompi/mca/coll/adapt/coll_adapt_algorithms.h
  ompi/mca/coll/adapt/coll_adapt_bcast.c
  ompi/mca/coll/adapt/coll_adapt_component.c
  ompi/mca/coll/adapt/coll_adapt_context.c
  ompi/mca/coll/adapt/coll_adapt_context.h
  ompi/mca/coll/adapt/coll_adapt_ibcast.c
  ompi/mca/coll/adapt/coll_adapt_inbuf.c
  ompi/mca/coll/adapt/coll_adapt_inbuf.h
  ompi/mca/coll/adapt/coll_adapt_ireduce.c
  ompi/mca/coll/adapt/coll_adapt_item.c
  ompi/mca/coll/adapt/coll_adapt_item.h
  ompi/mca/coll/adapt/coll_adapt_module.c
  ompi/mca/coll/adapt/coll_adapt_reduce.c
  ompi/mca/coll/adapt/coll_adapt_topocache.c
  ompi/mca/coll/adapt/coll_adapt_topocache.h
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/coll_libnbc.h
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/tuned/coll_tuned_component.c
  ompi/mpi/c/ibcast.c
  ompi/mpi/c/ireduce_scatter_block.c
  ompi/mpi/c/reduce_scatter_block.c
  ompi/request/request.h
Labels: Severity: blocker, Target: v4.1.x

#8054 patcher: remove the linux component
  opal/mca/patcher/linux/Makefile.am
  opal/mca/patcher/linux/configure.m4
  opal/mca/patcher/linux/patcher_linux.h
  opal/mca/patcher/linux/patcher_linux_component.c
  opal/mca/patcher/linux/patcher_linux_module.c
Labels: Target: master, code cleanup

#8070 OSC RDMA: put memory for each process into separate pages
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master
