Repository open-mpi/ompi, pull requests merged in 2020-11, with the labels that each got.

#8165 Convert 12 .3in files to md
  ompi/mpi/man/man3/MPI_Graph_create.3in
  ompi/mpi/man/man3/MPI_Graph_create.md
  ompi/mpi/man/man3/MPI_Graph_get.3in
  ompi/mpi/man/man3/MPI_Graph_get.md
  ompi/mpi/man/man3/MPI_Graph_map.3in
  ompi/mpi/man/man3/MPI_Graph_map.md
  ompi/mpi/man/man3/MPI_Graph_neighbors_count.3in
  ompi/mpi/man/man3/MPI_Graph_neighbors_count.md
  ompi/mpi/man/man3/MPI_Graphdims_get.3in
  ompi/mpi/man/man3/MPI_Graphdims_get.md
  ompi/mpi/man/man3/MPI_Grequest_complete.3in
  ompi/mpi/man/man3/MPI_Grequest_complete.md
  ompi/mpi/man/man3/MPI_Grequest_start.3in
  ompi/mpi/man/man3/MPI_Grequest_start.md
  ompi/mpi/man/man3/MPI_Group_compare.3in
  ompi/mpi/man/man3/MPI_Group_compare.md
  ompi/mpi/man/man3/MPI_Group_difference.3in
  ompi/mpi/man/man3/MPI_Group_difference.md
  ompi/mpi/man/man3/MPI_Group_excl.3in
  ompi/mpi/man/man3/MPI_Group_excl.md
  ompi/mpi/man/man3/MPI_Group_free.3in
  ompi/mpi/man/man3/MPI_Group_free.md
  ompi/mpi/man/man3/MPI_Group_incl.3in
  ompi/mpi/man/man3/MPI_Group_incl.md
  ompi/mpi/man/man3/MPI_Group_intersection.3in
  ompi/mpi/man/man3/MPI_Group_intersection.md
  ompi/mpi/man/man3/Makefile.am
Labels: documentation, hacktoberfest

#8148 v4.1.x: reproducible builds + portability fix
  README
  autogen.pl
  config/getdate.sh
  config/opal_functions.m4
  config/opal_get_version.m4
  configure.ac
  ompi/tools/mpisync/Makefile.am
  ompi/tools/ompi_info/Makefile.am
  orte/tools/orte-info/Makefile.am
  oshmem/tools/oshmem_info/Makefile.am
Labels: NEWS, RM approved, Target: v4.1.x, enhancement

#8153 Using package_rank to select between NIC of equal distance from the process.
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/help-common-ofi.txt
Labels: RM approved, Target: master, Target: v4.1.x

#8172 NEWS: More updates for v4.1.0
  NEWS
Labels: RM approved, Target: v4.1.x, documentation

#8168 README: Provide example of differing linker search paths
  README
Labels: Target: v5.0.x, documentation

#8139 [v4.0.x] mtl/ofi: Fix erroneous FI_PEEK/FI_CLAIM usage
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v4.0.x, bug

#8180 op/avx: check for _mm512_mullo_epi64() AVX512 intrinsic
  ompi/mca/op/avx/configure.m4
Labels: Target: master, enhancement

#8143 [v4.0.x] pml/ucx: fix zero sized datatype transfers
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: Target: v4.0.x, bug

#8147 v4.0.x: reproducible builds + portability fix
  README
  autogen.pl
  config/getdate.sh
  config/opal_functions.m4
  config/opal_get_version.m4
  configure.ac
  ompi/tools/mpisync/Makefile.am
  ompi/tools/ompi_info/Makefile.am
  orte/tools/orte-info/Makefile.am
  oshmem/tools/oshmem_info/Makefile.am
Labels: NEWS, Target: v4.0.x, enhancement

#8156 OPAL: fix string buffer allocation for large env variables [4.0.x]
  opal/util/keyval_parse.c
Labels: NEWS, Target: v4.0.x

#8188 v4.1.x: Some getdate.sh fixes
  config/Makefile.am
  config/opal_functions.m4
Labels: RM approved, Target: v4.1.x, bug

#8116 configury: enhance the check for ISO_FORTRAN_ENV module
  config/ompi_fortran_check_iso_fortran_env.m4
Labels: Target: master, enhancement, fortran bindings

#8181 op/avx: check for _mm512_mullo_epi64() AVX512 intrinsic
  ompi/mca/op/avx/configure.m4
Labels: RM approved, Target: v4.1.x, enhancement

#8099 v4.0.x: orterun.1in: fix minor mistake in :PE=2 example and add more descriptions/explanations
  orte/tools/orterun/orterun.1in
Labels: Target: v4.0.x, documentation

#8192 v4.1.x: orterun.1in: fix minor mistake in :PE=2 example and add more descriptions/explanations
  orte/tools/orterun/orterun.1in
Labels: RM approved, Target: v4.1.x, documentation

#8176 v4.1.x: Using package_rank to select between NIC of equal distance from the process
  .gitignore
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/help-common-ofi.txt
  orte/mca/ess/base/ess_base_fns.c
  orte/orted/pmix/pmix_server_register_fns.c
Labels: RM approved, Target: v4.1.x

#8199 Fix confusion between cpuset and locality
  ompi/dpm/dpm.c
  ompi/runtime/ompi_rte.c
  opal/mca/common/ofi/common_ofi.c
  opal/util/proc.c
  opal/util/proc.h
Labels: bug

#8198 Fix some issues with dynamic algorithm selection in coll/tuned
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
  ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c
  ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
  ompi/mca/coll/tuned/coll_tuned_alltoallv_decision.c
  ompi/mca/coll/tuned/coll_tuned_barrier_decision.c
  ompi/mca/coll/tuned/coll_tuned_bcast_decision.c
  ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
  ompi/mca/coll/tuned/coll_tuned_exscan_decision.c
  ompi/mca/coll/tuned/coll_tuned_gather_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_scatter_decision.c
  ompi/mca/coll/tuned/coll_tuned_scan_decision.c
  ompi/mca/coll/tuned/coll_tuned_scatter_decision.c
Labels: RM approved, Target: v4.1.x

#8186 Fix some issues with dynamic algorithm selection in coll/tuned
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
  ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c
  ompi/mca/coll/tuned/coll_tuned_alltoall_decision.c
  ompi/mca/coll/tuned/coll_tuned_alltoallv_decision.c
  ompi/mca/coll/tuned/coll_tuned_barrier_decision.c
  ompi/mca/coll/tuned/coll_tuned_bcast_decision.c
  ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
  ompi/mca/coll/tuned/coll_tuned_exscan_decision.c
  ompi/mca/coll/tuned/coll_tuned_gather_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_scatter_block_decision.c
  ompi/mca/coll/tuned/coll_tuned_reduce_scatter_decision.c
  ompi/mca/coll/tuned/coll_tuned_scan_decision.c
  ompi/mca/coll/tuned/coll_tuned_scatter_decision.c
Labels: Target: master

#8178 mtl/ofi: Check cq_data_size without querying providers again
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v4.1.x, bug

#8202 v4.1.x: Update Internal PMIx to OpenPMIx v3.2.1
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
Labels: RM approved, Target: v4.1.x

#8205 [v4.1.x] mtl/ofi: Check cq_data_size without querying providers again
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: RM approved, Target: v4.1.x

#7632 UCX osc: make progress on idle worker if none are active
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: master, Target: v5.0.x

#8207 coll/base: do not drop const qualifier
  ompi/datatype/ompi_datatype.h
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  opal/class/opal_object.h
Labels: Target: master

#8210 coll/hcoll: svatterv inplace fix
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: bug

#8211 V4.1.x coll/hcoll: svatterv inplace fix
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: bug

#8201 v4.0.x: Update Internal PMIx to OpenPMIx v3.2.1
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
Labels: NEWS, Target: v4.0.x

#8187 v4.0.x: Some getdate.sh fixes
  config/Makefile.am
  config/opal_functions.m4
Labels: NEWS, Target: v4.0.x, bug

#8190 PML/UCX: improved error processing in MPI_Recv - v4.1
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.h
Labels: RM approved, Target: v4.1.x

#8216 v4.1.x: Correctly skip the "mpirun" node when launching orted on it
  orte/mca/ras/base/ras_base_node.c
  orte/mca/rmaps/base/rmaps_base_support_fns.c
Labels: RM approved, Target: v4.1.x, bug

#8196 v4.0.x: Backport fixes to cpuset availability
  .gitignore
  orte/mca/ess/base/ess_base_fns.c
  orte/orted/pmix/pmix_server_register_fns.c
Labels: Target: v4.0.x, bug

#8215 v4.0.x: Correctly skip the "mpirun" node when launching orted on it
  orte/mca/ras/base/ras_base_node.c
  orte/mca/rmaps/base/rmaps_base_support_fns.c
Labels: Target: v4.0.x, bug

#8209 COLL TUNED: Use per-rank data size instead of total size for decision in allgatherv
  ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: Target: master, Target: v4.1.x

#8223 oshmem/tools/oshmem_info: fix fortran keyword issue when compiling param.c
  oshmem/tools/oshmem_info/param.c
Labels: Target: master, Target: v5.0.x

#8224 COLL TUNED: Use per-rank data size instead of total size for decision [4.1.x]
  ompi/mca/coll/tuned/coll_tuned_decision_dynamic.c
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: RM approved, Target: v4.1.x

#8228 v4.1.x: oshmem/tools/oshmem_info: fix an issue with fortran keyword when comp…
  oshmem/tools/oshmem_info/param.c
Labels: RM approved, Target: v4.1.x

#8229 Do not pass --enable-debug to internal hwloc
  config/opal_config_hwloc.m4
Labels: code cleanup

#8235 Remove PMIx man page setup
  opal/mca/pmix/pmix3x/pmix/config/pmix.m4
  opal/mca/pmix/pmix3x/pmix/config/pmix_setup_man_pages.m4
  opal/mca/pmix/pmix3x/pmix/src/tools/pmix_info/support.c
Labels: RM approved, bug

#8234 Remove PMIx man page setup
  opal/mca/pmix/pmix3x/pmix/config/pmix.m4
  opal/mca/pmix/pmix3x/pmix/config/pmix_setup_man_pages.m4
  opal/mca/pmix/pmix3x/pmix/src/tools/pmix_info/support.c
Labels: bug

#8227 v4.0.x: oshmem/tools/oshmem_info: fix fortran keyword issue when compiling param.c #8221
  oshmem/tools/oshmem_info/param.c
Labels: NEWS

#8220 Fix preference treatment in coll/base
  ompi/mca/coll/adapt/coll_adapt_module.c
  ompi/mca/coll/base/coll_base_comm_select.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mca/coll/sm/coll_sm_module.c
Labels: Target: master, Target: v4.1.x

#8237 Fix preference treatment in coll/base [v4.1.x]
  ompi/mca/coll/adapt/coll_adapt_module.c
  ompi/mca/coll/base/coll_base_comm_select.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mca/coll/sm/coll_sm_module.c
Labels: RM approved, Target: v4.1.x

#8203 Fix many compiler warnings
  configure.ac
  ompi/dpm/dpm.c
  ompi/errhandler/errhandler.c
  ompi/mca/coll/adapt/coll_adapt_ireduce.c
  ompi/mca/common/monitoring/Makefile.am
  ompi/mca/common/monitoring/monitoring_prof.c
  ompi/mca/common/monitoring/monitoring_prof_f.c
  ompi/mca/osc/rdma/osc_rdma_types.h
  ompi/mca/pml/base/pml_base_select.c
  ompi/mca/topo/treematch/treematch/tm_tree.c
  ompi/tools/mpisync/Makefile.am
  ompi/tools/ompi_info/Makefile.am
  opal/datatype/opal_datatype_pack.h
  opal/mca/base/mca_base_alias.c
  opal/mca/memory/patcher/memory_patcher_component.c
  oshmem/tools/oshmem_info/Makefile.am
Labels: Target: master, Target: v5.0.x

#8239 configury: fix OPAL_GET_VERSION
  config/opal_get_version.m4
Labels: Target: master, bug, enhancement

#8242 v4.0.x: autogen.pl: patch libtool.m4 for OSX Big Sur
  autogen.pl
Labels: NEWS, Target: v4.0.x, enhancement

#8238 OSC RDMA: put memory for each process into separate pages [4.1.x]
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: RM approved, Target: v4.1.x

#8240 v4.1.x: configury reproducibility fixes
  config/opal_get_version.m4
  ompi/tools/mpisync/Makefile.am
  orte/tools/orte-info/Makefile.am
Labels: RM approved, Target: v4.1.x, bug

#8241 v4.1.x: autogen.pl: patch libtool.m4 for OSX Big Sur
  autogen.pl
Labels: RM approved, Target: v4.1.x, enhancement

#8247 VERSION: 4.1.0rc4
  NEWS
  VERSION
Labels: RM approved, Target: v4.1.x, documentation

#8250 coll/han: fix coll preference selection in mca_coll_han_comm_create_new
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: master

#8251 v4.1.x: coll/han: fix coll preference selection in mca_coll_han_comm_create_new
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: RM approved, Target: v4.1.x

#8243 VERSION: update for the 4.0.6 release
  VERSION
Labels: Target: v4.0.x

#8255 v4.1.x: Fix missed compiler warnings
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  opal/mca/if/bsdx_ipv6/if_bsdx_ipv6.c
  opal/mca/if/if.h
  opal/mca/if/linux_ipv6/if_linux_ipv6.c
  opal/mca/memory/patcher/configure.m4
  opal/util/if.c
  opal/util/net.c
Labels: RM approved, Target: v4.1.x, code cleanup

#8256 v4.1.x: Fix the verbose output in ess base
  orte/mca/ess/base/ess_base_fns.c
Labels: RM approved, code cleanup
