Repository open-mpi/ompi, pull requests merged in 2020-12, with the labels that each got.

#8254 Replace usage of the deprecated NB API of UCX with NBX
  config/ompi_check_ucx.m4
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: RM approved, Target: v4.1.x

#8265 v4.1.x: Fixed uninitialized memory access bug in base64 encoding
  opal/mca/pmix/base/pmix_base_fns.c
Labels: RM approved, Target: v4.1.x, bug

#8275 [v4.1.x] ompi : add memory barrier in PMIx registration callback
  ompi/errhandler/errhandler.c
  ompi/interlib/interlib.c
Labels: RM approved, Target: v4.1.x

#8273 v4.1.x: Update PMIx to v3.2.2
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/configure.ac
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
Labels: RM approved, Target: v4.1.x, code cleanup

#8277 VERSION: 4.1.0rc5
  NEWS
  VERSION
Labels: Target: v4.1.x

#8280 do not include automatically generated file into the dist tarball
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpiext/shortfloat/c/Makefile.am
  ompi/mpiext/shortfloat/mpif-h/Makefile.am
  ompi/mpiext/shortfloat/use-mpi-f08/Makefile.am
Labels: Target: master

#8276 [v4.0.x] ompi : add memory barrier in PMIx registration callback
  ompi/errhandler/errhandler.c
  ompi/interlib/interlib.c
Labels: Target: v4.0.x

#8258 v4.0.x: Bring fixes back from v4.1.x branch
  ompi/datatype/ompi_datatype.h
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/common/monitoring/Makefile.am
  ompi/mca/common/monitoring/monitoring_prof.c
  ompi/mca/common/monitoring/monitoring_prof_f.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  ompi/mca/osc/rdma/osc_rdma_types.h
  ompi/tools/mpisync/Makefile.am
  ompi/tools/ompi_info/Makefile.am
  opal/class/opal_object.h
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype_pack.h
  opal/mca/btl/usnic/btl_usnic_cagent.c
  opal/mca/if/bsdx_ipv6/if_bsdx_ipv6.c
  opal/mca/if/if.h
  opal/mca/if/linux_ipv6/if_linux_ipv6.c
  opal/mca/memory/patcher/configure.m4
  opal/mca/memory/patcher/memory_patcher_component.c
  opal/mca/patcher/base/patcher_base_patch.c
  opal/mca/pmix/pmix3x/pmix3x.c
  opal/util/if.c
  opal/util/net.c
  opal/util/os_path.c
  opal/util/os_path.h
  opal/util/show_help.c
  opal/util/show_help.h
  orte/mca/ess/base/ess_base_fns.c
  orte/mca/schizo/slurm/schizo_slurm.c
  orte/tools/orte-info/Makefile.am
  orte/util/show_help.c
  orte/util/show_help.h
  oshmem/tools/oshmem_info/Makefile.am
Labels: Target: v4.0.x, bug, code cleanup

#8272 v4.0.x: Update PMIx to v3.2.2
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/configure.ac
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
Labels: Target: v4.0.x, code cleanup

#8281 NEWS: update that we are moving to 3.2.2
  NEWS
Labels: Target: v4.0.x

#8286 libevent: disable checks
  config/opal_config_libevent.m4
Labels: Target: master

#8289 v4.1.x: Update Slurm launch support
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: RM approved, bug

#8293 Topic/lustre perf fix
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/fbtl/posix/fbtl_posix.h
  ompi/mca/fbtl/posix/fbtl_posix_component.c
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_component.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/io/ompio/io_ompio_component.c
Labels: enhancement

#8297 ompio: resync v4.1 branch to master
  NEWS
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_buffer.c
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/fbtl/posix/fbtl_posix.h
  ompi/mca/fbtl/posix/fbtl_posix_component.c
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_component.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_read_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/fs/lustre/fs_lustre.h
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/pvfs2/fs_pvfs2.h
  ompi/mca/fs/ufs/fs_ufs.h
  ompi/mca/fs/ufs/fs_ufs_file_open.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/io/ompio/io_ompio_file_read.c
  ompi/mca/io/ompio/io_ompio_file_set_view.c
  ompi/mca/io/ompio/io_ompio_file_write.c
  ompi/mca/io/ompio/io_ompio_module.c
Labels: RM approved, Target: v4.1.x, enhancement

#8302 VERSION: Onward to v4.1.1
  VERSION
Labels: Target: v4.1.x

#8244 common/ofi: fixing error message to be a debug output
  opal/mca/common/ofi/common_ofi.c
Labels: Target: master, bug

#8288 v4.0.x: Update Slurm launch support
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: NEWS, bug
