Repository open-mpi/ompi, pull requests merged in 2020-02, with the labels that each got.

#7210 Fix Fortran st_size fields of mpi_fortran_argv_null_, mpi_fortran_weights_empty_, mpi_fortran_unweighted_, mpi_fortran_errcodes_ignore_, and mpi_fortran_argvs_null_
  ompi/mpi/fortran/base/gen-mpi-mangling.pl
Labels: bug

#7345 PR 7268 follow-up
  config/opal_setup_wrappers.m4
Labels: Target: master, bug

#7355 v4.0.x: Make C and Fortran types for MPI sentinels agree in size
  ompi/mpi/fortran/base/gen-mpi-mangling.pl
Labels: NEWS, Target: v4.0.x

#7265 Fortran fixes
  config/ompi_config_files.m4
  ompi/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/base/buffer_detach.c
  ompi/mpi/fortran/use-mpi-f08/bindings/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpiext/pcollreq/use-mpi-f08/Makefile.am
Labels: Target: master, Target: v4.0.x, bug

#7360 v4.0.x: Fortran fixes
  config/ompi_config_files.m4
  ompi/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/base/buffer_detach.c
  ompi/mpi/fortran/use-mpi-f08/base/constants.c
  ompi/mpi/fortran/use-mpi-f08/bindings/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpiext/pcollreq/use-mpi-f08/Makefile.am
Labels: NEWS, Target: v4.0.x, bug

#7383 rcache/grdma: fix potential deadlock
  opal/mca/rcache/grdma/rcache_grdma_module.c
Labels: Target: master, bug

#7356 Topic/pr7201 to v40x
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: NEWS

#7392 v4.0.x: Fix pgcc18 support.
  config/opal_check_vendor.m4
Labels: NEWS, Target: v4.0.x

#7371 v3.0.x: Fix PGI compiler error.
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: RM approved, Target: v3.0.x

#7390 v3.0.x: Fix pgcc18 support.
  config/opal_check_vendor.m4
Labels: RM approved, Target: v3.0.x

#7372 v3.1.x: Fix PGI compiler error.
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: RM approved, Target: v3.1.x

#7391 v3.1.x: Fix pgcc18 support.
  config/opal_check_vendor.m4
Labels: RM approved, Target: v3.1.x

#7411 VERSION: 3.0.6rc3
  VERSION
Labels: Target: v3.0.x

#7412 VERSION: 3.1.6rc3
  VERSION
Labels: Target: v3.1.x

#7404 opal_setup_cli.m4: do not escape $
  config/opal_setup_cli.m4
Labels: Target: master, Target: v4.0.x

#7416 opal/mca: check if the user home directory is NULL
  opal/mca/base/mca_base_var.c
Labels: Severity: critical, Target: master, bug

#7421 osc/rdma: fix bug in attach for non-debug builds
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
Labels: Target: master, bug

#7425 opal/atomic: clean out s390(x)
  config/opal_config_asm.m4
  opal/include/opal/sys/architecture.h
  opal/include/opal/sys/cma.h
Labels: Target: master, code cleanup

#7426 opal/asm: remove MIPS
  config/opal_config_asm.m4
  opal/include/opal/sys/architecture.h
  opal/include/opal/sys/atomic.h
  opal/include/opal/sys/cma.h
Labels: Target: master, code cleanup

#7446 Remove "compress" OPAL framework
  opal/mca/compress/Makefile.am
  opal/mca/compress/base/Makefile.am
  opal/mca/compress/base/base.h
  opal/mca/compress/base/compress_base_fns.c
  opal/mca/compress/base/compress_base_frame.c
  opal/mca/compress/base/compress_base_select.c
  opal/mca/compress/base/owner.txt
  opal/mca/compress/bzip/.opal_ignore
  opal/mca/compress/bzip/Makefile.am
  opal/mca/compress/bzip/compress_bzip.h
  opal/mca/compress/bzip/compress_bzip_component.c
  opal/mca/compress/bzip/compress_bzip_module.c
  opal/mca/compress/bzip/owner.txt
  opal/mca/compress/compress.h
  opal/mca/compress/fwd/.opal_ignore
  opal/mca/compress/fwd/Makefile.am
  opal/mca/compress/fwd/owner.txt
  opal/mca/compress/fwd/regx_fwd.c
  opal/mca/compress/fwd/regx_fwd.h
  opal/mca/compress/fwd/regx_fwd_component.c
  opal/mca/compress/gzip/.opal_ignore
  opal/mca/compress/gzip/Makefile.am
  opal/mca/compress/gzip/compress_gzip.h
  opal/mca/compress/gzip/compress_gzip_component.c
  opal/mca/compress/gzip/compress_gzip_module.c
  opal/mca/compress/gzip/owner.txt
  opal/mca/compress/reverse/.opal_ignore
  opal/mca/compress/reverse/Makefile.am
  opal/mca/compress/reverse/owner.txt
  opal/mca/compress/reverse/regx_reverse.c
  opal/mca/compress/reverse/regx_reverse.h
  opal/mca/compress/reverse/regx_reverse_component.c
  opal/mca/compress/zlib/Makefile.am
  opal/mca/compress/zlib/compress_zlib.c
  opal/mca/compress/zlib/compress_zlib.h
  opal/mca/compress/zlib/compress_zlib_component.c
  opal/mca/compress/zlib/configure.m4
  opal/mca/compress/zlib/owner.txt
  opal/runtime/opal_init.c
Labels: code cleanup

#7438 Correctly set baseptr in contiguous shared memory window with local size zero (v4.0.x)
  ompi/mca/osc/sm/osc_sm_component.c
Labels: NEWS, Target: v4.0.x

#7427 README: update tested systems
  README
Labels: Target: master, documentation

#7444 Fix incorrect argument in manual page.
  ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
Labels: documentation

#7470 btl/sm: remove the deprecation-notice shell
  opal/mca/btl/sm/Makefile.am
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/configure.m4
  opal/mca/btl/sm/help-mpi-btl-sm.txt
  opal/mca/btl/sm/owner.txt
Labels: Target: master, Target: v5.0.x

#7462 sharedfp/individual: defer error when not being able to open datafile
  ompi/mca/sharedfp/individual/sharedfp_individual_file_open.c
  ompi/mca/sharedfp/individual/sharedfp_individual_write.c
Labels: NEWS, bug

#7463 Updating OMPI v4.0.x to PMIx v3.1.5 released
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/config/pmix_check_vendor.m4
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/src/client/pmix_client_get.c
  opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.c
  opal/mca/pmix/pmix3x/pmix/src/include/pmix_globals.h
  opal/mca/pmix/pmix3x/pmix/src/tool/pmix_tool.c
Labels: Target: v4.0.x

#7478 v4.0.x: osc/sm: fix typo and minor correction
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: v4.0.x, bug

#7479 opal: Fix opal_initialized reference counter
  opal/runtime/opal_init.c
Labels: Target: master, bug

#7467 v4.0.x: Fix incorrect argument in manual page.
  ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
Labels: Target: v4.0.x

#7465 Disabled Mellanox Open MPI per-commit CI (as redundant) - v4.0.x
  .ci/README.md
  .ci/mellanox/azure-pipelines.yml
Labels: Target: v4.0.x

#7484 man: fix typos and descriptions.
  ompi/mpi/man/man3/MPI_Comm_accept.3in
  ompi/mpi/man/man3/MPI_Dist_graph_create.3in
  ompi/mpi/man/man3/MPI_Dist_graph_create_adjacent.3in
  ompi/mpi/man/man3/MPI_File_get_position_shared.3in
  ompi/mpi/man/man3/MPI_Request_free.3in
  ompi/mpi/man/man3/MPI_Scan.3in
  ompi/mpi/man/man3/MPI_Scatterv.3in
  ompi/mpi/man/man3/MPI_Type_create_indexed_block.3in
  ompi/mpi/man/man3/MPI_Win_attach.3in
  ompi/mpi/man/man3/MPI_Win_get_info.3in
Labels: Target: master, documentation

#7228 Harmonize return values of progress callbacks
  ompi/communicator/comm_request.c
  ompi/mca/coll/libnbc/coll_libnbc_component.c
  ompi/mca/mtl/psm2/mtl_psm2.c
  ompi/mca/osc/pt2pt/osc_pt2pt_component.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/request/grequest.c
  ompi/request/grequestx.c
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: master, enhancement

#7490 Re-add debugger flag configury
  config/ompi_setup_debugger_flags.m4
  configure.ac
Labels: Target: master, bug

#7491 Tweak the C++ binding deprecation check
  config/ompi_deleted_options.m4
  ompi/mca/pml/base/pml_base_frame.c
Labels: code cleanup

#7492 Fix singleton operation
  ompi/runtime/ompi_rte.c
Labels: bug
