Repository open-mpi/ompi, pull requests merged in 2020-01, with the labels that each got.

#7238 mtl/ofi: ignore case when comparing provider names
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: master, bug

#7269 mtl/ofi: ignore case when comparing provider names
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v4.0.x

#7168 v4.0.x: schizo/ompi: correctly handle the yield_when_idle option
  ompi/runtime/ompi_mpi_params.c
  orte/mca/schizo/ompi/schizo_ompi.c
Labels: NEWS, Target: v4.0.x, bug

#7271 Fix typo and update URLs (https, redirection) [skip ci]
  ompi/mpi/man/man3/MPI.3in
  ompi/tools/ompi_info/ompi_info.1in
  opal/mca/crs/opal_crs.7in
  opal/mca/pmix/pmix4x/openpmix/src/tools/wrapper/pmix_wrapper.1in
  opal/tools/wrappers/opal_wrapper.1in
  oshmem/tools/oshmem_info/oshmem_info.1in
Labels: documentation

#7245 v3.0.x: neighbor alltoall fix
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/basic/coll_basic_neighbor_allgather.c
  ompi/mca/coll/basic/coll_basic_neighbor_allgatherv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoall.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c
Labels: RM approved, Target: v3.0.x, bug

#7230 v3.0.x: portals4: fix flow control bugs
  ompi/mca/mtl/portals4/mtl_portals4.c
  opal/mca/btl/portals4/configure.m4
Labels: RM approved, Target: v3.0.x, bug

#7244 v3.1.x: neighbor alltoall fix
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/basic/coll_basic_neighbor_allgather.c
  ompi/mca/coll/basic/coll_basic_neighbor_allgatherv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoall.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallv.c
  ompi/mca/coll/basic/coll_basic_neighbor_alltoallw.c
Labels: RM approved, Target: v3.1.x, bug

#7231 v3.1.x: portals4: fix flow control bugs
  ompi/mca/mtl/portals4/mtl_portals4.c
  opal/mca/btl/portals4/configure.m4
Labels: Target: v3.1.x, bug

#7181 uGNI: Fix potential deadlock when processing outstanding transfers (v3.1.x)
  opal/mca/btl/ugni/btl_ugni_component.c
Labels: RM approved, Target: v3.1.x

#6972 v3.1.x: UCX osc: properly release exclusive lock to avoid lockup
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
Labels: RM approved, Target: v3.1.x, bug

#7258 MTL/OFI: Fix segfault when ompi_mtl_ofi_add_procs fails
  ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
Labels: RM approved, Target: v3.0.x, bug

#7259 MTL/OFI: Fix segfault when ompi_mtl_ofi_add_procs fails
  ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
Labels: RM approved, Target: v3.1.x, bug

#7149 Prevent overflow when dealing with datatype count.
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_add.c
  opal/datatype/opal_datatype_copy.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_fake_stack.c
  opal/datatype/opal_datatype_get_count.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_position.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
Labels: Severity: blocker, Target: master, bug

#7264 openmpi.spec: update modulefile_path behavior
  contrib/dist/linux/openmpi.spec
Labels: Target: master, Target: v4.0.x

#7178 v3.0.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs
  opal/mca/btl/openib/mca-btl-openib-device-params.ini
  opal/mca/common/verbs/common_verbs_port.c
Labels: NEWS, RM approved, Target: v3.0.x

#7179 v3.1.x: OPAL/MCA/BTL/OPENIB: Detect ConnectX-6 HCAs
  opal/mca/btl/openib/mca-btl-openib-device-params.ini
  opal/mca/common/verbs/common_verbs_port.c
Labels: NEWS, RM approved, Target: v3.1.x

#7281 v3.0.x: openmpi.spec: update modulefile_path behavior
  contrib/dist/linux/openmpi.spec
Labels: Target: v3.0.x, enhancement

#7280 v3.1.x: openmpi.spec: update modulefile_path behavior
  contrib/dist/linux/openmpi.spec
Labels: Target: v3.1.x, enhancement

#7279 v4.0.x: openmpi.spec: update modulefile_path behavior
  contrib/dist/linux/openmpi.spec
Labels: NEWS, Target: v4.0.x, enhancement

#7282 v4.0.x: Large count DDT fixes
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_add.c
  opal/datatype/opal_datatype_copy.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_fake_stack.c
  opal/datatype/opal_datatype_get_count.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_position.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
Labels: NEWS, Target: v4.0.x, bug

#7287 cray ftn: modify fortran module loc checker
  config/ompi_fortran_find_module_include_flag.m4
Labels: Target: v4.0.x

#7294 lustre: squash some compiler warnings
  ompi/mca/fs/lustre/fs_lustre.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: Target: v4.0.x

#7289 v3.0.x: Add the missing code to check a return code
  opal/mca/shmem/mmap/shmem_mmap_component.c
Labels: RM approved, Target: v3.0.x

#7288 v4.0.x: Add the missing code to check a return code
  opal/mca/shmem/mmap/shmem_mmap_component.c
Labels: Target: v4.0.x

#7290 v3.1.x: Add the missing code to check a return code
  opal/mca/shmem/mmap/shmem_mmap_component.c
Labels: RM approved, Target: v3.1.x

#7189 dims_create: fix calculation of factors for odd squares
  ompi/mpi/c/dims_create.c
Labels: Target: master

#7174 mtl/ofi: increase the FI_VERSION requested to 1.5 and make sure to check for OFI_LOCAL_COMM
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/configure.m4
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/usnic/configure.m4
Labels: Target: master, bug

#7291 Topic/v4.0.x/from pr7190 7192
  opal/class/opal_list.c
  opal/util/argv.h
  opal/util/cmd_line.c
  opal/util/opal_environ.h
  opal/util/path.c
Labels: Target: v4.0.x

#7248 MTL/OFI: Check threshold number of peers allowed per rank
  ompi/mca/mtl/ofi/mtl_ofi.c
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_endpoint.h
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v4.0.x, bug, fix for v4.0.2

#7296 dims_create: fix calculation of factors for odd squares (v4.0.x)
  ompi/mpi/c/dims_create.c
Labels: NEWS, Target: v4.0.x, bug

#7283 Fix issues in both vader and opal interval tree t that were causing issue 6524
  opal/class/opal_interval_tree.c
  opal/mca/btl/vader/btl_vader_xpmem.c
Labels: Target: master, bug

#7276 Backport a fix for checking locking support in PMIx
  opal/mca/pmix/pmix2x/pmix/config/pmix.m4
  opal/mca/pmix/pmix2x/pmix/config/pmix_check_lock.m4
  opal/mca/pmix/pmix2x/pmix/config/pmix_config_pthreads.m4
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/configure.m4
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
  opal/mca/pmix/pmix2x/pmix/src/mca/gds/ds21/configure.m4
Labels: Target: v3.1.x, bug

#7304 btl/vader: modify how the max attachment address is determined
  opal/mca/btl/vader/btl_vader.h
  opal/mca/btl/vader/btl_vader_component.c
  opal/mca/btl/vader/btl_vader_endpoint.h
  opal/mca/btl/vader/btl_vader_module.c
  opal/mca/btl/vader/btl_vader_xpmem.c
  opal/mca/btl/vader/btl_vader_xpmem.h
Labels: Target: master, bug

#7305 Prep for v3.0.6
  NEWS
  README
  VERSION
Labels: Target: v3.0.x, documentation

#7306 Prep for v3.1.6
  NEWS
  README
  VERSION
Labels: Target: v3.1.x, documentation

#7326 opal: ensure opal_gethostname() always returns a value
  opal/runtime/opal.h
  opal/runtime/opal_init.c
Labels: Target: master

#7273 oshmem/ucx: Fix progress in iput/iget: periodically poke progress to prevent hardware stalls when using DCT transport.
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: bug

#7274 oshmem/ucx: multi-threaded spml ucx performance improvements
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: enhancement

#7328 fs/ime: fix compilation errors due to missing header inclusion
  ompi/mca/fs/ime/fs_ime_file_close.c
  ompi/mca/fs/ime/fs_ime_file_delete.c
  ompi/mca/fs/ime/fs_ime_file_get_size.c
  ompi/mca/fs/ime/fs_ime_file_set_size.c
  ompi/mca/fs/ime/fs_ime_file_sync.c
Labels: Target: master, bug

#7337 plm/rsh: Fix segv on missing agent.
  orte/mca/errmgr/base/errmgr_base_fns.c
  orte/mca/plm/rsh/plm_rsh_component.c
Labels: Target: master, Target: v4.0.x, bug

#6970 coll/cuda: remove unnecessary references to ORTE
  ompi/mca/coll/cuda/coll_cuda_module.c
Labels: Target: master, bug

#7340 plm/rsh: Fix segv on missing agent.
  orte/mca/errmgr/base/errmgr_base_fns.c
  orte/mca/plm/rsh/plm_rsh_component.c
Labels: NEWS, Target: v4.0.x, bug

#7315 Handle error cases in TCP BTL (v2)
  ompi/mca/pml/ob1/pml_ob1.c
  opal/mca/btl/tcp/btl_tcp.c
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/tcp/btl_tcp_frag.c
  opal/mca/btl/tcp/btl_tcp_hdr.h
Labels: Target: master, enhancement

#7134 btl tcp: Use reachability and graph solving for global interface matching
  opal/mca/btl/tcp/btl_tcp.c
  opal/mca/btl/tcp/btl_tcp.h
  opal/mca/btl/tcp/btl_tcp_addr.h
  opal/mca/btl/tcp/btl_tcp_component.c
  opal/mca/btl/tcp/btl_tcp_proc.c
  opal/mca/btl/tcp/btl_tcp_proc.h
Labels: Target: master, bug

#7167 Reachable documentation change
  opal/mca/reachable/netlink/reachable_netlink_module.c
  opal/mca/reachable/reachable.h
Labels: Target: master, documentation

#7318 ompio: fix abstraction violation in 3.1.x series
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_aggregators.h
  ompi/mca/common/ompio/common_ompio_callbacks.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_print_queue.h
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/fbtl/posix/fbtl_posix.h
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/individual/Makefile.am
  ompi/mca/fcoll/static/Makefile.am
  ompi/mca/fcoll/two_phase/Makefile.am
  ompi/mca/io/ompio/Makefile.am
  ompi/mca/io/ompio/io_ompio.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/io/ompio/io_ompio_file_open.c
  ompi/mca/io/ompio/io_ompio_file_read.c
  ompi/mca/io/ompio/io_ompio_file_write.c
  ompi/mca/sharedfp/individual/Makefile.am
  ompi/mca/sharedfp/lockedfile/Makefile.am
  ompi/mca/sharedfp/sm/Makefile.am
Labels: RM approved, Target: v3.1.x, bug

#6783 Prevent EPIPE on OSX.
  opal/mca/btl/tcp/btl_tcp.h
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  orte/mca/odls/base/odls_base_default_fns.c
Labels: Target: master, enhancement

#7336 ompio: fix abstraction violation in 3.0.x series
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_aggregators.h
  ompi/mca/common/ompio/common_ompio_callbacks.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_print_queue.h
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/fbtl/posix/fbtl_posix.h
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/individual/Makefile.am
  ompi/mca/fcoll/static/Makefile.am
  ompi/mca/fcoll/two_phase/Makefile.am
  ompi/mca/io/ompio/Makefile.am
  ompi/mca/io/ompio/io_ompio.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/io/ompio/io_ompio_file_open.c
  ompi/mca/io/ompio/io_ompio_file_read.c
  ompi/mca/io/ompio/io_ompio_file_write.c
  ompi/mca/sharedfp/individual/Makefile.am
  ompi/mca/sharedfp/lockedfile/Makefile.am
  ompi/mca/sharedfp/sm/Makefile.am
Labels: RM approved, Target: v3.0.x, bug

#7207 Remove unused opal_shmem_seg_hdr_t to retain alignment
  opal/mca/shmem/mmap/shmem_mmap_module.c
  opal/mca/shmem/posix/shmem_posix_module.c
  opal/mca/shmem/shmem_types.h
  opal/mca/shmem/sysv/shmem_sysv_module.c
Labels: code cleanup

#7267 v3.1.x: Fix incorrect behavior with length == 0
  ompi/datatype/ompi_datatype_create_contiguous.c
  ompi/datatype/ompi_datatype_create_darray.c
  ompi/datatype/ompi_datatype_create_indexed.c
  ompi/datatype/ompi_datatype_create_struct.c
  ompi/datatype/ompi_datatype_create_vector.c
Labels: RM approved, Target: v3.1.x, bug

#7343 Prepare for 3.1.6rc2
  NEWS
  VERSION
Labels: Target: v3.1.x

#7344 Prepare for 3.0.6rc2
  NEWS
  VERSION
Labels: Target: v3.0.x
