Repository open-mpi/ompi, pull requests merged in 2020-07, with the labels that each got.

#7904 Fix initialization warning reported by clang-10
  opal/util/proc.c
Labels: Target: master

#7905 Fix shifting signed integer
  opal/util/arch.c
  opal/util/net.c
Labels: Target: master

#7907 Fix null pointer arithmetic resulting in potential undefined behavior
  opal/class/opal_free_list.c
Labels: Target: master

#7895 v4.1.x: portals4: fix inappropriate use of abort() in mtl-portals4 and coll-portals4 components
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/mtl/portals4/mtl_portals4_component.c
Labels: RM approved, Target: v4.1.x, bug

#7881 v4.1.x: Accept UCX 1.8 in configure of btl/uct
  opal/mca/btl/uct/configure.m4
Labels: RM approved, Target: v4.1.x

#7890 v4.1.x: mtl-portals4: use the active PML to call add_procs()
  ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
Labels: RM approved, Target: v4.1.x, bug

#7802 mtl/ofi: break from progress loop when events are read
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: master

#7896 v4.1.x: Increment the vpid after assignment
  orte/mca/rmaps/base/rmaps_base_ranking.c
Labels: RM approved, Target: v4.1.x, bug

#7891 v4.0.x: mtl-portals4: use the active PML to call add_procs()
  ompi/mca/mtl/portals4/mtl_portals4_endpoint.h
Labels: Target: v4.0.x, bug

#7911 Prep for v4.1.0rc1 release
  NEWS
  VERSION
Labels: Target: v4.1.x

#7910 Trivial helper script to git clean submodules
  contrib/git-clean.sh
Labels: enhancement

#7916 config: add support for setting the wrapper C compiler
  config/opal_setup_cc.m4
  config/opal_setup_wrappers.m4
  configure.ac
Labels: enhancement

#7906 common/ofi: added address format check to fix provider selection
  opal/mca/common/ofi/common_ofi.c
Labels: Target: master, bug

#7921 mpi_f08: fix Fortran-8-byte-INTEGER vs. C-4-byte-int issue
  config/ompi_setup_mpi_fortran.m4
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
Labels: NEWS, bug, 😳 Backward compat break

#7913 btl: change argument type of BTL receive callbacks
  ompi/mca/pml/ob1/pml_ob1.h
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.h
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
  opal/mca/btl/btl.h
  opal/mca/btl/ofi/btl_ofi_frag.c
  opal/mca/btl/portals4/btl_portals4_component.c
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/btl_sm_fbox.h
  opal/mca/btl/tcp/btl_tcp.h
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/btl/ugni/btl_ugni.h
  opal/mca/btl/ugni/btl_ugni_get.c
  opal/mca/btl/ugni/btl_ugni_smsg.c
  opal/mca/btl/usnic/btl_usnic_frag.h
  opal/mca/btl/usnic/btl_usnic_recv.c
  opal/mca/btl/usnic/btl_usnic_recv.h
Labels: Target: master, enhancement

#7419 Add support for AVX
  config/opal_config_asm.m4
  ompi/mca/op/avx/Makefile.am
  ompi/mca/op/avx/configure.m4
  ompi/mca/op/avx/op_avx.h
  ompi/mca/op/avx/op_avx_component.c
  ompi/mca/op/avx/op_avx_functions.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/base/op_base_op_select.c
  ompi/mca/op/op.h
  test/datatype/Makefile.am
  test/datatype/check_op.sh
  test/datatype/reduce_local.c
Labels: Target: master, performance

#7893 UCX: initialize cuda from ucx pml component
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
Labels: ⚠️ WIP-DNM!

#7923 v4.1.x: fortran.m4: disallow when sizeof(int) != sizeof(INTEGER)
  config/ompi_setup_mpi_fortran.m4
Labels: NEWS, RM approved, Target: v4.1.x, bug

#7924 mpi/c: fix param checks in [I]Neighbor_alltoall{v,w}
  ompi/mpi/c/ineighbor_alltoallv.c
  ompi/mpi/c/ineighbor_alltoallw.c
  ompi/mpi/c/neighbor_alltoallv.c
  ompi/mpi/c/neighbor_alltoallw.c
Labels: Target: v4.1.x

#7922 v4.0.x: fortran.m4: disallow when sizeof(int) != sizeof(INTEGER)
  config/ompi_setup_mpi_fortran.m4
Labels: NEWS, Target: v4.0.x, bug

#7511 v4.0.x: schizo/slurm: Fix binding detection
  orte/mca/schizo/slurm/schizo_slurm.c
Labels: NEWS, Target: v4.0.x, bug

#7935 v4.1.x: Add supports for MPI_OP using AVX512, AVX2 and MMX
  config/opal_config_asm.m4
  ompi/mca/op/avx/Makefile.am
  ompi/mca/op/avx/configure.m4
  ompi/mca/op/avx/op_avx.h
  ompi/mca/op/avx/op_avx_component.c
  ompi/mca/op/avx/op_avx_functions.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/base/op_base_op_select.c
  ompi/mca/op/op.h
  test/datatype/Makefile.am
  test/datatype/check_op.sh
  test/datatype/reduce_local.c
Labels: NEWS, RM approved, Target: v4.1.x, enhancement

#7933 v4.1.x: schizo/slurm: Fix binding detection
  orte/mca/schizo/slurm/schizo_slurm.c
Labels: NEWS, RM approved, Target: v4.1.x, bug

#7934 v4.1.x: schizo/jsm: Disable binding when direct launched
  orte/mca/schizo/jsm/schizo_jsm.c
Labels: Target: v4.1.x, bug

#7938 NEWS: update for 4.0.5rc1
  NEWS
Labels: Target: v4.0.x

#7946 Adding SLURM binding policy change to README
  README
Labels: RM approved, Target: v4.1.x

#7947 Adding SLURM binding policy change to README
  README
Labels: Target: v4.0.x

#7931 Fix the BTL API conversion for the SMCUDA BTL
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/mca/common/cuda/common_cuda.c
Labels: Target: master

#7948 osc/rdma: fail query_btls if no endpoint for non-local peer is found
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master

#7951 (v4.1.x) osc/rdma: fail query_btls if no endpoint for non-local peer is found
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: RM approved, Target: v4.1.x

#7898 v4.0.x: UCX: initialize cuda from ucx pml component
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
Labels: Target: v4.0.x

#7943 v4.1.x: common/ofi: added address format check to fix provider selection
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v4.1.x

#7840 MPI-4: Initial error handler
  ompi/communicator/comm_init.c
  ompi/dpm/dpm.c
  ompi/errhandler/errcode.c
  ompi/errhandler/errcode.h
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
  ompi/info/info.c
  ompi/mpi/c/error_class.c
  ompi/mpi/c/error_string.c
  ompi/runtime/ompi_mpi_init.c
  ompi/runtime/ompi_rte.c
  opal/util/proc.c
  opal/util/proc.h
  test/simple/Makefile
  test/simple/initial_errh.c
Labels: MPI-4.0, Target: v5.0.x, enhancement

#7953 Fix memory leak in configure, which prevents leak sanitizer usage
  config/c_get_alignment.m4
Labels: Target: master, Target: v4.1.x

#7860 Coll/Hcoll: reduce_scatter(block) interface
  ompi/mca/coll/hcoll/coll_hcoll.h
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: Target: master, enhancement

#7960 v4.0.x: Fix memory leak in configure, which prevents leak sanitizer usage
  config/c_get_alignment.m4
Labels: Target: v4.0.x, bug

#7950 (v4.0.x) osc/rdma: fail query_btls if no endpoint for non-local peer is found
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: v4.0.x

#7936 Master: new thread-specific-data (tsd) api
  ompi/runtime/ompi_rte.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
  opal/mca/hwloc/base/hwloc_base_frame.c
  opal/mca/threads/argobots/threads_argobots_module.c
  opal/mca/threads/argobots/threads_argobots_tsd.h
  opal/mca/threads/base/Makefile.am
  opal/mca/threads/base/tsd.c
  opal/mca/threads/pthreads/threads_pthreads_module.c
  opal/mca/threads/pthreads/threads_pthreads_tsd.h
  opal/mca/threads/qthreads/threads_qthreads_module.c
  opal/mca/threads/qthreads/threads_qthreads_tsd.h
  opal/mca/threads/tsd.h
  opal/runtime/opal_init.c
  opal/util/net.c
Labels: Target: master

#7956 v4.1.x: BTL/OFI: Fix missing include file.
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: RM approved, Target: v4.1.x, bug

#7902 V4.1.x hcoll reduce scatter
  ompi/mca/coll/hcoll/coll_hcoll.h
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: RM approved, Target: v4.1.x

#7957 Use the unaligned SSE memory access primitive.
  ompi/mca/op/avx/op_avx_functions.c
  test/datatype/reduce_local.c
Labels: RM approved, Severity: blocker, Target: v4.1.x, Target: v5.0.x

#7969 RDMA osc: perform CAS in shared memory if possible (v4.0.x)
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: NEWS, Target: v4.0.x

#7959 v4.1: Fix memory leak in configure, which prevents leak sanitizer usage
  config/c_get_alignment.m4
Labels: RM approved, Target: v4.1.x, bug

#7730 coll/tuned: Change the default collective algorithm selection
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: Target: master, Target: v5.0.x

#7681 ompi/osc/ucx: remove global TLS tables
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx.h
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
  opal/mca/common/ucx/common_ucx_wpool_int.h
Labels: Target: master
