Repository open-mpi/ompi, pull requests merged in 2020-08, with the labels that each got.

#7952 coll/tuned: Change the default collective algorithm selection
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: RM approved, Target: v4.1.x

#7984 Missing function to populate java errors_abort handler
  ompi/mpi/java/java/Errhandler.java
Labels: Severity: blocker, Target: master, bug

#7897 Minor fix in cmd line parser help
  opal/util/cmd_line.c
  opal/util/cmd_line.h
Labels: Target: master

#7974 bug fix: des->tag = hdr->frag, should be hdr->tag
  opal/mca/btl/sm/btl_sm_component.c
Labels: Target: master, bug

#7991 v4.1.x: btl/ofi: Use common provider include/exclude list
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: RM approved, Target: v4.1.x

#7997 Use the unaligned SSE memory access primitive.
  ompi/mca/op/avx/op_avx_functions.c
  test/datatype/reduce_local.c
Labels: RM approved, Severity: blocker, Target: v4.1.x

#7973 btl/ofi: Disable EFA provider in versions earlier than libfabric 1.12.0
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: ⚠️ WIP-DNM!

#8006 Fix the cacheline usage in the CUDA BTL.
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: RM approved, Severity: blocker, Target: v4.1.x

#7998 V4.1.x btl/ofi backport disabling EFA and ofi_rxm providers
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: RM approved, Target: master, bug

#8009 v4.0.x: Fix the cacheline usage in the CUDA BTL.
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: v4.0.x

#8014 ofi mtl: fix problem with mrecv
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: RM approved, Target: v4.1.x, bug

#8019 coll/tuned: Revert RSB and RS default algorithms
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: bug

#8021 coll/tuned: Revert RSB and RS default algorithms
  ompi/mca/coll/tuned/coll_tuned_decision_fixed.c
Labels: Target: v4.1.x, bug

#8026 suppress icc long double message
  config/opal_setup_cc.m4
  config/opal_setup_cxx.m4
Labels: Target: v4.0.x

#8023 errors_are_fatal_comm_handler takes a pointer to the error constant
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/mca/pml/ob1/pml_ob1_sendreq.h
Labels: Target: master, bug

#8028 Fix MPI versions in MPI.3 manpage
  ompi/mpi/man/man5/Open-MPI.5.md
Labels: documentation

#8027 OFI: patch OFI MTL for GNI provider
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: RM approved, Target: v4.1.x, bug

#8031 btl: remove unused descriptor flags
  opal/mca/btl/btl.h
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/btl/template/btl_template.c
  opal/mca/btl/template/btl_template.h
  opal/mca/btl/uct/btl_uct_module.c
Labels: Target: master, code cleanup
