Repository open-mpi/ompi, pull requests merged in 2021-07, with the labels that each got.

#6389 configury: misc fixes
  config/ompi_check_ime.m4
  config/ompi_check_lustre.m4
  config/ompi_check_pvfs2.m4
  config/opal_check_package.m4
  ompi/mca/fs/ime/fs_ime.h
  ompi/mca/fs/ime/fs_ime_component.c
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: master, ⚠️ WIP-DNM!

#8904 Improvements to MPI_Test and friends
  ompi/request/req_test.c
  opal/runtime/opal_progress.c
  opal/runtime/opal_progress.h
Labels: Target: master

#9107 v5.0.x: oshmem: Reduce the service memory footprint
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/memheap/base/base.h
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/base/memheap_base_register.c
  oshmem/mca/spml/base/base.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v5.0.x

#9071 v5.0.x: fix hugepage allocator assert in finalize
  opal/mca/mpool/hugepage/mpool_hugepage_module.c
Labels: Severity: critical, Target: v5.0.x, bug

#8793 Wrapper compiler cleanups
  config/opal_config_files.m4
  config/opal_setup_wrappers.m4
  opal/tools/wrappers/Makefile.am
Labels: Target: master, bug

#6378 Fix inherited_linker_flags processing when building with NAG compiler
  autogen.pl
  config/ltmain_nag_pthread.diff
Labels: NEWS, Target: master

#9088 v4.0.x: Long live MPI_LONG and MPI_UNSIGNED_LONG
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_external.c
  ompi/datatype/ompi_datatype_internal.h
  ompi/datatype/ompi_datatype_module.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/op.h
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/op/op.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_copy_functions.c
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_module.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_unpack.c
  opal/util/arch.h
Labels: Target: v4.0.x

#9093 v4.1.x: Long live MPI_LONG and MPI_UNSIGNED_LONG
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_external.c
  ompi/datatype/ompi_datatype_internal.h
  ompi/datatype/ompi_datatype_module.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/op.h
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/op/op.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_copy_functions.c
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_module.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_unpack.c
  opal/util/arch.h
Labels: RM approved, Target: v4.1.x

#9125 v4.1.x: VERSION: make safe for C++ compilers
  VERSION
Labels: NEWS, RM approved, Target: v4.1.x, bug

#9121 v5.0.x: configury misc fixes
  config/ompi_check_ime.m4
  config/ompi_check_lustre.m4
  config/ompi_check_pvfs2.m4
  config/opal_check_package.m4
  ompi/mca/fs/ime/fs_ime.h
  ompi/mca/fs/ime/fs_ime_component.c
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: v5.0.x, bug, enhancement

#9081 v5.0.x: Coverity/v50x/ulfm
  ompi/communicator/ft/comm_ft_detector.c
  ompi/communicator/ft/comm_ft_reliable_bcast.c
  ompi/dpm/dpm.c
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/mca/coll/ftagree/coll_ftagree_earlyterminating.c
  opal/mca/base/mca_base_var.c
Labels: Target: v5.0.x, bug, code cleanup

#9126 v4.0.x: VERSION: make safe for C++ compilers
  VERSION
Labels: NEWS, Target: v4.0.x, bug

#9114 configury: skip SLURM provided PMIx detection when appropriate
  config/opal_check_pmi.m4
  configure.ac
Labels: NEWS, Target: v4.1.x, bug

#9134 dist: Sync NEWS from release branches
  NEWS
Labels: Target: master

#9118 v4.1.x: iof/base: (try to) set the winsize to the pty of the spawned tasks
  orte/mca/iof/base/iof_base_setup.c
Labels: NEWS, RM approved, Target: v4.1.x, enhancement

#9141 v4.1.x: dist: Sync NEWS from other release branches
  NEWS
Labels: Target: v4.1.x

#9144 romio314: do not link with CUDA
  ompi/mca/io/romio341/configure.m4
Labels: Target: master, bug

#9127 configury: skip SLURM provided PMIx detection when appropriate
  config/opal_check_pmi.m4
  configure.ac
Labels: NEWS, Target: v4.0.x, bug

#9147 test: Update Makefile.am files to not define distclean target
  test/asm/Makefile.am
  test/class/Makefile.am
  test/datatype/Makefile.am
  test/event/Makefile.am
  test/memchecker/Makefile.am
  test/monitoring/Makefile.am
  test/mpi/environment/Makefile.am
  test/mpool/Makefile.am
  test/runtime/Makefile.am
  test/spc/Makefile.am
  test/support/Makefile.am
  test/threads/Makefile.am
  test/util/Makefile.am
Labels: Target: master

#9145 romio314: do not link with CUDA
  ompi/mca/io/romio341/configure.m4
Labels: Target: v5.0.x

#9135 v5.0.x: Wrapper compiler cleanups
  config/opal_config_files.m4
  config/opal_setup_wrappers.m4
  opal/tools/wrappers/Makefile.am
Labels: Target: v5.0.x

#9143 v5.0.x: Always include the stddef.h header.
  configure.ac
Labels: Severity: blocker, Target: v5.0.x

#9142 v5.0.x: build: remove unused configuration from mpisync
  ompi/tools/mpisync/Makefile.am
Labels: Target: v5.0.x

#9139 v5.0.x: dist: Sync NEWS from release branches
  NEWS
Labels: Target: v5.0.x

#9150 ofi-common: fixes to some mca param reg bugs
  opal/mca/common/ofi/common_ofi.c
Labels: Target: master

#9156 v4.1.x: Add a mfence to opal_atomic_mb() for x86.
  opal/include/opal/sys/x86_64/atomic.h
Labels: NEWS, RM approved, Target: v4.1.x

#9149 v4.0.x: PML/UCX/DATATYPE: fixed memory leak - v4.0
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: Target: v4.0.x

#9119 iof/base: (try to) set the winsize to the pty of the spawned tasks
  orte/mca/iof/base/iof_base_setup.c
Labels: NEWS, Target: v4.0.x, enhancement

#9164 Fix ob1 when configured --without-ft
  ompi/mca/pml/ob1/pml_ob1.c
Labels: Target: v5.0.x

#9151 ofi-common: fixes to some mca param reg bugs
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#9153 v5.0.x: Add a mfence to opal_atomic_mb() for x86.
  opal/include/opal/sys/x86_64/atomic.h
Labels: Target: v5.0.x

#9165 v5.0:Fix ob1 when configured --without-ft
  ompi/mca/pml/ob1/pml_ob1.c
Labels: Target: v5.0.x

#9128 Correct some operations modifying status.MPI_ERROR when it is disallowed
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/portals4/mtl_portals4_probe.c
  ompi/mca/pml/cm/pml_cm.h
  ompi/mca/pml/ob1/pml_ob1_iprobe.c
  ompi/mca/pml/ob1/pml_ob1_irecv.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.h
  ompi/mpi/c/improbe.c
  ompi/mpi/c/iprobe.c
  ompi/mpi/c/mprobe.c
  ompi/mpi/c/mrecv.c
  ompi/mpi/c/probe.c
  ompi/mpi/c/recv.c
  ompi/mpi/c/request_get_status.c
  ompi/mpi/c/sendrecv.c
  ompi/mpi/c/testany.c
  ompi/mpi/c/wait.c
  ompi/mpi/c/waitany.c
  ompi/request/req_test.c
  ompi/request/req_wait.c
  ompi/request/request.h
Labels: Target: master, bug

#9176 v4.1.x: pmix3x: fix slurping of PMIx compiler/linker flags
  opal/mca/pmix/pmix3x/configure.m4
Labels: RM approved, Target: v4.1.x, bug

#9155 v4.0.x: Add a mfence to opal_atomic_mb() for x86.
  opal/include/opal/sys/x86_64/atomic.h
Labels: NEWS, Target: v4.0.x

#9177 v4.0.x: pmix3x: fix slurping of PMIx compiler/linker flags
  opal/mca/pmix/pmix3x/configure.m4
Labels: Target: v4.0.x, bug

#9173 v5.0.x: oshmem: Remove dead codes during oshmem communicator creation
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/scoll/basic/scoll_basic_alltoall.c
  oshmem/mca/scoll/basic/scoll_basic_barrier.c
  oshmem/mca/scoll/basic/scoll_basic_broadcast.c
  oshmem/mca/scoll/basic/scoll_basic_collect.c
  oshmem/mca/scoll/basic/scoll_basic_reduce.c
  oshmem/mca/scoll/mpi/scoll_mpi_module.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/proc/proc.c
  oshmem/proc/proc.h
  oshmem/runtime/oshmem_shmem_finalize.c
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/shmem/c/shmem_broadcast.c
  oshmem/shmem/c/shmem_ptr.c
  oshmem/shmem/fortran/shmem_broadcast_f.c
Labels: Target: v5.0.x

#9179 v5.0.x: tools/mpirun: include errno.h explicitly
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x

#9172 Fix AVX detection with icc.
  ompi/mca/op/avx/configure.m4
Labels: Severity: critical, bug

#9174 v5.0.x: pml/ucx: fix datatype refcount
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
Labels: Target: v5.0.x

#9185 pmix event handlers - add default and an LC one
  ompi/runtime/ompi_mpi_init.c
Labels: Target: master, Target: v5.0.x

#9188 Pr/file close incomplete handle fix v5.0
  ompi/mca/common/ompio/common_ompio_file_open.c
Labels: bug

#9180 Fix AVX detection with icc.
  ompi/mca/op/avx/configure.m4
Labels: NEWS, Target: v5.0.x

#9175 v4.1.x: pml/ucx: fix datatype refcount
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
Labels: Target: v4.1.x
