Repository open-mpi/ompi, pull requests merged in 2021-05, with the labels that each got.

#8901 lustre_file_open: Fix memory leak
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: memory leak

#8892 orted-mpir: add version to shared library
  orte/orted/orted-mpir/Makefile.am
Labels: RM approved, Target: v4.1.x

#8911 v5.0.x: Fix opal_progress.h copyright header.
  opal/runtime/opal_progress.h
Labels: Target: v5.0.x

#8903 io/ompio: fix get_byte_offset for 0-size fview
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: bug

#8920 pml/cm: fix a problem introduced with cuda support
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: Target: v5.0.x

#8891 v5.0.x: datatype fixes port
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_external.c
  ompi/datatype/ompi_datatype_internal.h
  ompi/datatype/ompi_datatype_module.c
  ompi/mca/op/base/op_base_functions.c
  ompi/mca/op/op.h
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
  ompi/op/op.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_copy_functions.c
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_module.c
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  opal/util/arch.h
  test/datatype/Makefile.am
  test/datatype/external32.c
  test/datatype/partial.c
  test/datatype/unpack_ooo.c
Labels: Target: v5.0.x

#8902 V5.0.x update
  .ci/lanl/gitlab-darwin-ci.yml
  README.md
  config/opal_config_asm.m4
  config/opal_config_libevent.m4
  config/opal_mca.m4
  ompi/dpm/dpm.c
  ompi/mca/osc/rdma/osc_rdma_frag.h
  ompi/mca/osc/rdma/osc_rdma_types.h
  ompi/mca/osc/sm/osc_sm.h
  ompi/mca/osc/sm/osc_sm_active_target.c
  ompi/mpi/man/man3/MPI_Alloc_mem.3in
  ompi/mpi/man/man3/MPI_Win_allocate.3in
  ompi/mpi/man/man3/MPI_Win_allocate_shared.3in
  ompi/mpi/man/man3/MPI_Win_create.3in
  ompi/mpi/man/man3/MPI_Win_create_dynamic.3in
  ompi/mpi/man/man3/MPI_Win_fence.3in
  ompi/mpi/man/man3/MPI_Win_free.3in
  ompi/mpi/man/man3/MPI_Win_lock.3in
  ompi/mpi/man/man3/MPI_Win_lock_all.3in
  ompi/mpi/man/man3/MPI_Win_post.3in
  ompi/mpi/man/man3/MPI_Win_shared_query.3in
  ompi/mpi/man/man3/MPI_Win_start.3in
  opal/include/opal/sys/Makefile.am
  opal/include/opal/sys/arm/Makefile.am
  opal/include/opal/sys/arm/atomic.h
  opal/include/opal/sys/arm/timer.h
  opal/include/opal/sys/arm/update.sh
  opal/include/opal/sys/arm64/atomic.h
  opal/include/opal/sys/arm64/timer.h
  opal/include/opal/sys/atomic.h
  opal/include/opal/sys/atomic_impl.h
  opal/include/opal/sys/atomic_stdc.h
  opal/include/opal/sys/gcc_builtin/atomic.h
  opal/include/opal/sys/ia32/Makefile.am
  opal/include/opal/sys/ia32/atomic.h
  opal/include/opal/sys/ia32/timer.h
  opal/include/opal/sys/ia32/update.sh
  opal/include/opal/sys/powerpc/atomic.h
  opal/include/opal/sys/timer.h
  opal/include/opal/sys/x86_64/atomic.h
  opal/include/opal/sys/x86_64/timer.h
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/ugni/btl_ugni_init.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/threads/pthreads/configure.m4
  opal/mca/threads/thread_usage.h
  test/asm/atomic_cmpset.c
  test/asm/atomic_math.c
  test/simple/add_host.c
Labels: Target: v5.0.x

#8912 v4.0.x: orted-mpir: do not install convenience library
  orte/orted/orted-mpir/Makefile.am
Labels: Target: v4.0.x

#8934 v5.0.x: coll/base: Fix the error handling in couple of collectives.
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/base/coll_base_barrier.c
  ompi/mca/coll/base/coll_base_bcast.c
  ompi/mca/coll/base/coll_base_gather.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/coll/base/coll_base_scatter.c
Labels: Target: v5.0.x

#8921 mtl/psm2: provide option to disable psm2 REFCNT check
  config/ompi_check_psm2.m4
  ompi/mca/mtl/psm2/mtl_psm2_component.c
Labels: RM approved, Target: v4.1.x

#8833 tests: fix make check on macOS
  test/threads/opal_atomic_thread_bench.c
Labels: Target: master, bug

#8948 v4.1.x: CI: Fix a bug in the cherry pick checker
  .github/workflows/git-commit-checks.py
Labels: RM approved, Target: v4.1.x

#8950 v3.1.x: CI: Fix a bug in the cherry pick checker
  .github/workflows/git-commit-checks.py
Labels: RM approved, Target: v3.1.x

#8935 v4.1.x: coll/base: Fix the error handling in couple of collectives.
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/base/coll_base_barrier.c
  ompi/mca/coll/base/coll_base_bcast.c
  ompi/mca/coll/base/coll_base_gather.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/coll/base/coll_base_scatter.c
Labels: RM approved, Target: v4.1.x

#8949 v4.0.x: CI: Fix a bug in the cherry pick checker.
  .github/workflows/git-commit-checks.py
Labels: Target: v4.0.x

#8936 v4.1.x: use sync_send mask for ofi_create_recv_tag
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: RM approved, Target: v4.1.x, bug

#8908 fix MPI_Sendrecv_replace
  ompi/mpi/c/sendrecv_replace.c
Labels: Target: master, bug

#8896 v5.0.x: Fix handling of large data in MPI_Sendrecv_replace
  ompi/mpi/c/sendrecv_replace.c
Labels: Target: v5.0.x, bug

#8922 v4.0.x: osc/ucx: Detach dynamic window memory when freeing a window
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v4.0.x

#8954 OSC/UCX: Use existing mem_recs when unpacking the rkey
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: master, bug

#8942 io/ompio: fix get_byte_offset for 0-size fview
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: RM approved, Target: v4.1.x, bug

#8852 v4.1.x: PML/UCX/DATATYPE: fixed memory leak - v4.1
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: RM approved, Target: v4.1.x

#8966 v4.1.x: btl tcp: Add workaround for "dropped connection" issue
  opal/mca/btl/tcp/btl_tcp_component.c
Labels: RM approved, Target: v4.1.x, bug

#8897 v4.1.x: Fix handling of large data in MPI_Sendrecv_replace
  ompi/mpi/c/sendrecv_replace.c
Labels: RM approved, Target: v4.1.x, bug

#8898 v4.0.x: Fix handling of large data in MPI_Sendrecv_replace
  ompi/mpi/c/sendrecv_replace.c
Labels: Target: v4.0.x, bug

#8957 v4.0.x: use sync_send mask for ofi_create_recv_tag
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v4.0.x, bug

#8915 Topic/swat issue 8860
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ucx/common_ucx.c
Labels: Target: master

#8968 ompi/mca/coll/tuned: Fix typo
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
Labels: Target: master, bug

#4737 oshmem: add pkg-config files
  config/oshmem_config_files.m4
  oshmem/tools/wrappers/Makefile.am
  oshmem/tools/wrappers/oshmem-c.pc.in
  oshmem/tools/wrappers/oshmem-cxx.pc.in
  oshmem/tools/wrappers/oshmem-fort.pc.in
  oshmem/tools/wrappers/oshmem.pc.in
Labels: Target: master, Target: v5.0.x, enhancement

#8978 ompi/mca/coll/tuned: Fix typo
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
Labels: Target: v5.0.x

#8979 ompi/mca/coll/tuned: Fix typo
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
Labels: Target: v4.0.x

#8980 v5.0.x: git-commit-checks.json: force cherry picks
  .github/workflows/git-commit-checks.json
Labels: Target: v5.0.x

#8965 OSC/UCX: Use existing mem_recs when unpacking the rkey [5.0.x]
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#8972 osc/ucx: Detach dynamic window memory when freeing a window
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v5.0.x

#8975 Topic/swat issue 8860 v5.0.x
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ucx/common_ucx.c
Labels: Target: v5.0.x

#8987 Correct PMIX_MAPBY flag to :DISPLAY in MPI_SPAWN and friends
  ompi/dpm/dpm.c
Labels: Severity: critical, Target: master, Target: v5.0.x, bug

#8988 ompi/runtime: initialize common symbol ompi_pmix_connect_timeout
  ompi/runtime/ompi_mpi_params.c
Labels: Target: master

#8843 OMPI/COLL: coll ucc component
  config/ompi_check_ucc.m4
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/ucc/Makefile.am
  ompi/mca/coll/ucc/coll_ucc.h
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_barrier.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_common.h
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_debug.h
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/configure.m4
Labels: Target: master

#8859 v4.0.x: Fix "partial" datatype issue
  config/opal_check_cuda.m4
  configure.ac
  opal/datatype/opal_convertor.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  test/datatype/Makefile.am
  test/datatype/external32.c
  test/datatype/partial.c
  test/datatype/unpack_ooo.c
Labels: Target: v4.0.x

#8974 configury: fix some problems with opal_mca
  config/opal_mca.m4
Labels: Target: master

#8977 ompi/mca/coll/tuned: Fix typo
  ompi/mca/coll/tuned/coll_tuned_allgather_decision.c
  ompi/mca/coll/tuned/coll_tuned_allgatherv_decision.c
Labels: Target: v4.1.x

#8994 v5.0.x: Add support for FI_CONTEXT2 in OFI MTL and BTL
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_request.h
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: v5.0.x

#8995 v4.1.x: Add support for FI_CONTEXT2 in OFI MTL and BTL.
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_request.h
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: RM approved, Target: v4.1.x

#8900 v4.1.x: lustre_file_open: Fix memory leak
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: RM approved, Target: v4.1.x, memory leak

#8971 v4.1.x: osc/ucx: Detach dynamic window memory when freeing a window
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: RM approved, Target: v4.1.x

#9001 configury: fix some problems with opal_mca
  config/opal_mca.m4
Labels: Target: v5.0.x

#8969 v5.0.x: coll ucc component
  config/ompi_check_ucc.m4
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/ucc/Makefile.am
  ompi/mca/coll/ucc/coll_ucc.h
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_barrier.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_common.h
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_debug.h
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/configure.m4
Labels: Target: v5.0.x

#9002 v5.0.x: Correct PMIX_MAPBY flag to :DISPLAY in MPI_SPAWN and friends
  ompi/dpm/dpm.c
Labels: Target: v5.0.x, bug
