Repository open-mpi/ompi, pull requests merged in 2021-12, with the labels that each got.

#9709 v5.0.x: Remove smartmatch warnings from autogen.pl
  autogen.pl
Labels: Target: v5.0.x

#9718 v5.0.x: Select all adapters with IPV4 addresses within specified subnet ranges.
  opal/mca/btl/tcp/btl_tcp_component.c
Labels: Target: v5.0.x

#9702 v5.0.x: Compiler and ident cleanup
  config/opal_check_ident.m4
  configure.ac
  ompi/dpm/dpm.c
  ompi/errhandler/errhandler_predefined.c
  ompi/include/ompi/constants.h
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/osc/base/base.h
  ompi/mca/osc/base/osc_base_frame.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/sm/osc_sm_component.c
  ompi/mpi/fortran/mpif-h/init_f.c
  ompi/mpiext/affinity/c/mpiext_affinity_c.h
  ompi/mpiext/affinity/c/mpiext_affinity_str.c
  ompi/runtime/ompi_mpi_init.c
  ompi/tools/ompi_info/param.c
  opal/mca/hwloc/base/base.h
  opal/mca/hwloc/base/help-opal-hwloc-base.txt
  opal/mca/hwloc/base/hwloc_base_frame.c
  opal/mca/hwloc/base/hwloc_base_maffinity.c
  opal/mca/hwloc/base/hwloc_base_proc_mempolicy.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/hwloc/hwloc-internal.h
  opal/mca/mpool/base/mpool_base_alloc.c
  opal/runtime/opal_init.c
  opal/util/cmd_line.c
  opal/util/os_path.c
  oshmem/runtime/oshmem_shmem_init.c
Labels: Target: v5.0.x

#9724 v5.0.x: Wrapper compiler static library improvements
  config/opal_check_pc.m4
  config/opal_config_hwloc.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
  config/opal_configure_options.m4
  config/opal_functions.m4
  config/opal_mca.m4
  config/opal_setup_wrappers.m4
  ompi/tools/wrappers/mpic++-wrapper-data.txt.in
  ompi/tools/wrappers/mpicc-wrapper-data.txt.in
  ompi/tools/wrappers/mpifort-wrapper-data.txt.in
  ompi/tools/wrappers/ompi-c.pc.in
  ompi/tools/wrappers/ompi-cxx.pc.in
  ompi/tools/wrappers/ompi-fort.pc.in
Labels: Target: v5.0.x

#9730 Topic/spml ucx fixed compilation coverity warnings
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/memheap/base/base.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: Target: v5.0.x

#9723 v5.0.x: coll/libnbc: correctly handle MPI_BOTTOM
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: Target: v5.0.x

#9753 nbc_ialltoallv: fix uninitialized variable
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: bug, Target: master

#9737 v5.0.x: Fix --without-ft build
  ompi/mpi/c/sendrecv.c
Labels: Target: v5.0.x

#9734 v5.0.x: btl/ofi: handle case where fi_read doesn't need a local descriptor.
  opal/mca/btl/ofi/btl_ofi_rdma.c
Labels: Target: v5.0.x

#9746 v5.0.x: build: Avoid accidental calls to AC_PROG_CC
  config/opal_configure_options.m4
  config/opal_mca.m4
  config/opal_setup_cc.m4
  config/opal_setup_wrappers.m4
  config/oshmem_configure_options.m4
  configure.ac
Labels: Target: v5.0.x

#9744 v5.0.x: Change print full path of argv[0] to basename at opal_wrapper.
  opal/tools/wrappers/opal_wrapper.c
Labels: Target: v5.0.x

#9741 v5.0.x: SPML/UCX: fixed build over older versions of UCX
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: v5.0.x

#9740 v5.0.x: PMIx_Connect usage: add optional timeout
  ompi/dpm/dpm.c
  ompi/runtime/ompi_mpi_params.c
  ompi/runtime/params.h
Labels: Target: v5.0.x

#9757 v5.0.x: nbc_ialltoallv: fix uninitialized variable
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: bug, Target: v5.0.x

#9742 v5.0.x: Update LICENSE
  LICENSE
Labels: Target: v5.0.x

#9739 v5.0.x: OFI MTL: Fix component selection debug output
  .mailmap
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v5.0.x

#9736 v5.0.x: configure: fix --enable-mca-direct
  config/opal_mca.m4
  opal/util/minmax.h
Labels: Target: v5.0.x

#9754 v5.0.x: Fix opal_show_help call in bucket allocator
  opal/mca/allocator/bucket/allocator_bucket_alloc.c
Labels: Target: v5.0.x

#9745 v5.0.x: Changes to env var name and behavior to reflect the OpenSHMEM spec
  oshmem/include/shmem.h.in
  oshmem/info/info.c
  oshmem/shmem/shmem_api_logger.h
Labels: Target: v5.0.x

#9727 v5.0.x: Remove .travis.yml as it's no longer used with CI.
  .travis.yml
Labels: Target: v5.0.x

#9735 v5.0.x: CUDA: Enhance MPIX_Query_cuda_support() with runtime support check
  ompi/mpiext/cuda/c/MPIX_Query_cuda_support.3in
  ompi/mpiext/cuda/c/mpiext_cuda.c
  opal/mca/common/cuda/common_cuda.c
  opal/runtime/opal_params.c
  opal/runtime/opal_params.h
Labels: Target: v5.0.x

#9731 v5.0.x: Add opal_recursive_mutex_t support to qthreads
  opal/mca/threads/argobots/Makefile.am
  opal/mca/threads/argobots/configure.m4
  opal/mca/threads/argobots/threads_argobots_mutex.h
  opal/mca/threads/argobots/threads_argobots_wait_sync.c
  opal/mca/threads/argobots/threads_argobots_wait_sync.h
  opal/mca/threads/base/Makefile.am
  opal/mca/threads/base/mutex.c
  opal/mca/threads/base/wait_sync.c
  opal/mca/threads/mutex.h
  opal/mca/threads/pthreads/Makefile.am
  opal/mca/threads/pthreads/configure.m4
  opal/mca/threads/pthreads/threads_pthreads_mutex.c
  opal/mca/threads/pthreads/threads_pthreads_mutex.h
  opal/mca/threads/pthreads/threads_pthreads_wait_sync.c
  opal/mca/threads/pthreads/threads_pthreads_wait_sync.h
  opal/mca/threads/qthreads/Makefile.am
  opal/mca/threads/qthreads/configure.m4
  opal/mca/threads/qthreads/threads_qthreads_mutex.c
  opal/mca/threads/qthreads/threads_qthreads_mutex.h
  opal/mca/threads/qthreads/threads_qthreads_wait_sync.h
  opal/mca/threads/wait_sync.h
Labels: Target: v5.0.x

#9714 Update NEWS with 4.1.2 items
  NEWS
Labels: documentation, Target: master

#9567 Drop unknown/ignored info keys on communicators, files, and windows
  ompi/communicator/comm.c
  ompi/file/file.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/osc/base/base.h
  ompi/mca/osc/base/osc_base_init.c
  ompi/win/win.c
  opal/util/info.c
  opal/util/info.h
Labels: Target: master, MPI-4.0

#9765 v5.0.x: Improvements to MPI_Test and friends
  ompi/request/req_test.c
  opal/runtime/opal_progress.c
  opal/runtime/opal_progress.h
Labels: Target: v5.0.x

#9768 v5.0.x: common_ofi.c: fix uninit variable warning
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#9770 Drop unknown/ignored info keys on communicators, files, and windows [v5.0.x]
  ompi/communicator/comm.c
  ompi/file/file.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/osc/base/base.h
  ompi/mca/osc/base/osc_base_init.c
  ompi/win/win.c
  opal/util/info.c
  opal/util/info.h
Labels: Target: v5.0.x, MPI-4.0

#9766 v5.0.x: btl/uct: add support for UCX 1.10.x
  opal/mca/btl/uct/btl_uct_endpoint.c
  opal/mca/btl/uct/btl_uct_frag.c
  opal/mca/btl/uct/btl_uct_rdma.c
  opal/mca/btl/uct/btl_uct_rdma.h
Labels: Target: v5.0.x

#9771 Fix broken internal pmix configure
  config/opal_config_pmix.m4
  config/opal_setup_wrappers.m4
Labels: bug, Target: master

#9756 v4.1.x: Select all adapters with IPV4 addresses within specified subnet ranges.
  opal/mca/btl/tcp/btl_tcp_component.c
  orte/mca/oob/tcp/oob_tcp_component.c
Labels: RM approved, Target: v4.1.x

#9794 sharedfp: fix minor memory leaks
  ompi/mca/sharedfp/sm/sharedfp_sm.c
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: bug, Target: master
