Repository open-mpi/ompi, pull requests merged in 2021-04, with the labels that each got.

#8737 configury: fix --disable-io-romio option
  ompi/mca/io/romio321/configure.m4
Labels: Target: v5.0.x

#8745 Fix .la files leaking into wrapper compilers
  config/opal_mca.m4
  config/opal_setup_wrappers.m4
Labels: Target: master, bug

#8751 ofi: fix typo in macro name
  opal/mca/common/ofi/common_ofi.c
Labels: RM approved, Severity: blocker, Target: v4.1.x

#8768 threads: Fix C++/Fortran pthread tests
  opal/mca/threads/pthreads/configure.m4
Labels: Target: master, Target: v5.0.x, bug

#8775 Hkuno/man pages
  oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_putmem_nbi.3in
Labels: documentation

#8777 spawn with info: do not erroneously free(tmp)
  ompi/dpm/dpm.c
Labels: Severity: blocker, Target: master, bug

#8753 v5.0: build: Fix typo that disabled shared components
  config/opal_mca.m4
Labels: Target: v5.0.x, bug

#8755 v5.0: Fix .la files leaking into wrapper compilers
  config/opal_mca.m4
  config/opal_setup_wrappers.m4
Labels: Target: v5.0.x, bug

#8781 v5.0.x: spawn with info: do not erroneously free(tmp)
  ompi/dpm/dpm.c
Labels: Severity: blocker, Target: v5.0.x, bug

#8784 v4.1.x: man pages updates
  oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_putmem_nbi.3in
Labels: RM approved, Target: v4.1.x, documentation

#8785 v5.0.x: man pages updates
  oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_putmem_nbi.3in
Labels: Target: v5.0.x, documentation

#8783 v4.0.x: man pages updates
  oshmem/shmem/man/man3/shmem_int_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_long_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_longlong_xor_to_all.3in
  oshmem/shmem/man/man3/shmem_putmem_nbi.3in
Labels: Target: v4.0.x, documentation

#8789 atomic/gcc_builtin: only apply the workaround when required.
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: Target: master, performance

#8791 v5.0: threads: Fix C++/Fortran pthread tests
  opal/mca/threads/pthreads/configure.m4
Labels: Target: v5.0.x, bug

#8792 libevent: Link against libevent_core, not libevent
  config/opal_config_libevent.m4
Labels: bug

#8794 atomic/gcc_builtin: only apply the workaround when required.
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: Target: v5.0.x, performance

#8798 v3.0.x: Bring the git commit checker GitHub action to v3.0.x
  .github/workflows/README.md
  .github/workflows/git-commit-checks.json
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: RM approved, Target: v3.0.x

#8795 v4.1.x: atomic/gcc_builtin: only apply the workaround when required.
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: RM approved, Severity: critical, Target: v4.1.x, performance

#8797 v3.1.x: Bring the git commit checker GitHub action to v3.1.x
  .github/workflows/README.md
  .github/workflows/git-commit-checks.json
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: Target: v3.1.x

#8802 Add the userid to the vader backing file path
  opal/mca/btl/vader/btl_vader_component.c
Labels: NEWS, Target: v4.0.x

#8804 Add the userid to the vader backing file path
  opal/mca/btl/vader/btl_vader_component.c
Labels: RM approved, Target: v4.1.x, bug

#8808 Add the userid to the sm backing file path
  opal/mca/btl/sm/btl_sm_component.c
Labels: Target: v5.0.x

#8817 v5.0: Fixing .clang-format to allow it to work with v10
  .clang-format
Labels: Target: v5.0.x

#8809 v5.0.x: opal/Makefile.am Remove duplicate symbols for common_cuda
  opal/Makefile.am
Labels: Target: v5.0.x, bug

#8814 OSHMEM/SEGMENT-REGISTRATION: added segment filtering - v5.0
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: Target: v5.0.x

#8821 [v4.1.x] mtl/ofi: Disable CUDA convertor for specified ofi providers
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: RM approved, Target: v4.1.x

#8815 OSHMEM/SEGMENT-REGISTRATION: added segment filtering - V4.1
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: RM approved, Target: v4.1.x

#8796 v4.0.x: atomic/gcc_builtin: only apply the workaround when required.
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: NEWS, Target: v4.0.x, performance

#8836 Topic/v3.1.x/fix pmix detection
  opal/mca/pmix/ext1x/pmix1x_component.c
  opal/mca/pmix/pmix2x/pmix2x_component.c
Labels: RM approved, bug

#8835 Topic/v3.0.x/fix pmix detection
  opal/mca/pmix/ext1x/pmix1x_component.c
  opal/mca/pmix/ext2x/pmix2x_component.c
  opal/mca/pmix/pmix2x/pmix2x_component.c
Labels: RM approved, bug

#8832 pmix/pmix3x: Fix internal PMIx discovery logic.
  opal/mca/pmix/ext1x/pmix1x_component.c
  opal/mca/pmix/ext2x/ext2x_component.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
Labels: RM approved, bug

#8837 Backport/datatype
  config/opal_check_cuda.m4
  configure.ac
  opal/datatype/opal_convertor.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  test/datatype/Makefile.am
  test/datatype/external32.c
  test/datatype/partial.c
  test/datatype/unpack_ooo.c
Labels: Target: v4.1.x

#8834 Topic/v4.0.x/fix pmix detection
  opal/mca/pmix/ext1x/pmix1x_component.c
  opal/mca/pmix/ext2x/ext2x_component.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
Labels: bug

#8847 VERSION: Bump to 4.1.2a1
  VERSION
Labels: RM approved, Target: v4.1.x, documentation

#8849 Minor makefile updates
  config/Makefile.am
  test/datatype/Makefile.am
Labels: Target: master, bug

#8691 MTL/PSM2: fix check for PSM2_LIB_REFCOUNT_CAP
  config/ompi_check_psm2.m4
Labels: Target: v4.1.x

#8851 PML/UCX/DATATYPE: fixed memory leak - v5.0
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: Target: v5.0.x

#8879 configury: do not use _Float16 if noisy build
  config/opal_check_alt_short_float.m4
Labels: Target: v5.0.x

#8874 v5.0.x: git-commit-checks.py: remind people about bot:notacherrypick
  .github/workflows/git-commit-checks.py
Labels: Target: v5.0.x, enhancement

#8866 v5.0.x: Fix typo in the reorder detection.
  ompi/communicator/comm.c
Labels: Target: v5.0.x, bug

#8855 v5.0.x: config/Makefile.am: add missing file to EXTRA_DIST
  config/Makefile.am
Labels: Target: v5.0.x, bug

#8873 v4.1.x: git-commit-checks.py: remind people about bot:notacherrypick
  .github/workflows/git-commit-checks.py
Labels: RM approved, Target: v4.1.x, enhancement

#8885 v5.0.x: clang-tidy braces - and other missing deps
  ompi/mca/coll/base/coll_base_topo.h
  opal/class/opal_bitmap.c
  opal/class/opal_cstring.c
  opal/class/opal_free_list.c
  opal/class/opal_hash_table.c
  opal/class/opal_interval_tree.c
  opal/class/opal_list.c
  opal/class/opal_value_array.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor_raw.c
  opal/datatype/opal_datatype_add.c
  opal/datatype/opal_datatype_copy.c
  opal/datatype/opal_datatype_create.c
  opal/datatype/opal_datatype_destroy.c
  opal/datatype/opal_datatype_dump.c
  opal/datatype/opal_datatype_get_count.c
  opal/datatype/opal_datatype_optimize.c
  opal/datatype/opal_datatype_pack.c
  opal/datatype/opal_datatype_position.c
  opal/datatype/opal_datatype_unpack.c
  opal/mca/allocator/basic/allocator_basic.c
  opal/mca/allocator/bucket/allocator_bucket_alloc.c
  opal/mca/base/mca_base_alias.c
  opal/mca/base/mca_base_open.c
  opal/mca/base/mca_base_var_enum.c
  opal/mca/btl/tcp/btl_tcp.c
  opal/mca/btl/tcp/btl_tcp_component.c
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/tcp/btl_tcp_frag.c
  opal/mca/hwloc/base/hwloc_base_frame.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/installdirs/base/installdirs_base_expand.c
  opal/mca/rcache/grdma/rcache_grdma_module.c
  opal/mca/threads/pthreads/threads_pthreads_wait_sync.c
  opal/memoryhooks/memory.c
  opal/runtime/opal_info_support.c
  opal/tools/wrappers/opal_wrapper.c
  opal/util/arch.c
  opal/util/argv.c
  opal/util/basename.c
  opal/util/crc.c
  opal/util/if.c
  opal/util/net.c
  opal/util/numtostr.c
  opal/util/opal_environ.c
  opal/util/os_path.c
  opal/util/path.c
  opal/util/proc.c
Labels: Target: v5.0.x

#8890 v5.0.x: Add a soft "breakpoint" capability
  ompi/runtime/ompi_rte.c
  ompi/runtime/ompi_rte.h
Labels: Target: v5.0.x

#8880 Be more robust in getting hwloc topology
  opal/mca/hwloc/base/hwloc_base_util.c
Labels: bug

#8875 MPI_Sendrecv_replace: correctly handle large data
  ompi/mpi/c/sendrecv_replace.c
Labels: Target: master, bug

#8895 MPI_Sendrecv_replace: add missing error handling
  ompi/mpi/c/sendrecv_replace.c
Labels: Target: master

#8889 v5.0.x: Restore singleton comm_spawn (yet again)
  ompi/dpm/dpm.c
Labels: Target: v5.0.x

#8894 v5.0.x: fix a bunch of warnings
  3rd-party/treematch/fibo.h
  3rd-party/treematch/tm_topology.c
  3rd-party/treematch/tm_tree.c
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/vprotocol/pessimist/vprotocol_pessimist_wait.c
  opal/mca/base/mca_base_var.c
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/tools/wrappers/opal_wrapper.c
Labels: Target: v5.0.x

#8899 lustre_file_open: Fix memory leak
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: Target: v5.0.x, memory leak

#8864 v4.0.x: Fix typo in the reorder detection.
  ompi/communicator/comm.c
Labels: MPI-4.0, NEWS, bug

#8872 v4.0.x: git-commit-checks.py: remind people about bot:notacherrypick
  .github/workflows/git-commit-checks.py
Labels: Target: v4.0.x, enhancement
