Repository open-mpi/ompi, pull requests merged in 2021-11, with the labels that each got.

#9600 [v5.0.x] mtl/ofi: call fi_setopt to state MPI p2p requirements for CUDA
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v5.0.x

#9607 osc/rdma: Make sure the rank_array is initialized
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: bug, Target: master

#9606 libnbc wrong answer (DI) fix for reduce_scatter
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: bug, Severity: critical

#9581 Add post_config hook for MPI extensions
  config/ompi_ext.m4
  ompi/mpiext/example/configure.m4
Labels: Target: master

#9612 libnbc DI fix for reduce_scatter
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: Target: v4.1.x

#9609 add libopen-orted-mpir when statically linking
  ompi/tools/wrappers/mpic++-wrapper-data.txt.in
  ompi/tools/wrappers/mpicc-wrapper-data.txt.in
  ompi/tools/wrappers/mpifort-wrapper-data.txt.in
Labels: bug, Target: v4.1.x

#9573 ompi/runtime: add instead of set opal_progress_event_flags
  ompi/runtime/ompi_mpi_init.c
Labels: Target: v5.0.x

#9602 OSC-RDMA: PSCW fix
  ompi/mca/osc/rdma/osc_rdma_active_target.c
Labels: Target: v5.0.x

#9578 v5.0.x: ofi: prevent issues with multi-plane fabrics
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#9597 v5.0.x: osc-portals4: fix undefined variable error in minimum alignment info key lookup
  ompi/mca/osc/portals4/osc_portals4_component.c
Labels: bug, Severity: blocker, Target: v5.0.x

#9615 osc/rdma: Make sure the rank_array is initialized [v5.0.x]
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: v5.0.x

#9611 libnbc DI fix for reduce_scatter
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: Target: v5.0.x

#9616 libnbc: Fix int overflow when handling count parameters
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/op/op.h
Labels: bug

#9620 Revert "add libopen-orted-mpir when statically linking"
  ompi/tools/wrappers/mpic++-wrapper-data.txt.in
  ompi/tools/wrappers/mpicc-wrapper-data.txt.in
  ompi/tools/wrappers/mpifort-wrapper-data.txt.in
Labels: Severity: blocker, RM approved, Target: v4.1.x

#9622 v4.1.x: libnbc: Fix int overflow when handling the count parameter
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/op/op.h
Labels: RM approved, Target: v4.1.x

#9623 v4.0.x: libnbc: Fix int overflow when handling the count parameter
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/op/op.h
Labels: Severity: critical, Target: v4.0.x

#9613 libnbc DI fix for reduce_scatter
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: Target: v4.0.x

#9614 NEWS: update for 4.0.7rc2
  NEWS
Labels: Target: v4.0.x

#9628 v5.0.x: tests: Backporting some fixes from master
  test/threads/Makefile.am
  test/threads/opal_atomic_thread_bench.c
  test/threads/opal_condition.c
Labels: Target: v5.0.x

#9608 v5.0.x: fortran MPI_Waitall array_of_requests etc to dimension(*)
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
Labels: Target: v5.0.x

#9639 v5.0: osc/ucx fixes dynamic windows
  .mailmap
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#9621 libnbc: Fix int overflow when handling count parameters
  ompi/mca/coll/libnbc/nbc.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/op/op.h
Labels: Target: v5.0.x

#9631 OSHMEM v1.5 API header
  oshmem/include/oshmem/constants.h
  oshmem/include/pshmem.h
  oshmem/include/pshmemx.h
  oshmem/include/shmem.h.in
  oshmem/include/shmemx.h
  oshmem/mca/atomic/atomic.h
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/Makefile.am
  oshmem/shmem/c/profile/Makefile.am
  oshmem/shmem/c/profile/defines.h
  oshmem/shmem/c/shmem_add.c
  oshmem/shmem/c/shmem_alloc.c
  oshmem/shmem/c/shmem_alltoall.c
  oshmem/shmem/c/shmem_broadcast.c
  oshmem/shmem/c/shmem_collect.c
  oshmem/shmem/c/shmem_cswap.c
  oshmem/shmem/c/shmem_cswap_nb.c
  oshmem/shmem/c/shmem_fadd.c
  oshmem/shmem/c/shmem_fadd_nb.c
  oshmem/shmem/c/shmem_fand.c
  oshmem/shmem/c/shmem_fand_nb.c
  oshmem/shmem/c/shmem_fetch.c
  oshmem/shmem/c/shmem_fetch_nb.c
  oshmem/shmem/c/shmem_finc.c
  oshmem/shmem/c/shmem_finc_nb.c
  oshmem/shmem/c/shmem_for.c
  oshmem/shmem/c/shmem_for_nb.c
  oshmem/shmem/c/shmem_fxor.c
  oshmem/shmem/c/shmem_fxor_nb.c
  oshmem/shmem/c/shmem_inc.c
  oshmem/shmem/c/shmem_p.c
  oshmem/shmem/c/shmem_pcontrol.c
  oshmem/shmem/c/shmem_put_signal.c
  oshmem/shmem/c/shmem_put_signal_nb.c
  oshmem/shmem/c/shmem_reduce.c
  oshmem/shmem/c/shmem_set.c
  oshmem/shmem/c/shmem_swap.c
  oshmem/shmem/c/shmem_swap_nb.c
  oshmem/shmem/c/shmem_sync.c
  oshmem/shmem/c/shmem_team.c
  oshmem/shmem/c/shmem_test_ivars.c
  oshmem/shmem/c/shmem_wait.c
  oshmem/shmem/c/shmem_wait_ivars.c
Labels: Target: master, Target: v5.0.x

#9644 coll/basic: correctly handle zero size datatypes in gatherv/scatterv
  ompi/mca/coll/basic/coll_basic_gatherv.c
  ompi/mca/coll/basic/coll_basic_scatterv.c
Labels: bug

#9536 Add a devel document to guide FT/ULFM upgrade of components
  contrib/doc-ft-components/DEVEL.FT-REQUIREMENTS.md
  contrib/doc-ft-components/general-ulfm-fault-handling.png
Labels: documentation, Target: master

#9642 v5.0.x: Install pmix tools into ompi exports/bin
  config/opal_config_pmix.m4
Labels: Target: v5.0.x

#9635 pml/ucx: pml_ucx_multi_send_nb support
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_datatype.c
  ompi/mca/pml/ucx/pml_ucx_datatype.h
Labels: Target: v5.0.x

#9652 v5.0.x: Fixes send/recv offsets in rbuf for the case of MPI_IN_PLACE
  ompi/mca/coll/base/coll_base_alltoall.c
Labels: Target: v5.0.x

#9653 v5.0.x: coll/basic: Correctly handle zero size datatypes in scatterv/gatherv
  ompi/mca/coll/basic/coll_basic_gatherv.c
  ompi/mca/coll/basic/coll_basic_scatterv.c
Labels: Target: v5.0.x

#9649 Skip running PMIX/PRRTE configure when not needed
  Makefile.am
  config/ompi_setup_prrte.m4
  config/opal_config_3rdparty.m4
  config/opal_config_pmix.m4
  configure.ac
Labels: Target: master

#9632 btl/uct: set reasonable defaults
  opal/mca/btl/uct/btl_uct_component.c
Labels: enhancement, Target: master

#9637 btl/uct: Bump supported version to UCX 1.11.x
  opal/mca/btl/uct/configure.m4
Labels: Target: master

#9546 MPI4: add support for mpi_info_get_string
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/info_get_string.c
  ompi/mpi/c/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/info_get_string_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/info_get_string_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
  ompi/mpi/man/man3/MPI_Info_get_string.3in
  ompi/mpi/man/man3/Makefile.am
Labels: Target: master, MPI-4.0

#9634 pml/ucx: pml_ucx_multi_send_nb support
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
  ompi/mca/pml/ucx/pml_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_datatype.c
  ompi/mca/pml/ucx/pml_ucx_datatype.h
Labels: RM approved, Target: v4.1.x

#9663 V4.1.x: coll/hcoll: fixes fallback on rooted ops
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: bug, RM approved, Target: v4.1.x

#9660 UCT: require at least UCX 1.9.0
  opal/mca/btl/uct/configure.m4
Labels: Target: master

#9661 4.1.x: Stat portability fix
  ompi/mca/io/romio321/romio/adio/common/ad_fstype.c
Labels: bug, RM approved, Target: v4.1.x

#9668 Alltoall{,v,w} IN_PLACE fixes
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/basic/coll_basic_alltoallw.c
Labels: bug, Target: master

#9672 v4.1.x: Backport alltoall in place fixes
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/basic/coll_basic_alltoallw.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_get_count.c
Labels: bug, RM approved, Target: v4.1.x

#9678 v4.1.x: Prep for 4.1.2 release
  NEWS
  VERSION
Labels: documentation, RM approved, Target: v4.1.x

#9641 [v5.0.x] Adding new oshmem APIs for oshmem v1.5
  oshmem/include/oshmem/constants.h
  oshmem/include/pshmem.h
  oshmem/include/pshmemx.h
  oshmem/include/shmem.h.in
  oshmem/include/shmemx.h
  oshmem/mca/atomic/atomic.h
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/Makefile.am
  oshmem/shmem/c/profile/Makefile.am
  oshmem/shmem/c/profile/defines.h
  oshmem/shmem/c/shmem_add.c
  oshmem/shmem/c/shmem_alloc.c
  oshmem/shmem/c/shmem_alltoall.c
  oshmem/shmem/c/shmem_broadcast.c
  oshmem/shmem/c/shmem_collect.c
  oshmem/shmem/c/shmem_cswap.c
  oshmem/shmem/c/shmem_cswap_nb.c
  oshmem/shmem/c/shmem_fadd.c
  oshmem/shmem/c/shmem_fadd_nb.c
  oshmem/shmem/c/shmem_fand.c
  oshmem/shmem/c/shmem_fand_nb.c
  oshmem/shmem/c/shmem_fetch.c
  oshmem/shmem/c/shmem_fetch_nb.c
  oshmem/shmem/c/shmem_finc.c
  oshmem/shmem/c/shmem_finc_nb.c
  oshmem/shmem/c/shmem_for.c
  oshmem/shmem/c/shmem_for_nb.c
  oshmem/shmem/c/shmem_fxor.c
  oshmem/shmem/c/shmem_fxor_nb.c
  oshmem/shmem/c/shmem_inc.c
  oshmem/shmem/c/shmem_p.c
  oshmem/shmem/c/shmem_pcontrol.c
  oshmem/shmem/c/shmem_put_signal.c
  oshmem/shmem/c/shmem_put_signal_nb.c
  oshmem/shmem/c/shmem_reduce.c
  oshmem/shmem/c/shmem_set.c
  oshmem/shmem/c/shmem_swap.c
  oshmem/shmem/c/shmem_swap_nb.c
  oshmem/shmem/c/shmem_sync.c
  oshmem/shmem/c/shmem_team.c
  oshmem/shmem/c/shmem_test_ivars.c
  oshmem/shmem/c/shmem_wait.c
  oshmem/shmem/c/shmem_wait_ivars.c
Labels: Target: v5.0.x

#9674 v5.0.x: Bucket overflow v5
  .mailmap
  opal/mca/allocator/bucket/Makefile.am
  opal/mca/allocator/bucket/allocator_bucket_alloc.c
  opal/mca/allocator/bucket/help-mca-allocator-bucket.txt
Labels: Target: v5.0.x

#9662 V5.0.x: coll/hcoll: fixes fallback on rooted ops
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: Target: v5.0.x

#9666 UCT: require at least UCX 1.9.0 [v5.0.x]
  opal/mca/btl/uct/configure.m4
Labels: Target: v5.0.x

#9671 v5.0.x: Backport alltoall{,v,w} in place fixes
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/basic/coll_basic_alltoallw.c
Labels: bug, Target: v5.0.x

#9676 v5.0.x: ulfm docs
  contrib/doc-ft-components/DEVEL.FT-REQUIREMENTS.md
  contrib/doc-ft-components/general-ulfm-fault-handling.png
Labels: documentation, Target: v5.0.x

#9675 v5.0.x: btl/uct: Set reasonable defaults
  opal/mca/btl/uct/btl_uct_component.c
Labels: Target: v5.0.x

#9677 v5.0.x: Skip running PMIX/PRRTE configure when not needed
  Makefile.am
  config/ompi_setup_prrte.m4
  config/opal_config_3rdparty.m4
  config/opal_config_pmix.m4
  configure.ac
Labels: Target: v5.0.x

#9679 v5.0.x: Add post_config hook for MPI extensions
  config/ompi_ext.m4
  ompi/mpiext/example/configure.m4
Labels: Target: v5.0.x

#9657 Fix misc. compiler warnings.
  ompi/dpm/dpm.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/osc/base/base.h
  ompi/mca/osc/base/osc_base_frame.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/sm/osc_sm_component.c
  ompi/mpi/fortran/mpif-h/init_f.c
  ompi/mpiext/affinity/c/mpiext_affinity_str.c
  ompi/runtime/ompi_mpi_init.c
  opal/mca/hwloc/base/hwloc_base_util.c
  opal/mca/mpool/base/mpool_base_alloc.c
  opal/runtime/opal_init.c
  opal/util/cmd_line.c
Labels: Target: master

#9673 v5.0.x: MPI4: add support for mpi_info_get_string
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/info_get_string.c
  ompi/mpi/c/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/info_get_string_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/info_get_string_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
  ompi/mpi/man/man3/MPI_Info_get_string.3in
  ompi/mpi/man/man3/Makefile.am
Labels: Target: v5.0.x, MPI-4.0

#9688 Wrapper compiler static library improvements
  config/opal_check_pc.m4
  config/opal_config_hwloc.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
  config/opal_configure_options.m4
  config/opal_functions.m4
  config/opal_mca.m4
  config/opal_setup_wrappers.m4
  ompi/tools/wrappers/mpic++-wrapper-data.txt.in
  ompi/tools/wrappers/mpicc-wrapper-data.txt.in
  ompi/tools/wrappers/mpifort-wrapper-data.txt.in
  ompi/tools/wrappers/ompi-c.pc.in
  ompi/tools/wrappers/ompi-cxx.pc.in
  ompi/tools/wrappers/ompi-fort.pc.in
Labels: Target: master

#9684 Update BTL documentation
  opal/mca/btl/btl.h
Labels: documentation

#9691 v4.1: pml/ucx: avoid completion callback for blocking send
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
Labels: bug, RM approved, Target: v4.1.x

#9700 v5.0.x: Fix compile failure with enable-heterogeneous.
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: bug, Target: v5.0.x

#9701 Complete removal of ident code
  config/opal_check_ident.m4
  configure.ac
  ompi/mpi/fortran/mpif-h/init_f.c
  oshmem/runtime/oshmem_shmem_init.c
Labels: bug, Target: master

#9692 v5.0: pml/ucx: avoid completion callback for blocking send
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
Labels: Target: v5.0.x

#9708 btl_base_am_rdma.c: fix typos identified by Coverity
  opal/mca/btl/base/btl_base_am_rdma.c
Labels: bug, Target: master

#9687 Remove smartmatch warnings from autogen.pl
  autogen.pl
Labels: bug

#9651 coll/libnbc: correctly handle MPI_BOTTOM
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: bug, Target: master

#9680 NEWS: fix a name misspelling
  NEWS
Labels: documentation, Target: v4.0.x

#9664 V4.0.x: coll/hcoll: fixes fallback on rooted ops
  ompi/mca/coll/hcoll/coll_hcoll_ops.c
Labels: bug, Target: v4.0.x
