Repository open-mpi/ompi, pull requests merged in 2021-02, with the labels that each got.

#8422 v4.0.x: Make sure MPIR_Breakpoint() is compiled without CFLAGS.
  config/orte_config_files.m4
  orte/Makefile.am
  orte/orted/Makefile.am
  orte/orted/orted-mpir/Makefile.am
  orte/orted/orted-mpir/orted_mpir.h
  orte/orted/orted-mpir/orted_mpir_breakpoint.c
  orte/orted/orted_submit.c
Labels: Target: v4.0.x

#8424 Let Slurm know that our daemons are not MPI tasks
  orte/mca/plm/slurm/plm_slurm_module.c
Labels: Target: v4.0.x, bug

#8394 Add fence_nb to flux pmix
  opal/mca/pmix/flux/pmix_flux.c
Labels: RM approved, Target: v4.1.x

#8412 opal: enable load-linked, store-conditional atomics for AArch64
  opal/class/opal_fifo.h
  opal/class/opal_lifo.h
  opal/include/opal/sys/arm64/Makefile.am
  opal/include/opal/sys/arm64/atomic.h
  opal/include/opal/sys/arm64/atomic_llsc.h
  opal/include/opal/sys/atomic.h
  opal/include/opal/sys/atomic_impl.h
  opal/include/opal/sys/atomic_stdc.h
  test/class/opal_fifo.c
  test/class/opal_lifo.c
Labels: Target: master

#8432 v3.1.x: Make sure MPIR_Breakpoint() is compiled without CFLAGS.
  config/orte_config_files.m4
  orte/Makefile.am
  orte/orted/Makefile.am
  orte/orted/orted-mpir/Makefile.am
  orte/orted/orted-mpir/orted_mpir.h
  orte/orted/orted-mpir/orted_mpir_breakpoint.c
  orte/orted/orted_submit.c
Labels: RM approved, bug

#8406 V4.0.x PML/UCX: don't do pml check during add_proc
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v4.0.x

#8440 op_avx: use MCA enum flags instead of integer values
  ompi/mca/op/avx/op_avx.h
  ompi/mca/op/avx/op_avx_component.c
Labels: enhancement

#8441 v4.1.x: op_avx: use MCA enum flags instead of integer values
  ompi/mca/op/avx/op_avx.h
  ompi/mca/op/avx/op_avx_component.c
Labels: RM approved, Target: v4.1.x

#8007 Improve predefined pack/unpack performance using mpich methods.
  LICENSE
  ompi/datatype/ompi_datatype.h
  ompi/mpi/c/pack.c
  ompi/mpi/c/unpack.c
  opal/datatype/Makefile.am
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_pack_unpack_predefined.h
  opal/datatype/opal_datatype_unpack.h
Labels: Target: master, Target: v5.0.x

#8415 ompi/datatype: Fix predefined datatype initialization/finalization
  ompi/datatype/ompi_datatype_module.c
Labels: Severity: minor, Target: master

#8445 Pr/v4.1.x mpich3.4 tstsuite fixes
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/fbtl/posix/fbtl_posix.c
  ompi/mca/io/ompio/io_ompio_file_set_view.c
Labels: RM approved, Target: v4.1.x, bug

#8449 osc/rdma: ensure bml add_procs has been called for all local procs
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master, bug

#8454 fcoll/two_phase: remove component
  ompi/mca/fcoll/base/fcoll_base_file_select.c
  ompi/mca/fcoll/two_phase/Makefile.am
  ompi/mca/fcoll/two_phase/fcoll_two_phase.h
  ompi/mca/fcoll/two_phase/fcoll_two_phase_component.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_read_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_file_write_all.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_module.c
  ompi/mca/fcoll/two_phase/fcoll_two_phase_support_fns.c
  ompi/mca/fcoll/two_phase/owner.txt
Labels: Target: master

#8459 op_avx: Fix MCA enum flags
  ompi/mca/op/avx/op_avx_component.c
Labels: Target: master, bug

#8460 v4.1.x: op_avx: Fix MCA enum flags
  ompi/mca/op/avx/op_avx_component.c
Labels: RM approved, Target: v4.1.x, bug

#8453 osc/rdma: ensure bml add_procs has been called for all local procs
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: RM approved, Target: v4.1.x, bug

#8456 Fix stale definition for OPAL_HAVE_ATOMIC_LLSC_PTR
  opal/include/opal/sys/atomic_impl.h
Labels: bug

#8447 common/ofi: Use opal_show_help() to call out lack of locality info
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/help-common-ofi.txt
Labels: Target: v4.1.x

#6301 osc/rdma: fix bug in MPI_OP_NO_OP support
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_lock.h
  ompi/mca/osc/rdma/osc_rdma_request.c
  ompi/mca/osc/rdma/osc_rdma_request.h
Labels: Target: master, Target: v5.0.x, bug

#8452 osc/rdma: ensure bml add_procs has been called for all local procs
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: v4.0.x, bug

#8443 Pr/v4.0.x mpich3.4 tstsuite fixes
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/fbtl/posix/fbtl_posix.c
  ompi/mca/io/ompio/io_ompio_file_set_view.c
Labels: Target: v4.0.x, bug

#7899 v4.1.x: UCX: initialize cuda from ucx pml component
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx.h
Labels: RM approved, Target: v4.1.x

#8446 NEWS and VERSION updates for 4.1.1rc1
  NEWS
  VERSION
Labels: Target: v4.1.x

#8470 btl/vader: improve support for dynamic add_procs
  opal/mca/btl/sm/btl_sm.h
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/btl_sm_endpoint.h
  opal/mca/btl/sm/btl_sm_module.c
Labels: Target: master, bug

#8469 osc/rdma: fix amo-based accumulate
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: master, bug

#8477 v4.1.x: Update PMIx to v3.2.3
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/config/pmix.m4
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event.h
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_registration.c
  opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
Labels: RM approved, Target: v4.1.x, bug

#8478 OSC/RDMA: fix typo in btl selection logic
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: Target: master, Target: v4.0.x, Target: v4.1.x

#8431 First cut at Git commit checks as Github Actions
  .github/workflows/README.md
  .github/workflows/git-commit-checks.json
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: Target: master, enhancement

#8471 btl/sm: do not set always callback frag when there is none
  opal/mca/btl/sm/btl_sm_send.c
Labels: Target: master, bug

#8482 v4.1.x: git commit checker GitHub action
  .github/workflows/README.md
  .github/workflows/git-commit-checks.json
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: Target: v4.1.x, enhancement

#8503 Osc fixes backport v4.1.x
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  ompi/mca/osc/rdma/osc_rdma_lock.h
  ompi/mca/osc/rdma/osc_rdma_request.c
  ompi/mca/osc/rdma/osc_rdma_request.h
Labels: RM approved, Target: v4.1.x, bug

#8476 v4.0.x: Update PMIx to v3.2.3
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/config/pmix.m4
  opal/mca/pmix/pmix3x/pmix/contrib/pmix.spec
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event.h
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_notification.c
  opal/mca/pmix/pmix3x/pmix/src/event/pmix_event_registration.c
  opal/mca/pmix/pmix3x/pmix/src/runtime/pmix_finalize.c
Labels: Target: v4.0.x, bug

#8037 Move yield capability to opal thread component
  ompi/runtime/ompi_mpi_params.c
  opal/mca/threads/argobots/threads_argobots_threads.h
  opal/mca/threads/pthreads/Makefile.am
  opal/mca/threads/pthreads/threads_pthreads.h
  opal/mca/threads/pthreads/threads_pthreads_component.c
  opal/mca/threads/pthreads/threads_pthreads_threads.h
  opal/mca/threads/pthreads/threads_pthreads_yield.c
  opal/mca/threads/qthreads/threads_qthreads_threads.h
  opal/mca/threads/threads.h
  opal/runtime/opal_progress.c
Labels: Target: master, Target: v5.0.x

#8511 ucx: disable version 1.8
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: master, Target: v4.0.x, Target: v4.1.x, Target: v5.0.x, bug

#8512 fs/lustre: Remove unneeded includes
  ompi/mca/fs/lustre/fs_lustre.c
Labels: Target: master, Target: v4.0.x, Target: v4.1.x

#8517 v4.1.x: ucx: disable version 1.8
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: NEWS, RM approved, Target: v4.1.x

#8516 v4.0.x: ucx: disable version 1.8
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: NEWS, Target: v4.0.x, bug

#8529 Fix a crash during CUDA initialization
  ompi/proc/proc.c
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: NEWS

#8534 Prevent the establishment of new BTL connections during matching
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
Labels: RM approved, Target: v4.1.x, bug

#8537 Fix compile errors
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/proc/proc.c
Labels: Target: master, bug
