Repository open-mpi/ompi, pull requests merged in 2022-07, with the labels that each got.

#10537 Op: Treat unsigned long as unsigned, not signed long [v5.0.x]
  ompi/mca/op/base/op_base_functions.c
Labels: Target: v5.0.x

#10442 sessions: add missing errhandler funcs
  docs/man-openmpi/man3/MPI_Session_call_errhandler.3.rst
  docs/man-openmpi/man3/MPI_Session_get_errhandler.3.rst
  docs/man-openmpi/man3/MPI_Session_set_errhandler.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/include/mpi.h.in
  ompi/instance/instance.c
  ompi/instance/instance.h
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/session_call_errhandler.c
  ompi/mpi/c/session_get_errhandler.c
  ompi/mpi/c/session_set_errhandler.c
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/mpif-h/session_call_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_create_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_get_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_set_errhandler_f.c
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces-callbacks.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_nth_pset_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_num_psets_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_pset_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_init_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_call_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_create_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_finalize_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_nth_pset_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_num_psets_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_pset_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_set_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
Labels: Severity: blocker, Target: main, Target: v5.0.x

#10547 osc/ucx: trigger opal progress only if no progress is made inside flush
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: enhancement

#10536 osc/ucx: implement rput and rget using ucp_worker_flush_nb
  ompi/mca/osc/ucx/osc_ucx_comm.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: enhancement, Target: main

#10556 sessions: add missing errhandler funcs
  docs/man-openmpi/man3/MPI_Session_call_errhandler.3.rst
  docs/man-openmpi/man3/MPI_Session_get_errhandler.3.rst
  docs/man-openmpi/man3/MPI_Session_set_errhandler.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/include/mpi.h.in
  ompi/instance/instance.c
  ompi/instance/instance.h
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/session_call_errhandler.c
  ompi/mpi/c/session_get_errhandler.c
  ompi/mpi/c/session_set_errhandler.c
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/mpif-h/session_call_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_create_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_get_errhandler_f.c
  ompi/mpi/fortran/mpif-h/session_set_errhandler_f.c
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces-callbacks.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_nth_pset_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_num_psets_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_get_pset_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/psession_init_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_call_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_create_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_finalize_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_nth_pset_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_num_psets_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_get_pset_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/session_set_errhandler_f08.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
Labels: Target: v5.0.x

#10553 Start fixes: parameter check and return code [v4.0.x]
  ompi/mpi/c/start.c
Labels: Target: v4.0.x

#10549 github-labeler: add label corresponding to the target branch
  .github/workflows/github-labeler.py
  .github/workflows/github-labeler.yaml
Labels: Target: main

#10557 ompi/dpm: make procs consistent before calling PMIx_Connect()
  ompi/dpm/dpm.c
Labels: Target: main, Target: v5.0.x

#10513 [v4.1.x] RDMA osc: perform CAS in shared memory if possible
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: bug, Target: v4.1.x

#10564 [v5.0.x] ompi/dpm: make procs consistent before calling PMIx_Connect()
  ompi/dpm/dpm.c
Labels: Target: v5.0.x

#10569 github-labeler: add label corresponding to the target branch (cherry pick to v5.0.x)
  .github/workflows/github-labeler.py
  .github/workflows/github-labeler.yaml
Labels: Target: v5.0.x

#10567 tools/mpisync: remove obsolete man page
  ompi/tools/mpisync/Makefile.am
  ompi/tools/mpisync/mpisync.1in
Labels: Target: main

#10571 github-labeler: add label corresponding to the target branch (cherry pick to v4.1.x)
  .github/workflows/github-labeler.py
  .github/workflows/github-labeler.yaml
Labels: RM approved, Target: v4.1.x

#10574 Topic/fixes
  ompi/mpi/c/parrived.c
  ompi/mpi/c/precv_init.c
  ompi/mpi/c/psend_init.c
  ompi/mpi/c/start.c
  ompi/runtime/ompi_spc.c
  ompi/runtime/ompi_spc.h
  opal/include/opal/opal_portable_platform_real.h
Labels: Target: main

#10568 ofi: add inject path to ofi btl
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_frag.c
Labels: Target: main

#10517 v4.1.x: coll/ucc: add support for dt float128 float32(64,128)_complex
  config/ompi_check_ucc.m4
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
Labels: Target: v4.1.x

#10497 V4.1.x: (s)coll/ucc: don't force cls by default
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_component.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
Labels: Target: v4.1.x

#10575 v5.0: tools/mpisync: remove obsolete man page
  ompi/tools/mpisync/Makefile.am
  ompi/tools/mpisync/mpisync.1in
Labels: Target: v5.0.x

#10514 Use module names in HAN.
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_component.c
Labels: enhancement, Target: main

#10582 sessions: fix arg checking for group_from_session_pset
  ompi/instance/instance.c
Labels: Target: main

#10587 sessions: fix arg checking for group_from_session_pset
  ompi/instance/instance.c
Labels: Target: v5.0.x

#10580 OSC/UCX Dynamic window fixes
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: main

#10591 v5.0.x: OSC/UCX Dynamic window fixes
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#10595 Fix typos in the oshmem/ subdirectory
  oshmem/include/pshmem.h
  oshmem/include/shmem-compat.h
  oshmem/include/shmem.h.in
  oshmem/mca/atomic/atomic.h
  oshmem/mca/memheap/README.md
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/buddy/memheap_buddy_component.c
  oshmem/mca/memheap/memheap.h
  oshmem/mca/memheap/ptmalloc/malloc.c
  oshmem/mca/memheap/ptmalloc/memheap_ptmalloc_component.c
  oshmem/mca/scoll/mpi/help-oshmem-scoll-mpi.txt
  oshmem/mca/scoll/scoll.h
  oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt
  oshmem/mca/spml/base/spml_base_select.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/sshmem/base/sshmem_base_open.c
  oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
  oshmem/request/request.h
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/profile-defines.h
  oshmem/util/oshmem_util.h
Labels: code cleanup, Target: main

#10596 v5.0.x: Fix typos in the oshmem/ subdirectory
  oshmem/include/pshmem.h
  oshmem/include/shmem-compat.h
  oshmem/include/shmem.h.in
  oshmem/mca/atomic/atomic.h
  oshmem/mca/memheap/README.md
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/buddy/memheap_buddy_component.c
  oshmem/mca/memheap/memheap.h
  oshmem/mca/memheap/ptmalloc/malloc.c
  oshmem/mca/memheap/ptmalloc/memheap_ptmalloc_component.c
  oshmem/mca/scoll/mpi/help-oshmem-scoll-mpi.txt
  oshmem/mca/scoll/scoll.h
  oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt
  oshmem/mca/spml/base/spml_base_select.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/sshmem/base/sshmem_base_open.c
  oshmem/mca/sshmem/sysv/sshmem_sysv_module.c
  oshmem/request/request.h
  oshmem/runtime/oshmem_shmem_init.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/profile-defines.h
  oshmem/util/oshmem_util.h
Labels: code cleanup, Target: v5.0.x

#10597 Consolidate "contributing to Open MPI" docs
  .github/CONTRIBUTING.md
  docs/contributing.rst
  docs/developers/rst-for-markdown-expats.rst
Labels: documentation, Target: main

#10599 v5.0.x: Consolidate "contributing to Open MPI" docs
  .github/CONTRIBUTING.md
  docs/contributing.rst
  docs/developers/rst-for-markdown-expats.rst
Labels: documentation, Target: v5.0.x

#10570 github-labeler: add label corresponding to the target branch (cherry pick to v4.0.x)
  .github/workflows/github-labeler.py
  .github/workflows/github-labeler.yaml
Labels: Target: v4.0.x

#10603 v5.0.x: topic/fixes
  ompi/mpi/c/parrived.c
  ompi/mpi/c/precv_init.c
  ompi/mpi/c/psend_init.c
  ompi/mpi/c/start.c
  ompi/runtime/ompi_spc.c
  ompi/runtime/ompi_spc.h
  opal/include/opal/opal_portable_platform_real.h
Labels: Target: v5.0.x

#10608 v5.0.x: CONTRIBUTING.md: remove stale text
  .github/CONTRIBUTING.md
Labels: code cleanup, Target: v5.0.x

#10561 Cleanup sync object handling in ompi_request_complete
  ompi/request/request.h
Labels: Target: main

#10552 Start fixes: parameter check and return code [v4.1.x]
  ompi/mpi/c/start.c
Labels: RM approved, Target: v4.1.x

#10615 Cleanup sync object handling in ompi_request_complete [v5.0.x]
  ompi/request/request.h
Labels: Target: v5.0.x

#10616 docs/news: Add 4.1.4 NEWS items
  docs/news/news-v4.1.x.rst
Labels: documentation, Target: main

#10618 v5.0.x: docs/news: Add 4.1.4 NEWS items
  docs/news/news-v4.1.x.rst
Labels: documentation, Target: v5.0.x

#9583 MPI4: deprecate MPI_Info_get
  ompi/include/mpi.h.in
Labels: Target: main, MPI-4.0

#10619 Cleanup deprecation warning defines for MPI 4.0
  ompi/include/mpi.h.in
Labels: code cleanup, Target: main
