Repository open-mpi/ompi, pull requests merged in 2022-08, with the labels that each got.

#10600 Remove stale kruft
  .gitignore
  ompi/tools/ompi_info/Makefile.am
  ompi/tools/ompi_info/ompi_info.1in
Labels: code cleanup, Target: main

#10623 v5.0.x: Remove stale kruft
  .gitignore
  ompi/tools/ompi_info/Makefile.am
  ompi/tools/ompi_info/ompi_info.1in
Labels: code cleanup, Target: v5.0.x

#10268 Populate some additional MPI_INFO_ENV keys with singleton launch.
  ompi/instance/instance.c
  ompi/instance/instance.h
  ompi/mpi/c/session_init.c
  ompi/runtime/ompi_mpi_init.c
  ompi/runtime/ompi_rte.c
Labels: Target: main

#10593 OSC/UCX: Adding locks to win attach/detach and fixing build warnings
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: main

#10620 OFI: call fi_getname twice
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: Target: main

#10555 set instance field when creating new group objects
  ompi/communicator/comm.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/dpm/dpm.c
  ompi/group/group.h
  ompi/group/group_bitmap.c
  ompi/group/group_init.c
  ompi/group/group_plist.c
  ompi/group/group_sporadic.c
  ompi/group/group_strided.c
  ompi/instance/instance.c
Labels: Target: main, Target: v5.0.x

#10637 sessions: switch to mpi_size for info key
  ompi/include/mpi.h.in
Labels: Target: main

#10626 v5.0.x: OSC/UCX: Adding locks to win attach/detach and fixing build warnings
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v5.0.x

#10636 set instance field when creating new group objects
  ompi/communicator/comm.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/dpm/dpm.c
  ompi/group/group.h
  ompi/group/group_bitmap.c
  ompi/group/group_init.c
  ompi/group/group_plist.c
  ompi/group/group_sporadic.c
  ompi/group/group_strided.c
  ompi/instance/instance.c
Labels: Target: v5.0.x

#10640 v5.0.x: docs: update runpath/rpath docs
  docs/installing-open-mpi/configure-cli-options/index.rst
  docs/installing-open-mpi/configure-cli-options/installation.rst
  docs/installing-open-mpi/configure-cli-options/rpath-and-runpath.rst
Labels: documentation, Target: v5.0.x

#10630 MPI 4: Add MPI_COMM_TYPE_HW_UNGUIDED and MPI_COMM_TYPE_HW_GUIDED
  ompi/communicator/comm.c
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
  ompi/mpi/c/comm_split_type.c
Labels: Target: main, MPI-4.0

#10614 Revert "Start: check return value of request start function"
  ompi/mpi/c/start.c
Labels: Target: v4.0.x

#10642 Fixup: osc/ucx: implement rput and rget using ucp_worker_flush_nb
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: main

#10634 osc/rdma: fix data integrity issue in rdma get_accumulate
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: main

#10654 v4.1.x: osc/rdma: fix data integrity and memleak issue in rdma get_accumulate
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: RM approved, Target: v4.1.x

#10644 v4.1: Remove error message from --do-not-launch
  orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
Labels: RM approved, Target: v4.1.x

#10653 Fix typos in config subdirectory
  config/extract-3rd-party-configure.pl
  config/oac_check_package.m4
  config/ompi_find_mpi_aint_count_offset.m4
  config/ompi_fortran_check.m4
  config/ompi_fortran_find_module_include_flag.m4
  config/ompi_setup_fc.m4
  config/ompi_setup_mpi_fortran.m4
  config/ompi_setup_prrte.m4
  config/opal_case_sensitive_fs_setup.m4
  config/opal_check_knem.m4
  config/opal_config_3rdparty.m4
  config/opal_config_asm.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
  config/opal_configure_options.m4
  config/opal_functions.m4
  config/opal_mca.m4
  config/opal_setup_cc.m4
  config/opal_setup_wrappers.m4
  config/opal_subdir_env.m4
  config/opal_summary.m4
Labels: code cleanup, Target: main

#10632 git-commit-checks: comment on PR with error(s)
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: Target: main

#10645 v4.0: Remove error message from --do-not-launch
  orte/mca/errmgr/default_hnp/errmgr_default_hnp.c
Labels: Target: v4.0.x

#10658 osc/ucx: Add missing calls to OMPI_OSC_UCX_REQUEST_ALLOC in rget/rput error paths
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: main

#10666 Revert "git-commit-checks: comment on PR with error(s)"
  .github/workflows/git-commit-checks.py
  .github/workflows/git-commit-checks.yml
Labels: Target: main

#10663 Fix remaining typos in source documentation and comments
  autogen.pl
  config/ompi_setup_mpi_fortran.m4
  config/opal_mca.m4
  config/opal_setup_ft.m4
  configure.ac
  contrib/amca-param-sets/ft-mpi
  contrib/build-mca-comps-outside-of-tree/btl_tcp2.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_component.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_endpoint.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_proc.c
  contrib/check_unnecessary_headers.sh
  contrib/dist/linux/README.md
  contrib/dist/linux/buildrpm.sh
  contrib/dist/linux/ompi-spec-generator.py
  contrib/dist/linux/openmpi.spec
  contrib/doc-ft-components/DEVEL.FT-REQUIREMENTS.md
  contrib/find_occurence.pl
  contrib/fix_headers.pl
  contrib/gen_stats.pl
  contrib/header_replacement.sh
  contrib/nightly/reports/check_devel_headers.pl
  contrib/nightly/reports/illegal_symbols_report.pl
  contrib/ompi-time.sh
  contrib/ompi_cplusplus.sed
  contrib/ompi_cplusplus.sh
  contrib/purge-tab-indents.pl
  contrib/purge-trailing-blank-lines.pl
  contrib/search_replace.pl
  contrib/test_headers_in_ompi.pl
  contrib/uncrustify_open_mpi.cfg
  contrib/update-my-copyright.pl
  docs/networking/cuda.rst
  docs/release-notes/compilers.rst
  examples/spc_example.c
  ompi/communicator/comm_request.c
  ompi/communicator/comm_request.h
  ompi/errhandler/errcode-internal.c
  ompi/file/file.h
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/pml/base/pml_base_frame.c
  opal/class/opal_cstring.h
  opal/datatype/opal_datatype_add.c
  opal/mca/base/mca_base_var.h
  opal/util/path.c
  opal/util/path.h
  opal/util/stacktrace.c
  test/class/ompi_rb_tree.c
  test/class/opal_bitmap.c
  test/datatype/reduce_local.c
  test/monitoring/check_monitoring.c
  test/monitoring/test_overhead.sh
  test/simple/crisscross.c
  test/simple/initial_errh.c
  test/simple/no-disconnect.c
  test/spc/spc_test.c
  test/util/opal_argv.c
Labels: Target: main

#10655 v5.0.x: osc/rdma: fix data integrity and memleak issue in rdma get_accumulate
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: v5.0.x

#10659 v5.0.x: OFI: call fi_getname twice
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: Target: v5.0.x

#10650 sessions: switch to mpi_size for info key
  ompi/include/mpi.h.in
Labels: Target: v5.0.x

#10656 v5.0.x: Fix typos in config subdirectory
  config/extract-3rd-party-configure.pl
  config/oac_check_package.m4
  config/ompi_find_mpi_aint_count_offset.m4
  config/ompi_fortran_check.m4
  config/ompi_fortran_find_module_include_flag.m4
  config/ompi_setup_fc.m4
  config/ompi_setup_mpi_fortran.m4
  config/ompi_setup_prrte.m4
  config/opal_case_sensitive_fs_setup.m4
  config/opal_check_knem.m4
  config/opal_config_3rdparty.m4
  config/opal_config_asm.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
  config/opal_configure_options.m4
  config/opal_functions.m4
  config/opal_mca.m4
  config/opal_setup_cc.m4
  config/opal_setup_wrappers.m4
  config/opal_subdir_env.m4
  config/opal_summary.m4
Labels: code cleanup, Target: v5.0.x

#10671 v4.0: Fix Display Topo
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: Target: v4.0.x

#10621 OSC/UCX: Fix the opal_progress call condition inside flush
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: main

#10677 fortran/ignore-tkr: fix typos in PMPI_* symbols
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
Labels: Target: main

#10670 v4.1: Fix Display Topo
  orte/runtime/data_type_support/orte_dt_print_fns.c
Labels: RM approved, Target: v4.1.x

#10676 fixing an int overflow in the basic collectives alltoall
  ompi/mca/coll/base/coll_base_alltoall.c
Labels: Target: main

#10684 fixing an int overflow in the basic collectives alltoall
  ompi/mca/coll/base/coll_base_alltoall.c
Labels: Target: v4.0.x

#10679 Improve support for AMD ROCm GPU devices
  .gitignore
  .mailmap
  config/opal_check_rocm.m4
  config/opal_config_files.m4
  configure.ac
  docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/mpiext/rocm/Makefile.am
  ompi/mpiext/rocm/c/Makefile.am
  ompi/mpiext/rocm/c/mpiext_rocm.c
  ompi/mpiext/rocm/c/mpiext_rocm_c.h.in
  ompi/mpiext/rocm/configure.m4
  opal/Makefile.am
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_datatype_copy.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  opal/rocm/Makefile.am
  opal/rocm/common_rocm.c
  opal/rocm/common_rocm.h
  opal/rocm/common_rocm_prototypes.h
  opal/rocm/owner.txt
  opal/runtime/opal_init.c
  opal/runtime/opal_params.c
  opal/runtime/opal_params.h
Labels: Target: v5.0.x

#10675 v5.0.x OSC/UCX: Fix the opal_progress call condition inside flush
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#10680 v5.0.x: fortran/ignore-tkr: fix typos in PMPI_* symbols
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
Labels: bug, Target: v5.0.x

#10686 fixing an int overflow in the basic collectives alltoall
  ompi/mca/coll/base/coll_base_alltoall.c
Labels: Target: v5.0.x

#10681 Fix MPI_COMM_TYPE_HW_GUIDED split
  ompi/communicator/comm.c
Labels: Target: main

#10683 Move MPI Standard version to VERSION file
  VERSION
  config/opal_get_version.m4
  config/opal_save_version.m4
  config/opal_summary.m4
  configure.ac
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
Labels: Target: main

#10696 v5.0.x: More spelling fixes
  autogen.pl
  config/ompi_setup_mpi_fortran.m4
  config/opal_mca.m4
  config/opal_setup_ft.m4
  configure.ac
  contrib/amca-param-sets/ft-mpi
  contrib/build-mca-comps-outside-of-tree/btl_tcp2.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_component.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_endpoint.c
  contrib/build-mca-comps-outside-of-tree/btl_tcp2_proc.c
  contrib/check_unnecessary_headers.sh
  contrib/dist/linux/README.md
  contrib/dist/linux/buildrpm.sh
  contrib/dist/linux/ompi-spec-generator.py
  contrib/dist/linux/openmpi.spec
  contrib/doc-ft-components/DEVEL.FT-REQUIREMENTS.md
  contrib/find_occurence.pl
  contrib/fix_headers.pl
  contrib/gen_stats.pl
  contrib/header_replacement.sh
  contrib/nightly/reports/check_devel_headers.pl
  contrib/nightly/reports/illegal_symbols_report.pl
  contrib/ompi-time.sh
  contrib/ompi_cplusplus.sed
  contrib/ompi_cplusplus.sh
  contrib/purge-tab-indents.pl
  contrib/purge-trailing-blank-lines.pl
  contrib/search_replace.pl
  contrib/test_headers_in_ompi.pl
  contrib/uncrustify_open_mpi.cfg
  contrib/update-my-copyright.pl
  docs/networking/cuda.rst
  docs/release-notes/compilers.rst
  examples/spc_example.c
  ompi/communicator/comm_request.c
  ompi/communicator/comm_request.h
  ompi/errhandler/errcode-internal.c
  ompi/file/file.h
  ompi/mca/io/ompio/io_ompio_component.c
  opal/class/opal_cstring.h
  opal/datatype/opal_datatype_add.c
  opal/mca/base/mca_base_var.h
  opal/util/path.c
  opal/util/path.h
  opal/util/stacktrace.c
  test/class/ompi_rb_tree.c
  test/class/opal_bitmap.c
  test/datatype/reduce_local.c
  test/monitoring/check_monitoring.c
  test/monitoring/test_overhead.sh
  test/simple/crisscross.c
  test/simple/initial_errh.c
  test/simple/no-disconnect.c
  test/spc/spc_test.c
  test/util/opal_argv.c
Labels: code cleanup, Target: v5.0.x

#10695 Fix the dpm to fwd IO to the spawning parent
  ompi/dpm/dpm.c
Labels: Target: main

#10697 java: catch exceptions if we fail to load mpi_java
  ompi/mpi/java/java/MPI.java
Labels: Target: main

#10688 Fix Singletons and Singleton Spawn
  ompi/dpm/dpm.c
  ompi/runtime/ompi_rte.c
Labels: Target: main

#10700 DPM: Force 'hash' GDS component when singleton spawn
  ompi/dpm/dpm.c
Labels: Target: main

#10488 Coll/base: FIX bruck when sdtype and rdtype are different
  ompi/mca/coll/base/coll_base_alltoall.c
Labels: Severity: critical, Target: main, Target: v4.0.x, Target: v5.0.x, Target: v4.1.x

#10706 prrte schizo: add an env variable for OMPI libdir
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x

#10707 java: catch exceptions if we fail to load mpi_java
  ompi/mpi/java/java/MPI.java
Labels: Target: v5.0.x

#10711 MEMHEAP/BASE: removed hard segments limit - v5.0
  oshmem/mca/memheap/base/base.h
  oshmem/mca/memheap/base/memheap_base_alloc.c
  oshmem/mca/memheap/base/memheap_base_frame.c
  oshmem/mca/memheap/base/memheap_base_mkey.c
  oshmem/mca/memheap/base/memheap_base_static.c
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
Labels: Target: v5.0.x

#10694 smsc/cma: Add a check for CAP_SYS_PTRACE between processes
  config/opal_check_cma.m4
  opal/mca/smsc/cma/smsc_cma_module.c
Labels: Target: main

#10721 Atomics: several fixes the GCC backend
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: Target: main

#10716 v5: Fix singleton spawn
  ompi/dpm/dpm.c
  ompi/runtime/ompi_rte.c
Labels: Target: v5.0.x

#10723 [4.1.x] GCC atomics: acquire thread-fence was busted until GCC 8.1.0
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: Target: v4.1.x

#10728 update to safety valve for MCA callbacks
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/rcache/base/rcache_base_create.c
  opal/memoryhooks/memory.c
Labels: Target: main

#9748 v5.0.x: Safety valve for callbacks
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/rcache/base/rcache_base_create.c
  opal/memoryhooks/memory.c
Labels: Target: v5.0.x

#10722 Gcc atomic fixes v5.0.x
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: Target: v5.0.x

#10724 Make GCC atomics the default atomic implementation
  config/opal_config_asm.m4
Labels: Target: main

#10692 Minor odds and ends; fix 1 compiler warning
  examples/Hello.java
  ompi/mpi/java/java/CartComm.java
  ompi/mpi/java/java/CartParms.java
  ompi/mpi/java/java/Comm.java
  ompi/mpi/java/java/Count.java
  ompi/mpi/java/java/Datatype.java
  ompi/mpi/java/java/Errhandler.java
  ompi/mpi/java/java/Freeable.java
  ompi/mpi/java/java/GraphComm.java
  ompi/mpi/java/java/GraphParms.java
  ompi/mpi/java/java/Group.java
  ompi/mpi/java/java/Intercomm.java
  ompi/mpi/java/java/Intracomm.java
  ompi/mpi/java/java/MPI.java
  ompi/mpi/java/java/MPIException.java
  ompi/mpi/java/java/Op.java
  ompi/mpi/java/java/Prequest.java
  ompi/mpi/java/java/Request.java
  ompi/mpi/java/java/ShiftParms.java
  ompi/mpi/java/java/Status.java
  ompi/mpi/java/java/UserFunction.java
  ompi/mpi/java/java/Version.java
  ompi/tools/mpirun/main.c
  opal/util/bipartite_graph.c
  opal/util/bipartite_graph.h
  opal/util/if.c
  oshmem/tools/wrappers/oshmem-c.pc.in
  oshmem/tools/wrappers/oshmem-cxx.pc.in
  oshmem/tools/wrappers/oshmem-fort.pc.in
  oshmem/tools/wrappers/oshmem.pc.in
  test/util/opal_path_nfs.c
Labels: Target: main

#10690 btl/sm: Use node rank instead of local rank for sm backing file
  opal/mca/btl/sm/btl_sm_component.c
Labels: Target: main

#10725 GitHub Workflows security hardening
  .github/workflows/github-labeler.yaml
Labels: Target: main
