Repository open-mpi/ompi, pull requests merged in 2022-01, with the labels that each got.

#9796 README: add ifort/macOS linker error note and workaround
  README.md
Labels: documentation, Target: master

#9792 ompi_deleted_options.m4: minor cleanups
  config/ompi_deleted_options.m4
Labels: enhancement, Target: master

#9758 ompi/util/timings.h: use back-end OMPI calls
  ompi/runtime/ompi_mpi_init.c
  ompi/util/timings.h
Labels: Target: master

#9801 config/opal_config_asm.m4: Trivial output label fix
  config/opal_config_asm.m4
Labels: documentation, Target: master

#9805 help-smsc-knem.txt: fix incorrect messages, remove stale messages
  opal/mca/smsc/knem/help-smsc-knem.txt
Labels: documentation, Target: master, Target: v5.0.x

#9818 sharedfp_sm_file_open: minor code cleanup
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: code cleanup

#9829 sharedfp_sm_file_open: remove illegal free
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: bug, Target: master

#9827 v4.0.x: README: add ifort/macOS linker error note and workaround
  README
Labels: documentation, Target: v4.0.x

#9814 Fix compiler warnings
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/util/malloc.h
  opal/util/stacktrace.c
Labels: Target: master

#9798 RFC: opal_clock_gettime() and opal_clock_getres()
  configure.ac
  ompi/mpi/c/wtick.c
  ompi/mpi/c/wtime.c
  opal/util/Makefile.am
  opal/util/clock_gettime.h
Labels: Target: master, Target: v5.0.x

#9806 mpi module: add the mpi_f08 TYPE(MPI_Foo) types
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
  ompi/mpi/fortran/use-mpi/mpi-types.F90.in
Labels: bug, fortran bindings, Target: master, Target: v5.0.x

#9831 Two updates: 1) better message in msgq, 2) pedantic casting in osc/rdma
  ompi/debuggers/ompi_msgq_dll.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: master

#9813 v4.1.x: fix several compiler warnings
  ompi/debuggers/ompi_msgq_dll.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  opal/mca/btl/ofi/btl_ofi_frag.c
  opal/mca/btl/ofi/btl_ofi_frag.h
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/btl/openib/btl_openib_component.c
  opal/mca/pmix/flux/pmix_flux.c
  opal/mca/pmix/pmix3x/pmix3x_component.c
Labels: RM approved, Target: v4.1.x

#9832 v5.0.x: Add opal_clock_gettime() / opal_clock_getres()
  configure.ac
  ompi/mpi/c/wtick.c
  ompi/mpi/c/wtime.c
  opal/util/Makefile.am
  opal/util/clock_gettime.h
Labels: Target: v5.0.x

#9830 v5.0.x: compiler warning fixes
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/util/malloc.h
  opal/util/stacktrace.c
Labels: Target: v5.0.x

#9788 v5.0.x: sharedfp_sm_file_component_query: add file open to ensure correct ope…
  ompi/mca/sharedfp/sm/sharedfp_sm.c
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: bug, Target: v5.0.x

#9800 v5.0.x: README: add ifort/macOS linker error note and workaround
  README.md
Labels: documentation, Target: v5.0.x

#9817 v5.0.x: config/opal_config_asm.m4: Trivial output label fix
  config/opal_config_asm.m4
Labels: documentation, Target: v5.0.x

#9839 m4: fix 2 broken uses of AC_LANG_PROGRAM
  config/opal_check_icc.m4
  config/opal_config_asm.m4
Labels: Severity: blocker, Target: master

#9824 Fix broken internal pmix configure
  config/opal_config_pmix.m4
  config/opal_setup_wrappers.m4
Labels: Target: v5.0.x

#9822 Update NEWS with 4.1.2 items
  NEWS
Labels: documentation, Target: v5.0.x

#9823 Remove double semicolon in shmem headers
  oshmem/include/pshmem.h
  oshmem/include/shmem.h.in
Labels: Target: v5.0.x

#9821 Update BTL documentation
  opal/mca/btl/btl.h
Labels: documentation, Target: v5.0.x

#9834 v5.0.x: mpi module: add the mpi_f08 TYPE(MPI_Foo) types
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
  ompi/mpi/fortran/use-mpi/mpi-types.F90.in
Labels: fortran bindings, Target: v5.0.x

#9819 v5.0.x: help-smsc-knem.txt: fix incorrect messages, remove stale messages
  opal/mca/smsc/knem/help-smsc-knem.txt
Labels: documentation, Target: v5.0.x

#9841 configure: remove ancient / no-longer-relevant icc test
  config/opal_check_icc.m4
  configure.ac
Labels: Target: master

#9835 OSC RDMA initialization cleanups
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_component.c
Labels: bug, Target: master

#9803 v5.0.x: ompi_deleted_options.m4: minor cleanups
  config/ompi_deleted_options.m4
Labels: enhancement, Target: v5.0.x

#9804 v5.0.x: ompi/util/timings.h: use back-end OMPI calls
  ompi/runtime/ompi_mpi_init.c
  ompi/util/timings.h
Labels: bug, Target: v5.0.x

#9840 v5.0.x: m4: fix 2 broken uses of AC_LANG_PROGRAM
  config/opal_check_icc.m4
  config/opal_config_asm.m4
Labels: bug, Severity: blocker, Target: v5.0.x

#9655 Relax memory order in opal_atomic_lock_init
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: master

#9844 btl/sm: fix crash on put/get to self
  opal/mca/btl/sm/Makefile.am
  opal/mca/btl/sm/btl_sm.h
  opal/mca/btl/sm/btl_sm_endpoint.h
  opal/mca/btl/sm/btl_sm_get.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/btl_sm_put.c
Labels: bug, Target: master

#9847 mpi.h: add OMPI_ATTR_PREDEFINED_KEY_MAX
  ompi/include/mpi.h.in
Labels: Target: master, sessions

#9852 Patched libnbc to not round fractions based on float precision
  ompi/mca/coll/libnbc/nbc_iallreduce.c
  ompi/mca/coll/libnbc/nbc_ibarrier.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: Target: master

#9849 Relax memory order in opal_atomic_lock_init
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: v5.0.x

#9775 v4.1.x: configure/lsf: Make failure to find yp_all() more clear.
  config/orte_check_lsf.m4
Labels: Target: v4.1.x

#9787 v4.1.x: sharedfp_sm_file_component_query: add file open to ensure correct ope…
  ompi/mca/sharedfp/sm/sharedfp_sm.c
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: bug, RM approved, Target: v4.1.x

#9799 v4.1.x: README: add ifort/macOS linker error note and workaround
  README
Labels: documentation, Target: v4.1.x

#9857 v5.0.x: Patched libnbc to not round fractions based on float precision
  ompi/mca/coll/libnbc/nbc_iallreduce.c
  ompi/mca/coll/libnbc/nbc_ibarrier.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: bug, Target: v5.0.x

#9848 ompi/attr: update attribute system to prepare for sessions
  ompi/attribute/attribute.c
  ompi/attribute/attribute.h
  ompi/attribute/attribute_predefined.c
  ompi/communicator/comm_init.c
  ompi/datatype/ompi_datatype_module.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  ompi/win/win.c
Labels: Target: master, sessions

#9874 Require HWLOC 1.11.0 or later
  config/opal_config_hwloc.m4
Labels: Target: master

#9891 BUFSIZ is undefined in mpiext/affinity.h
  ompi/mpiext/affinity/c/mpiext_affinity_c.h
Labels: bug, Severity: blocker, Target: master, Target: v5.0.x

#9895 UCX/DSO/BUILD: fixed build when DSO is enabled - v5.x
  oshmem/mca/atomic/ucx/Makefile.am
  oshmem/mca/spml/ucx/Makefile.am
Labels: Target: v5.0.x

#9896 Require HWLOC 1.11.0 or later
  config/opal_config_hwloc.m4
Labels: Target: v5.0.x

#9898 v5.0.x: BUFSIZ is undefined in mpiext/affinity.h replace it with 1024 as it w…
  ompi/mpiext/affinity/c/mpiext_affinity_c.h
Labels: Target: v5.0.x

#9816 fcoll: move read_all functions to base
  ompi/mca/fcoll/base/Makefile.am
  ompi/mca/fcoll/base/base.h
  ompi/mca/fcoll/base/fcoll_base_file_read_all.c
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic/fcoll_dynamic.h
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_module.c
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c
  ompi/mca/fcoll/vulcan/Makefile.am
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_module.c
Labels: code cleanup

#9719 Rework the MPI_Op support.
  ompi/mca/op/base/op_base_functions.c
  test/datatype/reduce_local.c
Labels: code cleanup, performance, Target: v5.0.x

#9707 MPI4:implement MPI_Comm_idup_with_info
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/comm_idup_with_info.c
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/comm_idup_with_info_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/comm_idup_with_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
  ompi/mpi/man/man3/MPI_Comm_idup_with_info.3in
  ompi/mpi/man/man3/Makefile.am
Labels: Target: master, Target: v5.0.x, MPI-4.0

#9863 v4.1.x: Fix compile failure with enable-heterogeneous.
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: bug, RM approved, Target: v4.1.x

#9856 v4.1.x: Patched libnbc to not round fractions based on float precision
  ompi/mca/coll/libnbc/nbc_iallreduce.c
  ompi/mca/coll/libnbc/nbc_ibarrier.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
Labels: bug, RM approved, Target: v4.1.x

#9887 romio321 gpfs, change stat64 to stat
  ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_open.c
Labels: RM approved, Target: v4.1.x

#9911 Fix Fortran preprocessor issue with CPPFLAGS
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpiext/example/use-mpi-f08/Makefile.am
  ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
Labels: Target: v5.0.x

#9913 treematch: Fix warnings
  3rd-party/treematch/tm_topology.c
Labels: code cleanup, Target: master

#9667 MPI4: implement mpi_isendrecv and variant
  ompi/communicator/comm_request.c
  ompi/communicator/comm_request.h
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/isendrecv.c
  ompi/mpi/c/isendrecv_replace.c
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/isendrecv_f.c
  ompi/mpi/fortran/mpif-h/isendrecv_replace_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/isendrecv_f08.F90
  ompi/mpi/fortran/use-mpi-f08/isendrecv_replace_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/man/man3/MPI_Isendrecv.3in
  ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
  ompi/mpi/man/man3/Makefile.am
  ompi/runtime/ompi_spc.c
  ompi/runtime/ompi_spc.h
Labels: Target: master, Target: v5.0.x, MPI-4.0

#9922 sharedfp/sm: Fix resource leak
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: Target: master

#9921 hwloc: enable --enable-plugins when appropriate
  config/opal_config_hwloc.m4
Labels: Target: master

#9904 Allow explicit use of the Active Message RDMA interface
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/mca/btl/base/btl_base_am_rdma.h
  opal/mca/btl/btl.h
Labels: Target: master

#9908 v5.0.x: Slight MPI_Op optimization
  ompi/mca/op/base/op_base_functions.c
  test/datatype/reduce_local.c
Labels: NEWS, Target: v5.0.x

#9926 MPI4: implement mpi_isendrecv and variant
  ompi/communicator/comm_request.c
  ompi/communicator/comm_request.h
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/isendrecv.c
  ompi/mpi/c/isendrecv_replace.c
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/isendrecv_f.c
  ompi/mpi/fortran/mpif-h/isendrecv_replace_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/isendrecv_f08.F90
  ompi/mpi/fortran/use-mpi-f08/isendrecv_replace_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/man/man3/MPI_Isendrecv.3in
  ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
  ompi/mpi/man/man3/Makefile.am
  ompi/runtime/ompi_spc.c
  ompi/runtime/ompi_spc.h
Labels: NEWS, Target: v5.0.x

#9929 manpages:mpi_isendrecv_replace
  ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
Labels: Target: master

#9931 isendrecv_rplace: fix problem with req status
  ompi/mpi/c/isendrecv_replace.c
Labels: Target: master

#9930 spc: fix up an update for isendrecv, etc.
  ompi/runtime/ompi_spc.c
Labels: Target: master

#9865 v4.0.x: configure/lsf: Make failure to find yp_all() more clear.
  config/orte_check_lsf.m4
Labels: Target: v4.0.x

#9888 romio321 gpfs, change stat64 to stat
  ompi/mca/io/romio321/romio/adio/ad_gpfs/ad_gpfs_open.c
Labels: Target: v4.0.x

#9809 v4.0.x: README: update --enable-heterogeneous warning
  README
Labels: documentation, Target: v4.0.x

#9786 v4.0.x: sharedfp_sm_file_component_query: add file open to ensure correct ope…
  ompi/mca/sharedfp/sm/sharedfp_sm.c
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
Labels: bug, NEWS, Target: v4.0.x

#9880 btl/sm: avoid using xpmem for fast boxes
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/btl_sm_module.c
Labels: Target: master, Target: v5.0.x, Target: v4.1.x

#9939 v5.0.x: fcoll: move read_all functions to base
  config/ompi_configure_options.m4
  ompi/mca/fbtl/base/Makefile.am
  ompi/mca/fcoll/base/Makefile.am
  ompi/mca/fcoll/base/base.h
  ompi/mca/fcoll/base/fcoll_base_file_read_all.c
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic/fcoll_dynamic.h
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_module.c
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c
  ompi/mca/fcoll/vulcan/Makefile.am
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_module.c
  ompi/mca/fs/base/Makefile.am
  ompi/mca/sharedfp/base/Makefile.am
Labels: Target: v5.0.x

#9947 manpages:mpi_isendrecv_replace
  ompi/mpi/man/man3/MPI_Isendrecv_replace.3in
Labels: Target: v5.0.x

#9935 v5.0.x warnings fixes
  3rd-party/treematch/tm_topology.c
  ompi/attribute/attribute.c
  ompi/attribute/attribute.h
  ompi/attribute/attribute_predefined.c
  ompi/communicator/comm_init.c
  ompi/datatype/ompi_datatype_module.c
  ompi/dpm/dpm.c
  ompi/include/mpi.h.in
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/sharedfp/sm/sharedfp_sm.c
  ompi/mca/sharedfp/sm/sharedfp_sm_file_open.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  ompi/tools/mpirun/main.c
  ompi/win/win.c
  opal/datatype/opal_datatype_unpack.c
  opal/mca/backtrace/execinfo/backtrace_execinfo.c
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/mca/mpool/base/mpool_base_default.c
  opal/mca/rcache/base/rcache_base_mem_cb.c
  opal/util/Makefile.am
  opal/util/daemon_init.c
  opal/util/daemon_init.h
  opal/util/error.c
  opal/util/output.c
  opal/util/output.h
  opal/util/path.c
  opal/util/stacktrace.c
Labels: Target: v5.0.x
