Repository open-mpi/ompi, pull requests merged in 2022-04, with the labels that each got.

#10232 Fix accidental change from 'master' -> 'main' for OpenUCX docs.
  docs/networking/cuda.rst
Labels: Target: main

#10231 v5.0.x: SS11: initial ofi btl fixes
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_module.c
Labels: Target: v5.0.x

#10229 v5.0.x: common/ucx: fix variable registration
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: Target: v5.0.x

#10236 Fix undefined PLATFORM_COMPILER_GNU build warning
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: main

#10237 Fix undefined PLATFORM_COMPILER_GNU build warning
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: v5.0.x

#10240 v5.0.x: Update news for v5.0.0rc5.
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10241 v5.0.x: Update VERSION to v5.0.0rc5.
  VERSION
Labels: Target: v5.0.x

#10171 coll/ucc: port UCC component to v4.x
  README
  config/ompi_check_ucc.m4
  ompi/mca/coll/base/coll_tags.h
  ompi/mca/coll/ucc/Makefile.am
  ompi/mca/coll/ucc/coll_ucc.h
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_barrier.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_common.h
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_debug.h
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/coll_ucc_reduce.c
  ompi/mca/coll/ucc/configure.m4
  oshmem/mca/scoll/ucc/Makefile.am
  oshmem/mca/scoll/ucc/configure.m4
  oshmem/mca/scoll/ucc/help-oshmem-scoll-ucc.txt
  oshmem/mca/scoll/ucc/scoll_ucc.h
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_common.h
  oshmem/mca/scoll/ucc/scoll_ucc_component.c
  oshmem/mca/scoll/ucc/scoll_ucc_debug.h
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: enhancement, ⚠️ WIP-DNM!, Target: v4.1.x

#10198 reachable/netlink: Fix missing LDFLAGS
  opal/mca/reachable/netlink/Makefile.am
Labels: Target: v4.1.x

#10181 v4.1.x: common/ompio: fix a division by zero problem in cost_calc
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: Target: v4.1.x

#10213 Minor docs updates
  docs/Makefile.am
  docs/requirements.txt
  docs/to-do.rst
  examples/README.md
Labels: documentation, Target: main

#10199 Netlink/reachable link fixes
  opal/mca/reachable/netlink/Makefile.am
  opal/mca/reachable/netlink/configure.m4
Labels: Target: v4.0.x

#10182 common/ompio: fix a division by zero problem in cost_calc
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: Target: v4.0.x

#10177 v4.0.x: Don't overwrite NULL descriptors.
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: NEWS, Target: v4.0.x

#10262 v5.0.x: btl/usnic: Fix broken build
  config/opal_check_ofi.m4
  opal/mca/btl/usnic/Makefile.am
  opal/mca/btl/usnic/configure.m4
Labels: Target: v5.0.x

#10267 Add 'openpmix' alias for 'pmix' when disabling 3rd party
  autogen.pl
Labels: Target: v5.0.x

#10224 openmpi.spec: updates for v5.0.0
  contrib/dist/linux/README.md
  contrib/dist/linux/buildrpm.sh
  contrib/dist/linux/openmpi.spec
Labels: Target: v5.0.x

#10269 buildrpm.sh: remove debug statement
  contrib/dist/linux/buildrpm.sh
Labels: Target: main

#10255 v5.0.x: Yet more docs updates
  docs/Makefile.am
  docs/features/java.rst
  docs/requirements.txt
  docs/to-do.rst
  examples/README.md
Labels: documentation, Target: v5.0.x

#10270 v5.0.x: openmpi.spec: updates for v5.0.0
  contrib/dist/linux/README.md
  contrib/dist/linux/buildrpm.sh
  contrib/dist/linux/openmpi.spec
Labels: Target: v5.0.x

#10272 Documentation: MPI_Info_set string arguments are const
  docs/man-openmpi/man3/MPI_Info_set.3.rst
  docs/man-openmpi/man3/MPI_Pack_external_size.3.rst
Labels: Target: main

#10253 smsc/xpmem: header detection fix
  config/opal_check_xpmem.m4
Labels: NEWS

#10275 v5.0.x: Docs: datarep argument to MPI_Pack_external_size is const
  docs/man-openmpi/man3/MPI_Info_set.3.rst
  docs/man-openmpi/man3/MPI_Pack_external_size.3.rst
Labels: documentation, Target: v5.0.x

#10274 v5.0.x: smsc/xpmem: header detection fix
  config/opal_check_xpmem.m4
Labels: NEWS, Target: v5.0.x

#10277 Correctly handle MPI_UNSIGNED_LONG.
  ompi/datatype/ompi_datatype_module.c
Labels: bug, Severity: blocker, NEWS, Target: v4.0.x, Target: v5.0.x, Target: v4.1.x

#10281 v5.0.x: Correctly handle MPI_UNSIGNED_LONG.
  ompi/datatype/ompi_datatype_module.c
Labels: Target: v5.0.x

#10280 v4.1.x: Correctly handle MPI_UNSIGNED_LONG.
  ompi/datatype/ompi_datatype_module.c
Labels: RM approved, Target: v4.1.x

#10282 v5.0.x: ompi_check_libhcoll: Fix bug where --with-hcoll will fail to configure.
  config/ompi_check_libhcoll.m4
Labels: Target: v5.0.x

#10284 v5.0.x: Update News and version
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10294 scoll/ucc: proper fallback
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: bug

#10289 runtime: warn before using singleton mode
  ompi/runtime/help-mpi-runtime.txt
  ompi/runtime/ompi_rte.c
Labels: enhancement, Target: main

#10306 Properly initialize group pointer passed to ompi_group_from_pset
  ompi/communicator/comm_init.c
Labels: Target: main

#10305 V5.0.x: scoll/ucc: proper fallback
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: Target: v5.0.x

#10310 v5.0.x: Release the temporary arrays for nonblocking collectives.
  ompi/include/ompi/memchecker.h
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/coll/hcoll/coll_hcoll_rte.c
  ompi/mpi/fortran/mpif-h/allgatherv_init_f.c
  ompi/mpi/fortran/mpif-h/alltoallv_init_f.c
  ompi/mpi/fortran/mpif-h/alltoallw_init_f.c
  ompi/mpi/fortran/mpif-h/gatherv_init_f.c
  ompi/mpi/fortran/mpif-h/iallgatherv_f.c
  ompi/mpi/fortran/mpif-h/ialltoallv_f.c
  ompi/mpi/fortran/mpif-h/ialltoallw_f.c
  ompi/mpi/fortran/mpif-h/igatherv_f.c
  ompi/mpi/fortran/mpif-h/ineighbor_allgatherv_f.c
  ompi/mpi/fortran/mpif-h/ineighbor_alltoallv_f.c
  ompi/mpi/fortran/mpif-h/ineighbor_alltoallw_f.c
  ompi/mpi/fortran/mpif-h/ireduce_scatter_f.c
  ompi/mpi/fortran/mpif-h/iscatterv_f.c
  ompi/mpi/fortran/mpif-h/neighbor_allgatherv_init_f.c
  ompi/mpi/fortran/mpif-h/neighbor_alltoallv_init_f.c
  ompi/mpi/fortran/mpif-h/neighbor_alltoallw_init_f.c
  ompi/mpi/fortran/mpif-h/reduce_scatter_init_f.c
  ompi/mpi/fortran/mpif-h/scatterv_init_f.c
Labels: Target: v5.0.x

#10316 dist: Update VERSION to prep for 4.1.4
  VERSION
Labels: RM approved, Target: v4.1.x

#10279 v4.0.x: Correctly handle MPI_UNSIGNED_LONG.
  ompi/datatype/ompi_datatype_module.c
Labels: Target: v4.0.x

#10311 Add missing "#if OPAL_CUDA_GDR_SUPPORT" protection.
  ompi/mca/pml/ob1/pml_ob1_cuda.c
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: main

#10290 Add missing "#if OPAL_CUDA_GDR_SUPPORT" protection.
  ompi/mca/pml/ob1/pml_ob1_cuda.c
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: v4.1.x

#10331 oshmem: making shmem_calloc spec-compliant regarding zero-byte inputs
  oshmem/shmem/c/shmem_alloc.c
Labels: Target: main

#10320 osc/ucx: use remote state mem to do fetch-and-add to realize the completion of put/get
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: main

#10317 PML/UCX/DATATYPE: fixed potential race - v5.0
  ompi/mca/pml/ucx/pml_ucx_datatype.c
  ompi/mca/pml/ucx/pml_ucx_datatype.h
Labels: Target: v5.0.x

#10319 v5.0.x: scoll/ucc: Split UCC initialization and context creation
  oshmem/mca/scoll/ucc/scoll_ucc.h
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_component.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: Target: v5.0.x

#10330 ulfm: endpoint->btl_eager can be empty when the dst has failed
  ompi/mca/pml/ob1/pml_ob1_isend.c
Labels: bug, Target: v5.0.x

#10332 v5.0.x: oshmem: making shmem_calloc spec-compliant regarding zero-byte inputs
  oshmem/shmem/c/shmem_alloc.c
Labels: Target: v5.0.x

#10329 Ignore receive buffer at non-root for cuda reduce collective
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: Target: main

#10321 mpirun: Refactor to better play with prefixes
  config/ompi_setup_prrte.m4
  ompi/tools/mpirun/Makefile.am
  ompi/tools/mpirun/help-mpirun.txt
  ompi/tools/mpirun/main.c
Labels: Target: main

#10337 v5.0.x: oshmem/wrappers: Fix oshmem Fortran wrapper
  config/opal_setup_wrappers.m4
Labels: bug, Target: v5.0.x

#10327 v5.0: Ignore receive buffer at non-root for cuda reduce collective
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: Target: v5.0.x

#10338 mpirun: Refactor to better play with prefixes
  config/ompi_setup_prrte.m4
  ompi/tools/mpirun/Makefile.am
  ompi/tools/mpirun/help-mpirun.txt
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x
