Repository open-mpi/ompi, pull requests merged in 2022-10, with the labels that each got.

#10881 autogen.pl: patch generated configure file for ifort support on OS X
  autogen.pl
Labels: Target: main

#10880 Fix debugger attach during MPI_Init
  ompi/runtime/ompi_rte.c
Labels: Target: main

#10877 v5.0.x: .ci: trivial README.md updates
  .ci/README.md
  .ci/mellanox/README.md
Labels: code cleanup, Target: v5.0.x

#10882 ofi/common: add a missing mutex unlock
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#10883 ofi/common: remove dead code
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#10864 pml/cm: Fix call convertor_prepare_for_send to use the right pointer
  ompi/mca/pml/cm/pml_cm.h
Labels: Target: main

#10889 opal/accelerator: Fix base selection logic
  opal/mca/accelerator/base/accelerator_base_select.c
Labels: Target: main

#10887 ofi/common: remove dead code
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#10888 ofi/common: add a missing mutex unlock
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#10795 process set query: if pmix_query_info_nb returns error
  ompi/instance/instance.c
Labels: Target: main

#10892 ci/lanl: use recursive git submodule init
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: main

#10894 autogen.pl: patch generated configure file for ifort support on OS X
  autogen.pl
Labels: Target: v4.1.x

#10885 sessions: fixes for invoking some functions before init
  ompi/mpi/c/error_class.c
  ompi/mpi/c/error_string.c
  ompi/mpi/c/info_f2c.c
  ompi/mpi/c/info_free.c
  ompi/mpi/c/info_get_nthkey.c
  ompi/mpi/c/info_get_string.c
Labels: Target: main

#10896 mtl/ofi: fix a resource leak found by coverity
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#10891 process set query: if pmix_query_info_nb returns error
  ompi/instance/instance.c
Labels: Target: v5.0.x

#10893 autogen.pl: patch generated configure file for ifort support on OS X
  autogen.pl
Labels: Target: v5.0.x

#10898 sessions: fixes for invoking some functions before init
  ompi/mpi/c/error_class.c
  ompi/mpi/c/error_string.c
  ompi/mpi/c/info_f2c.c
  ompi/mpi/c/info_free.c
  ompi/mpi/c/info_get_nthkey.c
  ompi/mpi/c/info_get_string.c
Labels: Target: v5.0.x

#10905 mtl/ofi: fix convertor on ofi_req
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#10904 pml/cm: Fix call convertor_prepare_for_send to use the right pointer
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: Target: main

#10907 mtl/ofi: fix a resource leak found by coverity
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v5.0.x

#10906 mtl/ofi: fix convertor on ofi_req
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v5.0.x

#10909 docs: Update cuda installation and support docs
  docs/networking/cuda.rst
Labels: Target: main

#10897 Initialize opal/smsc outside of btl/sm, to enable its use without it
  ompi/instance/instance.c
  opal/mca/btl/sm/btl_sm_component.c
Labels: Target: main

#10899 ucx/pml: show warning if already unsupported UCX version is used
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: main

#10815 Fix compilation of x86-64-asm atomic backend
  opal/include/opal/sys/x86_64/atomic.h
Labels: Target: main

#10515 Correctly retain the datatypes for topological communicators.
  ompi/mca/coll/base/coll_base_util.c
  ompi/mca/coll/base/coll_base_util.h
  ompi/mpi/c/alltoallw_init.c
  ompi/mpi/c/ialltoallw.c
  ompi/mpi/c/ineighbor_alltoallw.c
  ompi/mpi/c/neighbor_alltoallw_init.c
Labels: bug, Target: main

#10913 [v5.0.x] Fix compilation of x86-64-asm based atomic backend
  opal/include/opal/sys/x86_64/atomic.h
Labels: Target: v5.0.x

#10918 Updates to mailmap file
  .mailmap
Labels: Target: main

#10915 docs: add documentation on ROCm devices
  docs/Makefile.am
  docs/networking/ib-and-roce.rst
  docs/networking/index.rst
  docs/networking/rocm.rst
Labels: Target: main

#10916 docs: Minor updates to MPIX man pages
  docs/features/extensions.rst
  docs/man-openmpi/man3/MPIX_Query_cuda_support.3.rst
  docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
Labels: documentation, Target: main

#10921 v5.0.x: Fix mailmap file
  .mailmap
Labels: documentation, Target: v5.0.x

#10919 v5.0.x: ucx/pml: show warning if already unsupported UCX version is used
  config/ompi_check_ucx.m4
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v5.0.x

#10925 v5.0.x: docs: Minor updates to MPIX man pages
  docs/features/extensions.rst
  docs/man-openmpi/man3/MPIX_Query_cuda_support.3.rst
  docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
Labels: documentation, Target: v5.0.x

#10912 v5.0.x: Initialize opal/smsc outside of btl/sm, to enable its use without it
  ompi/instance/instance.c
  opal/mca/btl/sm/btl_sm_component.c
Labels: Target: v5.0.x

#10917 Fix 1 byte overlay in comm_method_string: Coverity CID 1515829
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
Labels: Target: main

#10930 opal/event: use epoll by default on Linux
  opal/util/event.c
Labels: bug, Target: main

#10933 pack external32 long double conversion (extended 80 / quad 128)
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/util/arch.h
Labels: Target: v5.0.x

#10924 v5.0.x: docs: add documentation on ROCm devices
  docs/Makefile.am
  docs/networking/ib-and-roce.rst
  docs/networking/index.rst
  docs/networking/rocm.rst
Labels: Target: v5.0.x

#10932 v5.0.x: opal/event: use epoll by default on Linux
  opal/util/event.c
Labels: Target: v5.0.x

#10937 sessions: fix comm cleanup during mpi_finalize
  ompi/communicator/comm_init.c
Labels: Target: main

#10945 v5.0.x: Fix resource leak reported by coverity scan report CID 1515816
  ompi/communicator/comm.c
Labels: Target: v5.0.x, memory leak

#10832 Update MCA mutexes to use the qthreads ULT backend
  opal/mca/threads/argobots/threads_argobots_mutex.h
  opal/mca/threads/base/help-opal-threads.txt
  opal/mca/threads/pthreads/threads_pthreads_mutex.h
  opal/mca/threads/qthreads/threads_qthreads_mutex.h
Labels: Target: main

#10946 Update MCA mutexes to use the qthreads ULT backend
  opal/mca/threads/argobots/threads_argobots_mutex.h
  opal/mca/threads/base/help-opal-threads.txt
  opal/mca/threads/pthreads/threads_pthreads_mutex.h
  opal/mca/threads/qthreads/threads_qthreads_mutex.h
Labels: Target: v5.0.x

#10948 opal_check_cuda.m4: Add AC_ARG_WITH for libdir option
  config/opal_check_cuda.m4
Labels: Target: main

#10951 opal_check_cuda.m4: Add AC_ARG_WITH for libdir option
  config/opal_check_cuda.m4
Labels: Target: v5.0.x

#10950 pml/ob1: Fix typo succedded
  ompi/mca/pml/ob1/pml_ob1_progress.c
Labels: Target: main

#10953 config: add accelerator summary to configure output
  config/opal_check_cuda.m4
  opal/mca/accelerator/rocm/configure.m4
Labels: Target: main

#10920 oshmem: Fix unsigned type comparisons
  oshmem/mca/spml/base/spml_base.c
  oshmem/shmem/c/shmem_wait.c
Labels: Target: main

#10958 Reduce the overhead of UCX add_procs with intercommunicators
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: main

#10936 Part 1 of resolving global symbol name pollution issue #10708
  ompi/mca/coll/libnbc/libdict/dict.c
  ompi/mca/coll/libnbc/libdict/dict.h
  ompi/mca/coll/libnbc/libdict/hb_tree.c
  ompi/mca/coll/libnbc/libdict/hb_tree.h
  opal/mca/smsc/base/base.h
  opal/mca/smsc/base/smsc_base_frame.c
Labels: Target: v5.0.x

#10957 config: add accelerator summary to configure output
  config/opal_check_cuda.m4
  opal/mca/accelerator/rocm/configure.m4
Labels: Target: v5.0.x

#10967 Update news in preparation for v5.0.0rc9.
  docs/news/news-v5.0.x.rst
Labels: Target: main

#10968 v5.0.xrc9 prep work
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10960 Reduce the overhead of UCX add_procs with intercommunicators
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v5.0.x

#10935 Fix memory leak in ompi_report_comm_methods by removing redundant malloc, Coverity CID 1515837
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
Labels: Target: main

#10970 dist: Prep for 4.1.5rc1 release
  NEWS
  VERSION
Labels: Target: v4.1.x

#10979 Fix memory leak in ompi_report_comm_methods by removing redundant malloc, fixes Coverity CID 1515837
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
Labels: Target: v5.0.x

#10863 Part 3 of resolving global symbol name pollution #10708 - treematch
  3rd-party/treematch/IntConstantInitializedVector.c
  3rd-party/treematch/IntConstantInitializedVector.h
  3rd-party/treematch/PriorityQueue.c
  3rd-party/treematch/fibo.c
  3rd-party/treematch/fibo.h
  3rd-party/treematch/k-partitioning.c
  3rd-party/treematch/k-partitioning.h
  3rd-party/treematch/tm_bucket.c
  3rd-party/treematch/tm_bucket.h
  3rd-party/treematch/tm_kpartitioning.c
  3rd-party/treematch/tm_kpartitioning.h
  3rd-party/treematch/tm_malloc.c
  3rd-party/treematch/tm_malloc.h
  3rd-party/treematch/tm_mapping.c
  3rd-party/treematch/tm_mapping.h
  3rd-party/treematch/tm_mt.c
  3rd-party/treematch/tm_mt.h
  3rd-party/treematch/tm_solution.c
  3rd-party/treematch/tm_solution.h
  3rd-party/treematch/tm_thread_pool.c
  3rd-party/treematch/tm_thread_pool.h
  3rd-party/treematch/tm_timings.c
  3rd-party/treematch/tm_timings.h
  3rd-party/treematch/tm_topology.c
  3rd-party/treematch/tm_topology.h
  3rd-party/treematch/tm_tree.c
  3rd-party/treematch/tm_tree.h
  3rd-party/treematch/tm_verbose.h
  3rd-party/treematch/treematch.h
  ompi/include/ompi_config.h
Labels: Target: main

#10828 Coll/han Improvements on algorithm selection through MCA and configuration file
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_algorithms.c
  ompi/mca/coll/han/coll_han_algorithms.h
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_dynamic_file.c
Labels: Target: main

#10964 Fix potential oob read in mca_coll_han_query_module_from_mca
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: main

#10982 Fix potential oob read in mca_coll_han_query_module_from_mca [5.0.x]
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: v5.0.x

#10981 Part 3 of resolving global symbol name pollution #10708 for V5.0.x
  3rd-party/treematch/IntConstantInitializedVector.c
  3rd-party/treematch/IntConstantInitializedVector.h
  3rd-party/treematch/PriorityQueue.c
  3rd-party/treematch/fibo.c
  3rd-party/treematch/fibo.h
  3rd-party/treematch/k-partitioning.c
  3rd-party/treematch/k-partitioning.h
  3rd-party/treematch/tm_bucket.c
  3rd-party/treematch/tm_bucket.h
  3rd-party/treematch/tm_kpartitioning.c
  3rd-party/treematch/tm_kpartitioning.h
  3rd-party/treematch/tm_malloc.c
  3rd-party/treematch/tm_malloc.h
  3rd-party/treematch/tm_mapping.c
  3rd-party/treematch/tm_mapping.h
  3rd-party/treematch/tm_mt.c
  3rd-party/treematch/tm_mt.h
  3rd-party/treematch/tm_solution.c
  3rd-party/treematch/tm_solution.h
  3rd-party/treematch/tm_thread_pool.c
  3rd-party/treematch/tm_thread_pool.h
  3rd-party/treematch/tm_timings.c
  3rd-party/treematch/tm_timings.h
  3rd-party/treematch/tm_topology.c
  3rd-party/treematch/tm_topology.h
  3rd-party/treematch/tm_tree.c
  3rd-party/treematch/tm_tree.h
  3rd-party/treematch/tm_verbose.h
  3rd-party/treematch/treematch.h
  ompi/include/ompi_config.h
Labels: Target: v5.0.x

#10983 Properly free variables in coll_han_dynamic_file
  ompi/mca/coll/han/coll_han_dynamic_file.c
Labels: Target: main

#10976 sharedfp/sm: convert output to use verbosity levels
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile.c
  ompi/mca/sharedfp/sm/sharedfp_sm.c
Labels: Target: main

#10987 Fix possible memory leak in ompi_dpm_dyn_finalize
  ompi/dpm/dpm.c
Labels: Target: main

#10977 coll/basic: Fix clang warnings
  ompi/mca/coll/basic/coll_basic_reduce.c
  ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
  ompi/mca/coll/basic/coll_basic_scatterv.c
Labels: code cleanup, Target: main

#10993 btl/ofi: fix an uninitialized variable
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: main

#10985 Fix multiple potential memory leaks in mca_topo_base_cart_allocate
  ompi/mca/topo/base/topo_base_cart_create.c
Labels: Target: main

#10984 Fix potential memory leak in opal/mca/base/mca_base_var_enum.c
  opal/mca/base/mca_base_var_enum.c
Labels: Target: main

#10989 sharedfp/sm: convert output to use verbosity levels
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile.c
  ompi/mca/sharedfp/sm/sharedfp_sm.c
Labels: Target: v5.0.x

#10992 Fix access after free in han dynamic rules parser (CID 1516459)
  ompi/mca/coll/han/coll_han_dynamic_file.c
Labels: Target: main

#10942 Fix resource leak reported by coverity scan report CID 1515756
  ompi/tools/mpirun/main.c
Labels: Target: main, memory leak
