Repository open-mpi/ompi, pull requests merged in 2022-11, with the labels that each got.

#11003 v5: doc/mpirun: Fixup the rankfile documentation
  config/opal_setup_sphinx.m4
  docs/man-openmpi/man1/mpirun.1.rst
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11002 btl/ofi: fix an uninitialized variable
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: v5.0.x

#11006 docs: trivial typo fix
  docs/index.rst
Labels: documentation, Target: main

#10994 mpi4: fix init check for a few more functions
  ompi/mpi/c/errhandler_c2f.c
  ompi/mpi/c/errhandler_free.c
  ompi/mpi/c/session_call_errhandler.c
Labels: Target: main, MPI-4.0

#10975 ofi/common: release opal memory base framework
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#10990 sharedfp/sm: convert output to use verbosity levels
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile.c
  ompi/mca/sharedfp/sm/sharedfp_sm.c
Labels: Target: v4.1.x

#10961 Reduce the overhead of UCX add_procs with intercommunicators
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v4.1.x

#11000 lanl-ci: sync v5.0.x yml file with main
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: v5.0.x

#11014 v5.0.x: docs: trivial typo fix
  docs/index.rst
Labels: documentation, Target: v5.0.x

#11013 v4.1.x: docs: trivial typo fix
  docs/index.rst
Labels: documentation, RM approved, Target: v4.1.x

#11016 opal_setup_sphinx.m4: make version check better
  config/opal_setup_sphinx.m4
Labels: Target: main

#11004 docs: conditionally install wrapper compiler man pages
  autogen.pl
  config/ompi_setup_mpi_fortran.m4
  docs/Makefile.am
Labels: documentation, Target: main

#11012 v4.0.x: docs: trivial typo fix
  docs/index.rst
Labels: documentation, Target: v4.0.x

#11011 mpi4: fix init check for a few more functions
  ompi/mpi/c/errhandler_c2f.c
  ompi/mpi/c/errhandler_free.c
  ompi/mpi/c/session_call_errhandler.c
Labels: Target: v5.0.x

#11009 Fix possible memory leak in ompi_dpm_dyn_finalize
  ompi/dpm/dpm.c
Labels: Target: v5.0.x

#11007 Fix potential memory leak in opal/mca/base/mca_base_var_enum.c for v5.0.x
  opal/mca/base/mca_base_var_enum.c
Labels: Target: v5.0.x

#11008 Fix multiple potential memory leaks in mca_topo_base_cart_allocate for v5.0.x
  ompi/mca/topo/base/topo_base_cart_create.c
Labels: Target: v5.0.x

#11019 v5.0.x: opal_setup_sphinx.m4: make version check better
  config/opal_setup_sphinx.m4
Labels: Target: v5.0.x

#11021 v5.0.x: docs: conditionally install wrapper compiler man pages
  autogen.pl
  config/ompi_setup_mpi_fortran.m4
  docs/Makefile.am
Labels: Target: v5.0.x

#10973 oshmem: Fix unsigned type comparisons
  oshmem/mca/spml/base/spml_base.c
  oshmem/shmem/c/shmem_wait.c
Labels: Target: v5.0.x

#11010 ofi/common: release opal memory base framework
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#10709 OSC/UCX: Adding the following optimizations (nonblocking accumulate and reusing resources)
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  ompi/mca/osc/ucx/osc_ucx_request.c
  ompi/mca/osc/ucx/osc_ucx_request.h
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: main

#11024 Fix potential memory leak in opal_init_gethostname
  opal/runtime/opal_init_core.c
Labels: Target: main

#11025 V5.0.x OSC/UCX: Adding the following optimizations (nonblocking accumulate and reusing resources)
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
  ompi/mca/osc/ucx/osc_ucx_request.c
  ompi/mca/osc/ucx/osc_ucx_request.h
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#11027 v5.0.x: Fix resource leak reported by coverity scan report CID 1515756
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x

#11031 add sha256 generation func to opal util toolbox
  .gitignore
  opal/util/Makefile.am
  opal/util/sha256.c
  opal/util/sha256.h
  test/util/Makefile.am
  test/util/opal_sha256.c
Labels: Target: main

#10972 oshmem: Fix unsigned type comparisons
  oshmem/include/oshmem/constants.h
  oshmem/mca/spml/base/spml_base.c
  oshmem/shmem/c/shmem_wait.c
Labels: RM approved, Target: v4.1.x

#11018 mtl/ofi: Fix FI_HMEM bit check
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: main

#11035 ofi/common: use verbosity level to control
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11039 mtl/ofi: Fix FI_HMEM bit check
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v5.0.x

#11026 doc: Update mpirun map/rank/bind to reflect PRRTE
  docs/man-openmpi/man1/mpirun.1.rst
Labels: Target: main

#11041 v5.0: Fix potential memory leak in opal_init_gethostname
  opal/runtime/opal_init_core.c
Labels: Target: v5.0.x

#11037 ofi/common: close memory base in an error path
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11033 OSC/UCX: Fix coverity issues
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: main

#10127 smsc/xpmem: alignment and stack memory space
  opal/mca/smsc/xpmem/smsc_xpmem_module.c
Labels: Target: main

#11049 docs: fix typo
  docs/developers/sphinx.rst
Labels: documentation, Target: main

#11051 v5.0.x: docs: fix typo
  docs/developers/sphinx.rst
Labels: documentation, Target: v5.0.x

#11044 v5.0.x: doc: Update mpirun map/rank/bind to reflect PRRTE
  docs/man-openmpi/man1/mpirun.1.rst
Labels: documentation, Target: v5.0.x

#11061 opal/list: Fix the bug in function opal_list_insert
  contrib/check_unnecessary_headers.sh
  opal/class/opal_list.c
  opal/class/opal_list.h
  test/class/opal_list.c
Labels: Target: main

#11045 MCA/PML/UCX: Enabled multi_send_nb option by default.
  ompi/mca/pml/ucx/pml_ucx_component.c
Labels: Target: main

#11054 v5.0.x OSC/UCX: Fix coverity issues and missing extend var in nb acc
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#11060 A variety of CID fixes
  ompi/instance/instance.c
  ompi/mca/coll/base/coll_base_allreduce.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
  opal/mca/base/mca_base_component_repository.c
  opal/mca/mpool/hugepage/mpool_hugepage_component.c
  opal/util/ethtool.c
Labels: bug, Target: main

#11040 Update Open MPI FAQ debugging page to describe MPIR shim usage
  docs/faq/debugging.rst
Labels: Target: main

#11075 mtl: Fix datatype offsetting
  ompi/mca/mtl/base/mtl_base_datatype.h
  ompi/mca/pml/cm/pml_cm.h
Labels: Target: main

#11036 singleton: reduce chattiness under slurm
  ompi/runtime/help-mpi-runtime.txt
  ompi/runtime/ompi_rte.c
Labels: Target: main

#11076 OFI/MTL: bypass HMEM mem reg for CXI provider
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: main

#11083 build: fix bashisms in configure
  ompi/mca/op/avx/configure.m4
  opal/mca/memory/patcher/configure.m4
Labels: Target: main

#11017 MPI_Comm_create_from_group: fix help message
  ompi/communicator/comm_cid.c
Labels: Target: main

#11080 test/datatype/partial.c: fix compiler warnings
  test/datatype/partial.c
Labels: Target: main

#11094 oshmem: Fix segment reset
  oshmem/mca/sshmem/base/sshmem_base_wrappers.c
Labels: bug, Target: main

#11043 Coll han update file reading 5.0.x
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_algorithms.c
  ompi/mca/coll/han/coll_han_algorithms.h
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_dynamic.h
  ompi/mca/coll/han/coll_han_dynamic_file.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: v5.0.x

#11069 v5.0.x: Coverity fixes
  ompi/instance/instance.c
  ompi/mca/coll/base/coll_base_allreduce.c
  ompi/mca/coll/base/coll_base_reduce.c
  ompi/mca/coll/basic/coll_basic_reduce_scatter_block.c
  opal/mca/base/mca_base_component_repository.c
  opal/mca/mpool/hugepage/mpool_hugepage_component.c
  opal/util/ethtool.c
Labels: bug, Target: v5.0.x

#11072 Remove function opal_list_insert()
  contrib/check_unnecessary_headers.sh
  opal/class/opal_list.c
  opal/class/opal_list.h
  test/class/opal_list.c
Labels: code cleanup, Target: v5.0.x

#11078 mtl: Fix datatype offsetting
  ompi/mca/mtl/base/mtl_base_datatype.h
  ompi/mca/pml/cm/pml_cm.h
Labels: bug, Target: v5.0.x

#11074 MCA/PML/UCX: Enabled multi_send_nb option by default.
  ompi/mca/pml/ucx/pml_ucx_component.c
Labels: Target: v5.0.x

#11085 singleton: add field to opal_process_info
  ompi/dpm/dpm.c
  ompi/instance/instance.c
  ompi/interlib/interlib.c
  ompi/runtime/ompi_mpi_finalize.c
  ompi/runtime/ompi_mpi_init.c
  ompi/runtime/ompi_rte.c
  ompi/runtime/ompi_rte.h
  opal/util/proc.c
  opal/util/proc.h
Labels: Target: v5.0.x

#11092 docs: update "Getting help"
  docs/getting-help.rst
Labels: documentation, Target: main

#11102 Better ofi common quiet
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11110 OSC/UCX: Properly releasing the resources and adding some debug info
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: main

#11095 osc/ucx: Fix bugs with dynamic windows
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: main

#11111 mtl/ofi: require libfabric 1.9 or higher
  ompi/mca/mtl/ofi/configure.m4
Labels: Target: main

#11109 Fix undefined file offset in mca_io_ompio_file_seek.
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: Target: main

#11103 Fix divide by zero error in calculate_num_nodes_up_to_level using MPI_Bcast with 2 tasks
  ompi/mca/coll/adapt/coll_adapt_topocache.c
  ompi/mca/coll/base/coll_base_topo.c
Labels: Target: main

#11073 MCA/PML/UCX: Enabled multi_send_nb option by default.
  ompi/mca/pml/ucx/pml_ucx_component.c
Labels: RM approved, Target: v4.1.x

#11081 config/opal_check_os_flavors.m4: fix -Wimplicit-int in OPAL_CHECK_OS_...
  config/opal_check_os_flavors.m4
Labels: Target: main

#11121 v5.0.x OSC/UCX: Properly releasing the resources and adding some debug info
  ompi/mca/osc/ucx/osc_ucx_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x

#11104 v5.0.x: docs: update "Getting help"
  docs/getting-help.rst
Labels: documentation, Target: v5.0.x

#11105 oshmem: Fix segment reset
  oshmem/mca/sshmem/base/sshmem_base_wrappers.c
Labels: bug, Target: v5.0.x

#11113 singleton: reduce chattiness under slurm
  ompi/runtime/help-mpi-runtime.txt
  ompi/runtime/ompi_rte.c
Labels: Target: v5.0.x

#11117 MPI_Comm_create_from_group: fix help message
  ompi/communicator/comm_cid.c
Labels: Target: v5.0.x

#11119 Fix undefined file offset in mca_io_ompio_file_seek.
  ompi/mca/io/ompio/io_ompio_file_open.c
Labels: Target: v5.0.x

#11120 Fix divide by zero error in calculate_num_nodes_up_to_level using MPI_Bcast with 2 tasks
  ompi/mca/coll/adapt/coll_adapt_topocache.c
  ompi/mca/coll/base/coll_base_topo.c
Labels: Target: v5.0.x

#11115 v5.0.x: Fix bugs with dynamic windows
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: bug, Target: v5.0.x

#11082 Move debugging section of OpenMPI faq to new section in user documentation
  docs/Makefile.am
  docs/app-debug/debug-options.rst
  docs/app-debug/debug-tools.rst
  docs/app-debug/index.rst
  docs/app-debug/lost-output.rst
  docs/app-debug/memchecker.rst
  docs/app-debug/mpir-tools.rst
  docs/app-debug/serial-debug.rst
  docs/app-debug/valgrind.rst
  docs/faq/debugging.rst
  docs/faq/index.rst
  docs/index.rst
Labels: Target: main

#11124 v5.0.x OSC/UCX: NB Accumulate with DT and fix for issue/11114
  ompi/mca/osc/ucx/osc_ucx_comm.c
  opal/mca/common/ucx/common_ucx_wpool.h
Labels: Target: v5.0.x
