Repository open-mpi/ompi, pull requests merged in 2022-03, with the labels that each got.

#10054 v5.0.x: remove libompitrace
  autogen.pl
  config/ompi_contrib.m4
  config/ompi_setup_contrib.m4
  configure.ac
  ompi/Makefile.am
  ompi/contrib/README.md
  ompi/contrib/libompitrace/Makefile.am
  ompi/contrib/libompitrace/abort.c
  ompi/contrib/libompitrace/accumulate.c
  ompi/contrib/libompitrace/add_error_class.c
  ompi/contrib/libompitrace/add_error_code.c
  ompi/contrib/libompitrace/add_error_string.c
  ompi/contrib/libompitrace/allgather.c
  ompi/contrib/libompitrace/allgatherv.c
  ompi/contrib/libompitrace/alloc_mem.c
  ompi/contrib/libompitrace/allreduce.c
  ompi/contrib/libompitrace/barrier.c
  ompi/contrib/libompitrace/bcast.c
  ompi/contrib/libompitrace/configure.m4
  ompi/contrib/libompitrace/finalize.c
  ompi/contrib/libompitrace/get_address.c
  ompi/contrib/libompitrace/init.c
  ompi/contrib/libompitrace/isend.c
  ompi/contrib/libompitrace/recv.c
  ompi/contrib/libompitrace/reduce.c
  ompi/contrib/libompitrace/request_free.c
  ompi/contrib/libompitrace/send.c
  ompi/contrib/libompitrace/sendrecv.c
Labels: Target: v5.0.x

#10055 v5.0.x: opal_case_sensitive_fs_setup.m4: remove warning
  config/opal_case_sensitive_fs_setup.m4
Labels: Target: v5.0.x

#10046 v5.0.x: Fix leak of sm_segment files in /dev/shm.
  opal/mca/pmix/base/pmix_base_fns.c
Labels: Target: v5.0.x

#10064 Eliminate OPAL_FLAGS_UNIQ
  config/ompi_fortran_check_real16_c_equiv.m4
  config/opal_check_cflags.m4
  config/opal_functions.m4
  config/opal_setup_cc.m4
Labels: bug

#10037 Fix a performance regression in datatype pack/unpack
  opal/datatype/opal_datatype_pack_unpack_predefined.h
Labels: Target: master

#10034 v5.0.x: OSC backports
  .gitignore
  ompi/mca/osc/base/osc_base_init.c
  ompi/mca/osc/monitoring/osc_monitoring_component.c
  ompi/mca/osc/rdma/Makefile.am
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_active_target.c
  ompi/mca/osc/rdma/osc_rdma_btl_comm.c
  ompi/mca/osc/rdma/osc_rdma_btl_comm.h
  ompi/mca/osc/rdma/osc_rdma_comm.c
  ompi/mca/osc/rdma/osc_rdma_comm.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  ompi/mca/osc/rdma/osc_rdma_lock.h
  ompi/mca/osc/rdma/osc_rdma_module.c
  ompi/mca/osc/rdma/osc_rdma_peer.c
  ompi/mca/osc/sm/osc_sm.h
  ompi/mca/osc/sm/osc_sm_component.c
  opal/class/opal_cstring.c
  opal/class/opal_cstring.h
  opal/mca/btl/base/btl_base_am_rdma.c
  test/class/Makefile.am
  test/class/opal_cstring.c
Labels: bug, Target: v5.0.x

#10072 Fix alltoallv with inplace - v5.0.x
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: Target: v5.0.x

#10078 v4.1.x: coll/libnbc: correctly handle MPI_BOTTOM
  ompi/mca/coll/libnbc/nbc_internal.h
Labels: Target: v4.1.x

#10008 Pr/lockedfile fixes v4.0
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Labels: bug

#10077 v5.0.x: Adding progress call in Parrived and moved a intialization flag assig…
  ompi/mca/part/persist/part_persist.h
Labels: Target: v5.0.x

#10081 v5.0.x: NEWS: Update in preparation for v5.0.0rc3.
  NEWS
Labels: Target: v5.0.x

#9843 Fix issues with mpi_assert_allow_overtaking
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1_isend.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.h
Labels: Target: master

#9820 Fix issues turned up by opal_show_help() audit
  contrib/check-help-strings.pl
  ompi/dpm/dpm.c
  ompi/dpm/help-dpm.txt
  ompi/errhandler/errhandler_predefined.c
  ompi/mca/mtl/psm2/help-mtl-psm2.txt
  ompi/mpi/help-mpi-api.txt
  ompi/runtime/help-mpi-runtime.txt
  opal/mca/btl/sm/Makefile.am
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/help-btl-sm.txt
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/tcp/help-mpi-btl-tcp.txt
  opal/mca/btl/usnic/help-mpi-btl-usnic.txt
  opal/mca/common/sm/help-mpi-common-sm.txt
  opal/mca/pmix/base/Makefile.am
  opal/mca/pmix/base/help-pmix-base.txt
  opal/mca/pmix/base/pmix_base_fns.c
  opal/mca/smsc/knem/help-smsc-knem.txt
  opal/tools/wrappers/help-opal-wrapper.txt
  test/simple/hello_show_help.c
Labels: documentation, Target: master

#10087 docs: continued updates to docs content
  docs/developers/rst-for-markdown-expats.rst
  docs/to-do.rst
Labels: documentation, Target: v5.0.x

#10102 v5.0.x: Define the object class for the isendrecv request once.
  ompi/mpi/c/isendrecv.c
  ompi/mpi/c/isendrecv_replace.c
Labels: bug, Severity: blocker, Target: v5.0.x

#10104 v4.1.x: NEWS and VERSION updates for v4.1.3
  NEWS
  VERSION
Labels: documentation, Target: v4.1.x

#10101 v5.0.x: Fix issues turned up by opal_show_help() audit
  contrib/check-help-strings.pl
  ompi/dpm/dpm.c
  ompi/dpm/help-dpm.txt
  ompi/errhandler/errhandler_predefined.c
  ompi/mca/mtl/psm2/help-mtl-psm2.txt
  ompi/mpi/help-mpi-api.txt
  ompi/runtime/help-mpi-runtime.txt
  opal/mca/btl/sm/Makefile.am
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/help-btl-sm.txt
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/tcp/help-mpi-btl-tcp.txt
  opal/mca/btl/usnic/help-mpi-btl-usnic.txt
  opal/mca/common/sm/help-mpi-common-sm.txt
  opal/mca/pmix/base/Makefile.am
  opal/mca/pmix/base/help-pmix-base.txt
  opal/mca/pmix/base/pmix_base_fns.c
  opal/mca/smsc/knem/help-smsc-knem.txt
  opal/tools/wrappers/help-opal-wrapper.txt
  test/simple/hello_show_help.c
Labels: Target: v5.0.x

#10108 Various RST docs updates.
  docs/developers/rst-for-markdown-expats.rst
  docs/developers/sphinx.rst
  docs/news/news-v4.1.x.rst
Labels: documentation

#10105 common/ucx: fix variable registration memory leak and cleanup
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: bug, Target: master

#10107 reachable/netlink: Fix flags exporting
  opal/mca/reachable/netlink/Makefile.am
  opal/mca/reachable/netlink/configure.m4
Labels: bug, Target: master

#10112 v4.1.x: Add skeleton ReadTheDocs docs for the v4.1.x branch
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/openmpi_logo.png
Labels: documentation, Target: v4.1.x

#10113 v4.0.x: Add skeleton ReadTheDocs docs for the v4.0.x branch
  .gitignore
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/openmpi_logo.png
Labels: documentation, Target: v4.0.x

#10094 v4.1.x: libnbc fix for iallreduce count*extent overflowing int
  ompi/mca/coll/libnbc/nbc_iallreduce.c
Labels: bug, RM approved, Target: v4.1.x

#10119 v4.1.x: FORTRAN:add elemental attribute to handle compars
  NEWS
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
Labels: RM approved, NEWS, Target: v4.1.x

#10090 Fix a performance regression in datatype pack/unpack [v5.0.x]
  opal/datatype/opal_datatype_pack_unpack_predefined.h
Labels: Target: v5.0.x

#10092 opal/datatype: Avoid issuing multiple cuda memcpy ops for contig ddt
  opal/datatype/opal_datatype_copy.c
  opal/datatype/opal_datatype_copy.h
Labels: performance, Target: v5.0.x

#10114 Continued docs updates
  .readthedocs.yaml
  docs/Makefile.am
  docs/conf.py
  docs/faq/debugging.rst
  docs/faq/fault-tolerance.rst
  docs/faq/running-mpi-apps.rst
  docs/faq/sysadmin.rst
  docs/features/ulfm.rst
  docs/index.rst
  docs/installing-open-mpi/compilers-and-flags.rst
  docs/installing-open-mpi/configure-cli-options/networking.rst
  docs/man-openmpi/man1/mpisync.1.rst
  docs/man-openmpi/man1/ompi-wrapper-compiler.1.rst
  docs/man-openshmem/man1/oshmem-wrapper-compiler.1.rst
  docs/networking/cuda.rst
  docs/networking/ib-and-roce.rst
  docs/news/news-v1.x.rst
  docs/news/news-v4.1.x.rst
  docs/release-notes/networks.rst
  docs/running-apps/gridengine.rst
Labels: documentation, Target: master

#10130 v4.1.x: reachable/netlink: Fix flags exporting
  opal/mca/reachable/netlink/Makefile.am
  opal/mca/reachable/netlink/configure.m4
Labels: bug, RM approved, Target: v4.1.x

#10129 README.md: fix doc URL
  README.md
Labels: documentation, Target: master

#10123 v5.0.x: FORTRAN: add elemental attribute to comp ops
  config/ompi_fortran_check_elemental.m4
  config/ompi_setup_mpi_fortran.m4
  ompi/mpi/fortran/use-mpi/mpi-types.F90.in
Labels: Target: v5.0.x

#10143 release: Bump version to 3.1.3rc2
  VERSION
Labels: Target: v4.1.x

#10138 v5.0.x: osc/ucx: one sided fixes
  ompi/mca/osc/ucx/osc_ucx_active_target.c
  ompi/mca/osc/ucx/osc_ucx_comm.c
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v5.0.x

#10139 v5.0.x: Two cleanup commits
  contrib/check_unnecessary_headers.sh
  ompi/attribute/attribute.c
  ompi/attribute/attribute.h
  ompi/attribute/attribute_predefined.c
  ompi/mca/coll/hcoll/coll_hcoll_module.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/pml/base/pml_base_select.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mpi/c/comm_create_keyval.c
  ompi/mpi/c/keyval_create.c
  ompi/mpi/c/type_create_keyval.c
  ompi/mpi/c/win_create_keyval.c
Labels: Target: v5.0.x

#10141 v5.0.x: open-mpi side mpirun/mpiexec --version fix
  config/opal_save_version.m4
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x

#10144 v4.1.x: Accept a NULL pointer to descriptor in sendi.
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: RM approved, Target: v4.1.x

#10147 v4.1.x: NEWS: Add smcuda bullet
  NEWS
Labels: documentation, Target: v4.1.x

#10148 Small docs tweaks
  docs/index.rst
  docs/news/news-v4.1.x.rst
Labels: documentation, Target: master

#10145 v4.0.x: Accept a NULL pointer to descriptor in sendi.
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: Target: v4.0.x

#10140 v5.0x: Make abi compatible with 4.1.x
  ompi/datatype/ompi_datatype_args.c
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
Labels: Target: v5.0.x

#10146 v5.0.x: Accept a NULL pointer to descriptor in sendi.
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: Target: v5.0.x

#10089 Fix issues with mpi_assert_allow_overtaking [v5.0.x]
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1_isend.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.h
Labels: Target: v5.0.x

#10128 opal_atomic_rmb: GCC has fixed its acquire fence barrier in its 8 release [v5.0.x]
  opal/include/opal/sys/atomic_stdc.h
Labels: Target: v5.0.x

#10160 Rename relevant "master" references
  .ci/mellanox/azure-pipelines.yml
  README.md
  contrib/annual-maintenance/convert-to-git.txt
  contrib/check-owner.pl
  contrib/clang-format-ompi.sh
  contrib/ompi-time.sh
  docs/developers/gnu-autotools.rst
  docs/features/ulfm.rst
  docs/man-openmpi/man3/MPI_Comm_rank.3.rst
  docs/networking/cuda.rst
  docs/news/index.rst
  docs/news/news-main.rst
  examples/Ring.java
  examples/ring_c.c
  examples/ring_mpifh.f
  examples/ring_usempi.f90
  examples/ring_usempif08.f90
Labels: documentation, Target: main

#10162 v4.1.x: Rename relevant "master" references
  .ci/mellanox/azure-pipelines.yml
  HACKING
  VERSION
  config/ompi_setup_mpi_fortran.m4
  contrib/annual-maintenance/convert-to-git.txt
  contrib/check-owner.pl
  contrib/ompi-time.sh
  examples/Ring.java
  examples/ring_c.c
  examples/ring_cxx.cc
  examples/ring_mpifh.f
  examples/ring_usempi.f90
  examples/ring_usempif08.f90
  ompi/mpi/man/man3/MPI_Comm_rank.3in
  opal/mca/btl/usnic/README.txt
  opal/mca/btl/usnic/btl_usnic_compat.h
  opal/threads/thread_usage.h
Labels: documentation, RM approved, Target: v4.1.x

#10163 v4.0.x: Rename relevant "master" references
  .ci/mellanox/azure-pipelines.yml
  HACKING
  VERSION
  config/ompi_setup_mpi_fortran.m4
  contrib/annual-maintenance/convert-to-git.txt
  contrib/check-owner.pl
  contrib/ompi-time.sh
  examples/Ring.java
  examples/ring_c.c
  examples/ring_cxx.cc
  examples/ring_mpifh.f
  examples/ring_usempi.f90
  examples/ring_usempif08.f90
  ompi/mpi/man/man3/MPI_Comm_rank.3in
  opal/mca/btl/usnic/README.txt
  opal/mca/btl/usnic/btl_usnic_compat.h
  opal/threads/thread_usage.h
Labels: documentation, Target: v4.0.x

#10125 sessions: save a place for the world
  ompi/communicator/comm_init.c
Labels: Target: main

#10176 v4.1.x: Don't overwrite NULL descriptors.
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: RM approved, Target: v4.1.x

#10133 common/ompio: fix a division by zero problem in cost_calc
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: bug

#10178 v5.0.x: Don't overwrite NULL descriptors.
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: Target: v5.0.x

#10180 common/ompio: fix a division by zero problem in cost_calc
  ompi/mca/common/ompio/common_ompio_aggregators.c
Labels: Target: v5.0.x

#10188 release: Bump version to 4.1.3rc3
  VERSION
Labels: RM approved, Target: v4.1.x

#10192 reachable/netlink: Fix missing LDFLAGS
  opal/mca/reachable/netlink/Makefile.am
Labels: bug

#10196 Fix cuda linking issue
  config/opal_config_files.m4
  ompi/mca/coll/cuda/coll_cuda_allreduce.c
  ompi/mca/coll/cuda/coll_cuda_exscan.c
  ompi/mca/coll/cuda/coll_cuda_reduce.c
  ompi/mca/coll/cuda/coll_cuda_reduce_scatter_block.c
  ompi/mca/coll/cuda/coll_cuda_scan.c
  ompi/mca/coll/libnbc/nbc_internal.h
  ompi/mca/common/ompio/common_ompio_buffer.c
  ompi/mca/mtl/base/mtl_base_datatype.h
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/pml/ob1/Makefile.am
  ompi/mca/pml/ob1/pml_ob1_progress.c
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ucx/pml_ucx.c
  opal/Makefile.am
  opal/cuda/Makefile.am
  opal/cuda/README.md
  opal/cuda/common_cuda.c
  opal/cuda/common_cuda.h
  opal/cuda/help-mpi-common-cuda.txt
  opal/cuda/owner.txt
  opal/datatype/opal_convertor.c
  opal/datatype/opal_datatype_copy.c
  opal/datatype/opal_datatype_pack_unpack_predefined.h
  opal/mca/btl/smcuda/Makefile.am
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/mca/btl/smcuda/btl_smcuda_frag.h
  opal/mca/btl/tcp/Makefile.am
  opal/mca/btl/tcp/btl_tcp_component.c
  opal/mca/common/cuda/Makefile.am
  opal/mca/common/cuda/configure.m4
  opal/mca/common/sm/common_sm_mpool.c
  opal/mca/rcache/gpusm/Makefile.am
  opal/mca/rcache/gpusm/rcache_gpusm_module.c
  opal/mca/rcache/grdma/Makefile.am
  opal/mca/rcache/grdma/rcache_grdma_module.c
  opal/mca/rcache/rgpusm/Makefile.am
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
Labels: Target: v5.0.x

#10200 v5.0.x: osc/sm: Fix detection of non-contig info
  ompi/mca/osc/sm/osc_sm_component.c
Labels: Target: v5.0.x

#10189 fs/lustre and fs/pvfs2: fix info names
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/pvfs2/fs_pvfs2_file_open.c
Labels: Target: v5.0.x

#10201 This is bringing back the news from 66ecc05,
  docs/news/index.rst
  docs/news/news-main.rst
  docs/news/news-master.rst
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10202 Topic/v5.0.x/version rc4
  VERSION
Labels: Target: v5.0.x

#10206 v5.0.x: news-main and news-v5.0.x updates.
  docs/news/news-main.rst
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10204 dist: Update VERSION to 4.1.4a1
  NEWS
  VERSION
Labels: Target: v4.1.x
