Repository open-mpi/ompi, pull requests merged in 2022-05, with the labels that each got.

#10344 Attributes: replace custom void* union with C union
  ompi/attribute/attribute.c
Labels: Target: main

#10346 hook/comm_method: Fix segv when not fully conected
  ompi/mca/hook/comm_method/hook_comm_method.h
  ompi/mca/hook/comm_method/hook_comm_method_component.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
Labels: Target: main, Target: v5.0.x

#10351 hook/comm_method: Fix segv when not fully conected
  ompi/mca/hook/comm_method/hook_comm_method.h
  ompi/mca/hook/comm_method/hook_comm_method_component.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
Labels: bug, Target: v5.0.x

#10325 v4.1: Ignore receive buffer at non-root for cuda reduce collective
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: Target: v4.1.x

#10250 Improve support for AMD ROCm GPU devices
  .gitignore
  config/opal_check_rocm.m4
  config/opal_config_files.m4
  configure.ac
  docs/man-openmpi/man3/MPIX_Query_rocm_support.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/mpiext/rocm/Makefile.am
  ompi/mpiext/rocm/c/Makefile.am
  ompi/mpiext/rocm/c/mpiext_rocm.c
  ompi/mpiext/rocm/c/mpiext_rocm_c.h.in
  ompi/mpiext/rocm/configure.m4
  opal/Makefile.am
  opal/datatype/opal_convertor.c
  opal/datatype/opal_convertor.h
  opal/datatype/opal_datatype_copy.c
  opal/datatype/opal_datatype_pack.h
  opal/datatype/opal_datatype_unpack.c
  opal/datatype/opal_datatype_unpack.h
  opal/rocm/Makefile.am
  opal/rocm/common_rocm.c
  opal/rocm/common_rocm.h
  opal/rocm/common_rocm_prototypes.h
  opal/rocm/owner.txt
  opal/runtime/opal_init.c
  opal/runtime/opal_params.c
  opal/runtime/opal_params.h
Labels: Target: main

#10352 common/ompio: increase internal default fview size
  ompi/mca/common/ompio/common_ompio.h
Labels: bug

#10369 v5.0.x: glob.h check fixed, otherwise it always fails
  config/ompi_check_psm2.m4
Labels: Target: v5.0.x

#10326 v4.0: Ignore receive buffer at non-root for cuda reduce collective
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: NEWS, Target: v4.0.x

#10359 sessions: support MPI_TAG_UB
  ompi/attribute/attribute.h
  ompi/attribute/attribute_predefined.c
  ompi/communicator/comm.c
  ompi/communicator/comm_init.c
  ompi/instance/instance.c
Labels: Target: v5.0.x

#10384 v5.0.0rc7 news and version update
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#10393 Fix build failure with unreleased PMIx.
  opal/util/show_help.c
Labels: Target: main

#10387 config: Fix syntax errors in CUDA checks
  config/opal_check_cuda.m4
Labels: NEWS, Target: main

#10394 v5.0.x: Fix build failure with unreleased PMIx.
  opal/util/show_help.c
Labels: Target: v5.0.x

#10379 common/ompio: increase internal default fview size
  ompi/mca/common/ompio/common_ompio.h
Labels: RM approved, Target: v4.1.x

#10367 topo/treematch: Update and sync with fixes from main
  ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
  ompi/mca/topo/treematch/treematch/PriorityQueue.c
  ompi/mca/topo/treematch/treematch/fibo.h
  ompi/mca/topo/treematch/treematch/tm_bucket.c
  ompi/mca/topo/treematch/treematch/tm_kpartitioning.c
  ompi/mca/topo/treematch/treematch/tm_kpartitioning.h
  ompi/mca/topo/treematch/treematch/tm_malloc.c
  ompi/mca/topo/treematch/treematch/tm_mapping.c
  ompi/mca/topo/treematch/treematch/tm_mapping.h
  ompi/mca/topo/treematch/treematch/tm_solution.c
  ompi/mca/topo/treematch/treematch/tm_solution.h
  ompi/mca/topo/treematch/treematch/tm_thread_pool.c
  ompi/mca/topo/treematch/treematch/tm_thread_pool.h
  ompi/mca/topo/treematch/treematch/tm_topology.c
  ompi/mca/topo/treematch/treematch/tm_topology.h
  ompi/mca/topo/treematch/treematch/tm_tree.c
  ompi/mca/topo/treematch/treematch/treematch.h
Labels: bug, Target: v4.1.x

#10365 common/ucx: fix variable registration
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: bug, Target: v4.1.x

#10360 v4.1.x: odls/default: cap the max number of child FDs to close
  orte/mca/odls/default/odls_default.h
  orte/mca/odls/default/odls_default_component.c
  orte/mca/odls/default/odls_default_module.c
Labels: RM approved, Target: v4.1.x

#10396 v5.0.x: ompi/mca/sharedfp/sm: Include missing `sys/stat.h` in `sharedfp_sm.c`
  ompi/mca/sharedfp/sm/sharedfp_sm.c
Labels: Target: v5.0.x

#10246 Miscellaneous cleanups
  config/ompi_configure_options.m4
  config/ompi_setup_prrte.m4
  config/opal_configure_options.m4
  config/oshmem_configure_options.m4
  configure.ac
  ompi/mpi/java/c/mpi_Info.c
Labels: Target: main, Target: v5.0.x

#10399 dist: Prep for v4.1.4rc2
  NEWS
  VERSION
Labels: RM approved, Target: v4.1.x

#10403 v5.0.x: Miscellaneous cleanups
  config/ompi_configure_options.m4
  config/ompi_setup_prrte.m4
  config/opal_configure_options.m4
  config/oshmem_configure_options.m4
  configure.ac
  ompi/mpi/java/c/mpi_Info.c
Labels: Target: v5.0.x

#10292 Correctly pass the process group for creating intra-communicators
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
Labels: bug, Target: main

#10378 libnbc: int overflow "offset = i * count * extent"
  ompi/mca/coll/libnbc/nbc_iallgather.c
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_igather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_alltoall.c
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/mca/coll/libnbc/nbc_iscatter.c
Labels: bug, Target: main

#10406 v5.0.x: configure: do look for sed
  configure.ac
Labels: Target: v5.0.x

#10375 The matching lock should be acquired only once.
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
Labels: bug

#10349 MPI_Info_dup: allocate info through ompi_info_allocate instead of OBJ_NEW
  ompi/mca/io/romio341/src/io_romio341_component.c
  ompi/mca/io/romio341/src/io_romio341_file_open.c
  ompi/mpi/c/info_dup.c
Labels: Target: main

#10350 Don't retain/release the ompi instance for predefined attributes
  ompi/attribute/attribute.c
Labels: Target: main

#10419 Optimize the file descriptor cleanup on OSX
  orte/mca/odls/default/odls_default_module.c
  orte/mca/odls/pspawn/odls_pspawn.c
Labels: enhancement, Target: v4.1.x

#10407 v4.1.x: two cleanups
  configure.ac
  ompi/mpi/java/c/mpi_Info.c
Labels: Target: v4.1.x

#10424 Nbc counts v41x
  ompi/mca/coll/libnbc/nbc_iallgather.c
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_igather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_alltoall.c
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/mca/coll/libnbc/nbc_iscatter.c
Labels: RM approved

#10409 common/ucx: Fix case where variable goes out of scope
  opal/mca/common/ucx/common_ucx.c
Labels: bug, RM approved, Target: v4.1.x

#10427 dist: Update news for 4.1.4 release
  NEWS
Labels: Target: v4.1.x

#10429 Switch from 4.1.4 to 4.1.5
  NEWS
  VERSION
Labels: Target: v4.1.x

#10428 oversubscribe: put back in a bit of code squashed by sessions
  ompi/instance/instance.c
Labels: Target: main, Target: v5.0.x

#10422 v4.0.x: Optimize the file descriptor cleanup on OSX
  orte/mca/odls/default/odls_default_module.c
  orte/mca/odls/pspawn/odls_pspawn.c
Labels: Target: v4.0.x

#10061 Initial fix for partcomm initialization.
  ompi/instance/instance.c
Labels: Target: main, Target: v5.0.x

#10434 oversubscribe: put back in a bit of code squashed by sessions
  ompi/instance/instance.c
Labels: Target: v5.0.x
