Repository open-mpi/ompi, pull requests merged in 2022-02, with the labels that each got.

#9938 v5.0.x: btl: introduce flag MCA_BTL_FLAGS_RDMA_REMOTE_COMPLETION
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/mca/btl/btl.h
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/btl/self/btl_self_component.c
  opal/mca/btl/ugni/btl_ugni_component.c
Labels: Target: v5.0.x

#9916 implement MPI_Comm_idup_with_info
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/comm_idup_with_info.c
  ompi/mpi/c/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/comm_idup_with_info_f.c
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/comm_idup_with_info_f08.F90
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
  ompi/mpi/fortran/use-mpi-tkr/pmpi-f90-interfaces.h
  ompi/mpi/man/man3/MPI_Comm_idup_with_info.3in
  ompi/mpi/man/man3/Makefile.am
Labels: Target: v5.0.x

#9941 v5.0.x: Two updates: 1) better message in msgq, 2) pedantic casting in osc/rdma
  ompi/debuggers/ompi_msgq_dll.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: v5.0.x

#9948 spc: fix up an update for isendrecv, etc.
  ompi/runtime/ompi_spc.c
Labels: Target: v5.0.x

#9949 isendrecv_rplace: fix problem with req status
  ompi/mpi/c/isendrecv_replace.c
Labels: Target: v5.0.x

#9936 v5.0.x: Atomics updates
  config/opal_config_asm.m4
  config/opal_configure_options.m4
  ompi/mca/osc/portals4/osc_portals4_component.c
  ompi/patterns/net/allreduce.c
  opal/include/opal/sys/Makefile.am
  opal/include/opal/sys/architecture.h
  opal/include/opal/sys/arm64/atomic.h
  opal/include/opal/sys/arm64/atomic_llsc.h
  opal/include/opal/sys/arm64/timer.h
  opal/include/opal/sys/arm64/update.sh
  opal/include/opal/sys/atomic.h
  opal/include/opal/sys/atomic_impl.h
  opal/include/opal/sys/atomic_impl_math.h
  opal/include/opal/sys/atomic_impl_minmax_math.h
  opal/include/opal/sys/atomic_impl_ptr_cswap.h
  opal/include/opal/sys/atomic_impl_ptr_llsc.h
  opal/include/opal/sys/atomic_impl_ptr_swap.h
  opal/include/opal/sys/atomic_impl_size_t_math.h
  opal/include/opal/sys/atomic_impl_spinlock.h
  opal/include/opal/sys/atomic_stdc.h
  opal/include/opal/sys/cma.h
  opal/include/opal/sys/gcc_builtin/atomic.h
  opal/include/opal/sys/powerpc/Makefile.am
  opal/include/opal/sys/powerpc/atomic.h
  opal/include/opal/sys/powerpc/atomic_helper.h
  opal/include/opal/sys/powerpc/atomic_llsc.h
  opal/include/opal/sys/powerpc/timer.h
  opal/include/opal/sys/powerpc/update.sh
  opal/include/opal/sys/timer.h
  opal/include/opal/sys/x86_64/atomic.h
  opal/include/opal/sys/x86_64/timer.h
  opal/include/opal/sys/x86_64/update.sh
  opal/include/opal_stdatomic.h
  opal/mca/patcher/base/base.h
  opal/mca/patcher/base/patcher_base_patch.c
  opal/mca/patcher/overwrite/patcher_overwrite_module.c
  opal/mca/patcher/patcher.h
  opal/mca/threads/mutex.h
  opal/mca/timer/linux/timer_linux_component.c
  oshmem/shmem/c/shmem_clear_cache_inv.c
  oshmem/shmem/c/shmem_clear_cache_line_inv.c
  oshmem/shmem/c/shmem_set_cache_inv.c
  oshmem/shmem/c/shmem_set_cache_line_inv.c
  oshmem/shmem/c/shmem_udcflush.c
  oshmem/shmem/c/shmem_udcflush_line.c
  test/asm/atomic_barrier.c
  test/asm/atomic_cmpset.c
Labels: Target: v5.0.x

#9940 v5.0.x: hwloc: enable --enable-plugins when appropriate
  config/opal_config_hwloc.m4
Labels: Target: v5.0.x

#9937 v5.0.x: btl/sm updates
  opal/mca/btl/sm/Makefile.am
  opal/mca/btl/sm/btl_sm.h
  opal/mca/btl/sm/btl_sm_endpoint.h
  opal/mca/btl/sm/btl_sm_get.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/btl_sm_put.c
Labels: Target: v5.0.x

#9960 v5.0.x: Misc build fixes.
  autogen.pl
  config/opal_config_hwloc.m4
  config/opal_config_libevent.m4
  config/opal_config_pmix.m4
Labels: Target: v5.0.x

#9961 v5.0.x: OSC rdma patches
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  opal/mca/btl/base/btl_base_am_rdma.c
  opal/mca/btl/base/btl_base_am_rdma.h
  opal/mca/btl/btl.h
Labels: Target: v5.0.x

#9944 ompio file_read_all: relocate implementation from base to common
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read_all.c
  ompi/mca/fcoll/base/Makefile.am
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic/fcoll_dynamic.h
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_module.c
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c
  ompi/mca/fcoll/vulcan/Makefile.am
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_module.c
Labels: bug

#9866 scoll/ucc: add onesided ucc support
  oshmem/mca/scoll/ucc/scoll_ucc.h
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: enhancement, Target: master

#9790 scoll/ucc: fix long long reduction dtype
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
Labels: Target: master

#9811 README.md: make the heterogeneous support more clear
  README.md
Labels: documentation, Target: master

#9810 v4.1.x: README: update --enable-heterogeneous warning
  README
Labels: documentation, Target: v4.1.x

#9973 ompi_mpi_init: fix some error handling code paths
  ompi/runtime/ompi_mpi_init.c
Labels: Target: master

#9971 v5.0.x: external prrte: Compile mpirun with PRTE_PATH to find prterun.
  config/ompi_setup_prrte.m4
  ompi/tools/mpirun/main.c
Labels: Target: v5.0.x

#9970 v4.1.x: README: make the heterogeneous support more clear
  README
Labels: documentation, RM approved, Target: v4.1.x

#9969 v4.0.x: README: make the heterogeneous support more clear
  README
Labels: documentation, Target: v4.0.x

#9966 v5.0.x: scoll/ucc: fix long reduction dtype
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
Labels: Target: v5.0.x

#9967 v5.0.x: scoll/ucc: add onesided ucc support
  oshmem/mca/scoll/ucc/scoll_ucc.h
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_barrier.c
  oshmem/mca/scoll/ucc/scoll_ucc_broadcast.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_reduce.c
Labels: Target: v5.0.x

#9968 v5.0.x: README.md: make the heterogeneous support more clear
  README.md
Labels: documentation, Target: v5.0.x

#9977 Fix intercommunicator overflow with big payload collectives
  ompi/mca/coll/inter/coll_inter_allgather.c
  ompi/mca/coll/inter/coll_inter_allgatherv.c
  ompi/mca/coll/inter/coll_inter_gather.c
  ompi/mca/coll/inter/coll_inter_gatherv.c
  ompi/mca/coll/inter/coll_inter_scatter.c
  ompi/mca/coll/inter/coll_inter_scatterv.c
Labels: Target: v5.0.x

#9981 master: Portals4: replace comm->c_contextid use with ompi_comm_get_local_cid()
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/mtl/portals4/mtl_portals4_flowctl.h
  ompi/mca/mtl/portals4/mtl_portals4_probe.c
  ompi/mca/mtl/portals4/mtl_portals4_recv.c
  ompi/mca/mtl/portals4/mtl_portals4_send.c
  ompi/mca/osc/portals4/osc_portals4_component.c
Labels: bug, Target: master

#10000 Pr/lockedfile fixes v5.0
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Labels: bug

#9999 ompio file_read_all: relocate implementation from base to common
  ompi/mca/common/ompio/Makefile.am
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read_all.c
  ompi/mca/fcoll/base/Makefile.am
  ompi/mca/fcoll/dynamic/Makefile.am
  ompi/mca/fcoll/dynamic/fcoll_dynamic.h
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_read_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_file_write_all.c
  ompi/mca/fcoll/dynamic/fcoll_dynamic_module.c
  ompi/mca/fcoll/dynamic_gen2/Makefile.am
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2.h
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_read_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_file_write_all.c
  ompi/mca/fcoll/dynamic_gen2/fcoll_dynamic_gen2_module.c
  ompi/mca/fcoll/vulcan/Makefile.am
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_module.c
Labels: bug

#9979 Fix intercommunicator overflow with big payload collectives
  ompi/mca/coll/inter/coll_inter_allgather.c
  ompi/mca/coll/inter/coll_inter_allgatherv.c
  ompi/mca/coll/inter/coll_inter_gather.c
  ompi/mca/coll/inter/coll_inter_gatherv.c
  ompi/mca/coll/inter/coll_inter_scatter.c
  ompi/mca/coll/inter/coll_inter_scatterv.c
Labels: Target: v4.0.x

#9990 Define the object class for the isendrecv request once.
  ompi/mpi/c/isendrecv.c
  ompi/mpi/c/isendrecv_replace.c
Labels: bug

#10007 MPI_Type_get_envelope.3in: update for MPI-3.0
  ompi/mpi/man/man3/MPI_Type_get_envelope.3in
Labels: documentation, Target: master

#9956 Fix base reduce_scatter_block for large payloads
  ompi/mca/coll/base/coll_base_reduce_scatter_block.c
Labels: bug, Target: master

#9975 osc/rdma: Handle remote completion behavior
  ompi/mca/osc/rdma/Makefile.am
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_active_target.c
  ompi/mca/osc/rdma/osc_rdma_btl_comm.c
  ompi/mca/osc/rdma/osc_rdma_btl_comm.h
  ompi/mca/osc/rdma/osc_rdma_comm.c
  ompi/mca/osc/rdma/osc_rdma_comm.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  ompi/mca/osc/rdma/osc_rdma_lock.h
  ompi/mca/osc/rdma/osc_rdma_module.c
  ompi/mca/osc/rdma/osc_rdma_peer.c
  opal/mca/btl/base/btl_base_am_rdma.c
Labels: bug, Target: master

#10010 OPAL/COMMON/UCX: enable OPAL memory hooks by default - v5.0
  contrib/platform/mellanox/optimized.conf
  opal/mca/common/ucx/common_ucx.c
Labels: Target: v5.0.x

#10012 Fix base reduce_scatter_block for large payloads
  ompi/mca/coll/base/coll_base_reduce_scatter_block.c
Labels: Target: v5.0.x

#10019 More warning fixes
  ompi/communicator/comm.c
  ompi/communicator/ft/comm_ft.c
  ompi/communicator/ft/comm_ft_reliable_bcast.c
  ompi/datatype/ompi_datatype_module.c
  ompi/instance/instance.c
  ompi/mca/osc/sm/osc_sm_component.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_seek.c
Labels: Target: master

#10021 git-commit-checks: handle empty PR body
  .github/workflows/git-commit-checks.py
Labels: Target: master

#10023 v4.1.x: git-commit-checks: handle empty PR body
  .github/workflows/git-commit-checks.py
Labels: RM approved, Target: v4.1.x

#10035 libompitrace: handle MPI_DATATYPE_NULL
  ompi/contrib/libompitrace/allgather.c
  ompi/contrib/libompitrace/allgatherv.c
  ompi/contrib/libompitrace/allreduce.c
  ompi/contrib/libompitrace/bcast.c
  ompi/contrib/libompitrace/isend.c
  ompi/contrib/libompitrace/recv.c
  ompi/contrib/libompitrace/reduce.c
  ompi/contrib/libompitrace/send.c
  ompi/contrib/libompitrace/sendrecv.c
Labels: Target: master

#10014 Fix base reduce_scatter_block for large payloads
  ompi/mca/coll/base/coll_base_reduce_scatter_block.c
Labels: Target: v4.0.x

#10024 v4.0.x: git-commit-checks: handle empty PR body
  .github/workflows/git-commit-checks.py
Labels: Target: v4.0.x

#10051 ompi/contrib: remove libompitrace
  autogen.pl
  config/ompi_contrib.m4
  config/ompi_setup_contrib.m4
  configure.ac
  ompi/Makefile.am
  ompi/contrib/README.md
  ompi/contrib/libompitrace/Makefile.am
  ompi/contrib/libompitrace/abort.c
  ompi/contrib/libompitrace/accumulate.c
  ompi/contrib/libompitrace/add_error_class.c
  ompi/contrib/libompitrace/add_error_code.c
  ompi/contrib/libompitrace/add_error_string.c
  ompi/contrib/libompitrace/allgather.c
  ompi/contrib/libompitrace/allgatherv.c
  ompi/contrib/libompitrace/alloc_mem.c
  ompi/contrib/libompitrace/allreduce.c
  ompi/contrib/libompitrace/barrier.c
  ompi/contrib/libompitrace/bcast.c
  ompi/contrib/libompitrace/configure.m4
  ompi/contrib/libompitrace/finalize.c
  ompi/contrib/libompitrace/get_address.c
  ompi/contrib/libompitrace/init.c
  ompi/contrib/libompitrace/isend.c
  ompi/contrib/libompitrace/recv.c
  ompi/contrib/libompitrace/reduce.c
  ompi/contrib/libompitrace/request_free.c
  ompi/contrib/libompitrace/send.c
  ompi/contrib/libompitrace/sendrecv.c
Labels: Target: master

#10052 opal_case_sensitive_fs_setup.m4: remove warning
  config/opal_case_sensitive_fs_setup.m4
Labels: Target: master

#10006 Pr/lockedfile fixes v4.1
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_file_open.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_request_position.c
Labels: bug, Target: v4.1.x

#10009 v4.1.x/UCX/PML/SPML/OSC: fix compiler warnings
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_request.h
  opal/mca/btl/uct/btl_uct_component.c
  opal/mca/common/ucx/common_ucx.c
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
  oshmem/mca/atomic/ucx/atomic_ucx_module.c
  oshmem/mca/memheap/base/base.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: Target: v4.1.x

#10038 v4.0.x: libompitrace: handle MPI_DATATYPE_NULL
  ompi/contrib/libompitrace/allgather.c
  ompi/contrib/libompitrace/allgatherv.c
  ompi/contrib/libompitrace/allreduce.c
  ompi/contrib/libompitrace/bcast.c
  ompi/contrib/libompitrace/isend.c
  ompi/contrib/libompitrace/recv.c
  ompi/contrib/libompitrace/reduce.c
  ompi/contrib/libompitrace/send.c
  ompi/contrib/libompitrace/sendrecv.c
Labels: Target: v4.0.x

#10039 v4.1.x: libompitrace: handle MPI_DATATYPE_NULL
  ompi/contrib/libompitrace/allgather.c
  ompi/contrib/libompitrace/allgatherv.c
  ompi/contrib/libompitrace/allreduce.c
  ompi/contrib/libompitrace/bcast.c
  ompi/contrib/libompitrace/isend.c
  ompi/contrib/libompitrace/recv.c
  ompi/contrib/libompitrace/reduce.c
  ompi/contrib/libompitrace/send.c
  ompi/contrib/libompitrace/sendrecv.c
Labels: Target: v4.1.x

#10013 Fix base reduce_scatter_block for large payloads
  ompi/mca/coll/base/coll_base_reduce_scatter_block.c
Labels: Target: v4.1.x
