Repository open-mpi/ompi, pull requests merged in 2022-06, with the labels that each got.

#10439 v5.0: Implement reporting of transport/device names used by MPI application when using UCX
  config/ompi_check_ucx.m4
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/pml/base/pml_base_frame.c
  ompi/mca/pml/pml.h
  ompi/mca/pml/ucx/pml_ucx.c
Labels: Target: v5.0.x

#10446 v5.0.x: Initial fix for partcomm initialization.
  ompi/instance/instance.c
Labels: Target: v5.0.x

#10408 v4.0.x: two cleanups
  configure.ac
  ompi/mpi/java/c/mpi_Info.c
Labels: Target: v4.0.x

#10423 Nbc counts v40x
  ompi/mca/coll/libnbc/nbc_iallgather.c
  ompi/mca/coll/libnbc/nbc_ialltoall.c
  ompi/mca/coll/libnbc/nbc_ibcast.c
  ompi/mca/coll/libnbc/nbc_igather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_allgather.c
  ompi/mca/coll/libnbc/nbc_ineighbor_alltoall.c
  ompi/mca/coll/libnbc/nbc_ireduce.c
  ompi/mca/coll/libnbc/nbc_ireduce_scatter_block.c
  ompi/mca/coll/libnbc/nbc_iscatter.c
Labels: Target: v4.0.x

#10450 docs: describe the MPI profiling interface
  docs/features/index.rst
  docs/features/profiling.rst
Labels: documentation, Target: v5.0.x

#10386 romio341: do not include auto-generated file in the dist tarball
  3rd-party/romio341/mpl/Makefile.am
Labels: Target: main

#10451 v5.0.x: docs: describe the MPI profiling interface
  docs/features/index.rst
  docs/features/profiling.rst
Labels: documentation, Target: v5.0.x

#10447 v5.0.x: The matching lock should be acquired only once.
  ompi/mca/pml/ob1/pml_ob1_recvfrag.c
Labels: Target: v5.0.x

#10483 v5.0.x: Remove "to do" section from RST docs
  docs/index.rst
  docs/installing-open-mpi/configure-cli-options/support-libraries.rst
  docs/to-do.rst
Labels: documentation, Target: v5.0.x

#10460 Errorhandler: don't fallback to COMM_WORLD, pass NULL instead
  ompi/errhandler/errhandler_invoke.c
Labels: Target: main, MPI-4.0

#10467 opal: Segfault avoidence in mca/btl/ofi
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_context.c
Labels: Target: main

#10485 Fix typos in the docs/ sub-directory
  docs/building-apps/building-static-apps.rst
  docs/faq/debugging.rst
  docs/faq/general-tuning.rst
  docs/faq/running-mpi-apps.rst
  docs/faq/troubleshooting.rst
  docs/features/extensions.rst
  docs/features/ulfm.rst
  docs/getting-help.rst
  docs/installing-open-mpi/installation-location.rst
  docs/installing-open-mpi/quickstart.rst
  docs/installing-open-mpi/required-support-libraries.rst
  docs/man-openmpi/man1/mpirun.1.rst
  docs/man-openmpi/man1/ompi-wrapper-compiler.1.rst
  docs/man-openmpi/man1/ompi_info.1.rst
  docs/man-openmpi/man3/MPI_Cart_coords.3.rst
  docs/man-openmpi/man3/MPI_Comm_split_type.3.rst
  docs/man-openmpi/man3/MPI_Dist_graph_create.3.rst
  docs/man-openmpi/man3/MPI_Dist_graph_create_adjacent.3.rst
  docs/man-openmpi/man3/MPI_Recv.3.rst
  docs/man-openmpi/man3/MPI_Request_get_status.3.rst
  docs/man-openmpi/man3/MPI_Session_get_pset_info.3.rst
  docs/man-openmpi/man3/MPI_T_cvar_handle_alloc.3.rst
  docs/man-openmpi/man3/MPI_T_pvar_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_pvar_get_num.3.rst
  docs/man-openshmem/man1/oshmem-wrapper-compiler.1.rst
  docs/man-openshmem/man3/shmalloc.3.rst
  docs/man-openshmem/man3/shmem_malloc.3.rst
  docs/man-openshmem/man3/shmem_udcflush.3.rst
  docs/networking/cuda.rst
  docs/networking/iwarp.rst
  docs/networking/tcp.rst
  docs/release-notes/compilers.rst
  docs/running-apps/localhost.rst
  docs/running-apps/slurm.rst
  docs/running-apps/ssh.rst
Labels: documentation, Target: main

#10493 OSC UCX: Enable software atomicity when lock is set to MPI_MODE_NOCHECK
  ompi/mca/osc/ucx/osc_ucx_passive_target.c
Labels: Target: main

#10496 V5.0.x: (s)coll/ucc: don't force cls by default
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_component.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
Labels: Target: v5.0.x

#10501 Errorhandler: don't fallback to COMM_WORLD, pass NULL instead [5.0.x]
  ompi/errhandler/errhandler_invoke.c
Labels: Target: v5.0.x, MPI-4.0

#10502 sessions: initialize instance field for world and self
  ompi/communicator/comm_init.c
Labels: Target: v5.0.x

#10508 v5.0.x: Fix typos in the docs/ sub-directory
  docs/building-apps/building-static-apps.rst
  docs/faq/debugging.rst
  docs/faq/general-tuning.rst
  docs/faq/running-mpi-apps.rst
  docs/faq/troubleshooting.rst
  docs/features/extensions.rst
  docs/features/ulfm.rst
  docs/getting-help.rst
  docs/installing-open-mpi/installation-location.rst
  docs/installing-open-mpi/quickstart.rst
  docs/installing-open-mpi/required-support-libraries.rst
  docs/man-openmpi/man1/mpirun.1.rst
  docs/man-openmpi/man1/ompi-wrapper-compiler.1.rst
  docs/man-openmpi/man1/ompi_info.1.rst
  docs/man-openmpi/man3/MPI_Cart_coords.3.rst
  docs/man-openmpi/man3/MPI_Comm_split_type.3.rst
  docs/man-openmpi/man3/MPI_Dist_graph_create.3.rst
  docs/man-openmpi/man3/MPI_Dist_graph_create_adjacent.3.rst
  docs/man-openmpi/man3/MPI_Recv.3.rst
  docs/man-openmpi/man3/MPI_Request_get_status.3.rst
  docs/man-openmpi/man3/MPI_Session_get_pset_info.3.rst
  docs/man-openmpi/man3/MPI_T_cvar_handle_alloc.3.rst
  docs/man-openmpi/man3/MPI_T_pvar_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_pvar_get_num.3.rst
  docs/man-openshmem/man1/oshmem-wrapper-compiler.1.rst
  docs/man-openshmem/man3/shmalloc.3.rst
  docs/man-openshmem/man3/shmem_malloc.3.rst
  docs/man-openshmem/man3/shmem_udcflush.3.rst
  docs/networking/cuda.rst
  docs/networking/iwarp.rst
  docs/networking/tcp.rst
  docs/release-notes/compilers.rst
  docs/running-apps/localhost.rst
  docs/running-apps/slurm.rst
  docs/running-apps/ssh.rst
Labels: documentation, Target: v5.0.x

#10509 v4.0.x: Backport alltoall in place fixes
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/basic/coll_basic_alltoallw.c
  opal/datatype/opal_convertor.c
  opal/datatype/opal_datatype.h
  opal/datatype/opal_datatype_get_count.c
Labels: NEWS, Target: v4.0.x

#10500 coll/ucc: add support for dt float128 float32(64,128)_complex
  config/ompi_check_ucc.m4
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
Labels: Target: main

#10491 Add Missing MPI_F_XXX C constants
  ompi/include/mpi.h.in
Labels: Target: main, MPI-4.0

#10533 v4.0.x: Add Missing MPI_F_XXX C constants #10530
  ompi/include/mpi.h.in
Labels: Target: v4.0.x

#10527 Op: Treat unsigned long as unsigned, not signed long
  ompi/mca/op/base/op_base_functions.c
Labels: Target: main

#10534 v4.1.x: Add Missing MPI_F_XXX C constants #10530
  ompi/include/mpi.h.in
Labels: RM approved, NEWS, Target: v4.1.x

#10532 v5.0.x: coll/hcoll: fix OPAL_UNSIGNED_LONG datatype conversion
  ompi/mca/coll/hcoll/coll_hcoll_dtypes.h
Labels: Target: v5.0.x

#10516 v5.0.x: coll/ucc: add support for dt float128 float32(64,128)_complex
  config/ompi_check_ucc.m4
  ompi/mca/coll/ucc/coll_ucc_dtypes.h
  oshmem/mca/scoll/ucc/scoll_ucc_dtypes.h
Labels: Target: v5.0.x

#10530 v5.0.x: Add Missing MPI_F_XXX C constants
  ompi/include/mpi.h.in
Labels: NEWS, Target: v5.0.x

#10529 [v5.0.x] btl/base: push operation->hdr to am_rdma_respond for queued operation
  opal/mca/btl/base/btl_base_am_rdma.c
Labels: Target: v5.0.x

#10518 v4.1.x: osc/rdma: removed deadlock in find dynamic region
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
Labels: RM approved, Target: v4.1.x
