Repository open-mpi/ompi, pull requests merged in 2023-12, with the labels that each got.

#12142 opal/accelerator: introduce accelerator ipc APIs and implement stubs
  opal/mca/accelerator/accelerator.h
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/null/accelerator_null_component.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
  opal/mca/accelerator/ze/accelerator_ze_module.c
Labels: Target: main

#12032 Topo aware coll comm v2
  contrib/check_unnecessary_headers.sh
  ompi/communicator/comm_cid.c
  ompi/communicator/communicator.h
  ompi/communicator/help-comm.txt
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: main

#12158 V5.0.x: news update, version update
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#12154 osc/rdma: fix compiler warnings in osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: main

#12155 [5.0.x] osc/rdma: fix compiler warnings in osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: v5.0.x

#12055 accelerator: build components as dso's by default
  config/opal_mca.m4
Labels: Target: main

#12162 docs: add some info about HPE CXI ofi provider
  docs/tuning-apps/networking/ofi.rst
Labels: Target: main

#12166 mtl/ofi: log request type on callback error
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#12167 lanl: darwin ci appears to need site tokens now
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: main

#12161 fs/lustre: recognize soft-links on file open
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: Target: main, Target: v5.0.x, Target: v4.1.x

#12164 docs: refine wording related to HPE CXI provider
  docs/tuning-apps/networking/ofi.rst
Labels: documentation, Target: main

#12177 Update VERSION and NEWS for 5.0.1
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#12178 [v5.0.x] accelerator: build components as dso's by default
  config/opal_mca.m4
Labels: Target: v5.0.x

#12163 v5.0.x: docs: add some info about HPE CXI ofi provider
  docs/tuning-apps/networking/ofi.rst
Labels: documentation, Target: v5.0.x

#12172 fs/lustre: recognize soft-links on file open
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: Target: v5.0.x

#12174 Add missing Fortran subroutines to profiling lib
  ompi/mpi/fortran/use-mpi-f08/comm_create_from_group_f08.F90
  ompi/mpi/fortran/use-mpi-f08/intercomm_create_from_groups_f08.F90
  ompi/mpi/fortran/use-mpi-f08/parrived_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_list_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_range_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90
Labels: Target: main

#12188 VERSION: bump to 5.0.2a1
  VERSION
Labels: Target: v5.0.x

#12182 move include of sys/mount back to where it was(restart ci)
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
Labels: Target: main

#12196 fbtl/posix: prepare component for new request types
  ompi/mca/fbtl/posix/fbtl_posix.c
  ompi/mca/fbtl/posix/fbtl_posix.h
  ompi/mca/fbtl/posix/fbtl_posix_ipreadv.c
  ompi/mca/fbtl/posix/fbtl_posix_ipwritev.c
Labels: Target: main

#12199 MPI_Startall: avoid returning MPI_ERR_REQUEST on NULL requests and zero count
  ompi/mpi/c/startall.c
Labels: Target: main
