Repository open-mpi/ompi, pull requests merged in 2023-01, with the labels that each got.

#11254 osc/rdma: fix for intel oneapi compiler
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: main

#11230 v5: Fix memory leak in mca_btl_tcp_proc_handle_modex_addresses
  opal/mca/btl/tcp/btl_tcp_proc.c
Labels: Target: v5.0.x

#11228 pml/ucx: move pmix finalize to the end of ompi_rte_finalize()
  ompi/runtime/ompi_rte.c
Labels: Target: main

#11265 accelerator/rocm: add buffer_id
  opal/mca/accelerator/rocm/accelerator_rocm.h
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: main

#11185 common/ompio: implement pipelined read and write operation
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/io/ompio/io_ompio.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: v5.0.x

#11197 fs/lustre: fix assignment of info objects to lustre args
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: Target: v5.0.x

#11209 accelerator/rocm: fix check_addr function
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: v5.0.x

#11249 update bml.h
  ompi/mca/bml/bml.h
Labels: code cleanup, Target: v5.0.x

#11252 [v5.0.x] opal/common/ofi: add net to provider exclude list
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#11268 LANL/CI: workaround for aocc module
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: v5.0.x

#11256 coll/cuda: fix issue in cuda check buffer
  ompi/mca/coll/cuda/coll_cuda.h
Labels: Target: main

#11271 Add platform files for Google Cloud HPC
  contrib/platform/google/debug
  contrib/platform/google/debug.conf
  contrib/platform/google/optimized
  contrib/platform/google/optimized.conf
Labels: Target: main

#11204 Fix memory leak in ompi_coll_base_reduce_intra_in_order_binary: Coverity CID 1397316
  ompi/mca/coll/base/coll_base_reduce.c
Labels: Target: main

#11267 timings: fixes to be usable again
  opal/runtime/opal_init.c
  opal/util/Makefile.am
  opal/util/timings.c
Labels: Target: main

#11277 docs: put restrictions on Sphinx versions
  docs/requirements.txt
Labels: documentation, Target: main

#11273 config: add rocm lib dir to LDFLAGS
  config/opal_check_rocm.m4
Labels: Target: main

#11234 OSC/UCX: avoid creating ucp context if MPI-RMA is not used
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: main

#11275 osc/rdma: Add checks for gpu support during dynamic attach
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
Labels: Target: main

#11281 v5.0.x OSC/UCX: avoid creating ucp context if the application does not have MPI-RMA
  ompi/mca/osc/ucx/osc_ucx.h
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: Target: v5.0.x

#11263 v5.0.x: pml/ucx: move pmix finalize to the end of ompi_rte_finalize()
  ompi/runtime/ompi_rte.c
Labels: Target: v5.0.x

#11287 v4.1.x: NEWS: Bump v4.1.5 release to January 2023
  NEWS
Labels: documentation, Target: v4.1.x

#11264 make_dist_tarball: update GNU Autotools versions
  contrib/dist/make_dist_tarball
Labels: Target: main

#11253 accelerator/cuda: Add delayed initialization logic
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/cuda/accelerator_cuda.h
  opal/mca/accelerator/cuda/accelerator_cuda_component.c
Labels: Target: main

#11259 bugfix/#11257 mca_atomic_ucx_cswap-Stack-Smashing
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
Labels: Target: main

#11086 OFI/MTL: bypass HMEM mem reg for CXI provider
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
Labels: Target: v5.0.x

#11266 accelerator/rocm: add buffer_id
  opal/mca/accelerator/rocm/accelerator_rocm.h
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: v5.0.x

#11272 v5: Fix memory leak in ompi_coll_base_reduce_intra_in_order_binary: Coverity CID 1397316
  ompi/mca/coll/base/coll_base_reduce.c
Labels: Target: v5.0.x

#11276 v5.0.x: coll/cuda: fix issue in cuda check buffer
  ompi/mca/coll/cuda/coll_cuda.h
Labels: Target: v5.0.x

#11279 v5.0.x: docs: put restrictions on Sphinx versions
  docs/requirements.txt
Labels: Target: v5.0.x

#11280 timings: fixes to be usable again
  opal/runtime/opal_init.c
  opal/util/Makefile.am
  opal/util/timings.c
Labels: Target: v5.0.x

#11291 v5.0.x: make_dist_tarball: update GNU Autotools versions
  contrib/dist/make_dist_tarball
Labels: Target: v5.0.x

#11297 v5.0.x accelerator/cuda: Add delayed initialization logic
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/cuda/accelerator_cuda.h
  opal/mca/accelerator/cuda/accelerator_cuda_component.c
Labels: Target: v5.0.x

#11298 v5.0.x Properly return cuda status
  ompi/mpiext/cuda/c/mpiext_cuda.c
Labels: Target: v5.0.x

#11284 coll/ucc: updating team desroy as nonblocking
  ompi/mca/coll/ucc/coll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
Labels: Target: main

#11274 pr-checks: compile with rocm support
  .github/workflows/compile-rocm.yaml
Labels: Target: main

#11300 timing framework: fix use of timers
  opal/mca/timer/base/timer_base_open.c
  opal/util/timings.c
  opal/util/timings.h
Labels: Target: main

#11304 OSC/RDMA: Fix Compare_and_swap return value when comp != target
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: main, Target: v5.0.x

#11313 v4.1: bugfix/#11257 mca atomic ucx cswap stack smashing
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
Labels: Target: v4.1.x

#11303 migrate Jenkins CI to Pipeline
  .ci/community-jenkins/Jenkinsfile
  .ci/community-jenkins/pr-builder.sh
Labels: Target: main

#11318 doc: fixed LSF documentation
  docs/launching-apps/lsf.rst
Labels: documentation, Target: main

#11315 v5.0.x: coll/ucc: updating team destroy as nonblocking
  ompi/mca/coll/ucc/coll_ucc_module.c
  oshmem/mca/scoll/ucc/scoll_ucc_module.c
Labels: Target: v5.0.x

#11314 v5.0.x: bugfix/#11257 mca atomic ucx cswap stack smashing
  oshmem/mca/atomic/ucx/atomic_ucx_cswap.c
Labels: Target: v5.0.x

#11140 V5.0.x Add Cache bypass mechanism to OFI BTL and OSC RDMA + OFI BTL FI_HMEM support
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
  ompi/mca/osc/rdma/osc_rdma_btl_comm.c
  ompi/mca/osc/rdma/osc_rdma_comm.c
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_dynamic.c
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/rcache/grdma/rcache_grdma_module.c
Labels: Target: v5.0.x

#11293 OSC/RDMA: Prevent BTL from handling DATA_COMPLEX ops
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: main

#11292 opal/mca/btl/ofi: Support full set of BTL ops
  opal/mca/btl/ofi/btl_ofi_atomics.c
Labels: Target: main

#11301 pr-checks: compile with rocm support
  .github/workflows/compile-rocm.yaml
Labels: Target: v5.0.x

#11320 add sha256 generation func to opal util toolbox
  .gitignore
  opal/util/Makefile.am
  opal/util/sha256.c
  opal/util/sha256.h
  test/util/Makefile.am
  test/util/opal_sha256.c
Labels: Target: v5.0.x

#11321 osc/rdma: fix for intel oneapi compiler
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: v5.0.x

#11325 v5.0.x pml/ob1: Fix typo succedded
  ompi/mca/pml/ob1/pml_ob1_progress.c
Labels: Target: v5.0.x

#11328 opal/mca/btl/ofi: Support full set of BTL ops
  opal/mca/btl/ofi/btl_ofi_atomics.c
Labels: Target: v5.0.x

#11329 OSC/RDMA: Prevent BTL from handling DATA_COMPLEX ops
  ompi/mca/osc/rdma/osc_rdma_accumulate.c
Labels: Target: v5.0.x

#11308 accelerator/cuda: Account for possibility that cuda will never be ini…
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1.h
  ompi/mca/pml/ob1/pml_ob1_component.c
  opal/datatype/opal_datatype_copy.c
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: main

#11326 v5.0.x missing commits.
  ompi/mca/pml/ob1/pml_ob1_cuda.c
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/mca/common/ucx/common_ucx_wpool.c
  oshmem/mca/scoll/ucc/scoll_ucc_alltoall.c
  oshmem/mca/scoll/ucc/scoll_ucc_collect.c
Labels: Target: v5.0.x

#11282 Have configure abort if building for 32 bit
  configure.ac
  docs/faq/supported-systems.rst
  docs/release-notes/platform.rst
Labels: Target: main

#11333 v5.0.x: Delayedbackport
  ompi/mca/pml/ob1/pml_ob1.c
  ompi/mca/pml/ob1/pml_ob1.h
  ompi/mca/pml/ob1/pml_ob1_component.c
  opal/datatype/opal_datatype_copy.c
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: v5.0.x

#11225 common/ompio: implement pipelined file_iwrite and iread
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: main

#11334 v5.0.x: Have configure abort if building for 32 bit
  configure.ac
  docs/faq/supported-systems.rst
  docs/release-notes/platform.rst
Labels: Target: v5.0.x

#11319 opal/common/ofi: add net to provider exclude list
  opal/mca/common/ofi/common_ofi.c
Labels: RM approved, Target: v4.1.x

#11337 Jenkinsfile: reduce CI resource using while debugging
  .ci/community-jenkins/Jenkinsfile
Labels: Target: main

#11343 lanl/ci: workaround for xlc builds
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: main

#11344 v5: MPI 4 Deprecation of MPI_Info_get and MPI_Cancel
  ompi/include/mpi.h.in
  ompi/mca/pml/base/pml_base_frame.c
  ompi/mca/pml/base/pml_base_sendreq.c
  ompi/mca/pml/base/pml_base_sendreq.h
  ompi/mca/pml/ob1/pml_ob1_isend.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
  ompi/request/request.c
  ompi/request/request.h
Labels: Target: v5.0.x

#11350 Fix summary output for MPI Standard Version
  config/opal_save_version.m4
Labels: Target: main

#11348 Update news in preparation for v5.0.0rc10.
  docs/news/news-v5.0.x.rst
Labels: Target: main

#11352 Fix summary output for MPI Standard Version
  config/opal_save_version.m4
Labels: Target: v5.0.x

#11351 v5.0.0rc10 prep
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11356 Revert "common/ompio: implement pipelined file_iwrite and iread"
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: main

#11355 lanl/ci: workaround for xlc builds
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: v5.0.x

#11173 Change the PMIX event observed to capture faults from PRTE
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/instance/instance.c
Labels: bug, Target: main
