Repository open-mpi/ompi, pull requests merged in 2023-07, with the labels that each got.

#11795 lanl-ci: remove ibm from test matrix
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: v5.0.x

#11773 Fix erroneous check for GCC version in compiler workaround in v4.1.x
  opal/include/opal/sys/gcc_builtin/atomic.h
Labels: RM approved, Target: v4.1.x

#11788 Remove some compiler warnings.
  ompi/communicator/comm.c
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/cuda/coll_cuda_reduce.c
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: main

#11808 Added workflow for self-hosted runner Nvidia/Mellanox into branch v5.0.x
  .github/workflows/ompi_nvidia.yaml
  .mailmap
Labels: Target: v5.0.x

#11807 group: defer the insertion of ompi_group_all_failed_procs to group_table
  ompi/group/group_init.c
Labels: Target: main

#11814 pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND_ALLOC()
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: Target: main

#11801 lanl-ci: remove cce build
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: v5.0.x

#11811 Added workflow for self-hosted runner Nvidia/Mellanox into branch v4.1.x
  .github/workflows/ompi_nvidia.yaml
  .mailmap
Labels: RM approved, Target: v4.1.x

#11810 Added workflow for self-hosted runner Nvidia/Mellanox into branch v4.0.x
  .github/workflows/ompi_nvidia.yaml
  .mailmap
Labels: Target: v4.0.x

#11802 v5.0x: Remove some compiler warnings.
  ompi/communicator/comm.c
  ompi/mca/coll/base/coll_base_alltoall.c
  ompi/mca/coll/cuda/coll_cuda_reduce.c
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: v5.0.x

#11804 v5.0.x: Reorder the topology to match the new ranks.
  ompi/mca/topo/treematch/topo_treematch_dist_graph_create.c
Labels: Target: v5.0.x

#11812 [v4.1.x ]Backport han allreduce fixes
  ompi/mca/coll/han/coll_han_allreduce.c
Labels: bug, RM approved, Target: v4.1.x

#11816 runtime/params: set ompi_mpi_compat_mpi3 to true by default
  ompi/runtime/ompi_mpi_params.c
  ompi/runtime/params.h
Labels: Target: main

#11800 coll/han: fix bug in reduce in place
  ompi/mca/coll/han/coll_han_reduce.c
Labels: Target: main

#11818 communicator: add errhandler_type back
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/debuggers/predefined_gap_test.c
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
Labels: Target: main

#11821 [v5.0.x] backport bugfixes created during mtt bug bash
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/debuggers/predefined_gap_test.c
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
  ompi/group/group_init.c
  ompi/mca/coll/han/coll_han_reduce.c
  ompi/mca/pml/cm/pml_cm_sendreq.h
  ompi/runtime/ompi_mpi_params.c
  ompi/runtime/params.h
Labels: Target: v5.0.x

#11805 v4.1.x: dist: update NEWS and VERSION for v4.1.6
  NEWS
  VERSION
Labels: Target: v4.1.x

#11797 OFI MTL: workaround for bug in CXI provider
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: RM approved, Target: v4.1.x

#11825 docs: update list of deprecated/removed functions
  docs/building-apps/abi-compatibility.rst
  docs/building-apps/deprecation-warnings.rst
  docs/building-apps/index.rst
  docs/building-apps/removed-mpi-constructs.rst
Labels: documentation, Target: main

#11837 v4.1.x: datatype: Fix MPI_Type_dup() to propagate errors from inner calls
  ompi/mpi/c/type_dup.c
Labels: RM approved, Target: v4.1.x

#11836 v5.0.x: datatype: Fix MPI_Type_dup() to propagate errors from inner calls
  ompi/mpi/c/type_dup.c
Labels: Target: v5.0.x

#11833 v5.0.x: docs: update list of deprecated/removed functions
  docs/building-apps/abi-compatibility.rst
  docs/building-apps/deprecation-warnings.rst
  docs/building-apps/index.rst
  docs/building-apps/removed-mpi-constructs.rst
Labels: documentation, Target: v5.0.x

#11839 Prep for 4.1.6rc2
  NEWS
  VERSION
Labels: RM approved, Target: v4.1.x
