Repository open-mpi/ompi, pull requests merged in 2023-02, with the labels that each got.

#11324 MTL/OFI: Fix MPI_Cancel dereferences NULL pointer
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#11327 MTL/OFI: Refactor SSend ACK generation and allow MRecv to process SSend's.
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#11374 Update news in preparation for v5.0.0rc10.
  docs/news/news-v5.0.x.rst
Labels: Target: main

#11375 v5.0.x: Update news in preparation for v5.0.0rc10.
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11376 contrib/dist/make_dist_tarball: Change permissions back to 755.
  contrib/dist/make_dist_tarball
Labels: Target: main

#11377 v5.0.x: contrib/dist/make_dist_tarball: Change permissions back to 755.
  contrib/dist/make_dist_tarball
Labels: Target: v5.0.x

#11372 ofi: check if libfabric has FI_HMEM_ROCR at configure time
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/ofi/btl_ofi_module.c
Labels: Target: main

#11380 docs: use proper :doi: for DOI links
  docs/features/ulfm.rst
Labels: documentation, Target: main

#11362 Bump priority of coll/han to make it the default
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: main

#11385 btl/smcuda: fix for cray llvm compiler
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: Target: main

#11389 Bump priority of coll/han
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: v5.0.x

#11395 docs: update requirements.txt
  docs/requirements.txt
Labels: documentation, Target: main

#10820 ompi_info color coding
  opal/mca/base/mca_base_pvar.c
  opal/mca/base/mca_base_var.c
  opal/mca/base/mca_base_var.h
  opal/mca/base/mca_base_var_enum.c
  opal/mca/base/mca_base_var_enum.h
  opal/runtime/help-opal-runtime.txt
  opal/runtime/opal_info_support.c
  opal/runtime/opal_params_core.c
  opal/runtime/opal_params_core.h
Labels: Target: main

#11368 [v5.0.x backport] MTL/OFI: Fix MPI_Cancel dereferences NULL pointer
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v5.0.x

#11369 [v5.0.x backport] MTL/OFI: Refactor SSend ACK generation and allow MRecv to process SSend's
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v5.0.x

#11387 btl/smcuda: fix for cray llvm compiler
  opal/mca/btl/smcuda/btl_smcuda.c
Labels: Target: v5.0.x

#11397 v5.0.x: docs: update requirements.txt
  docs/requirements.txt
Labels: documentation, Target: v5.0.x

#11396 accelerator/cuda: Add exception for CUDA_ERROR_INVALID_VALUE
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: main, Target: v5.0.x

#11393 opal/datatype: Account for error possibility in check addr
  opal/datatype/opal_datatype_copy.c
Labels: Target: main

#11382 v4.1.x: Fix compilation issue in OFI with CUDA
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Severity: blocker, Target: v4.1.x

#11405 communicator: make c_name a dynamic array and reorder struct
  ompi/communicator/comm.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/debuggers/predefined_gap_test.c
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
  ompi/include/ompi/memchecker.h
Labels: Target: main

#11400 accelerator/cuda: Add exception for CUDA_ERROR_INVALID_VALUE
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: v5.0.x

#11401 opal/datatype: Account for error possibility in check addr
  opal/datatype/opal_datatype_copy.c
Labels: Target: v5.0.x

#11420 Prep for v4.1.5rc3
  NEWS
  VERSION
Labels: Target: v4.1.x

#11398 v5.0.x: ompi_info color coding
  opal/mca/base/mca_base_pvar.c
  opal/mca/base/mca_base_var.c
  opal/mca/base/mca_base_var.h
  opal/mca/base/mca_base_var_enum.c
  opal/mca/base/mca_base_var_enum.h
  opal/runtime/help-opal-runtime.txt
  opal/runtime/opal_info_support.c
  opal/runtime/opal_params_core.c
  opal/runtime/opal_params_core.h
Labels: enhancement, Target: v5.0.x

#11415 v5.0.x: Change the PMIX event observed to capture faults from PRTE
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/instance/instance.c
Labels: bug, Target: v5.0.x

#11416 coll/han: workaround for nvcc compiler
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: v5.0.x

#11422 dist: bump version to 4.1.5rc4
  VERSION
Labels: Target: v4.1.x

#11424 io/romio: Break make dist on config failure
  ompi/mca/io/romio341/configure.m4
Labels: Target: main

#11423 [v4.1.x] osc/rdma: fix when determining the node with the rank_array info for …
  ompi/mca/osc/rdma/osc_rdma.h
  ompi/mca/osc/rdma/osc_rdma_component.c
  ompi/mca/osc/rdma/osc_rdma_peer.c
Labels: Target: v4.1.x

#11426 dist: Update NEWS in prep for release
  NEWS
Labels: Target: v4.1.x

#11262 ulfm: Do not try to send a fin fragment to a dead process
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
Labels: bug, Target: main

#11261 ulfm fix comm_agree deadlocks due to faults not being visible
  ompi/communicator/ft/comm_ft.c
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/proc/proc.h
Labels: Target: main

#11425 io/romio: Break make dist on config failure
  ompi/mca/io/romio341/configure.m4
Labels: Target: v5.0.x

#11383 Topic/ompio pipeline iread iwrite3
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_aggregators.c
  ompi/mca/common/ompio/common_ompio_buffer.h
  ompi/mca/common/ompio/common_ompio_file_open.c
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_view.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/common/ompio/common_ompio_request.c
  ompi/mca/common/ompio/common_ompio_request.h
  ompi/mca/fs/base/fs_base_file_get_size.c
  ompi/mca/io/ompio/io_ompio.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
  ompi/mca/io/ompio/io_ompio_file_open.c
  ompi/mca/io/ompio/io_ompio_file_set_view.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_iread.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_iwrite.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_read.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_seek.c
  ompi/mca/sharedfp/lockedfile/sharedfp_lockedfile_write.c
  ompi/mca/sharedfp/sm/sharedfp_sm_iread.c
  ompi/mca/sharedfp/sm/sharedfp_sm_iwrite.c
  ompi/mca/sharedfp/sm/sharedfp_sm_read.c
  ompi/mca/sharedfp/sm/sharedfp_sm_seek.c
  ompi/mca/sharedfp/sm/sharedfp_sm_write.c
Labels: Target: main

#10507 ULFM: new functions MPI_COMM_ACK/GET_FAILED (as per latest standard draft)
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/communicator/ft/comm_ft.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mpiext/ftmpi/c/Makefile.am
  ompi/mpiext/ftmpi/c/comm_ack_failed.c
  ompi/mpiext/ftmpi/c/comm_get_failed.c
  ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
  ompi/mpiext/ftmpi/c/profile/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/comm_ack_failed_f.c
  ompi/mpiext/ftmpi/mpif-h/comm_get_failed_f.c
  ompi/mpiext/ftmpi/mpif-h/prototypes_mpi.h
  ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
  ompi/mpiext/ftmpi/use-mpi-f08/comm_ack_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/comm_get_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
  ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ack_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_get_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h
Labels: Target: main

#11436 dist: Prep for 4.1.6 release
  NEWS
  VERSION
Labels: Target: v4.1.x

#11435 communicator: make c_name a dynamic array and reorder struct
  ompi/communicator/comm.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/debuggers/predefined_gap_test.c
  ompi/errhandler/errhandler.c
  ompi/errhandler/errhandler.h
  ompi/errhandler/errhandler_invoke.c
  ompi/include/ompi/memchecker.h
Labels: Target: v5.0.x

#11432 v5.0.x: ulfm: ulfm fix comm_agree deadlocks due to faults not being visible
  ompi/communicator/ft/comm_ft.c
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/proc/proc.h
Labels: bug, Target: v5.0.x

#11431 v5.0x: ulfm: Do not try to send a fin fragment to a dead process
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
Labels: bug, Target: v5.0.x

#11440 v5.0.x updates
  Makefile.am
  config/Makefile.am
  config/opal_check_ofi.m4
  config/opal_functions.m4
  config/opal_mca.m4
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/op/avx/configure.m4
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_module.c
  opal/mca/memory/patcher/configure.m4
Labels: Target: v5.0.x

#9925 Ulfm/ishrink: add the MPI_COMM_ISHRINK operation
  ompi/communicator/communicator.h
  ompi/communicator/ft/comm_ft.c
  ompi/mpiext/ftmpi/c/Makefile.am
  ompi/mpiext/ftmpi/c/comm_ishrink.c
  ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
  ompi/mpiext/ftmpi/mpif-h/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/comm_ishrink_f.c
  ompi/mpiext/ftmpi/mpif-h/comm_shrink_f.c
  ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
  ompi/mpiext/ftmpi/use-mpi-f08/comm_ishrink_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
  ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ishrink_f08.F90
  ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h
Labels: Target: main

#11445 Revert pr 11305
  ompi/instance/instance.c
  ompi/runtime/ompi_mpi_init.c
Labels: Target: main

#11442 coll/han: fix count of allreduce t3 task's bcast operations
  ompi/mca/coll/han/coll_han_allreduce.c
Labels: Target: main

#11449 3rd-party/romio/mpl/configure.ac: fix AC 2.71 and m4 quoting issues
  3rd-party/romio341/mpl/configure.ac
Labels: Target: main

#11453 v5.0.x: 3rd-party/romio/mpl/configure.ac: fix AC 2.71 and m4 quoting issues
  3rd-party/romio341/mpl/configure.ac
Labels: Severity: blocker, Target: v5.0.x

#11447 Fix/ishrink
  ompi/mca/coll/ftagree/coll_ftagree_earlyreturning.c
  ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
  ompi/mpiext/ftmpi/c/profile/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/comm_ishrink_f.c
  ompi/mpiext/ftmpi/mpif-h/prototypes_mpi.h
Labels: Target: main
