Repository open-mpi/ompi, pull requests merged in 2023-05, with the labels that each got.

#11633 ompi/communicator: fix cid_base retrieving
  ompi/communicator/comm_cid.c
Labels: bug, Target: main

#11631 smcuda: fix edge case when using enable mca dso
  opal/mca/btl/smcuda/btl_smcuda_accelerator.c
  opal/mca/btl/smcuda/btl_smcuda_accelerator.h
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: main

#11565 ofi: NIC selection update
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11638 lanl-ci: remove cce build
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: main

#11655 RTD: use ubuntu-22.04 as ReadTheDoc build OS
  .readthedocs.yaml
Labels: Target: main

#11658 v5.0.x: RTD: use ubuntu-22.04 as ReadTheDoc build OS
  .readthedocs.yaml
Labels: Target: v5.0.x

#11626 [v4.1.x] coll/base: do not send and receive 0 byte message for linear alltoallv
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: Target: v4.1.x

#11612 pml_ucx: use integer log2 calculation for datatype size
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: bug, Target: v4.1.x

#11661 [v4.1.x]: RTD: Copy .readthedocs.yaml from main
  .readthedocs.yaml
Labels: Target: v4.1.x

#11656 btl/ofi: increase outstanding_rdma eariler for flush
  opal/mca/btl/ofi/btl_ofi_atomics.c
  opal/mca/btl/ofi/btl_ofi_rdma.c
Labels: Target: main

#11651 mtl/ofi: Fix EP name length bug for fi_av_insert()
  ompi/mca/mtl/ofi/mtl_ofi.c
Labels: Target: main

#11649 mtl/ofi: scope down ompi_mtl_ofi_wc to function level
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: bug, Target: main

#11648 smcuda: fix edge case when using enable mca dso
  opal/mca/btl/smcuda/btl_smcuda_accelerator.c
  opal/mca/btl/smcuda/btl_smcuda_accelerator.h
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: v5.0.x

#11668 [v5.0.x] btl/ofi: increase outstanding_rdma eariler for flush
  opal/mca/btl/ofi/btl_ofi_atomics.c
  opal/mca/btl/ofi/btl_ofi_rdma.c
Labels: Target: v5.0.x

#11625 [v5.0.x] coll/base: do not send and receive 0 byte message for linear alltoallv
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: Target: v5.0.x

#11670 [v5.0.x] mtl/ofi: Fix EP name length bug for fi_av_insert()
  ompi/mca/mtl/ofi/mtl_ofi.c
Labels: Target: v5.0.x

#11673 v5.0.x mtl/ofi: scope down ompi_mtl_ofi_wc to function level
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: v5.0.x

#11617 accelerator/cuda: Check for cuda devices
  opal/mca/accelerator/cuda/accelerator_cuda_component.c
Labels: Target: main

#11621 OSHMEM/MCA/SPML/UCX:added missing opal_common_ucx_mca_deregister call
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v4.1.x

#11584 mtl/ofi: Use fi_tinject if possible in isend
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#11682 accelerator/rocm: add SYNC_MEMOPS support
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: main

#11687 opal/mca/accelerator: introduce get_device_pci_attr api
  opal/mca/accelerator/accelerator.h
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/null/accelerator_null_component.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: enhancement, Target: main

#11685 accelerator/rocm: add SYNC_MEMOPS support
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: v5.0.x

#11678 [v5.0.x] mtl/ofi: Use fi_tinject if possible in isend
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v5.0.x

#11697 Update news for v5.0.0rc12
  docs/news/news-v5.0.x.rst
Labels: Target: main

#11700 docs: update some links in the v5.0 news
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: main

#11662 [v4.0.x]: RTD: Copy .readthedocs.yaml from main
  .readthedocs.yaml
Labels: Target: v4.0.x

#11693 opal/ofi: package rank calculation bugfix
  opal/mca/common/ofi/common_ofi.c
Labels: bug, Target: main

#11704 configury: support external PMIx v3 and higher
  config/opal_check_pmi.m4
Labels: RM approved, Target: v4.1.x

#11702 v5.0.x: docs: update some links in the v5.0 news
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: v5.0.x

#11705 docs: fix typos in v5.0.x news
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: main

#11707 docs: improvements to the v5.0.x news
  docs/news/news-v5.0.x.rst
  docs/tuning-apps/dynamic-loading.rst
Labels: documentation, Target: main

#11714 v5.0.x: docs: improvements to the v5.0.x news
  docs/news/news-v5.0.x.rst
  docs/tuning-apps/dynamic-loading.rst
Labels: documentation, Target: v5.0.x

#11679 [v4.1.x] mtl/ofi: Use fi_tinject if possible in isend
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: v4.1.x

#11671 [v4.1.x] mtl/ofi: Fix EP name length bug for fi_av_insert()
  ompi/mca/mtl/ofi/mtl_ofi.c
Labels: Target: v4.1.x

#11713 pr/ompio info fixes - v4.1.x
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/pvfs2/fs_pvfs2_file_open.c
Labels: RM approved, Target: v4.1.x

#11717 ompi/ofi: fix compile with libfabric
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug, Target: v4.1.x

#11718 OFI MTL: workaround for bug in CXI provider
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: Target: main

#11710 opal/ofi: follow up fixes to package rank calculation
  opal/mca/common/ofi/common_ofi.c
Labels: bug, Target: main

#11665 Use acquire/release barrier to synchronize completion of request and test/wait
  ompi/request/req_test.c
  ompi/request/req_wait.c
  ompi/request/request.h
Labels: Target: main

#11712 Fix parameter name in MPI_Intercomm_merge()
  ompi/include/mpi.h.in
  ompi/mpi/fortran/mpif-h/intercomm_merge_f.c
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
Labels: code cleanup, fortran bindings, Target: main
