Repository open-mpi/ompi, pull requests merged in 2023-09, with the labels that each got.

#11888 mpif-h: add missing declaration in session_get_nth_pset_f()
  ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c
Labels: fortran bindings, Target: main

#11854 Address Github issue #11532 by translating legacy parameters for direct launches
  opal/mca/pmix/base/pmix_base_fns.c
Labels: Target: main

#11895 Prevent runs NVIDIA_CI on the fork v4.1.x
  .github/workflows/ompi_nvidia.yaml
Labels: RM approved, Target: v4.1.x

#11898 Prevent runs NVIDIA_CI on the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: v4.0.x

#11897 Prevent runs NVIDIA_CI on the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: v5.0.x

#11892 Revert "pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND…
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, Target: main

#11905 Prevent runs NVIDIA_CI in case triggered by PR in the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: main

#11909 Prevent runs NVIDIA_CI in case triggered by PR in the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: v4.0.x

#11911 Prevent runs NVIDIA_CI in case triggered by PR in the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: v5.0.x

#11884 v5.0.x: Fix: Assert that MPI_BYTE is 1 byte large
  ompi/datatype/ompi_datatype_internal.h
Labels: Target: v5.0.x

#11906 Revert "pml/cm: fix buffer usage in MCA_PML_CM_HVY_SEND_REQUEST_BSEND
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: Target: v5.0.x

#11871 coll/base,tuned: introduce allgather_reduce allreduce algorithm
  ompi/mca/coll/base/coll_base_allreduce.c
  ompi/mca/coll/base/coll_base_functions.h
  ompi/mca/coll/tuned/coll_tuned_allreduce_decision.c
Labels: Target: main

#11907 [4.1.x] pml/cm,mtl/ofi: fix datatype offsetting
  ompi/mca/mtl/base/mtl_base_datatype.h
  ompi/mca/pml/cm/pml_cm.h
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, RM approved, Target: v4.1.x

#11923 Address Github issue #11532 by translating legacy parameters for direct launches
  opal/mca/pmix/base/pmix_base_fns.c
Labels: Target: v5.0.x

#11890 Document ORTE -> PRRTE MCA parameter changes
  docs/mca.rst
  docs/version-numbering.rst
Labels: Target: main

#11926 Document MCA parameter changes from move from ORTE to PRRTE.
  docs/mca.rst
  docs/version-numbering.rst
Labels: documentation, Target: v5.0.x

#11925 opal: Do not follow links when doing chown
  opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c
  opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_segment.c
  opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
  opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c
  opal/mca/pmix/pmix3x/pmix/src/util/pmix_pty.c
  opal/util/opal_pty.c
Labels: Target: v4.1.x

#11912 OFI: add Intel Level Zero (aka ZE) to OFI MTL/BTL
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/ofi/btl_ofi_module.c
Labels: Target: main

#11929 ofi - add MCA parameters to not use FI_HMEM
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: main

#11872 accel/ze: initial pass at intel level zero
  config/opal_check_ze.m4
  opal/mca/accelerator/ze/Makefile.am
  opal/mca/accelerator/ze/accelerator_ze.h
  opal/mca/accelerator/ze/accelerator_ze_component.c
  opal/mca/accelerator/ze/accelerator_ze_module.c
  opal/mca/accelerator/ze/configure.m4
  opal/runtime/opal_params_core.c
  opal/runtime/opal_params_core.h
Labels: Target: main

#11932 fbtl/posix: fix data-sieving calculations
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
Labels: Target: main

#11933 fbtl/posix: fix data-sieving calculations -v 5.0
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
Labels: Target: v5.0.x

#11915 Replace writev by sendmsg
  ompi/group/group.h
  opal/mca/btl/tcp/btl_tcp_frag.c
  opal/win32/opal_uio.c
  opal/win32/opal_uio.h
Labels: Target: main

#11941 Update embedded PMIx to 3.2.5
  opal/mca/pmix/pmix3x/pmix/NEWS
  opal/mca/pmix/pmix3x/pmix/VERSION
  opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_base.c
  opal/mca/pmix/pmix3x/pmix/src/mca/common/dstore/dstore_segment.c
  opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_fcntl.c
  opal/mca/pmix/pmix3x/pmix/src/mca/gds/ds12/gds_ds12_lock_pthread.c
  opal/mca/pmix/pmix3x/pmix/src/mca/ptl/usock/ptl_usock_component.c
  opal/mca/pmix/pmix3x/pmix/src/util/pmix_pty.c
  opal/mca/pmix/pmix3x/pmix/test/simple/Makefile.am
Labels: Target: v4.1.x

#11942 Clean up asm checks to not break XCode 15
  config/opal_config_asm.m4
  opal/mca/pmix/pmix3x/pmix/config/pmix_config_asm.m4
Labels: Target: v4.1.x

#11927 opal: deprecate dead code
  contrib/ompi_cplusplus.txt
  opal/util/Makefile.am
  opal/util/opal_pty.c
  opal/util/opal_pty.h
Labels: Target: main

#11940 Use aggregate initialization to ensure all fields are set
  opal/mca/btl/tcp/btl_tcp_frag.c
Labels: enhancement, Target: main

#11944 dist: Update version to 4.1.6rc4
  VERSION
Labels: RM approved, Target: v4.1.x

#11945 Bugfix in OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC
  ompi/mpi/fortran/base/fint_2_int.h
Labels: Target: main

#11943 v5.0.x: Include PRTE RST content in mpirun.1 man page
  .gitignore
  .mailmap
  .readthedocs-pre-create-environment.sh
  .readthedocs.yaml
  Makefile.ompi-rules
  config/ompi_setup_prrte.m4
  configure.ac
  docs/Makefile.am
  docs/conf.py
  docs/index.rst
  docs/installing-open-mpi/packagers.rst
  docs/installing-open-mpi/required-support-libraries.rst
  docs/man-openmpi/man1/mpirun.1.rst
  docs/news/news-v5.0.x.rst
  docs/no-prrte-content.rst.txt
Labels: documentation, Target: v5.0.x

#11224 coll/han: reorder free calls and avoid read-after-free in debug builds
  ompi/mca/coll/han/coll_han_dynamic_file.c
Labels: Target: main

#11950 Bugfix in OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC
  ompi/mpi/fortran/base/fint_2_int.h
Labels: Target: v5.0.x

#11937 pr-checks: update compile-rocm workflow
  .github/workflows/compile-rocm.yaml
Labels: Target: main

#11922 ofi: check if libfabric has FI_HMEM_ROCR at configure time
  .github/workflows/compile-rocm.yaml
  config/opal_check_ofi.m4
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/ofi/btl_ofi_module.c
Labels: Target: v5.0.x

#11953 Update news in preparation for v5.0.0rc13.
  docs/news/news-v5.0.x.rst
Labels: Target: main

#11954 v5.0.x: news and version for rc13
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11957 Update version to 4.1.7a1
  VERSION
Labels: Target: v4.1.x

#11947 Bugfix in OMPI_ARRAY_FINT_2_INT_ALLOC and OMPI_ARRAY_LOGICAL_2_INT_ALLOC
  ompi/mpi/fortran/base/fint_2_int.h
Labels: RM approved, Target: v4.1.x
