Repository open-mpi/ompi, pull requests merged in 2023-04, with the labels that each got.

#11548 coll/han: Fix simple gather in place
  ompi/mca/coll/han/coll_han_gather.c
Labels: bug, Severity: critical, Severity: blocker, Target: main

#11526 Minor fix for UCX config
  config/ompi_check_ucx.m4
Labels: Target: main

#11549 Have btls check for whether convertor involves device memory
  ompi/mca/mtl/base/mtl_base_datatype.h
  opal/datatype/opal_convertor.h
  opal/mca/btl/portals4/btl_portals4.c
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/btl_sm_sendi.c
  opal/mca/btl/tcp/btl_tcp.c
  opal/mca/btl/ugni/btl_ugni_prepare.h
  opal/mca/btl/usnic/btl_usnic_compat.c
Labels: Target: main

#11338 mtl/ofi: NIC selection update
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11562 Revert "mtl/ofi: NIC selection update"
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11564 Have btls check for whether convertor involves device memory [v5.0.x]
  ompi/mca/mtl/base/mtl_base_datatype.h
  opal/datatype/opal_convertor.h
  opal/mca/btl/portals4/btl_portals4.c
  opal/mca/btl/self/btl_self.c
  opal/mca/btl/sm/btl_sm_module.c
  opal/mca/btl/sm/btl_sm_sendi.c
  opal/mca/btl/tcp/btl_tcp.c
  opal/mca/btl/ugni/btl_ugni_prepare.h
  opal/mca/btl/usnic/btl_usnic_compat.c
Labels: Target: v5.0.x

#11554 v5.0: doc: Add links to disable-io-romio option
  docs/installing-open-mpi/configure-cli-options/mpi.rst
  docs/mca.rst
  docs/tuning-apps/mpi-io/romio.rst
Labels: documentation, Target: v5.0.x

#11567 Update news in preparation for v5.0.0rc11.
  docs/news/news-v5.0.x.rst
Labels: Target: main

#11568 Rc11
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11573 Fix pre-built docs check
  configure.ac
Labels: Severity: blocker, documentation, Target: main

#11574 v5.0.x: Fix pre-built docs check
  configure.ac
Labels: Severity: blocker, documentation, Target: v5.0.x

#11576 pr-checks: add milestoner GitHub Action (cherry pick to v4.0.x)
  .github/workflows/pr-checks.yaml
Labels: Target: v4.0.x

#11577 pr-checks: add milestoner GitHub Action (cherry-pick to v5.0.x)
  .github/workflows/pr-checks.yaml
Labels: Target: v5.0.x

#11578 pr-checks: add milestoner GitHub Action (cherry-pick to v4.1.x)
  .github/workflows/pr-checks.yaml
Labels: Target: v4.1.x

#11580 UCC/HCOLL: return req null in request free
  ompi/mca/coll/hcoll/coll_hcoll_rte.c
  ompi/mca/coll/ucc/coll_ucc_module.c
Labels: Target: v5.0.x

#11592 Improving Jenkins error-handling and build description
  .ci/community-jenkins/Jenkinsfile
Labels: Target: main

#11581 V4.1.x UCC/HCOLL: return req null in request free
  ompi/mca/coll/hcoll/coll_hcoll_rte.c
  ompi/mca/coll/ucc/coll_ucc_module.c
Labels: Target: v4.1.x

#11598 Jenkins Improvements (cherry-pick to v4.1.x)
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v4.1.x

#11597 Jenkins Improvements (cherry-pick to v5.0.x)
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v5.0.x

#11599 Jenkins Improvements (cherry-pick to v4.0.x)
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v4.0.x

#11596 MPI_Get_processor_name.3.rst: trivial typo fix
  docs/man-openmpi/man3/MPI_Get_processor_name.3.rst
Labels: documentation, Target: main

#11601 Addressing change requests to Google Cloud HPC platform files.
  contrib/platform/google/debug.conf
  contrib/platform/google/optimized.conf
Labels: Target: main

#11603 v5.0.x: MPI_Get_processor_name.3.rst: trivial typo fix
  docs/man-openmpi/man3/MPI_Get_processor_name.3.rst
Labels: documentation, Target: v5.0.x

#11608 Correctly compute the length of contiguous blocks during optimization
  ompi/datatype/ompi_datatype_create_struct.c
  test/datatype/opal_ddt_lib.c
Labels: bug, Target: main

#11605 Improve AVX* detection.
  ompi/mca/op/avx/configure.m4
  ompi/mca/op/avx/op_avx_functions.c
Labels: bug, Target: main

#11606 pml_ucx: use integer log2 calculation for datatype size
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: bug, Target: main

#11611 pml_ucx: use integer log2 calculation for datatype size
  ompi/mca/pml/ucx/pml_ucx_datatype.c
Labels: bug, Target: v5.0.x

#11610 Don't overwhelm the blockLength.
  ompi/datatype/ompi_datatype_create_struct.c
  test/datatype/opal_ddt_lib.c
Labels: Target: v5.0.x

#11609 Improve AVX* detection.
  ompi/mca/op/avx/configure.m4
  ompi/mca/op/avx/op_avx_functions.c
Labels: Target: v5.0.x

#11531 Retire the FAQ section of the docs, moving its content to other locations
  docs/Makefile.am
  docs/app-debug/index.rst
  docs/app-debug/mpir-tools.rst
  docs/app-debug/parallel-debug.rst
  docs/building-apps/index.rst
  docs/faq/building-open-mpi.rst
  docs/faq/fault-tolerance.rst
  docs/faq/general-tuning.rst
  docs/faq/index.rst
  docs/faq/large-clusters.rst
  docs/faq/running-mpi-apps.rst
  docs/faq/supported-systems.rst
  docs/faq/sysadmin.rst
  docs/faq/troubleshooting.rst
  docs/index.rst
  docs/installing-open-mpi/compilers-and-flags.rst
  docs/installing-open-mpi/configure-cli-options/installation.rst
  docs/installing-open-mpi/custom-components.rst
  docs/installing-open-mpi/index.rst
  docs/installing-open-mpi/installation-location.rst
  docs/installing-open-mpi/required-support-libraries.rst
  docs/installing-open-mpi/supported-systems.rst
  docs/installing-open-mpi/sysadmins.rst
  docs/installing-open-mpi/updating.rst
  docs/launching-apps/index.rst
  docs/launching-apps/pmix-and-prrte.rst
  docs/launching-apps/prerequisites.rst
  docs/launching-apps/quickstart.rst
  docs/launching-apps/scheduling.rst
  docs/launching-apps/ssh.rst
  docs/launching-apps/troubleshooting.rst
  docs/launching-apps/unusual.rst
  docs/man-openmpi/man3/MPI_Get_version.3.rst
  docs/man-openmpi/man3/MPI_Init_thread.3.rst
  docs/man-openmpi/man3/MPI_Wtime.3.rst
  docs/mca.rst
  docs/release-notes/mpi.rst
  docs/release-notes/platform.rst
  docs/release-notes/run-time.rst
  docs/requirements.txt
  docs/tuning-apps/affinity.rst
  docs/tuning-apps/benchmarking.rst
  docs/tuning-apps/dynamic-loading.rst
  docs/tuning-apps/environment-var.rst
  docs/tuning-apps/fault-tolerance/checkpoint-restart.rst
  docs/tuning-apps/fault-tolerance/data-reliability.rst
  docs/tuning-apps/fault-tolerance/index.rst
  docs/tuning-apps/fault-tolerance/supported.rst
  docs/tuning-apps/fork-system-popen.rst
  docs/tuning-apps/heterogeneity.rst
  docs/tuning-apps/index.rst
  docs/tuning-apps/large-clusters/index.rst
  docs/tuning-apps/large-clusters/libraries.rst
  docs/tuning-apps/large-clusters/reduce-startup-time.rst
  docs/tuning-apps/large-clusters/reduce-wireup-time.rst
  docs/tuning-apps/large-clusters/static-cluster-config.rst
  docs/tuning-apps/mpi-io/index.rst
  docs/tuning-apps/multithreaded.rst
  docs/version-numbering.rst
Labels: Target: main

#11615 Bring FAQ retirement changes over
  docs/Makefile.am
  docs/app-debug/index.rst
  docs/app-debug/mpir-tools.rst
  docs/app-debug/parallel-debug.rst
  docs/building-apps/index.rst
  docs/faq/building-open-mpi.rst
  docs/faq/fault-tolerance.rst
  docs/faq/general-tuning.rst
  docs/faq/index.rst
  docs/faq/large-clusters.rst
  docs/faq/running-mpi-apps.rst
  docs/faq/supported-systems.rst
  docs/faq/sysadmin.rst
  docs/faq/troubleshooting.rst
  docs/index.rst
  docs/installing-open-mpi/compilers-and-flags.rst
  docs/installing-open-mpi/configure-cli-options/installation.rst
  docs/installing-open-mpi/custom-components.rst
  docs/installing-open-mpi/index.rst
  docs/installing-open-mpi/installation-location.rst
  docs/installing-open-mpi/required-support-libraries.rst
  docs/installing-open-mpi/supported-systems.rst
  docs/installing-open-mpi/sysadmins.rst
  docs/installing-open-mpi/updating.rst
  docs/launching-apps/index.rst
  docs/launching-apps/pmix-and-prrte.rst
  docs/launching-apps/prerequisites.rst
  docs/launching-apps/quickstart.rst
  docs/launching-apps/scheduling.rst
  docs/launching-apps/ssh.rst
  docs/launching-apps/troubleshooting.rst
  docs/launching-apps/unusual.rst
  docs/man-openmpi/man3/MPI_Get_version.3.rst
  docs/man-openmpi/man3/MPI_Init_thread.3.rst
  docs/man-openmpi/man3/MPI_Wtime.3.rst
  docs/mca.rst
  docs/release-notes/mpi.rst
  docs/release-notes/platform.rst
  docs/release-notes/run-time.rst
  docs/requirements.txt
  docs/tuning-apps/affinity.rst
  docs/tuning-apps/benchmarking.rst
  docs/tuning-apps/dynamic-loading.rst
  docs/tuning-apps/environment-var.rst
  docs/tuning-apps/fault-tolerance/checkpoint-restart.rst
  docs/tuning-apps/fault-tolerance/data-reliability.rst
  docs/tuning-apps/fault-tolerance/index.rst
  docs/tuning-apps/fault-tolerance/supported.rst
  docs/tuning-apps/fork-system-popen.rst
  docs/tuning-apps/heterogeneity.rst
  docs/tuning-apps/index.rst
  docs/tuning-apps/large-clusters/index.rst
  docs/tuning-apps/large-clusters/libraries.rst
  docs/tuning-apps/large-clusters/reduce-startup-time.rst
  docs/tuning-apps/large-clusters/reduce-wireup-time.rst
  docs/tuning-apps/large-clusters/static-cluster-config.rst
  docs/tuning-apps/mpi-io/index.rst
  docs/tuning-apps/multithreaded.rst
  docs/version-numbering.rst
Labels: documentation, Target: v5.0.x

#11620 OSHMEM/MCA/SPML/UCX: bugfix #11604 - missing opal_common_ucx_mca_deregister
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: main

#11622 OSHMEM/MCA/SPML/UCX: v5.0.x added missing opal_common_ucx_mca_deregister call
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v5.0.x

#11624 coll/base: do not send and receive 0 byte message for linear alltoallv
  ompi/mca/coll/base/coll_base_alltoallv.c
Labels: Target: main

#11613 Added lazy initialization of rocm component
  opal/mca/accelerator/rocm/accelerator_rocm.h
  opal/mca/accelerator/rocm/accelerator_rocm_component.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: main
