Repository open-mpi/ompi, pull requests merged in 2023-10, with the labels that each got.

#11960 docs: Fix build case with --disable-prrte
  docs/Makefile.am
Labels: Target: main

#11961 v5.0.x: docs: Fix build case with --disable-prrte
  docs/Makefile.am
Labels: documentation, Target: v5.0.x

#11962 Patch the prrte.spec file.
  autogen.pl
  config/prrte.spec.diff
Labels: Target: main

#11963 v5.0.x: Patch the prrte.spec file.
  autogen.pl
  config/prrte.spec.diff
Labels: Target: v5.0.x

#11866 OSHMEM/MCA/SSHMEM/UCX: DEVICE_NIC_MEM hint - implementation should use RDMA memory type
  config/ompi_check_ucx.m4
  oshmem/mca/sshmem/ucx/configure.m4
  oshmem/mca/sshmem/ucx/sshmem_ucx.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: Target: main

#11893 oshmem: Add symmetric remote key handling code
  config/ompi_check_ucx.m4
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: Target: main

#11983 Add support for MPI_ERR_VALUE_TOO_LARGE
  ompi/errhandler/errcode.c
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
Labels: Target: main

#11984 v5.0.x: Add support for MPI_ERR_VALUE_TOO_LARGE
  ompi/errhandler/errcode.c
  ompi/include/mpi.h.in
  ompi/include/mpif-values.pl
Labels: bug, Target: v5.0.x

#11981 ofi - add MCA parameters to not use FI_HMEM
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  ompi/mca/mtl/ofi/mtl_ofi_types.h
  opal/mca/btl/ofi/btl_ofi.h
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: v5.0.x

#11978 oshmem: Add symmetric remote key handling code
  config/ompi_check_ucx.m4
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: Target: v5.0.x

#11986 pcomm:fix fortran interface for precv/psend
  ompi/mpi/fortran/mpif-h/precv_init_f.c
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/mpif-h/psend_init_f.c
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/precv_init_f08.F90
  ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
Labels: Target: main

#11989 docs/news: update contributors
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: main

#11980 OPAL/MCA/COMMON/UCX: added a NULL check for tls and devices
  opal/mca/common/ucx/common_ucx.c
Labels: bug, Target: main

#11988 pcomm:fix fortran interface for precv/psend
  ompi/mpi/fortran/mpif-h/precv_init_f.c
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/mpif-h/psend_init_f.c
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/precv_init_f08.F90
  ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
Labels: Target: v5.0.x

#11985 v.5.0.x - OPAL/MCA/COMMON/UCX: added a NULL check for tls and devices
  opal/mca/common/ucx/common_ucx.c
Labels: Target: v5.0.x

#11993 Add William to the list of people who have worked on the docs
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: main

#11992 [v5.0.x] backport docs/news: update contributors
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: v5.0.x

#11995 Add William to the list of people who have worked on the docs
  docs/news/news-v5.0.x.rst
Labels: documentation, Target: v5.0.x

#11979 oshmem: Add symmetric remote key handling code
  config/ompi_check_ucx.m4
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/ucx/sshmem_ucx.h
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
Labels: RM approved, Target: v4.1.x

#11998 v5.0.x: docs: Better explain required versions of support libraries
  VERSION
  docs/Makefile.am
  docs/conf.py
  docs/installing-open-mpi/required-support-libraries.rst
Labels: documentation, Target: v5.0.x

#12000 v5.0.x: update news and version
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11796 SHMEM_LOCKS: MCS implementation of SHMEM LOCKS
  oshmem/runtime/oshmem_shmem_params.c
  oshmem/runtime/params.h
  oshmem/shmem/c/Makefile.am
  oshmem/shmem/c/shmem_clear_lock.c
  oshmem/shmem/c/shmem_mcs_lock.c
  oshmem/shmem/c/shmem_set_lock.c
  oshmem/shmem/c/shmem_test_lock.c
  oshmem/shmem/shmem_lock.h
Labels: Target: main

#12007 v5.0.x news and version update
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#11864 communicator: introduce OMPI_COMM_DISJOINT flag
  contrib/check_unnecessary_headers.sh
  ompi/communicator/comm.c
  ompi/communicator/comm_cid.c
  ompi/communicator/communicator.h
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: main

#12014 dpm: update PMIX attribute
  ompi/dpm/dpm.c
Labels: Target: main

#12002 SHMEM_LOCKS: MCS implementation of SHMEM LOCKS
  oshmem/runtime/oshmem_shmem_params.c
  oshmem/runtime/params.h
  oshmem/shmem/c/Makefile.am
  oshmem/shmem/c/shmem_clear_lock.c
  oshmem/shmem/c/shmem_mcs_lock.c
  oshmem/shmem/c/shmem_set_lock.c
  oshmem/shmem/c/shmem_test_lock.c
  oshmem/shmem/shmem_lock.h
Labels: RM approved, Target: v4.1.x

#12020 news updates for v5.0.0 release
  docs/news/news-v5.0.x.rst
Labels: Target: main

#12021 v5.0.0 news updates
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#12023 V5.0.x update LICENSE
  LICENSE
Labels: Target: v5.0.x

#11840 configury: support flang-new
  autogen.pl
Labels: enhancement, Target: main

#12022 Revert "Merge pull request #11864 from wenduwan/topo_aware_coll_comm"
  contrib/check_unnecessary_headers.sh
  ompi/communicator/comm.c
  ompi/communicator/comm_cid.c
  ompi/communicator/communicator.h
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: main

#12025 docs: enable --enable-mca-dso description
  docs/installing-open-mpi/configure-cli-options/installation.rst
Labels: documentation, Target: main

#11828 opal_var_dump_color_keys: fix an array overflow
  opal/runtime/opal_params_core.c
Labels: Target: main

#11689 opal/ofi: refactor NIC selection logic
  opal/mca/common/ofi/common_ofi.c
Labels: bug, Target: main
