Repository open-mpi/ompi, pull requests merged in 2023-08, with the labels that each got.

#11842 ofi: push part of commit 450c72d to v50x
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#11848 docs: update readthedocs.org config
  .readthedocs.yaml
Labels: documentation, Target: main

#11851 v5.0.x: docs: update readthedocs.org config
  .readthedocs.yaml
Labels: documentation, Target: v5.0.x

#11850 v4.1.x: docs: update readthedocs.org config
  .readthedocs.yaml
  docs/requirements.txt
Labels: documentation, RM approved, Target: v4.1.x

#11849 v4.0.x: docs: update readthedocs.org config
  .readthedocs.yaml
  docs/requirements.txt
Labels: documentation, Target: v4.0.x

#11736 Retrieve the modex of all jobs during accept/connect
  ompi/dpm/dpm.c
Labels: bug, Target: main

#11858 v4.1.x: help-mpi-btl-openib: fix grammar
  opal/mca/btl/openib/help-mpi-btl-openib.txt
Labels: documentation, RM approved, Target: v4.1.x

#11770 Allow the monitoring infrastructure to be compiled.
  ompi/mca/coll/monitoring/configure.m4
  ompi/mca/common/monitoring/configure.m4
  ompi/mca/osc/monitoring/configure.m4
  ompi/mca/pml/monitoring/configure.m4
Labels: bug, Target: main

#11688 Topic/fix split type for intercomm
  ompi/communicator/comm.c
  ompi/mca/coll/inter/coll_inter_allreduce.c
Labels: bug, Target: main

#11865 docs: remove a unicode character from a man page
  docs/man-openmpi/man3/MPI_Session_finalize.3.rst
Labels: documentation, Target: main

#11857 v4.1.x: Fix inconsistent configure-time check
  config/ompi_fortran_check_ignore_tkr.m4
Labels: RM approved, Target: v4.1.x

#11868 docs: fix HTML word wapping in table cells
  docs/building-apps/deprecation-warnings.rst
  docs/conf.py
  docs/installing-open-mpi/required-support-libraries.rst
  docs/launching-apps/ssh.rst
Labels: documentation, Target: main

#11859 Ask for the modex of all jobs connected.
  ompi/dpm/dpm.c
Labels: Target: v5.0.x

#11860 Allow the monitoring infrastructure to be compiled.
  ompi/mca/coll/monitoring/configure.m4
  ompi/mca/common/monitoring/configure.m4
  ompi/mca/osc/monitoring/configure.m4
  ompi/mca/pml/monitoring/configure.m4
Labels: enhancement, Target: v5.0.x

#11863 Backport/split type
  ompi/communicator/comm.c
  ompi/mca/coll/inter/coll_inter_allreduce.c
Labels: Target: v5.0.x

#11869 v5.0.x: docs: remove a unicode character from a man page
  docs/man-openmpi/man3/MPI_Session_finalize.3.rst
Labels: documentation, Target: v5.0.x

#11870 v5.0.x: docs: fix HTML word wapping in table cells
  docs/building-apps/deprecation-warnings.rst
  docs/conf.py
  docs/installing-open-mpi/required-support-libraries.rst
  docs/launching-apps/ssh.rst
Labels: documentation, Target: v5.0.x

#11862 v4.1.x: fortran: fix MPI_F_STATUS_SIZE
  config/ompi_setup_mpi_fortran.m4
  ompi/include/mpi.h.in
Labels: bug, RM approved, Target: v4.1.x

#11879 Prevent runs NVIDIA_CI on the fork
  .github/workflows/ompi_nvidia.yaml
Labels: Target: main

#11880 NEWS: Add some more bullets for v4.1.6
  NEWS
Labels: documentation, Target: v4.1.x

#11882 dist: Bump version to 4.1.6rc3
  VERSION
Labels: RM approved, Target: v4.1.x

#11883 Fix: Assert that MPI_BYTE is 1 byte large
  ompi/datatype/ompi_datatype_internal.h
Labels: Target: main
