Repository open-mpi/ompi, pull requests merged in 2023-06, with the labels that each got.

#11727 v5.0.x: Fix parameter name in MPI_Intercomm_merge()
  ompi/include/mpi.h.in
  ompi/mpi/fortran/mpif-h/intercomm_merge_f.c
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-tkr/mpi-f90-interfaces.h
Labels: Target: v5.0.x

#11529 coll/cuda: always compile component
  ompi/mca/coll/cuda/coll_cuda_module.c
  ompi/mca/coll/cuda/configure.m4
Labels: Target: main

#11684 [v4.1.x] btl/ofi: increase outstanding_rdma eariler for flush
  opal/mca/btl/ofi/btl_ofi_atomics.c
  opal/mca/btl/ofi/btl_ofi_rdma.c
Labels: Target: v4.1.x

#11640 OPAL/MCA/COMMON/UCX: #11632 bugfix - mca string variables registration
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
Labels: Target: main

#11728 opal/common/ofi: match openfabrics device by uuid and osname
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11741 Update ignores
  .gitignore
Labels: Target: main

#11472 pmix3x: use PMIX_VALUE_LOAD() and PMIX_INFO_LOAD() macros
  opal/mca/pmix/pmix3x/pmix3x.c
  opal/mca/pmix/pmix3x/pmix3x.h
  opal/mca/pmix/pmix3x/pmix3x_client.c
Labels: RM approved, Target: v4.1.x

#11744 opal/mca/ofi: Patch series to fix a crash due to double free on error path
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#11745 v5.0.x: Update ignores
  .gitignore
Labels: Target: v5.0.x

#11752 [v4.1.x] pml/cm: make heavy send request initialization to be same as thin one
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, Target: v4.1.x

#11754 Github workflows: update to newer Github actions versions
  .github/workflows/compile-rocm.yaml
  .github/workflows/pr-checks.yaml
Labels: Target: main

#11753 find_common_syms: use "grep -E" instead of "egrep"
  config/find_common_syms
Labels: Severity: minor, Target: main

#11758 v4.1.x: pr-checks.yaml: update actions versions v1.0.1
  .github/workflows/pr-checks.yaml
Labels: RM approved, Target: v4.1.x

#11757 v4.0.x: pr-checks.yaml: update actions versions v1.0.1
  .github/workflows/pr-checks.yaml
Labels: Target: v4.0.x

#11759 v5.0.x: Update Github Actions
  .github/workflows/compile-rocm.yaml
  .github/workflows/pr-checks.yaml
Labels: Target: v5.0.x

#11760 v4.1.x: find_common_syms: use "grep -E" instead of "egrep"
  config/find_common_syms
Labels: RM approved, Target: v4.1.x

#11767 v4.1.x: pmix3x: update to handle PMIx v4.2.3
  opal/mca/pmix/pmix3x/pmix3x.c
Labels: RM approved, Target: v4.1.x

#11766 examples/Makefile: use "grep -E" instead of "egrep"
  examples/Makefile
Labels: Target: main

#11769 Changed URL of CI repo to https://github.com/Mellanox/jenkins_scripts
  .ci/mellanox/azure-pipelines.yml
Labels: Target: main

#11762 lanl-ci: remove ibm from test matrix
  .ci/lanl/gitlab-darwin-ci.yml
Labels: Target: main

#11746 docs: update verbiage for using srun
  docs/launching-apps/slurm.rst
Labels: documentation, Target: main, Target: v5.0.x

#11761 v5.0.x: find_common_syms: use "grep -E" instead of "egrep"
  config/find_common_syms
Labels: Target: v5.0.x

#11768 v5.0.x: examples/Makefile: use "grep -E" instead of "egrep"
  examples/Makefile
Labels: Target: v5.0.x

#11739 V5.0.x: ofi: NIC selection update (revised)
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#11778 v5.0.x: Fix reordering of received data in the gather
  ompi/mca/coll/han/coll_han_gather.c
Labels: Target: v5.0.x

#11776 docs: add info on connect/accept
  docs/launching-apps/unusual.rst
Labels: documentation, Target: main

#11780 docs: add info on connect/accept
  docs/launching-apps/unusual.rst
Labels: Target: v5.0.x

#11782 Added workflow for self-hosted runner Nvidia/Mellanox
  .github/workflows/ompi_nvidia.yaml
  .mailmap
Labels: Target: main

#11790 docs: speed up Sphinx processing
  docs/Makefile.am
Labels: Target: main

#11775 [v5.0.x] opal/ofi: package rank calculation bugfix
  opal/mca/common/ofi/common_ofi.c
Labels: bug, Target: v5.0.x

#11787 v5.0.x: Fail configure if external hwloc >= v3.0.0 is found
  config/opal_config_hwloc.m4
  docs/installing-open-mpi/required-support-libraries.rst
Labels: Target: v5.0.x

#11792 v5.0.x: docs: speed up Sphinx processing
  docs/Makefile.am
Labels: Target: v5.0.x
