Repository open-mpi/ompi, pull requests merged in 2023-03, with the labels that each got.

#11443 smcuda: fixes when using enable-mca-dso
  opal/mca/btl/smcuda/btl_smcuda_accelerator.c
  opal/mca/btl/smcuda/btl_smcuda_accelerator.h
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: main

#11388 btl/ugni accelerator/cuda: Fix typo Destory -> Destroy
  opal/mca/accelerator/cuda/help-accelerator-cuda.txt
  opal/mca/btl/ugni/btl_ugni_progress_thread.c
Labels: Target: main

#11365 Fixing VERSION file for v5.0.0rc10
  VERSION
Labels: Target: v5.0.x

#10781 Adding man pages to document ULFM functions
  docs/Makefile.am
  docs/features/ulfm.rst
  docs/man-openmpi/man3/MPIX_Comm_ack_failed.3.rst
  docs/man-openmpi/man3/MPIX_Comm_agree.3.rst
  docs/man-openmpi/man3/MPIX_Comm_get_failed.3.rst
  docs/man-openmpi/man3/MPIX_Comm_iagree.3.rst
  docs/man-openmpi/man3/MPIX_Comm_is_revoked.3.rst
  docs/man-openmpi/man3/MPIX_Comm_ishrink.3.rst
  docs/man-openmpi/man3/MPIX_Comm_revoke.3.rst
  docs/man-openmpi/man3/MPIX_Comm_shrink.3.rst
  docs/man-openmpi/man3/index.rst
Labels: documentation, Target: main

#11454 coll/han: call fallback functin when HAN module is disabled
  ompi/mca/coll/cuda/coll_cuda_component.c
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_allgather.c
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_barrier.c
  ompi/mca/coll/han/coll_han_bcast.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_gather.c
  ompi/mca/coll/han/coll_han_reduce.c
  ompi/mca/coll/han/coll_han_scatter.c
Labels: Target: main

#11465 accelerator/rocm: silence warnings from header file
  opal/mca/accelerator/rocm/accelerator_rocm.h
Labels: Target: main

#11477 [V5.0.x] coll/han: fix infinite loop
  ompi/mca/coll/cuda/coll_cuda_component.c
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_allgather.c
  ompi/mca/coll/han/coll_han_allreduce.c
  ompi/mca/coll/han/coll_han_barrier.c
  ompi/mca/coll/han/coll_han_bcast.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_gather.c
  ompi/mca/coll/han/coll_han_reduce.c
  ompi/mca/coll/han/coll_han_scatter.c
Labels: Target: v5.0.x

#11487 Fix wrong buffer size in ompi_session_get_nth_pset_f
  ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c
Labels: Target: main

#11460 Fix a race condition between registering a callback and completing a request
  ompi/request/request.h
Labels: Target: main

#11479 accelerator/rocm: silence warnings from header file
  opal/mca/accelerator/rocm/accelerator_rocm.h
Labels: Target: v5.0.x

#11495 Fix wrong buffer size in ompi_session_get_nth_pset_f
  ompi/mpi/fortran/mpif-h/session_get_nth_pset_f.c
Labels: Target: v5.0.x

#11461 v5.0.x: smcuda: fixes when using enable-mca-dso
  opal/mca/btl/smcuda/btl_smcuda_accelerator.c
  opal/mca/btl/smcuda/btl_smcuda_accelerator.h
  opal/mca/btl/smcuda/btl_smcuda_component.c
Labels: Target: v5.0.x

#11499 Revert "Fix a race condition between registering a callback and completing a request"
  ompi/request/request.h
Labels: Target: main

#11497 Re-enable all Jenkinsfile tests.
  .ci/community-jenkins/Jenkinsfile
  .ci/community-jenkins/pr-builder.sh
Labels: Target: main

#11511 mpir: update links for the mpir shim new
  docs/app-debug/mpir-tools.rst
Labels: documentation, Target: main

#11311 v4.0.x: Migrate Jenkins CI to Pipeline
  .ci/community-jenkins/Jenkinsfile
  .ci/community-jenkins/pr-builder.sh
Labels: Target: v4.0.x

#11310 v5.0.x: Migrate Jenkins CI to Pipeline
  .ci/community-jenkins/Jenkinsfile
  .ci/community-jenkins/pr-builder.sh
Labels: Target: v5.0.x

#11518 ci: Clean workspace after every stage
  .ci/community-jenkins/Jenkinsfile
Labels: Target: main

#11514 mpir: update links for the mpir shim new
  docs/app-debug/mpir-tools.rst
Labels: documentation, Target: v5.0.x

#11517 [v5.0.x] Set default values before mca param registration
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/io/romio341/src/io_romio341_component.c
  opal/runtime/opal_params_core.c
  oshmem/mca/scoll/ucc/scoll_ucc_component.c
Labels: Target: v5.0.x

#11488 coll/han,base: correctly handle MPI_IN_PLACE
  ompi/mca/coll/han/coll_han_allreduce.c
Labels: Target: main

#11520 v4.1.x: ci: Clean workspace after every stage
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v4.1.x

#11522 docs:add note about needing hwloc 2.8.0 for PV
  docs/installing-open-mpi/required-support-libraries.rst
Labels: documentation, Target: v5.0.x

#11434 v5.0.x: ULFM: new functions MPI_COMM_ACK/GET_FAILED (as per latest standard draft)
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/communicator/ft/comm_ft.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mpiext/ftmpi/c/Makefile.am
  ompi/mpiext/ftmpi/c/comm_ack_failed.c
  ompi/mpiext/ftmpi/c/comm_get_failed.c
  ompi/mpiext/ftmpi/c/mpiext_ftmpi_c.h
  ompi/mpiext/ftmpi/c/profile/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/Makefile.am
  ompi/mpiext/ftmpi/mpif-h/comm_ack_failed_f.c
  ompi/mpiext/ftmpi/mpif-h/comm_get_failed_f.c
  ompi/mpiext/ftmpi/mpif-h/prototypes_mpi.h
  ompi/mpiext/ftmpi/use-mpi-f08/Makefile.am
  ompi/mpiext/ftmpi/use-mpi-f08/comm_ack_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/comm_get_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/mpiext_ftmpi_usempif08.h
  ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_ack_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi-f08/profile/pcomm_get_failed_f08.F90
  ompi/mpiext/ftmpi/use-mpi/mpiext_ftmpi_usempi.h
Labels: Target: v5.0.x

#11515 mtl/ofi: use libfabric 1.18 API if available
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: main

#11528 pml/cm: Fix datatype offset in isend
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, Severity: blocker, Target: main, Target: v5.0.x

#11516 btl/ofi: use libfabric 1.18 API if available
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: main

#11496 Add MPI_SESSION_NULL to fortran
  ompi/include/mpif-values.pl
  ompi/mpi/fortran/mpif-h/session_finalize_f.c
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-types.F90
Labels: Target: main

#11523 [v5.0.x] coll/han: correctly handle MPI_IN_PLACE
  ompi/mca/coll/han/coll_han_allreduce.c
Labels: Target: v5.0.x

#11530 pml/cm: Fix datatype offset in isend
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, Severity: blocker, Target: v5.0.x

#11502 sessions: plug hole in support for sessions erh
  ompi/errhandler/errhandler_invoke.c
Labels: Target: main

#11527 [v5.0.x] mtl,btl/ofi: use libfabric 1.18 API if available
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: v5.0.x

#11498 doc: Add MPI-4.0 partial compliance features
  docs/conf.py
  docs/man-openmpi/man3/MPI_Get_version.3.rst
  docs/man-openmpi/man7/Open-MPI.7.rst
  docs/release-notes/mpi.rst
Labels: documentation, Target: main

#11489 Allow for optimized scale launches
  ompi/mca/pml/base/base.h
  ompi/mca/pml/base/pml_base_frame.c
  ompi/mca/pml/base/pml_base_select.c
Labels: Target: main

#11546 Allow for optimized scale launches
  ompi/mca/pml/base/base.h
  ompi/mca/pml/base/pml_base_frame.c
  ompi/mca/pml/base/pml_base_select.c
Labels: Target: v5.0.x

#11538 sessions: plug hole in support for sessions erh
  ompi/errhandler/errhandler_invoke.c
Labels: Target: v5.0.x

#11539 doc: Add MPI-4.0 partial compliance features
  docs/conf.py
  docs/man-openmpi/man3/MPI_Get_version.3.rst
  docs/man-openmpi/man7/Open-MPI.7.rst
  docs/release-notes/mpi.rst
Labels: documentation, Target: v5.0.x

#11537 Example updates
  examples/README.md
  examples/connectivity_c.c
  examples/spc_example.c
Labels: documentation, Target: main, Target: v5.0.x

#11550 oshmem: Use the right datatype for PMIX_DATA_BUFFER_UNLOAD (v5.0.x)
  oshmem/mca/memheap/base/memheap_base_mkey.c
Labels: Target: v5.0.x
