Repository open-mpi/ompi, pull requests merged in 2024-12, with the labels that each got.

#12937 Fix mpirun.1.rst typos
  docs/man-openmpi/man1/mpirun.1.rst
Labels: documentation, Target: main

#12956 fortran/use-mpi-f08: Add missing profile symbols
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
Labels: fortran bindings, Target: main

#12932 update user guide for coll tuned rules file v2
  docs/tuning-apps/coll-tuned.rst
Labels: documentation, Target: main

#12955 tests: Add stdint.h header
  test/support/support.h
Labels: Target: main

#12950 ci: Remove Ubuntu 18.04 (and gcc 5 / 6)
  .ci/community-jenkins/Jenkinsfile
  docs/release-notes/platform.rst
Labels: Target: main

#12957 ci: Fix build of branch commits
  .ci/community-jenkins/Jenkinsfile
Labels: Target: main

#12941 docs: update cuda related docs to reflect
  docs/tuning-apps/networking/cuda.rst
Labels: documentation, Target: main

#12964 comm: beef up args checking for some comm constructors
  ompi/mpi/c/comm_create_from_group.c
  ompi/mpi/c/intercomm_create_from_groups.c
Labels: Target: main

#12960 comm: beef up use of PMIx_Group_construct
  ompi/communicator/comm.c
  ompi/mpi/c/comm_create_from_group.c
Labels: Target: main

#12949 smsc/accelerator: add new smsc component
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/smsc/accelerator/Makefile.am
  opal/mca/smsc/accelerator/post_configure.sh
  opal/mca/smsc/accelerator/smsc_accelerator.h
  opal/mca/smsc/accelerator/smsc_accelerator_component.c
  opal/mca/smsc/accelerator/smsc_accelerator_internal.h
  opal/mca/smsc/accelerator/smsc_accelerator_module.c
  opal/mca/smsc/base/base.h
  opal/mca/smsc/base/smsc_base_frame.c
  opal/mca/smsc/smsc.h
Labels: Target: main

#12951 v5.0.x: Fix mpirun.1.rst typos
  docs/man-openmpi/man1/mpirun.1.rst
Labels: documentation, Target: v5.0.x

#12959 v5.0.x: fortran/use-mpi-f08: Add missing profile symbols
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
Labels: fortran bindings, Target: v5.0.x

#12961 ci: Fix build of branch commits
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v5.0.x

#12966 update user guide for coll tuned rules file v2
  docs/tuning-apps/coll-tuned.rst
Labels: documentation, Target: v5.0.x

#12958 MPI_Wtime relative to MPI_Init
  ompi/instance/instance.c
  ompi/mpi/c/wtime.c
Labels: Target: main

#12980 comm: suppress compiler warning
  ompi/communicator/comm_cid.c
Labels: Target: main

#12976 comm_create_from_groups: cherrypick two commits from main to fix mpi4py comm create from group etc tests
  ompi/communicator/comm.c
  ompi/communicator/comm_cid.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/mpi/c/comm_create_from_group.c
  ompi/runtime/ompi_mpi_params.c
  ompi/runtime/params.h
Labels: Target: v5.0.x

#12975 comm: beef up args checking for some comm constructors
  ompi/mpi/c/comm_create_from_group.c
  ompi/mpi/c/intercomm_create_from_groups.c
Labels: Target: v5.0.x

#12921 romio314: do not link with cudart
  ompi/mca/io/romio341/configure.m4
Labels: Target: main, Target: v5.0.x

#12978 v5.0.x: MPI_Wtime relative to MPI_Init
  ompi/instance/instance.c
  ompi/mpi/c/wtime.c
Labels: Target: v5.0.x

#12983 v5.0.x: romio314: do not link with cudart
  ompi/mca/io/romio341/configure.m4
Labels: Target: v5.0.x

#12858 oshmem/shmem: move warn if segment inside data region to verbose level
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: Target: main

#12944 request: correctly handle MPI_COMM_NULL
  ompi/request/request.c
Labels: bug, Target: main, Target: v5.0.x

#12986 coll/accelerator initial enhancements
  ompi/mca/coll/accelerator/coll_accelerator.h
  ompi/mca/coll/accelerator/coll_accelerator_allreduce.c
  ompi/mca/coll/accelerator/coll_accelerator_exscan.c
  ompi/mca/coll/accelerator/coll_accelerator_reduce.c
  ompi/mca/coll/accelerator/coll_accelerator_reduce_scatter_block.c
  ompi/mca/coll/accelerator/coll_accelerator_scan.c
Labels: Target: main

#12908 coll/xhc: Bring in latest developments
  ompi/mca/coll/xhc/Makefile.am
  ompi/mca/coll/xhc/README.md
  ompi/mca/coll/xhc/coll_xhc.c
  ompi/mca/coll/xhc/coll_xhc.h
  ompi/mca/coll/xhc/coll_xhc_allreduce.c
  ompi/mca/coll/xhc/coll_xhc_barrier.c
  ompi/mca/coll/xhc/coll_xhc_bcast.c
  ompi/mca/coll/xhc/coll_xhc_comm.c
  ompi/mca/coll/xhc/coll_xhc_component.c
  ompi/mca/coll/xhc/coll_xhc_hierarchy.c
  ompi/mca/coll/xhc/coll_xhc_intrinsic.h
  ompi/mca/coll/xhc/coll_xhc_module.c
  ompi/mca/coll/xhc/coll_xhc_reduce.c
  ompi/mca/coll/xhc/help-coll-xhc.txt
Labels: Target: main

#12995 Remove unnecessary qsort operation
  ompi/dpm/dpm.c
Labels: Target: main

#12997 examples: add hello_sessions to dist
  examples/Makefile.include
Labels: Target: main
