Repository open-mpi/ompi, pull requests merged in 2024-10, with the labels that each got.

#12838 5.0.x/ompi/coll/cuda: Implement reduce local
  ompi/mca/coll/cuda/coll_cuda.h
  ompi/mca/coll/cuda/coll_cuda_module.c
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: Target: v5.0.x

#12834 docs/rocm: fix syntax of osu_latency benchmark -v5.0.x
  docs/tuning-apps/networking/rocm.rst
Labels: Target: v5.0.x

#12839 Import several uct btl updates
  ompi/mca/pml/ob1/pml_ob1_isend.c
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_position.c
  opal/mca/btl/sm/btl_sm_send.c
  opal/mca/btl/uct/btl_uct_am.c
  opal/mca/btl/uct/btl_uct_module.c
  opal/mca/btl/uct/btl_uct_tl.c
Labels: bug, Target: v5.0.x

#12835 opal/cuda: Handle stream-ordered allocations and assign primary device context
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: main

#12846 fs/ufs and fs/lustre: change mca var type
  ompi/mca/fs/lustre/fs_lustre_component.c
  ompi/mca/fs/ufs/fs_ufs_component.c
Labels: Target: main

#12841 opal/cuda: Handle stream-ordered allocations and assign primary device context
  opal/mca/common/cuda/common_cuda.c
Labels: Target: v4.1.x

#12836 docs: add notes about dependency versions
  docs/installing-open-mpi/required-support-libraries.rst
Labels: documentation, Target: main

#12806 coll/han/alltoallv Bugfixes
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_alltoallv.c
  ompi/mca/coll/han/coll_han_component.c
Labels: Target: main

#12842 coll/han/allreduce: squelch a particularly noisy log message
  ompi/mca/coll/han/coll_han_allreduce.c
Labels: Target: main

#12860 big count: embiggen the pml bsend attach/detach
  ompi/mca/pml/base/pml_base_bsend.c
  ompi/mca/pml/base/pml_base_bsend.h
  ompi/mpi/c/buffer_attach.c
  ompi/mpi/c/buffer_detach.c
Labels: Target: main

#12847 Retain info references on public info dup
  opal/util/info.c
Labels: Target: main

#12856 pr-checks: update compile-rocm action
  .github/workflows/compile-rocm.yaml
Labels: Target: main

#12855 pr-checks: run hdf5 testsuite
  .github/workflows/hdf5-tests.yaml
Labels: Target: main

#12871 sessions: add smoke test
  .github/workflows/macos-checks.yaml
  examples/Makefile
  examples/hello_sessions_c.c
Labels: Target: main

#12866 coll tuned make mca parameters settable via MPI_T
  ompi/mca/coll/tuned/coll_tuned_component.c
Labels: Target: v4.1.x

#12851 Disable silent-rules on CI
  .ci/community-jenkins/pr-builder.sh
  .github/workflows/compile-cuda.yaml
  .github/workflows/compile-rocm.yaml
  .github/workflows/compile-ze.yaml
  .github/workflows/macos-checks.yaml
  .github/workflows/ompi_mpi4py.yaml
Labels: Target: main

#12874 dist: More changelog updates for 4.1.7
  NEWS
Labels: Target: v4.1.x

#12722 configury: patch configure to support nvfortran
  autogen.pl
  config/ompi_setup_fc.m4
Labels: enhancement, Target: main

#12723 sessions: add support for ucx and more
  ompi/communicator/comm.c
  ompi/communicator/comm_cid.c
  ompi/communicator/comm_init.c
  ompi/communicator/communicator.h
  ompi/mca/pml/ucx/pml_ucx.c
  ompi/mca/pml/ucx/pml_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx_request.c
  ompi/mca/pml/ucx/pml_ucx_request.h
  ompi/runtime/ompi_mpi_params.c
  ompi/runtime/params.h
Labels: Target: main

#12868 sessions: fix some problems with multiple init/fini
  ompi/instance/instance.c
  opal/mca/base/mca_base_var_group.c
Labels: Target: main

#12862 remove deprecated mca rmaps param
  .github/workflows/ompi_mpi4py.yaml
Labels: Target: main

#12878 v4.1.x: configury: patch configure to support nvfortran
  autogen.pl
  config/ompi_setup_fc.m4
Labels: RM approved, Target: v4.1.x

#12870 ofi/common: fix code that broke sessions
  opal/mca/common/ofi/common_ofi.c
Labels: Target: main

#12864 coll tuned make mca parameters settable via MPI_T
  ompi/mca/coll/tuned/coll_tuned_component.c
Labels: Target: v5.0.x

#12877 oshmem/shmem: move warn if segment inside data region to verbose level
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: RM approved, Target: v4.1.x

#12888 sessions: make sure to only finalize class
  examples/hello_sessions_c.c
  ompi/instance/instance.c
Labels: Target: main

#12843 5.0.x/opal/cuda: Handle stream-ordered allocations and assign primary device
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: v5.0.x

#12850 v5.0.x: docs: add notes about dependency versions
  docs/installing-open-mpi/required-support-libraries.rst
Labels: documentation, Target: v5.0.x

#12865 Retain info references on public info dup
  opal/util/info.c
Labels: Target: v5.0.x

#12882 ofi/common: fix code that broke sessions
  opal/mca/common/ofi/common_ofi.c
Labels: Target: v5.0.x

#12898 examples: add return 0 to sessions smoke test
  examples/hello_sessions_c.c
Labels: Target: main

#12897 v4.1.x: coll/ucc: add reduce scatter block
  ompi/mca/coll/ucc/Makefile.am
  ompi/mca/coll/ucc/coll_ucc.h
  ompi/mca/coll/ucc/coll_ucc_component.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
Labels: RM approved, Target: v4.1.x

#12894 fcoll/vulcan: add two_phase read_all
  ompi/mca/fcoll/vulcan/Makefile.am
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_component.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_read_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan_internal.h
Labels: Target: main

#12883 sessions: fix some problems with multiple init/fini
  ompi/instance/instance.c
  opal/mca/base/mca_base_var_group.c
Labels: Target: v5.0.x

#12893 sessions: add smoke test
  .github/workflows/macos-checks.yaml
  examples/Makefile
  examples/hello_sessions_c.c
  ompi/instance/instance.c
Labels: Target: v5.0.x

#12890 partitions: make it work with sessions
  ompi/instance/instance.c
Labels: Target: main
