Repository open-mpi/ompi, pull requests merged in 2024-09, with the labels that each got.

#12743 gcc 14 and clang 18 compiler warning fixes
  ompi/mca/coll/base/coll_base_allgather.c
  ompi/mca/coll/han/coll_han_alltoall.c
  ompi/mca/coll/xhc/coll_xhc_module.c
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/part/persist/part_persist.h
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/datatype/opal_datatype_copy.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/util/output.c
Labels: Target: main

#12678 fcoll/vulcan accelerator support
  ompi/mca/common/ompio/common_ompio.h
  ompi/mca/common/ompio/common_ompio_file_read.c
  ompi/mca/common/ompio/common_ompio_file_read_all.c
  ompi/mca/common/ompio/common_ompio_file_write.c
  ompi/mca/fcoll/vulcan/fcoll_vulcan.h
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
  ompi/mca/io/ompio/io_ompio.c
  ompi/mca/io/ompio/io_ompio.h
  ompi/mca/io/ompio/io_ompio_component.c
Labels: Target: main

#12789 v5.0.x: gcc 14 and clang 18 compiler warning fixes
  ompi/mca/hook/comm_method/hook_comm_method_fns.c
  ompi/mca/part/persist/part_persist.h
  opal/datatype/opal_copy_functions_heterogeneous.c
  opal/util/output.c
Labels: Target: v5.0.x

#12758 ompi/coll/accelerator: implement reduce_local
  ompi/mca/coll/accelerator/coll_accelerator.h
  ompi/mca/coll/accelerator/coll_accelerator_module.c
  ompi/mca/coll/accelerator/coll_accelerator_reduce.c
Labels: Target: main

#12800 [v5.0.x] .github/workflow: set up runtime params right before mpi4py test
  .github/workflows/ompi_mpi4py.yaml
  .github/workflows/ompi_mpi4py_tests.yaml
Labels: Target: v5.0.x

#12803 fcoll/vulcan: fix memory leak
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
Labels: Target: main, Target: v5.0.x

#12808 ci: always run configury build tests on Amazon Linux 2
  .ci/community-jenkins/Jenkinsfile
Labels: Target: main

#12809 v5.0.x: fcoll/vulcan: fix memory leak
  ompi/mca/fcoll/vulcan/fcoll_vulcan_file_write_all.c
Labels: Target: v5.0.x

#12781 V5.0.x: opal/cuda: Handle VMM pointers in cuda_check_addr
  config/opal_check_cuda.m4
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/cuda/accelerator_cuda.h
Labels: Target: v5.0.x

#12783 coll/acoll: Remove use of cid as array index
  ompi/mca/coll/acoll/coll_acoll.h
  ompi/mca/coll/acoll/coll_acoll_allgather.c
  ompi/mca/coll/acoll/coll_acoll_allreduce.c
  ompi/mca/coll/acoll/coll_acoll_barrier.c
  ompi/mca/coll/acoll/coll_acoll_bcast.c
  ompi/mca/coll/acoll/coll_acoll_component.c
  ompi/mca/coll/acoll/coll_acoll_module.c
  ompi/mca/coll/acoll/coll_acoll_reduce.c
  ompi/mca/coll/acoll/coll_acoll_utils.h
Labels: Target: main

#12788 oshmem/shmem: Fix sshmem start address and warn if inside data region - v4.1.x
  oshmem/mca/memheap/base/memheap_base_static.c
  oshmem/mca/sshmem/base/sshmem_base_open.c
Labels: RM approved, Target: v4.1.x

#12817 Fix various bugs in get/put fallbacks in pml/ob1
  ompi/mca/pml/ob1/pml_ob1_recvreq.c
  ompi/mca/pml/ob1/pml_ob1_sendreq.c
Labels: Target: main, Target: v5.0.x, Target: v6.0.x

#12818 btl/uct: fix fetching atomics support for osc/rdma
  opal/mca/btl/uct/btl_uct_module.c
  opal/mca/btl/uct/btl_uct_tl.c
Labels: Target: main, Target: v5.0.x, Target: v6.0.x

#12797 pml/cm,ob1: pack data from application buffer in successive MPI_Start calls
  ompi/mca/pml/cm/pml_cm_sendreq.h
  ompi/mca/pml/ob1/pml_ob1_start.c
Labels: bug, Target: main

#12793 Make sure a PSCW epoch is active on MPI_Win_complete calls
  ompi/mca/osc/rdma/osc_rdma_active_target.c
Labels: Target: main

#12821 v5.0.x: coll/ucc: fix int overflow in coll init
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_gather.c
  ompi/mca/coll/ucc/coll_ucc_gatherv.c
  ompi/mca/coll/ucc/coll_ucc_reduce.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
  ompi/mca/coll/ucc/coll_ucc_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatterv.c
Labels: Target: v5.0.x

#12829 Update opal_portable_platform_real.h from upstream gasnet
  ompi/include/Makefile.am
  ompi/include/mpi.h.in
  opal/include/opal/opal_portable_platform.h
  opal/include/opal/opal_portable_platform_real.h
Labels: Target: main

#12828 accelecrator/cuda: fix for unresolved symbol
  opal/mca/accelerator/cuda/accelerator_cuda_component.c
Labels: Target: v5.0.x

#12823 Topic/fix ob1 segmentation with UCT BTL
  ompi/mca/pml/ob1/pml_ob1_isend.c
  opal/datatype/opal_datatype_internal.h
  opal/datatype/opal_datatype_position.c
  opal/mca/btl/sm/btl_sm_send.c
  opal/mca/btl/uct/btl_uct_am.c
Labels: bug, Target: main

#12832 docs/rocm: fix syntax of osu_latency benchmark
  docs/tuning-apps/networking/rocm.rst
Labels: Target: main

#12824 v4.1.x: coll/ucc: fix int overflow in coll init
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_reduce.c
Labels: Target: v4.1.x

#12760 fs/ufs: change default locking protocol - v4.1.x
  ompi/mca/fs/lustre/fs_lustre.h
  ompi/mca/fs/lustre/fs_lustre_component.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/ufs/fs_ufs_file_open.c
Labels: Target: v4.1.x

#12752 v4.1.x: ompi/coll/cuda: implement reduce_local
  ompi/mca/coll/cuda/coll_cuda.h
  ompi/mca/coll/cuda/coll_cuda_module.c
  ompi/mca/coll/cuda/coll_cuda_reduce.c
Labels: Target: v4.1.x

#12751 v4.1.x: opal/cuda: Handle VMM pointers
  config/opal_check_cuda.m4
  opal/mca/common/cuda/common_cuda.c
Labels: Target: v4.1.x

#12830 v5.0.x: Update opal_portable_platform_real.h from upstream gasnet
  ompi/include/Makefile.am
  ompi/include/mpi.h.in
  opal/include/opal/opal_portable_platform.h
  opal/include/opal/opal_portable_platform_real.h
Labels: Target: v5.0.x
