Repository open-mpi/ompi, pull requests merged in 2024-07, with the labels that each got.

#12651 Bump workflow actions to node20
  .github/workflows/compile-cuda.yaml
  .github/workflows/compile-rocm.yaml
  .github/workflows/compile-ze.yaml
  .github/workflows/ompi_nvidia.yaml
Labels: Target: main

#12616 Differentiate blocking unblocking collectives in UCC
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_barrier.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_common.h
  ompi/mca/coll/ucc/coll_ucc_gather.c
  ompi/mca/coll/ucc/coll_ucc_gatherv.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/coll_ucc_reduce.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
  ompi/mca/coll/ucc/coll_ucc_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatterv.c
Labels: enhancement, Target: main

#12613 pml/ucx: Propagate MPI serialized thread mode
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx.c
  opal/mca/common/ucx/common_ucx.c
  opal/mca/common/ucx/common_ucx.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: RM approved, Target: v4.1.x

#12649 Parameterize and move Fortran MPI bindings modulefiles install location
  config/ompi_configure_options.m4
  config/opal_setup_wrappers.m4
  docs/installing-open-mpi/configure-cli-options/mpi.rst
  ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi/Makefile.am
Labels: Target: main

#12650 ompi_setup_fc.m4: use -Wl,-ld_classic if supported
  config/ompi_setup_fc.m4
Labels: Target: main

#12663 v4.1.x: ompi_setup_fc.m4: use -Wl,-ld_classic if supported
  config/ompi_setup_fc.m4
Labels: Target: v4.1.x

#12642 improve documentation for the coll tuned component
  docs/tuning-apps/coll-tuned.rst
  docs/tuning-apps/index.rst
Labels: documentation, Target: main

#12665 v5.0.x: improve documentation for the coll tuned component
  docs/tuning-apps/coll-tuned.rst
  docs/tuning-apps/index.rst
Labels: documentation, Target: v5.0.x

#12531 Introduce new JSON parser utility
  config/opal_config_files.m4
  opal/util/Makefile.am
  opal/util/json/3rd-party/json.c
  opal/util/json/3rd-party/json.h
  opal/util/json/Makefile.am
  opal/util/json/help-json.txt
  opal/util/json/opal_json.c
  opal/util/json/opal_json.h
  test/support/support.c
  test/support/support.h
  test/util/Makefile.am
  test/util/opal_json.c
Labels: Target: main

#12667 docs: Add explicit docs about --with-mpi-moduledir
  config/opal_setup_wrappers.m4
  docs/installing-open-mpi/configure-cli-options/misc.rst
  docs/installing-open-mpi/installation-location.rst
Labels: documentation, Target: main

#12664 v5.0.x: ompi_setup_fc.m4: use -Wl,-ld_classic if supported
  config/ompi_setup_fc.m4
Labels: Target: v5.0.x

#12654 pml/ob1: make no. of events an mca parameter
  ompi/mca/pml/ob1/pml_ob1.h
  ompi/mca/pml/ob1/pml_ob1_accelerator.c
  ompi/mca/pml/ob1/pml_ob1_component.c
Labels: Target: main

#12659 v5.0.x: configure: Add --with-mpi-moduledir configure CLI option
  config/ompi_configure_options.m4
  config/opal_setup_wrappers.m4
  docs/installing-open-mpi/configure-cli-options/misc.rst
  docs/installing-open-mpi/configure-cli-options/mpi.rst
  docs/installing-open-mpi/installation-location.rst
  ompi/mpi/fortran/mpiext-use-mpi-f08/Makefile.am
  ompi/mpi/fortran/mpiext-use-mpi/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi-tkr/Makefile.am
  ompi/mpi/fortran/use-mpi/Makefile.am
Labels: Target: v5.0.x

#12656 Differentiate blocking unblocking collectives in UCC
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_allreduce.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_barrier.c
  ompi/mca/coll/ucc/coll_ucc_bcast.c
  ompi/mca/coll/ucc/coll_ucc_common.h
  ompi/mca/coll/ucc/coll_ucc_gather.c
  ompi/mca/coll/ucc/coll_ucc_gatherv.c
  ompi/mca/coll/ucc/coll_ucc_module.c
  ompi/mca/coll/ucc/coll_ucc_reduce.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter_block.c
  ompi/mca/coll/ucc/coll_ucc_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatterv.c
Labels: Target: v5.0.x

#12648 OSHMEM/SHMEM: fix warnings regarding types and unused variables in shmem
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/shmem_test_ivars.c
  oshmem/shmem/c/shmem_wait_ivars.c
Labels: Target: main

#12672 pml/ob1: make no. of events an mca parameter
  ompi/mca/pml/ob1/pml_ob1.h
  ompi/mca/pml/ob1/pml_ob1_accelerator.c
  ompi/mca/pml/ob1/pml_ob1_component.c
Labels: Target: v5.0.x

#12671 v5.0x: OSHMEM/SHMEM: fix warnings regarding types and unused variables in shmem
  oshmem/mca/spml/spml.h
  oshmem/mca/spml/ucx/spml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
  oshmem/mca/sshmem/ucx/sshmem_ucx_module.c
  oshmem/runtime/runtime.h
  oshmem/shmem/c/shmem_test_ivars.c
  oshmem/shmem/c/shmem_wait_ivars.c
Labels: Target: v5.0.x

#12676 V5.0.4rc1
  VERSION
  docs/release-notes/changelog/v5.0.x.rst
Labels: Target: v5.0.x

#12387 coll/han: Add alltoall algorithm
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_algorithms.c
  ompi/mca/coll/han/coll_han_algorithms.h
  ompi/mca/coll/han/coll_han_alltoall.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_subcomms.c
  ompi/mca/coll/han/configure.m4
Labels: Target: main

#12683 op/aarch64: refactor SVE functions
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: enhancement, Target: main

#12639 coll tuned make mca parameters settable via MPI_T
  ompi/mca/coll/tuned/coll_tuned_component.c
Labels: Target: main

#12688 V5.0.4 release
  VERSION
  docs/release-notes/changelog/v5.0.x.rst
Labels: Target: v5.0.x

#12687 Read The Docs updates
  docs/Makefile.am
  docs/conf.py
Labels: documentation, Target: main

#12690 v4.1.x: docs/conf.py: updates per RTD docs
  docs/conf.py
Labels: documentation, Target: v4.1.x

#12691 Check that requests belong to similar sessions
  ompi/communicator/communicator.h
  ompi/mpi/c/testall.c
  ompi/mpi/c/testany.c
  ompi/mpi/c/testsome.c
  ompi/mpi/c/waitall.c
  ompi/mpi/c/waitany.c
  ompi/mpi/c/waitsome.c
  ompi/request/request.c
  ompi/request/request.h
Labels: bug, Target: main

#12692 Bump version after v5.0.4 release
  VERSION
Labels: Target: v5.0.x

#12694 aarch64_functions.c: fix trivial typo
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: Target: v5.0.x

#12689 v5.0.x: Read The Docs updates
  docs/Makefile.am
  docs/conf.py
Labels: documentation, Target: v5.0.x

#12697 Check that requests belong to similar sessions
  ompi/communicator/communicator.h
  ompi/mpi/c/testall.c
  ompi/mpi/c/testany.c
  ompi/mpi/c/testsome.c
  ompi/mpi/c/waitall.c
  ompi/mpi/c/waitany.c
  ompi/mpi/c/waitsome.c
  ompi/request/request.c
  ompi/request/request.h
Labels: bug, Target: v5.0.x

#12696 workflow: add MacOS compile check
  .github/workflows/macos-checks.yaml
Labels: Target: main

#12700 Prepare for v5.0.5 quick follow-up release
  .github/workflows/macos-checks.yaml
  VERSION
  docs/release-notes/changelog/v5.0.x.rst
  ompi/communicator/communicator.h
  ompi/mpi/c/testall.c
  ompi/mpi/c/testany.c
  ompi/mpi/c/testsome.c
  ompi/mpi/c/waitall.c
  ompi/mpi/c/waitany.c
  ompi/mpi/c/waitsome.c
  ompi/request/request.c
  ompi/request/request.h
Labels: Target: v5.0.x

#12681 configury: harden IGNORE_TKR check
  config/ompi_fortran_check_ignore_tkr.m4
Labels: bug, fortran bindings, Target: main

#12703 Changes for post-v5.0.5 release
  VERSION
  ompi/communicator/communicator.h
  ompi/mpi/c/testall.c
  ompi/mpi/c/testany.c
  ompi/mpi/c/testsome.c
  ompi/mpi/c/waitall.c
  ompi/mpi/c/waitany.c
  ompi/mpi/c/waitsome.c
  ompi/request/request.c
  ompi/request/request.h
Labels: Target: v5.0.x

#12706 configury: harden IGNORE_TKR check
  config/ompi_fortran_check_ignore_tkr.m4
Labels: Target: v5.0.x

#12711 Identify requests from the same instance.
  ompi/request/request.c
Labels: Target: v5.0.x

#12716 docs: fix typo in launcher section
  docs/launching-apps/quickstart.rst
Labels: Target: main
