Repository open-mpi/ompi, pull requests merged in 2024-08, with the labels that each got.

#12724 opal,ompi: move container_of definition to its own header
  contrib/check_unnecessary_headers.sh
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/usnic/btl_usnic.h
  opal/util/Makefile.am
  opal/util/bipartite_graph.c
  opal/util/misc.h
Labels: Target: main

#12728 [v5.0.x] opal,ompi: move container_of definition to its own header
  contrib/check_unnecessary_headers.sh
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/usnic/btl_usnic.h
  opal/util/Makefile.am
  opal/util/bipartite_graph.c
  opal/util/misc.h
Labels: Target: v5.0.x

#12729 fix explanation of in-place option for MPI_Allgather(v)
  docs/man-openmpi/man3/MPI_Allgather.3.rst
  docs/man-openmpi/man3/MPI_Allgatherv.3.rst
Labels: Target: main

#12727 [v4.1.x] opal,ompi: move container_of definition to its own header
  contrib/check_unnecessary_headers.sh
  ompi/mca/mtl/ofi/mtl_ofi.h
  opal/mca/btl/usnic/btl_usnic.h
  opal/util/Makefile.am
  opal/util/bipartite_graph.c
  opal/util/misc.h
Labels: RM approved, Target: v4.1.x

#12721 accelerator/rocm: adjust rocm mca parameter names
  opal/mca/accelerator/rocm/accelerator_rocm_component.c
  opal/mca/accelerator/ze/accelerator_ze_component.c
Labels: Target: main

#12730 Added a partcomm fix for mismatched types
  ompi/mca/part/persist/part_persist.h
  ompi/mca/part/persist/part_persist_request.h
Labels: Target: main

#12733 README: annotate --with-libfabric with version requirement for Open MPI 4.1.6
  README
Labels: documentation, RM approved, Target: v4.1.x

#12731 op/aarch64: refactor SVE functions
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: Target: v5.0.x

#12736 fixed argument name in MPI_Precv_init man page
  docs/man-openmpi/man3/MPI_Precv_init.3.rst
Labels: documentation, Target: main

#12737 fixed argument name in MPI_Precv_init man page
  docs/man-openmpi/man3/MPI_Precv_init.3.rst
Labels: documentation, Target: v5.0.x

#12720 Fix typo in LDFLAGS_save_xcode variable name
  config/ompi_setup_fc.m4
Labels: Target: main

#12685 Fix some compiler warnings
  ompi/communicator/comm.c
  ompi/mca/coll/base/coll_base_allreduce.c
  ompi/mpi/fortran/base/fint_2_int.h
  opal/mca/smsc/xpmem/smsc_xpmem_component.c
Labels: Target: main

#12740 v4.1.x: Fix typo in LDFLAGS_save_xcode variable name
  config/ompi_setup_fc.m4
Labels: bug, Target: v4.1.x

#12679 dist: Prepare for 4.1.7 release
  NEWS
  VERSION
Labels: Target: v4.1.x

#12741 v5.0.x: Fix typo in LDFLAGS_save_xcode variable name
  config/ompi_setup_fc.m4
Labels: bug, Target: v5.0.x

#12714 portals4: update the coll-portals4 component to be Big Count compliant
  ompi/mca/coll/portals4/coll_portals4.h
  ompi/mca/coll/portals4/coll_portals4_allreduce.c
  ompi/mca/coll/portals4/coll_portals4_bcast.c
  ompi/mca/coll/portals4/coll_portals4_component.c
  ompi/mca/coll/portals4/coll_portals4_gather.c
  ompi/mca/coll/portals4/coll_portals4_reduce.c
  ompi/mca/coll/portals4/coll_portals4_scatter.c
  ompi/mca/mtl/portals4/mtl_portals4_recv.c
  ompi/mca/mtl/portals4/mtl_portals4_send.c
  ompi/mca/osc/portals4/osc_portals4_comm.c
  ompi/mca/osc/portals4/osc_portals4_component.c
Labels: Target: main

#12749 Fix a variety of typos in comments and strings
  test/carto/carto-file
  test/monitoring/check_monitoring.c
  test/simple/concurrent_spawn.c
  test/simple/hello_show_help.c
  test/simple/intercomm1.c
  test/util/opal_error.c
Labels: Target: main

#12748 man pages: fix typos in MPI_Pready* man pages
  docs/man-openmpi/man3/MPI_Parrived.3.rst
  docs/man-openmpi/man3/MPI_Pready.3.rst
  docs/man-openmpi/man3/MPI_Pready_list.3.rst
  docs/man-openmpi/man3/MPI_Pready_range.3.rst
Labels: documentation, Target: main

#12750 DOCS: minor fix to autogen.pl related page
  docs/developers/autogen.rst
Labels: documentation, Target: main

#12753 v5.0.x: DOCS: minor fix to autogen.pl related page
  docs/developers/autogen.rst
Labels: documentation, Target: v5.0.x

#12754 v5.0.x: fix typos
  docs/man-openmpi/man3/MPI_Parrived.3.rst
  docs/man-openmpi/man3/MPI_Pready.3.rst
  docs/man-openmpi/man3/MPI_Pready_list.3.rst
  docs/man-openmpi/man3/MPI_Pready_range.3.rst
  test/carto/carto-file
  test/monitoring/check_monitoring.c
  test/simple/concurrent_spawn.c
  test/simple/hello_show_help.c
  test/simple/intercomm1.c
  test/util/opal_error.c
Labels: documentation, Target: v5.0.x

#12756 fs/ufs: change default locking protocol
  ompi/mca/fs/lustre/fs_lustre.h
  ompi/mca/fs/lustre/fs_lustre_component.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/ufs/fs_ufs_file_open.c
Labels: Target: main

#12761 docs/../ofi.rst: Correct typographical error
  docs/tuning-apps/networking/ofi.rst
Labels: Target: main

#12762 docs/../ofi.rst: Correct typographical error
  docs/tuning-apps/networking/ofi.rst
Labels: documentation, Target: v5.0.x

#12765 docs: Transition Omni-Path references to Cornelis Networks
  docs/installing-open-mpi/configure-cli-options/networking.rst
  docs/tuning-apps/networking/cuda.rst
  docs/tuning-apps/networking/ofi.rst
Labels: documentation, Target: main

#12759 fs/ufs: change default locking protocol -v5.0.x
  ompi/mca/fs/lustre/fs_lustre.h
  ompi/mca/fs/lustre/fs_lustre_component.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
  ompi/mca/fs/ufs/fs_ufs_file_open.c
Labels: Target: v5.0.x

#12766 docs: Transition Omni-Path references to Cornelis Networks
  docs/installing-open-mpi/configure-cli-options/networking.rst
  docs/tuning-apps/networking/cuda.rst
  docs/tuning-apps/networking/ofi.rst
Labels: documentation, Target: v5.0.x

#12747 coll/han: Implement MPI_Alltoallv in han using SMSC and XPMEM
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_algorithms.c
  ompi/mca/coll/han/coll_han_algorithms.h
  ompi/mca/coll/han/coll_han_alltoallv.c
  ompi/mca/coll/han/coll_han_component.c
  ompi/mca/coll/han/coll_han_dynamic.c
  ompi/mca/coll/han/coll_han_module.c
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: main

#12768 coll/han: post large-count code cleanup and bugfix
  ompi/mca/coll/han/Makefile.am
  ompi/mca/coll/han/coll_han.h
  ompi/mca/coll/han/coll_han_gatherv.c
  ompi/mca/coll/han/coll_han_scatterv.c
  ompi/mca/coll/han/coll_han_utils.c
Labels: bug, Target: main

#12713 portals4: use PtlHandleIsEqual() to compare handles
  ompi/mca/mtl/portals4/mtl_portals4_cancel.c
  ompi/mca/mtl/portals4/mtl_portals4_recv_short.c
  ompi/mca/osc/portals4/osc_portals4_comm.c
  ompi/mca/osc/portals4/osc_portals4_component.c
  opal/mca/btl/portals4/btl_portals4.c
  opal/mca/btl/portals4/btl_portals4_frag.c
Labels: Target: main

#12774 mca/part: fix datatype memory leak
  ompi/mca/part/persist/part_persist_sendreq.h
Labels: Target: main

#12772 pml/cm: release datatype object in send completion callback
  ompi/mca/pml/cm/pml_cm_sendreq.h
Labels: bug, Target: v4.1.x

#12776 v5.0.x: mca/part: fix datatype memory leak
  ompi/mca/part/persist/part_persist_sendreq.h
Labels: Target: v5.0.x

#11716 opal/mca/ofi: select NIC closest to accelerator if requested
  opal/mca/common/ofi/common_ofi.c
Labels: enhancement, Target: main

#12757 opal/cuda: Handle CUDA VMM pointers in accelerator check_addr function
  config/opal_check_cuda.m4
  opal/mca/accelerator/cuda/accelerator_cuda.c
Labels: Target: main

#12769 portals4: use PtlHandleIsEqual() to compare handles
  ompi/mca/mtl/portals4/mtl_portals4_cancel.c
  ompi/mca/mtl/portals4/mtl_portals4_recv_short.c
  ompi/mca/osc/portals4/osc_portals4_comm.c
  ompi/mca/osc/portals4/osc_portals4_component.c
  opal/mca/btl/portals4/btl_portals4.c
  opal/mca/btl/portals4/btl_portals4_frag.c
Labels: Target: v5.0.x

#12764 oshmem/shmem: Fix sshmem start address and warn if inside data region
  oshmem/mca/memheap/base/memheap_base_static.c
  oshmem/mca/sshmem/base/sshmem_base_open.c
Labels: Target: main

#12782 oshmem/shmem: Fix sshmem start address and warn if inside data region - v5.0.x
  oshmem/mca/memheap/base/memheap_base_static.c
  oshmem/mca/sshmem/base/sshmem_base_open.c
Labels: Target: v5.0.x
