Repository open-mpi/ompi, pull requests merged in 2024-02, with the labels that each got.

#12301 accelerator/ze: actually implement wait event
  opal/mca/accelerator/ze/accelerator_ze_module.c
Labels: Target: main

#12311 docs: update for Python 3.12
  docs/conf.py
Labels: documentation, Target: main

#12300 accelerator null component must be static
  opal/mca/accelerator/null/configure.m4
Labels: Target: main

#12297 ompi/oshmem/spml/ucx: Fix cleanup when disconnected: avoid double free
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: main

#12320 Bump version after v5.0.2 release
  VERSION
Labels: Target: v5.0.x

#12135 [v5.0.x] opal/common/ofi: refactor NIC selection logic
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/help-common-ofi.txt
Labels: Target: v5.0.x

#12287 [v5.0.x] Minor fixes: comment correction and spelling "Registration"
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/osc/rdma/osc_rdma_peer.c
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/rcache/base/rcache_base_vma_tree.h
  opal/mca/rcache/rcache.h
  opal/mca/smsc/knem/smsc_knem_module.c
  opal/mca/smsc/smsc.h
Labels: Target: v5.0.x

#12312 v5.0.x: docs: update for Python 3.12
  docs/conf.py
Labels: documentation, Target: v5.0.x

#12304 Correct missing info argument in man pages for MPI_Psend_init and MPI_Precv_init
  docs/man-openmpi/man3/MPI_Precv_init.3.rst
  docs/man-openmpi/man3/MPI_Psend_init.3.rst
Labels: documentation, Target: main, Target: v5.0.x

#12324 docs: move "news" to "release notes -> changelog"
  docs/Makefile.am
  docs/index.rst
  docs/news/index.rst
  docs/news/news-main.rst
  docs/release-notes/changelog/index.rst
  docs/release-notes/changelog/v1.x.rst
  docs/release-notes/changelog/v2.x.rst
  docs/release-notes/changelog/v3.0.x.rst
  docs/release-notes/changelog/v3.1.x.rst
  docs/release-notes/changelog/v4.0.x.rst
  docs/release-notes/changelog/v4.1.x.rst
  docs/release-notes/changelog/v5.0.x.rst
  docs/release-notes/index.rst
Labels: documentation, Target: main

#12325 v5.0.x: docs: Move "news" to "changelog"
  docs/Makefile.am
  docs/index.rst
  docs/news/index.rst
  docs/news/news-main.rst
  docs/release-notes/changelog/index.rst
  docs/release-notes/changelog/v1.x.rst
  docs/release-notes/changelog/v2.x.rst
  docs/release-notes/changelog/v3.0.x.rst
  docs/release-notes/changelog/v3.1.x.rst
  docs/release-notes/changelog/v4.0.x.rst
  docs/release-notes/changelog/v4.1.x.rst
  docs/release-notes/changelog/v5.0.x.rst
  docs/release-notes/index.rst
Labels: documentation, Target: v5.0.x

#12322 [5.0.x] Correct missing info argument in man pages for MPI_Psend_init and MPI_Precv_init
  docs/man-openmpi/man3/MPI_Precv_init.3.rst
  docs/man-openmpi/man3/MPI_Psend_init.3.rst
Labels: documentation, Target: v5.0.x

#12327 ompi/oshmem/spml/ucx: Fix cleanup when disconnected: avoid double free
  oshmem/mca/spml/ucx/spml_ucx.h
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v5.0.x

#12338 btl/smcuda: Add atomic_wmb() before sm_fifo_write
  opal/mca/btl/smcuda/btl_smcuda_fifo.h
Labels: Target: main

#12329 CI: Bot to mark abandoned Github Issues stale/closed
  .github/workflows/close-stale-issues.yaml
  .github/workflows/remove-awaiting-user-info-label.yaml
Labels: Target: main

#12343 [v5.0.x] btl/smcuda: Add atomic_wmb() before sm_fifo_write
  opal/mca/btl/smcuda/btl_smcuda_fifo.h
Labels: Target: v5.0.x

#12350 CI: remove ":" from close-the-issue bot label names
  .github/workflows/close-stale-issues.yaml
  .github/workflows/remove-awaiting-user-info-label.yaml
Labels: Target: main

#12344 [v4.1.x] btl/smcuda: Add atomic_wmb() before sm_fifo_write
  opal/mca/btl/smcuda/btl_smcuda_fifo.h
Labels: RM approved, Target: v4.1.x

#12352 accelerator: introduce compare_ipc_handles fnct
  opal/mca/accelerator/accelerator.h
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/null/accelerator_null_component.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
  opal/mca/accelerator/ze/accelerator_ze_module.c
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
Labels: Target: main

#12341 accelerator/rocm: some minor fixes
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: main

#12347 [v5.0.x] Backport alltoallv fixes
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: Target: v5.0.x

#12355 btl/usnic: move btl_usnic_lock initialization
  opal/mca/btl/usnic/btl_usnic_component.c
Labels: Target: main

#12366 [v5.0.x] btl/usnic: move btl_usnic_lock initialization
  opal/mca/btl/usnic/btl_usnic_component.c
Labels: Target: v5.0.x

#12365 Fix documentation of the mca_base_component_show_load_errors MCA variable
  docs/installing-open-mpi/configure-cli-options/installation.rst
  docs/mca.rst
Labels: documentation, Target: main

#12368 Github CI: use unique Github Action names
  .github/workflows/compile-rocm.yaml
  .github/workflows/ompi_mpi4py.yaml
  .github/workflows/pr-checks.yaml
Labels: Target: main

#12372 ompi_setup_prrte.m4: fix uninitialized shell variable
  config/ompi_setup_prrte.m4
Labels: Target: main

#12377 accel/ze: fix compile error with compare function
  opal/mca/accelerator/ze/accelerator_ze_module.c
Labels: Target: main

#12357 gha/mpi4py: Re-enable multi proc runs
  .github/workflows/ompi_mpi4py.yaml
Labels: Target: main

#12374 v5.0.x: ompi_setup_prrte.m4: fix uninitialized shell variable
  config/ompi_setup_prrte.m4
Labels: Target: v5.0.x

#12371 v5.0.x: Github CI: use unique Github Action names
  .github/workflows/compile-rocm.yaml
  .github/workflows/pr-checks.yaml
Labels: Target: v5.0.x

#12369 v5.0.x: Fix documentation of the mca_base_component_show_load_errors MCA variable
  docs/installing-open-mpi/configure-cli-options/installation.rst
  docs/mca.rst
Labels: documentation, Target: v5.0.x

#12378 Find libcuda.so automatically if --with-cuda-lib is not passed
  config/opal_check_cuda.m4
Labels: Target: main
