Repository open-mpi/ompi, pull requests merged in 2024-01, with the labels that each got.

#12218 [v5.0.x] backport pr12175
  ompi/mca/mtl/ofi/mtl_ofi.h
Labels: bug, Target: v5.0.x

#12184 Add missing Fortran subroutines to profiling lib
  ompi/mpi/fortran/use-mpi-f08/comm_create_from_group_f08.F90
  ompi/mpi/fortran/use-mpi-f08/intercomm_create_from_groups_f08.F90
  ompi/mpi/fortran/use-mpi-f08/parrived_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_list_f08.F90
  ompi/mpi/fortran/use-mpi-f08/pready_range_f08.F90
  ompi/mpi/fortran/use-mpi-f08/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/psend_init_f08.F90
Labels: Target: v5.0.x

#12203 move include of sys/mount back to where it was
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
Labels: Target: v5.0.x

#12211 pml/cm: use MCA_PML_CM_* macros for recv
  ompi/mca/pml/cm/pml_cm.h
Labels: Target: main

#12171 fs/lustre: recognize soft-links on file open
  ompi/mca/fs/base/base.h
  ompi/mca/fs/base/fs_base_get_parent_dir.c
  ompi/mca/fs/lustre/fs_lustre_file_open.c
Labels: RM approved, Target: v4.1.x

#12215 Detect devel builds based on .git/ in $OPAL_TOP_SRCDIR
  config/opal_configure_options.m4
Labels: Target: main

#12220 Update Github issue templates
  .github/ISSUE_TEMPLATE/ask-a-question.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Target: main

#12159 convert last components to use accelerator framework
  ompi/mca/pml/ob1/pml_ob1_accelerator.c
  opal/include/opal/Makefile.am
  opal/include/opal/opal_gpu.h
  opal/mca/accelerator/accelerator.h
  opal/mca/accelerator/base/accelerator_base_frame.c
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/null/accelerator_null_component.c
  opal/mca/accelerator/rocm/accelerator_rocm.h
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
  opal/mca/accelerator/ze/accelerator_ze_module.c
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_accelerator.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/mca/btl/smcuda/btl_smcuda_frag.h
  opal/mca/btl/smcuda/configure.m4
  opal/mca/rcache/gpusm/configure.m4
  opal/mca/rcache/gpusm/rcache_gpusm.h
  opal/mca/rcache/gpusm/rcache_gpusm_module.c
  opal/mca/rcache/rgpusm/configure.m4
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
  opal/runtime/opal_params_core.c
  opal/runtime/opal_params_core.h
Labels: Target: main

#12222 sessions: fix issue with query of num psets
  ompi/instance/instance.c
Labels: Target: main

#12229 opal/accelerator: allow 0 size copies
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
  opal/mca/accelerator/ze/accelerator_ze_module.c
Labels: Target: main

#11686 mtl/ofi: Remove unused variables, and check ompi_ret
  ompi/mca/mtl/ofi/mtl_ofi.c
  ompi/mca/mtl/ofi/mtl_ofi.h
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: main

#12198 coll/alltoallv,ialltoallv: skip send/recv 0-byte data
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: Target: main

#12144 ofi nic selection bugfix and document update
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
  opal/mca/common/ofi/help-common-ofi.txt
Labels: Target: main

#12223 communicator: fix max_local_peers value in disjoint function
  ompi/communicator/comm_cid.c
Labels: Target: main

#12239 v4.1.x: osc/ucx: fixed memory leak
  ompi/mca/osc/ucx/osc_ucx_component.c
Labels: bug, RM approved, Target: v4.1.x

#12234 ofi: follow user specified include/exclude list to select providers
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: Target: main

#12246 ompi/communicator: do not use MPI_IN_PLACE for iallreduce callback
  ompi/communicator/comm_cid.c
Labels: bug, Target: main

#12242 fix a bug introduced by PR 11854
  opal/mca/pmix/base/pmix_base_fns.c
Labels: Target: main

#11683 Propagate the error from the generalize request free callback to the user
  ompi/request/grequest.c
  ompi/request/grequest.h
Labels: bug, Target: main

#12117 Allow OMPI to compile on OSX with gcc13
  3rd-party/romio341/mpl/configure.ac
  3rd-party/romio341/mpl/src/str/mpl_str.c
  configure.ac
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
  opal/include/opal_config_bottom.h
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda.h
  opal/mca/btl/usnic/btl_usnic_map.c
  opal/mca/common/ucx/common_ucx.c
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: Target: main

#12241 opal/accelerator: allow 0 size copies - v5.0.x
  opal/mca/accelerator/cuda/accelerator_cuda.c
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: v5.0.x

#12251 [v5.0.x] ofi: follow user specified include/exclude list to select providers
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/btl_ofi_component.c
  opal/mca/common/ofi/common_ofi.c
  opal/mca/common/ofi/common_ofi.h
Labels: bug, Severity: blocker, Target: v5.0.x

#12256 Revert "btl/ofi: add FI_REMOTE_COMM to required capabilities"
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: main

#12248 Properly initialize mca_rcache_base_module_t members
  opal/mca/rcache/base/base.h
  opal/mca/rcache/base/rcache_base_frame.c
  opal/mca/rcache/gpusm/rcache_gpusm_module.c
  opal/mca/rcache/grdma/rcache_grdma_module.c
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
  opal/mca/rcache/udreg/rcache_udreg_module.c
Labels: Target: main

#12261 Properly initialize mca_rcache_base_module_t members [v5.0.x]
  opal/mca/rcache/base/base.h
  opal/mca/rcache/base/rcache_base_frame.c
  opal/mca/rcache/gpusm/rcache_gpusm_module.c
  opal/mca/rcache/grdma/rcache_grdma_module.c
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
  opal/mca/rcache/udreg/rcache_udreg_module.c
Labels: Target: v5.0.x

#12252 a fix a bug introduced by PR 11854
  opal/mca/pmix/base/pmix_base_fns.c
Labels: Target: v5.0.x

#12267 Add support for gcc13 to 5.x
  3rd-party/romio341/mpl/configure.ac
  3rd-party/romio341/mpl/src/str/mpl_str.c
  configure.ac
  ompi/mca/fbtl/posix/fbtl_posix_preadv.c
  ompi/mca/fbtl/posix/fbtl_posix_pwritev.c
  opal/include/opal_config_bottom.h
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda.h
  opal/mca/btl/usnic/btl_usnic_map.c
  opal/mca/common/ucx/common_ucx.c
  oshmem/mca/memheap/base/memheap_base_static.c
Labels: Target: v5.0.x

#12262 Properly initialize mca_rcache_base_module_t members [v4.1.x]
  opal/mca/rcache/base/base.h
  opal/mca/rcache/base/rcache_base_frame.c
  opal/mca/rcache/gpusm/rcache_gpusm_module.c
  opal/mca/rcache/grdma/rcache_grdma_module.c
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
  opal/mca/rcache/udreg/rcache_udreg_module.c
Labels: RM approved, Target: v4.1.x

#12254 Squash clang-14 warnings in OPAL
  opal/mca/btl/smcuda/btl_smcuda.c
  opal/mca/btl/smcuda/btl_smcuda_component.c
  opal/mca/btl/smcuda/btl_smcuda_fifo.h
  opal/mca/rcache/rgpusm/rcache_rgpusm_module.c
Labels: Target: main

#12271 V5.0.2rc1 wenduwan
  LICENSE
  VERSION
  docs/news/news-v5.0.x.rst
Labels: Target: v5.0.x

#12276 Update platform file and cleanup ignores
  .gitignore
  contrib/platform/intel/bend/mac
Labels: Target: main

#10886 sessions:deworldify behavior of pmix pset lookup
  ompi/instance/instance.c
Labels: Target: main

#12258 coll/base: correctly handle non-commutative ops in allgather-reduce allreduce
  ompi/mca/coll/base/coll_base_allreduce.c
Labels: Target: main

#12268 docs/mca: update btl usage in osc/rdma
  docs/mca.rst
Labels: documentation, Target: main

#12283 Minor code fixes
  ompi/communicator/communicator.h
  opal/util/event.h
Labels: Target: main

#12284 ompi/op: change reduce function prototypes to use a const source pointer
  ompi/op/op.h
Labels: Target: main

#12281 Minor fixes: comment correction and spelling "Registration"
  ompi/mca/coll/base/coll_base_util.h
  ompi/mca/osc/rdma/osc_rdma_peer.c
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/rcache/base/rcache_base_vma_tree.h
  opal/mca/rcache/rcache.h
  opal/mca/smsc/knem/smsc_knem_module.c
  opal/mca/smsc/smsc.h
Labels: Target: main

#11358 smsc/xpmem: Refactor reg-cache to use tree's find() instead of iterate()
  opal/mca/btl/sm/btl_sm_component.c
  opal/mca/smsc/xpmem/smsc_xpmem_component.c
  opal/mca/smsc/xpmem/smsc_xpmem_internal.h
  opal/mca/smsc/xpmem/smsc_xpmem_module.c
Labels: Target: main

#12289 Sessions: improve error checking for PMIX MEMBERSHIP
  ompi/instance/instance.c
Labels: Target: main

#12288 Fix alltoallv dtype size check
  ompi/mca/coll/base/coll_base_alltoallv.c
  ompi/mca/coll/libnbc/nbc_ialltoallv.c
Labels: bug, Target: main

#12290 mtl: ofi change to allow cxi anywhere in provname
  ompi/mca/mtl/ofi/mtl_ofi_component.c
Labels: Target: main

#12294 accelerator/rocm: minor updates
  opal/mca/accelerator/rocm/accelerator_rocm_component.c
Labels: Target: main

#12217 github-action: add a MPI4PY sanity check
  .github/workflows/ompi_mpi4py.yaml
Labels: Target: main

#11505 Fix MPI function names in error output
  ompi/communicator/comm.c
  ompi/communicator/comm_cid.c
Labels: Target: main
