Repository open-mpi/ompi, pull requests merged in 2025-09, with the labels that each got.

#13393 dist: Prep for 5.0.9 release
  VERSION
Labels: Target: v5.0.x

#13329 v5.0.x: Thread level set from ENV crashes (cherry #13211)
  docs/man-openmpi/man3/MPI_Finalize.3.rst
  docs/man-openmpi/man3/MPI_Finalized.3.rst
  docs/man-openmpi/man3/MPI_Init.3.rst
  docs/man-openmpi/man3/MPI_Init_thread.3.rst
  docs/man-openmpi/man3/MPI_Initialized.3.rst
  docs/man-openmpi/man3/MPI_Session_c2f.3.rst
  docs/man-openmpi/man3/MPI_Session_finalize.3.rst
  docs/man-openmpi/man3/MPI_Session_init.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/mpi/c/init.c
  ompi/mpi/c/init_thread.c
  ompi/runtime/mpiruntime.h
  ompi/runtime/ompi_mpi_init.c
Labels: bug, documentation, Target: v5.0.x

#13403 smsc/xpmem: Don't call unmap inside the iterate callback in cleanup
  opal/mca/smsc/xpmem/smsc_xpmem_module.c
Labels: Target: main

#13401 TYPE_RESOURCE_GUIDED: add minimal support
  docs/man-openmpi/man3/MPI_Comm_split_type.3.rst
  ompi/communicator/comm.c
  ompi/include/mpi.h.in
  ompi/include/mpif-values.py
  ompi/mpi/bindings/ompi_bindings/consts.py
  ompi/mpi/c/comm_split_type.c.in
Labels: Target: main

#13408 Fix bug in MCA_PML_OB1_ADD_ACK_TO_PENDING that causes memory overruns…
  ompi/mca/pml/ob1/pml_ob1_recvreq.h
Labels: Target: main

#13406 OMPI/MCA/PML/UCX: Set node local id.
  config/ompi_check_ucx.m4
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: main

#13413 OMPI/MCA/PML/UCX: Set node local id - v4.1.x
  config/ompi_check_ucx.m4
  ompi/mca/osc/ucx/osc_ucx_component.c
  ompi/mca/pml/ucx/pml_ucx.c
  oshmem/mca/spml/ucx/spml_ucx_component.c
Labels: Target: v4.1.x

#13110 [v4.1.x]btl/tcp: Correctly report TCP connect errors
  opal/mca/btl/tcp/btl_tcp_endpoint.c
  opal/mca/btl/tcp/btl_tcp_proc.c
  opal/mca/btl/tcp/help-mpi-btl-tcp.txt
Labels: Target: v4.1.x

#13398 bugfix: coll/han double free'd subcomms
  ompi/mca/coll/han/coll_han_subcomms.c
Labels: Target: main

#13384 add MPI_Remove_error_{string,code,class}
  docs/Makefile.am
  docs/man-openmpi/man3/MPI_Remove_error_class.3.rst
  docs/man-openmpi/man3/MPI_Remove_error_code.3.rst
  docs/man-openmpi/man3/MPI_Remove_error_string.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/errhandler/errcode.c
  ompi/errhandler/errcode.h
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/remove_error_class.c.in
  ompi/mpi/c/remove_error_code.c.in
  ompi/mpi/c/remove_error_string.c.in
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/mpif-h/prototypes_mpi.h
  ompi/mpi/fortran/mpif-h/remove_error_class_f.c
  ompi/mpi/fortran/mpif-h/remove_error_code_f.c
  ompi/mpi/fortran/mpif-h/remove_error_string_f.c
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-interfaces.h.in
  ompi/mpi/fortran/use-mpi-f08/mod/mpi-f08-rename.h
  ompi/mpi/fortran/use-mpi-f08/remove_error_class_f08.F90
  ompi/mpi/fortran/use-mpi-f08/remove_error_code_f08.F90
  ompi/mpi/fortran/use-mpi-f08/remove_error_string_f08.F90
  ompi/mpi/fortran/use-mpi-ignore-tkr/mpi-ignore-tkr-interfaces.h.in
  ompi/mpi/fortran/use-mpi-ignore-tkr/pmpi-ignore-tkr-interfaces.h
Labels: Target: main, MPI 4.1
