Repository open-mpi/ompi, pull requests merged in 2025-03, with the labels that each got.

#13086 MPI_T: provide a stub implementation of events
  configure.ac
  docs/Makefile.am
  docs/man-openmpi/man3/MPI_T.3.rst
  docs/man-openmpi/man3/MPI_T_ERRORS.rst
  docs/man-openmpi/man3/MPI_T_event_callback_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_event_callback_set_info.3.rst
  docs/man-openmpi/man3/MPI_T_event_copy.3.rst
  docs/man-openmpi/man3/MPI_T_event_get_index.3.rst
  docs/man-openmpi/man3/MPI_T_event_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_event_get_num.3.rst
  docs/man-openmpi/man3/MPI_T_event_get_source.3.rst
  docs/man-openmpi/man3/MPI_T_event_get_timestamp.3.rst
  docs/man-openmpi/man3/MPI_T_event_handle_alloc.3.rst
  docs/man-openmpi/man3/MPI_T_event_handle_free.3.rst
  docs/man-openmpi/man3/MPI_T_event_handle_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_event_handle_set_info.3.rst
  docs/man-openmpi/man3/MPI_T_event_read.3.rst
  docs/man-openmpi/man3/MPI_T_event_register_callback.3.rst
  docs/man-openmpi/man3/MPI_T_event_set_dropped_handler.3.rst
  docs/man-openmpi/man3/MPI_T_source_get_info.3.rst
  docs/man-openmpi/man3/MPI_T_source_get_num.3.rst
  docs/man-openmpi/man3/MPI_T_source_get_timestamp.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/include/mpi.h.in
  ompi/mpi/tool/Makefile.am
  ompi/mpi/tool/event_callback_get_info.c
  ompi/mpi/tool/event_callback_set_info.c
  ompi/mpi/tool/event_copy.c
  ompi/mpi/tool/event_get_index.c
  ompi/mpi/tool/event_get_info.c
  ompi/mpi/tool/event_get_num.c
  ompi/mpi/tool/event_get_source.c
  ompi/mpi/tool/event_get_timestamp.c
  ompi/mpi/tool/event_handle_alloc.c
  ompi/mpi/tool/event_handle_free.c
  ompi/mpi/tool/event_handle_get_info.c
  ompi/mpi/tool/event_handle_set_info.c
  ompi/mpi/tool/event_read.c
  ompi/mpi/tool/event_register_callback.c
  ompi/mpi/tool/event_set_dropped_handler.c
  ompi/mpi/tool/source_get_info.c
  ompi/mpi/tool/source_get_num.c
  ompi/mpi/tool/source_get_timestamp.c
Labels: Target: main

#13109 comm: use comm instance for value for memkind set
  ompi/communicator/comm.c
Labels: Target: main

#13117 Latest Fedora has dropped the arch suffix from the openjdk directory
  config/ompi_setup_java.m4
Labels: Target: main

#13124 accelerator/rocm: minor cleanup
  opal/mca/accelerator/rocm/accelerator_rocm_module.c
Labels: Target: main

#13122 v4.1.x: Latest Fedora has dropped the arch suffix from the openjdk directory
  config/ompi_setup_java.m4
Labels: Target: v4.1.x

#13115 Fix race condition in coll_han_alltoall.c
  ompi/mca/coll/han/coll_han_alltoall.c
Labels: Target: main

#13125 mpi: add new status_set/get functions
  docs/Makefile.am
  docs/man-openmpi/man3/MPI_Status_get_error.3.rst
  docs/man-openmpi/man3/MPI_Status_get_source.3.rst
  docs/man-openmpi/man3/MPI_Status_get_tag.3.rst
  docs/man-openmpi/man3/MPI_Status_set_error.3.rst
  docs/man-openmpi/man3/MPI_Status_set_source.3.rst
  docs/man-openmpi/man3/MPI_Status_set_tag.3.rst
  docs/man-openmpi/man3/index.rst
  ompi/include/mpi.h.in
  ompi/mpi/c/Makefile.am
  ompi/mpi/c/status_get_error.c
  ompi/mpi/c/status_get_source.c
  ompi/mpi/c/status_get_tag.c
  ompi/mpi/c/status_set_error.c
  ompi/mpi/c/status_set_source.c
  ompi/mpi/c/status_set_tag.c
Labels: Target: main

#13126 osc/ucx: ignore lock table if "no_locks" info key is set to true
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: main, Target: v5.0.x

#13135 osc/ucx: ignore lock table if "no_locks" info key is set
  ompi/mca/osc/ucx/osc_ucx_comm.c
Labels: Target: v5.0.x

#13132 docs: minor additions to the new MPI_Status_* man pages
  docs/man-openmpi/man3/MPI_Status_get_error.3.rst
  docs/man-openmpi/man3/MPI_Status_get_source.3.rst
  docs/man-openmpi/man3/MPI_Status_get_tag.3.rst
  docs/man-openmpi/man3/MPI_Status_set_error.3.rst
  docs/man-openmpi/man3/MPI_Status_set_source.3.rst
  docs/man-openmpi/man3/MPI_Status_set_tag.3.rst
  docs/release-notes/changelog/v6.0.x.rst
Labels: documentation, Target: main

#13083 Add a link to the gcc discussion about patcher.
  opal/mca/patcher/patcher.h
Labels: Target: main

#13121 v5.0.x: Latest Fedora has dropped the arch suffix from the openjdk directory
  config/ompi_setup_java.m4
Labels: Target: v5.0.x

#13139 fix up use of opal_enable_debug
  ompi/mca/vprotocol/example/vprotocol_example_recv.c
  oshmem/mca/atomic/base/base.h
  oshmem/mca/memheap/base/base.h
  oshmem/mca/scoll/base/base.h
  oshmem/mca/scoll/mpi/scoll_mpi_debug.h
  oshmem/mca/scoll/ucc/scoll_ucc_debug.h
  oshmem/mca/spml/base/base.h
  oshmem/shmem/shmem_api_logger.h
Labels: Target: main

#13150 hdf5-tests: abbreviate the wget output
  .github/workflows/hdf5-tests.yaml
Labels: Target: main

#13158 external data pack: switch to using size_t
  ompi/datatype/ompi_datatype.h
  ompi/datatype/ompi_datatype_external.c
Labels: Target: main

#13142 configury: fix support for flang on OSX
  autogen.pl
  config/ltmain_flang_darwin.diff
Labels: enhancement, Target: main

#13144 Encode help-*.txt file contents into C source code
  .gitignore
  ompi/Makefile.am
  ompi/communicator/Makefile.am
  ompi/dpm/Makefile.am
  ompi/errhandler/Makefile.am
  ompi/mca/bml/r2/Makefile.am
  ompi/mca/coll/base/Makefile.am
  ompi/mca/coll/xhc/Makefile.am
  ompi/mca/hook/base/Makefile.am
  ompi/mca/mtl/ofi/Makefile.am
  ompi/mca/mtl/psm2/Makefile.am
  ompi/mca/pml/ob1/Makefile.am
  ompi/mpi/Makefile.am
  ompi/mpiext/ftmpi/c/Makefile.am
  ompi/runtime/Makefile.am
  ompi/tools/mpirun/Makefile.am
  opal/Makefile.am
  opal/mca/accelerator/base/Makefile.am
  opal/mca/accelerator/cuda/Makefile.am
  opal/mca/allocator/bucket/Makefile.am
  opal/mca/base/Makefile.am
  opal/mca/btl/base/Makefile.am
  opal/mca/btl/ofi/Makefile.am
  opal/mca/btl/smcuda/Makefile.am
  opal/mca/btl/tcp/Makefile.am
  opal/mca/btl/usnic/Makefile.am
  opal/mca/common/ofi/Makefile.am
  opal/mca/common/sm/Makefile.am
  opal/mca/hwloc/base/Makefile.am
  opal/mca/if/linux_ipv6/Makefile.am
  opal/mca/mpool/Makefile.am
  opal/mca/mpool/base/Makefile.am
  opal/mca/rcache/base/Makefile.am
  opal/mca/shmem/mmap/Makefile.am
  opal/mca/shmem/posix/Makefile.am
  opal/mca/shmem/sysv/Makefile.am
  opal/mca/smsc/knem/Makefile.am
  opal/mca/timer/linux/Makefile.am
  opal/runtime/Makefile.am
  opal/tools/wrappers/Makefile.am
  opal/util/Makefile.am
  opal/util/convert-help-files-to-c-code.py
  opal/util/show_help.c
  opal/util/show_help.h
  opal/util/show_help_lex.h
  opal/util/show_help_lex.l
  oshmem/Makefile.am
  oshmem/mca/memheap/base/Makefile.am
  oshmem/mca/scoll/mpi/Makefile.am
  oshmem/mca/scoll/ucc/Makefile.am
  oshmem/mca/sshmem/base/Makefile.am
  oshmem/mca/sshmem/mmap/Makefile.am
  oshmem/mca/sshmem/sysv/Makefile.am
  oshmem/mca/sshmem/ucx/Makefile.am
  oshmem/runtime/Makefile.am
  oshmem/shmem/Makefile.am
  oshmem/tools/oshmem_info/Makefile.am
Labels: Target: main

#13146 A series of minor updates / cleanups
  contrib/check-help-strings.pl
  contrib/check-owner.pl
  contrib/check_unnecessary_headers.sh
  contrib/completion/mpirun.sh
  contrib/dist/linux/ompi-spec-generator.py
  contrib/ompi-time.sh
  contrib/spread/spread-init.txt
  contrib/spread/spread.conf
  contrib/submit_test.pl
  ompi/mca/coll/xhc/resources/xhc-hierarchy.svg
  ompi/mca/mtl/ofi/generate-opt-funcs.pl
  test/asm/run_tests
Labels: Target: main

#13165 Revert "fortran:fix integer kind=8 problem"
  ompi/mpi/fortran/use-mpi-f08/bindings/mpi-f-interfaces-bind.h
Labels: Target: main

#13162 v5.0.x: configury: fix support for flang on OSX
  autogen.pl
  config/ltmain_flang_darwin.diff
Labels: enhancement, Target: v5.0.x

#13163 Remove components for old operating systems
  opal/mca/if/solaris_ipv6/Makefile.am
  opal/mca/if/solaris_ipv6/configure.m4
  opal/mca/if/solaris_ipv6/if_solaris_ipv6.c
  opal/mca/if/solaris_ipv6/owner.txt
  opal/mca/memory/malloc_solaris/Makefile.am
  opal/mca/memory/malloc_solaris/configure.m4
  opal/mca/memory/malloc_solaris/memory_malloc_solaris_component.c
  opal/mca/memory/malloc_solaris/owner.txt
  opal/mca/timer/altix/Makefile.am
  opal/mca/timer/altix/configure.m4
  opal/mca/timer/altix/owner.txt
  opal/mca/timer/altix/timer_altix.h
  opal/mca/timer/altix/timer_altix_component.c
  opal/mca/timer/solaris/Makefile.am
  opal/mca/timer/solaris/configure.m4
  opal/mca/timer/solaris/owner.txt
  opal/mca/timer/solaris/timer_solaris.h
  opal/mca/timer/solaris/timer_solaris_component.c
Labels: Target: main
