Repository open-mpi/ompi, pull requests merged in 2025-05, with the labels that each got.

#13219 v5.0.x: mpool/hugepage: fix sizing of hugepages
  opal/mca/mpool/hugepage/mpool_hugepage_component.c
Labels: Target: v5.0.x

#13224 coll/ucc: refactor UCC collective operations to handle MPI_IN_PLACE correctly
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_gather.c
  ompi/mca/coll/ucc/coll_ucc_gatherv.c
  ompi/mca/coll/ucc/coll_ucc_reduce_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatterv.c
Labels: Target: main

#13221 docs: add a blurb about current state of MPI_T events
  docs/man-openmpi/man3/MPI_T.3.rst
Labels: Target: main

#13209 configure: --with-prrte=internal would be ignored
  config/ompi_setup_prrte.m4
Labels: Target: main

#13228 v5.0.x: refactor UCC collective operations to handle MPI_IN_PLACE correctly
  ompi/mca/coll/ucc/coll_ucc_allgather.c
  ompi/mca/coll/ucc/coll_ucc_allgatherv.c
  ompi/mca/coll/ucc/coll_ucc_alltoall.c
  ompi/mca/coll/ucc/coll_ucc_alltoallv.c
  ompi/mca/coll/ucc/coll_ucc_gather.c
  ompi/mca/coll/ucc/coll_ucc_gatherv.c
  ompi/mca/coll/ucc/coll_ucc_scatter.c
  ompi/mca/coll/ucc/coll_ucc_scatterv.c
Labels: Target: v5.0.x

#13233 docs: fix typo about --with-ft configure CLI option
  docs/installing-open-mpi/configure-cli-options/misc.rst
Labels: documentation, Target: main

#13236 docs: Add a "Last updated on:" HTML footer
  docs/conf.py
Labels: documentation, Target: main

#13235 v5.0.x: docs: fix typo about --with-ft configure CLI option
  docs/installing-open-mpi/configure-cli-options/misc.rst
Labels: documentation, Target: v5.0.x

#13237 v5.0.x: docs: Add a "Last updated on:" HTML footer
  docs/conf.py
Labels: documentation, Target: v5.0.x

#13231 Convert some Perl build scripts to Python
  autogen.pl
  config/ompi_fortran_get_alignment.m4
  config/ompi_setup_mpi_fortran.m4
  ompi/communicator/comm_init.c
  ompi/datatype/ompi_datatype_module.c
  ompi/include/Makefile.am
  ompi/include/mpi.h.in
  ompi/include/mpif-sentinels.h
  ompi/include/mpif-values.pl
  ompi/include/mpif-values.py
  ompi/mpi/fortran/base/Makefile.am
  ompi/mpi/fortran/base/gen-mpi-mangling.pl
  ompi/mpi/fortran/base/gen-mpi-mangling.py
  ompi/mpi/fortran/base/gen-mpi-sizeof.pl
  ompi/mpi/fortran/base/gen-mpi-sizeof.py
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
Labels: Target: main

#13204 aarch64 op: Enable two‑stage SVE detection in component configuration
  ompi/mca/op/aarch64/configure.m4
  ompi/mca/op/aarch64/op_aarch64.h
  ompi/mca/op/aarch64/op_aarch64_component.c
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: Target: main

#13222 coll/acoll: Bcast/Barrier enhancements and bug fixes.
  ompi/mca/coll/acoll/README
  ompi/mca/coll/acoll/coll_acoll.h
  ompi/mca/coll/acoll/coll_acoll_allgather.c
  ompi/mca/coll/acoll/coll_acoll_allreduce.c
  ompi/mca/coll/acoll/coll_acoll_alltoall.c
  ompi/mca/coll/acoll/coll_acoll_barrier.c
  ompi/mca/coll/acoll/coll_acoll_bcast.c
  ompi/mca/coll/acoll/coll_acoll_component.c
  ompi/mca/coll/acoll/coll_acoll_module.c
  ompi/mca/coll/acoll/coll_acoll_reduce.c
  ompi/mca/coll/acoll/coll_acoll_utils.h
Labels: Target: main

#13201 Implement Connectivity.java example using Java bindings
  config/ompi_setup_java.m4
  examples/Connectivity.java
  examples/Makefile
Labels: Target: main

#13246 mca/op: always define aarch64 macros
  ompi/mca/op/aarch64/Makefile.am
  ompi/mca/op/aarch64/configure.m4
  ompi/mca/op/aarch64/op_aarch64_component.c
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: Target: main

#13239 configure: be more verbose about fort TS 29113
  config/opal_summary.m4
Labels: Target: main

#13247 show_help: only parse specific trees for help files
  opal/util/Makefile.am
  opal/util/convert-help-files-to-c-code.py
Labels: Target: main

#13251 v5.0.x: update version and release notes for rc2
  VERSION
  docs/release-notes/changelog/v5.0.x.rst
Labels: Target: v5.0.x

#13244 v5.0.x: Add SVE detection alongside NEON in aarch64 op component
  ompi/mca/op/aarch64/configure.m4
  ompi/mca/op/aarch64/op_aarch64.h
  ompi/mca/op/aarch64/op_aarch64_component.c
  ompi/mca/op/aarch64/op_aarch64_functions.c
Labels: Target: v5.0.x

#13248 Add explicit test for Python >= v3.7 in configure
  VERSION
  config/ompi_configure_options.m4
  configure.ac
  docs/conf.py
  docs/developers/prerequisites.rst
  docs/developers/sphinx.rst
  docs/installing-open-mpi/quickstart.rst
  docs/installing-open-mpi/supported-systems.rst
  docs/release-notes/changelog/v6.0.x.rst
Labels: documentation, Target: main

#13255 configury: ensure to remove *.mod files
  config/ompi_fortran_check_ignore_tkr.m4
Labels: Target: main

#13254 configury: always require Python for building Open MPI
  config/ompi_setup_mpi_fortran.m4
  configure.ac
  docs/developers/prerequisites.rst
  docs/installing-open-mpi/supported-systems.rst
  ompi/include/Makefile.am
  ompi/mpi/c/Makefile.am
  ompi/mpi/fortran/mpif-h/Makefile.am
  ompi/mpi/fortran/mpif-h/profile/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/base/Makefile.am
  ompi/mpi/fortran/use-mpi-f08/mod/Makefile.am
  ompi/mpi/fortran/use-mpi-ignore-tkr/Makefile.am
Labels: Target: main

#13262 CI: Remove Ubuntu 18 and RHEL 7
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v4.1.x

#13061 Fix exploding idle ctxs array
  oshmem/mca/spml/ucx/spml_ucx.c
Labels: Target: main

#13198 configury: test Fortran complex(real16)
  config/ompi_fortran_check_iso_fortran_env_real16.m4
Labels: enhancement, Target: main

#13264 v5.0.x: CI: remove Ubuntu 18 and RHEL 7
  .ci/community-jenkins/Jenkinsfile
Labels: Target: v5.0.x

#13259 docs: Update the v6.0.0 changelog
  docs/release-notes/changelog/v6.0.x.rst
Labels: documentation, Target: main

#13245 Bring better Fortran TKR support in 4.1
  config/ompi_fortran_check_asynchronous.m4
  config/ompi_fortran_check_bind_c.m4
  config/ompi_fortran_check_ignore_tkr.m4
Labels: bug, Target: v4.1.x

#13266 Fix OFI build warnings
  ompi/mca/mtl/ofi/mtl_ofi_component.c
  opal/mca/btl/ofi/README.md
  opal/mca/btl/ofi/btl_ofi_component.c
Labels: Target: main

#13268 v5.0.x: configury: fix Fortran common alignment detection
  config/ompi_setup_mpi_fortran.m4
Labels: Target: v5.0.x

#13123 Mark mpif.h as deprecated
  config/ompi_configure_options.m4
  config/ompi_fortran_check_warning.m4
  config/ompi_setup_fc.m4
  config/ompi_setup_mpi_fortran.m4
  docs/release-notes/changelog/v6.0.x.rst
  ompi/include/mpif.h.in
Labels: Target: main

#13277 Fix for CID 1645329 in memkind info code
  ompi/info/info_memkind.c
Labels: Target: main

#13281 Force alignment of opal_atomic_int128_t to be 16B
  opal/include/opal_stdatomic.h
Labels: Target: main

#13283 v5.0.x: v5.0.8 release
  VERSION
  docs/release-notes/changelog/v5.0.x.rst
Labels: Target: v5.0.x
